<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : zh_TW (OGame: tw)
 * Source   : resources/lang/en/t_resources.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'metal_mine' => [
        'title' => '金屬礦',
        'description' => '金屬礦是用來萃取金屬礦石的,金屬礦對於所有新興的帝國和已建立的帝國都極為重要.',
        'description_long' => '金屬礦是用來萃取金屬礦石的,金屬礦對於所有新興的帝國和已建立的帝國都極為重要.',
    ],
    'crystal_mine' => [
        'title' => '晶體礦',
        'description' => '晶體是應用於生産電子電路和構成某些合金混合物的重要資源.',
        'description_long' => '晶體是應用於生産電子電路和構成某些合金混合物的重要資源.',
    ],
    'deuterium_synthesizer' => [
        'title' => '重氫合成器',
        'description' => '重氫是太空船的重要燃料,重氫採集於深海,是極為罕見的物質,並因此價值相對昂貴.',
        'description_long' => '重氫是太空船的重要燃料,重氫採集於深海,是極為罕見的物質,並因此價值相對昂貴.',
    ],
    'solar_plant' => [
        'title' => '太陽能發電廠',
        'description' => '太陽能發電廠可以吸收及轉換來自太陽輻射的能量.所有的礦厰都需要能量來運作.',
        'description_long' => '太陽能發電廠可以吸收及轉換來自太陽輻射的能量.所有的礦厰都需要能量來運作.',
    ],
    'fusion_plant' => [
        'title' => '核融合反應器',
        'description' => '核融合反應器使用重氫為原料生産高純度的能源.',
        'description_long' => '核融合反應器使用重氫為原料生産高純度的能源.',
    ],
    'metal_store' => [
        'title' => '金屬儲存器',
        'description' => '金屬儲存器是用來儲存金屬資源的.',
        'description_long' => '這個巨大的儲存設施用於儲存金屬礦石。 每升級一級都會增加可儲存的金屬礦石數量。 如果商店已滿，則不會再開採金屬。 

金屬倉庫保護了礦山日常產量的一定比例（最多 10%）。',
    ],
    'crystal_store' => [
        'title' => '晶體儲存器',
        'description' => '晶體儲存器是用來儲存晶體的.',
        'description_long' => '未加工的水晶將同時存放在這些巨大的儲藏大廳中。 每升級一級，可以儲存的水晶數量就會增加。 如果水晶商店已滿，則不會再開採水晶。 

水晶儲存保護了礦山一定比例的日常產量（最多 10%）。',
    ],
    'deuterium_store' => [
        'title' => '重氫儲存槽',
        'description' => '重氫儲存槽是用來儲存新近萃取的重氫.',
        'description_long' => '氘罐用於儲存新合成的氘。 一旦經過合成器處理，就會透過管道輸送到該罐中以供以後使用。 隨著水箱的每次升級，總儲存容量都會增加。 一旦達到容量，將不再合成氘。 

氘罐保護合成器日常產量的一定比例（最多 10%）。',
    ],
    'robot_factory' => [
        'title' => '機器人工廠',
        'description' => '機器人工廠提供便宜且確實的勞動力用以進行基礎建設.每提昇一級,建築物升級的速度也就越快.',
        'description_long' => '機器人工廠提供便宜且確實的勞動力用以進行基礎建設.每提昇一級,建築物升級的速度也就越快.',
    ],
    'shipyard' => [
        'title' => '造船廠',
        'description' => '各式各樣的艦船以及防禦設施都可以在行星的造船廠建造.',
        'description_long' => '各式各樣的艦船以及防禦設施都可以在行星的造船廠建造.',
    ],
    'research_lab' => [
        'title' => '研究實驗室',
        'description' => '實驗研究室是用來指導執行新科技研究的.',
        'description_long' => '研究實驗室是任何帝國都必不可少的一個重要組成,在那裡您可以發現新科技以及將舊有科技加以升級.每升一級研究實驗室,研發新技術的效率速度將大大提昇,同時也解鎖某些新科技的研究限制.為了能盡可能快地完成研究,研究實驗室的科學家們應該被立即部署到新殖民地展開工作和開發.這樣,新科技的知識就可以很快地傳播到整個帝國.',
    ],
    'alliance_depot' => [
        'title' => '聯盟太空站',
        'description' => '聯盟太空站為運行在軌道內提供防禦協助的友好艦隊提供燃料供給.',
        'description_long' => '聯盟太空站為運行在軌道內提供防禦協助的友好艦隊提供燃料供給.',
    ],
    'missile_silo' => [
        'title' => '導彈發射井',
        'description' => '導彈發射井是用於存儲導彈的.',
        'description_long' => '在21世紀發生的全面核戰爭摧毀了地球本身,但就科技而言,在宇宙中依然需要這個恐怖的武器的存在.科學家十分擔憂被無賴恐怖組織掌控核彈轟炸.所以他們決定使用同樣的彈道技術製造了一個截然相反的制衡武器抵禦恐怖襲擊.導彈發射井是用來建造,儲藏及發射星際導彈和反彈道導彈的設施.每一級導彈發射井可以儲存5枚星際導彈或10枚反彈道導彈. 導彈是可以混合儲存的; 一枚星際導彈所需的空間可以放置兩枚反彈道導彈.',
    ],
    'nano_factory' => [
        'title' => '奈米機器人工廠',
        'description' => '奈米機器人工廠是機器人工學的終極革命. 每提昇一個等級將可以大量節省建造建築物,艦船,以及防禦設施的時間.',
        'description_long' => '奈米機器人工廠是機器人工學的終極革命. 每提昇一個等級將可以大量節省建造建築物,艦船,以及防禦設施的時間.',
    ],
    'terraformer' => [
        'title' => '地形改造器',
        'description' => '地形改造器可以增加行星可用地表空間.',
        'description_long' => '隨著星球建設的不斷增多，就連殖民地的生存空間也變得越來越有限。 高層建築、地下建築等傳統方法日益顯得不足。 一小群高能物理學家和奈米工程師最終找到了解決方案：地形改造。 
利用巨大的能量，地形改造者可以使整片土地甚至大陸變得可耕種。 該建築生產專門為此目的而生產的奈米材料，確保整個地面品質始終如一。 

每個地形改造者等級可耕種 5 個田地。 每一層，地形改造者都會佔據一個區域。 每 2 個 terraformer 等級，您將獲得 1 個獎勵區域。 

一旦建造完成，地形改造器就無法拆除。',
    ],
    'space_dock' => [
        'title' => '宇宙港',
        'description' => '艦隊遺骸可在宇宙港內被修復.',
        'description_long' => '太空船塢提供了修復在戰鬥中被摧毀並留下殘骸的船隻的可能性。 修復時間最多需要12個小時，但至少需要30分鐘才能讓船隻重新投入使用。 

修復必須在殘骸產生後 3 天內開始。 修復後的船舶必須在修復完成後人工返回執勤。 如果不這樣做，任何類型的個別船舶將在 3 天後恢復使用。 

只有當超過 150,000 單位被摧毀（包括參與戰鬥且價值至少為艦船點數 5% 的己方艦船）時，殘骸才會出現。 

由於太空船塢漂浮在軌道上，因此不需要行星場。',
    ],
    'lunar_base' => [
        'title' => '月球基地',
        'description' => '由於月球沒有大氣層，因此需要月球基地來產生可居住的空間。',
        'description_long' => '由於月球並沒有大氣層,要提供可居住空間就須建立一個月球基地.',
    ],
    'sensor_phalanx' => [
        'title' => '感應陣列',
        'description' => '使用感測器方陣，可以發現和觀察其他帝國的艦隊。 感測器方陣陣列越大，可以掃描的範圍越大。',
        'description_long' => '透過使用感應陣列,將可發現並檢測其它帝國的艦隊.更大型的感應陣列,將可以掃描更遠的距離.',
    ],
    'jump_gate' => [
        'title' => '空間跳躍門',
        'description' => '跳躍門是巨大的收發器，能夠立即將最大的艦隊發送到遙遠的跳躍門。',
        'description_long' => '空間跳躍門是巨大的傳輸工具,即使是龐大的艦隊也能瞬間進行遠距離的空間跳躍.',
    ],
    'energy_technology' => [
        'title' => '能源技術',
        'description' => '掌握不同類型的能源知識,是很多新技術發展及應用的必要條件.',
        'description_long' => '掌握不同類型的能源知識,是很多新技術發展及應用的必要條件.',
    ],
    'laser_technology' => [
        'title' => '雷射技術',
        'description' => '聚焦光線産生一道光束,當光束射擊至物體上時産生破壞力.',
        'description_long' => '聚焦光線産生一道光束,當光束射擊至物體上時産生破壞力.',
    ],
    'ion_technology' => [
        'title' => '離子技術',
        'description' => '高濃度離子能允許您興建能產生巨大殺傷力的加農炮,並同時每一級升級能讓您減少 4% 的降級拆除費用.',
        'description_long' => '高濃度離子能允許您興建能產生巨大殺傷力的加農炮,並同時每一級升級能讓您減少 4% 的降級拆除費用.',
    ],
    'hyperspace_technology' => [
        'title' => '超空間科技',
        'description' => '透過整合第四維和第五維，現在可以研究一種更經濟、更有效率的新型驅動器。',
        'description_long' => '透過整合4次元及5次元空間,現在已研發出一種全新的引擎,更為經濟,更為有效能. 透過使用第四維和第五維空間，現在可壓縮您艦船的載貨區，以節省更多空間。',
    ],
    'plasma_technology' => [
        'title' => '電漿技術',
        'description' => '電漿技術是離子技術的進一步發展成果,透過加速高能電漿産生的超高溫電漿束,進而造成毀滅性的力量並額外每一級加速了金屬 1% / 0.66% 晶體 / 0.33% 重氫的產量.',
        'description_long' => '電漿技術是離子技術的進一步發展成果,透過加速高能電漿産生的超高溫電漿束,進而造成毀滅性的力量並額外每一級加速了金屬 1% / 0.66% 晶體 / 0.33% 重氫的產量.',
    ],
    'combustion_drive' => [
        'title' => '燃燒引擎',
        'description' => '儘管每升一級燃燒引擎,只能提昇基礎速度的10%,但該引擎技術的研發還是會使得艦船速度更快.',
        'description_long' => '儘管每升一級燃燒引擎,只能提昇基礎速度的10%,但該引擎技術的研發還是會使得艦船速度更快.',
    ],
    'impulse_drive' => [
        'title' => '脈衝引擎',
        'description' => '脈衝引擎基於反作用力的原理而設計的.儘管每升一級脈衝引擎僅能提昇基礎速度的20%,但隨著該引擎的發展,將還是會使得某些艦船速度更快.',
        'description_long' => '脈衝引擎基於反作用力的原理而設計的.儘管每升一級脈衝引擎僅能提昇基礎速度的20%,但隨著該引擎的發展,將還是會使得某些艦船速度更快.',
    ],
    'hyperspace_drive' => [
        'title' => '超空間引擎',
        'description' => '超空間引擎能將艦船週邊的空間扭曲.儘管每升一級僅能提昇基礎速度的30%,但升級該引擎技術還是能令某些艦船速度更快.',
        'description_long' => '超空間引擎能將艦船週邊的空間扭曲.儘管每升一級僅能提昇基礎速度的30%,但升級該引擎技術還是能令某些艦船速度更快.',
    ],
    'espionage_technology' => [
        'title' => '間諜偵察技術',
        'description' => '透過該科技,可以蒐集到其它行星和月球的資訊.',
        'description_long' => '透過該科技,可以蒐集到其它行星和月球的資訊.',
    ],
    'computer_technology' => [
        'title' => '電腦技術',
        'description' => '透過升級電腦能力就可以指揮更多的艦隊.每升一級電腦技術,可以增加指揮艦隊的最大數量.',
        'description_long' => '透過升級電腦能力就可以指揮更多的艦隊.每升一級電腦技術,可以增加指揮艦隊的最大數量.',
    ],
    'astrophysics' => [
        'title' => '天體物理學',
        'description' => '利用天體物理學技術,艦船可以進行更遠的遠征探險.每2級天體物理學科技便可殖民多一個行星.',
        'description_long' => '利用天體物理學技術,艦船可以進行更遠的遠征探險.每2級天體物理學科技便可殖民多一個行星.',
    ],
    'intergalactic_research_network' => [
        'title' => '星際研究網路',
        'description' => '各個不同行星上的研究人員都透過該網路相互聯繫.',
        'description_long' => '各個不同行星上的研究人員都透過該網路相互聯繫.',
    ],
    'graviton_technology' => [
        'title' => '重子技術',
        'description' => '透過一束密集的重子粒子束可以構建一個人工的重力場,該重力場可以毀滅艦船乃至月球.',
        'description_long' => '透過一束密集的重子粒子束可以構建一個人工的重力場,該重力場可以毀滅艦船乃至月球.',
    ],
    'weapon_technology' => [
        'title' => '武器技術',
        'description' => '武器技術使得武器系統更有效能.每級武器技術將提昇武器系統基礎數值的10%.',
        'description_long' => '武器技術使得武器系統更有效能.每級武器技術將提昇武器系統基礎數值的10%.',
    ],
    'shielding_technology' => [
        'title' => '防禦盾技術',
        'description' => '盾牌技術使船艦和防禦設施上的盾牌更有效率。 每提升一層護盾科技，護盾強度就會增加基礎值的10%。',
        'description_long' => '防禦盾技術使得艦船及防禦設施的護盾更加高效能.每級防禦盾技術提昇將使得防禦盾的基礎值提昇10%強度.',
    ],
    'armor_technology' => [
        'title' => '裝甲技術',
        'description' => '特殊合金提昇了艦船及防禦設施的裝甲.每級裝甲技術提昇將增加10%基礎裝甲.',
        'description_long' => '特殊合金提昇了艦船及防禦設施的裝甲.每級裝甲技術提昇將增加10%基礎裝甲.',
    ],
    'small_cargo' => [
        'title' => '小型運輸艦',
        'description' => '小型運輸艦是一種靈巧的艦船,可以快速地運輸資源到其它行星.',
        'description_long' => '小型運輸艦是一種靈巧的艦船,可以快速地運輸資源到其它行星.',
    ],
    'large_cargo' => [
        'title' => '大型運輸艦',
        'description' => '這是一種比小型運輸艦更大型的運輸艦,運送速度較之更快,這有賴於改進後的引擎系統.',
        'description_long' => '這是一種比小型運輸艦更大型的運輸艦,運送速度較之更快,這有賴於改進後的引擎系統.',
    ],
    'colony_ship' => [
        'title' => '殖民船',
        'description' => '可以用這艘船前往無人行星殖民.',
        'description_long' => '20世紀，人類決定追尋星空。 首先，它登陸月球。 之後，建造了太空站。 不久之後火星就被殖民了。 人們很快就確定我們的發展依賴殖民其他世界。 世界各地的科學家和工程師齊聚一堂，共同開發人類有史以來最偉大的成就。 殖民船誕生了。 

這艘船是用來為新發現的星球殖民做準備的。 一旦到達目的地，太空船就會立即轉變為習慣性的生活空間，以協助新世界的人口繁殖和採礦。 因此，行星的最大數量取決於天文物理學研究的進展。 兩個新層級的天體技術允許殖民另外一個星球。',
    ],
    'recycler' => [
        'title' => '回收船',
        'description' => '回收船是唯一能夠在戰鬥後收集漂浮在行星軌道上的碎片場的船隻。',
        'description_long' => '回收船是唯一能採集回收在戰鬥後漂浮在行星軌道上的廢墟資源的艦船.',
    ],
    'espionage_probe' => [
        'title' => '間諜衛星',
        'description' => '間諜衛星是小巧靈活的探測器,它為您能提供超遠距離的艦隊或行星資料.',
        'description_long' => '間諜衛星是小巧靈活的探測器,它為您能提供超遠距離的艦隊或行星資料.',
    ],
    'solar_satellite' => [
        'title' => '太陽能衛星',
        'description' => '太陽能衛星是簡單的太陽能電池平台，位於高靜止軌道上。 它們收集陽光並透過雷射將其傳輸到地面站。',
        'description_long' => '太陽能衛星是一個環繞在行星同步軌道上空,使用太陽能光伏版採集能源的簡單平臺.它們採集太陽光並利用雷射技術將能源傳輸回地面站. 太陽能衛星於本行星生産 35 能源.',
    ],
    'crawler' => [
        'title' => '履帶車',
        'description' => 'Crawler steigern die Produktion von Metall, Kristall und Deuterium auf dem Einsatzplaneten pro Stück um je 0,02%, 0,02% und 0,02%. Als Kollektor steigert sich die Produktion zusätzlich. Der maximale Gesamtbonus ist vom Gesamtlevel deiner Minen abhängig.',
        'description_long' => '履帶車可將任務星球上的金屬、水晶和氘產量分別提高0.02%、0.02% 和 0.02%。作為採礦師，產量也會增加。最高總獎勵取決於您的礦產的整體水平。',
    ],
    'pathfinder' => [
        'title' => '探路者',
        'description' => '探路者號是一艘快速且靈活的飛船，專為探索未知的太空區域而建造。',
        'description_long' => '探路者飛船速度超快且空間巨大，可用於開採遠征探索途中發現的廢墟帶。總產量也會增加。',
    ],
    'light_fighter' => [
        'title' => '輕型戰鬥機',
        'description' => '這是所有帝國都會建造的首款戰鬥艦船.輕型戰鬥機是一種靈巧的艦船,不過自身卻十分脆弱.不過數量龐大的話,對任何帝國來說都是一個巨大的威脅.它們是對敵人防禦薄弱的小型或大型運輸艦的首選最佳武器.',
        'description_long' => '這是所有帝國都會建造的首款戰鬥艦船.輕型戰鬥機是一種靈巧的艦船,不過自身卻十分脆弱.不過數量龐大的話,對任何帝國來說都是一個巨大的威脅.它們是對敵人防禦薄弱的小型或大型運輸艦的首選最佳武器.',
    ],
    'heavy_fighter' => [
        'title' => '重型戰鬥機',
        'description' => '重型戰鬥機比輕型戰鬥機擁有更高的攻擊力和更好地裝甲防禦.',
        'description_long' => '重型戰鬥機比輕型戰鬥機擁有更高的攻擊力和更好地裝甲防禦.',
    ],
    'cruiser' => [
        'title' => '巡洋艦',
        'description' => '巡洋艦的裝甲幾乎是重型戰鬥機的3倍,火力強2倍.它的速度也是所有船艦中最快的.',
        'description_long' => '巡洋艦的裝甲幾乎是重型戰鬥機的3倍,火力強2倍.它的速度也是所有船艦中最快的.',
    ],
    'battle_ship' => [
        'title' => '戰列艦',
        'description' => '戰列艦是一支艦隊的主力所在.它們的重型加農炮,高速度,和大型的倉儲容量使得它們的對手倍感壓力.',
        'description_long' => '戰列艦是一支艦隊的主力所在.它們的重型加農炮,高速度,和大型的倉儲容量使得它們的對手倍感壓力.',
    ],
    'battlecruiser' => [
        'title' => '戰鬥巡洋艦',
        'description' => '戰鬥巡洋艦是一種專門負責攔截敵人艦隊的高速艦船.',
        'description_long' => '戰鬥巡洋艦是一種專門負責攔截敵人艦隊的高速艦船.',
    ],
    'bomber' => [
        'title' => '導彈艦',
        'description' => '導彈艦是專門研發用來摧毀行星防禦設施的.',
        'description_long' => '幾個世紀以來，隨著防禦系統開始變得更大、更複雜，艦隊開始以驚人的速度被摧毀。 決定需要一艘新船來突破防禦，以確保最大成果。 經過多年的研究和開發，轟炸機誕生了。 

轟炸機使用雷射導引瞄準設備和等離子炸彈，尋找並摧毀它能找到的任何防禦機制。 一旦超空間驅動發展到8級，轟炸機就加裝了超空間引擎，可以以更高的速度飛行。',
    ],
    'destroyer' => [
        'title' => '毀滅者',
        'description' => '毀滅者是艦船中的王者.',
        'description_long' => 'Destroyer 是多年工作和開發的成果。 隨著死亡之星的發展，人們決定需要一類船來防禦如此巨大的武器。 憑藉改良的尋的感測器、多方陣離子砲、高斯炮和等離子砲塔，驅逐艦成為最可怕的戰艦之一。 

由於驅逐艦非常大，其機動性受到嚴重限制，這使得它更像一個戰鬥站而不是一艘戰艦。 其強大的火力彌補了機動性的不足，但建造和運行也需要大量的氘。',
    ],
    'deathstar' => [
        'title' => '死星',
        'description' => '死星的破壞力超凡卓絕而無人能及.',
        'description_long' => '死星號是有史以來最強大的飛船。 這艘月球大小的船是地面上唯一能用肉眼看到的船。 不幸的是，當你發現它時，已經來不及採取任何行動了。 

這艘巨大的太空船配備了巨大的引力砲，這是宇宙中迄今為止最先進的武器系統，不僅有能力摧毀整個艦隊和防禦系統，而且有能力摧毀整個衛星。 只有最先進的帝國才有能力建造如此巨大的船隻。',
    ],
    'reaper' => [
        'title' => '惡魔飛船',
        'description' => '收割者號是一艘強大的戰鬥艦，專門用於侵略性襲擊和碎片田收割。',
        'description_long' => '惡魔級飛船是一款實力強大的毀滅性武器，可在戰鬥後立即開採廢墟帶。',
    ],
    'rocket_launcher' => [
        'title' => '飛彈發射器',
        'description' => 'Der Raketenwerfer ist eine einfache und kostengünstige Verteidigungsmöglichkeit.',
        'description_long' => '飛彈發射器是一種造價低廉,構造簡單的防衛系統.',
    ],
    'light_laser' => [
        'title' => '輕型雷射炮',
        'description' => 'Durch den konzentrierten Beschuss eines Ziels mit Photonen kann wesentlich größerer Schaden erzielt werden als mit gewöhnlichen ballistischen Waffen.',
        'description_long' => '用光子集中射擊於一個目標能夠産生比普通彈道武器更為顯著的攻擊傷害.',
    ],
    'heavy_laser' => [
        'title' => '重型雷射炮',
        'description' => 'Der schwere Laser ist eine konsequente Weiterentwicklung des leichten Lasers.',
        'description_long' => '重型雷射炮是透過輕型雷射炮的原理理論發展出來的.',
    ],
    'gauss_cannon' => [
        'title' => '磁軌炮',
        'description' => 'Die Gaußkanone beschleunigt tonnenschwere Geschosse unter gigantischem Energieaufwand.',
        'description_long' => '磁軌炮能將數以噸計重的炮彈以超高速投射出去.',
    ],
    'ion_cannon' => [
        'title' => '離子加農炮',
        'description' => 'Das Ionengeschütz schleudert eine Welle von Ionen, die ihrem Ziel erheblichen Schaden zufügt.',
        'description_long' => '離子加農炮透過發射一束持續加速的離子束,對被射擊的物體造成嚴重的傷害攻擊.',
    ],
    'plasma_turret' => [
        'title' => '電漿炮塔',
        'description' => 'Plasmageschütze setzen die Kraft einer Sonneneruption frei und übertreffen in ihrer vernichtenden Wirkung sogar den Zerstörer.',
        'description_long' => '電漿炮塔釋放的太陽閃焰能源束的攻擊力甚至遠超過毀滅者.',
    ],
    'small_shield_dome' => [
        'title' => '小型防護罩',
        'description' => 'Die kleine Schildkuppel umhüllt den ganzen Planeten mit einem Feld, das ungeheure Energiemengen absorbieren kann.',
        'description_long' => '小型防護罩把整個行星都罩了起來,並產生出一種力場,能吸收大量的能量.',
    ],
    'large_shield_dome' => [
        'title' => '大型防護罩',
        'description' => 'Die Weiterentwicklung der kleinen Schildkuppel kann wesentlich mehr Energie einsetzen, um Angriffe abzuwehren.',
        'description_long' => '小型防護罩的進階形態産物,它能運用相當大的能源力場來抵禦攻擊.',
    ],
    'anti_ballistic_missile' => [
        'title' => '反彈道導彈',
        'description' => 'Abfangraketen zerstören angreifende Interplanetarraketen.',
        'description_long' => '當您的行星或衛星受到行星際飛彈 (IPM) 攻擊時，反彈道飛彈 (ABM) 是您唯一的防線。 當偵測到 IPM 發射時，這些飛彈會自動啟動，在飛行電腦中處理發射代碼，瞄準傳入的 IPM，然後發射進行攔截。 在飛行過程中，不斷追蹤目標IPM並應用航向修正，直到ABM到達目標並摧毀攻擊的IPM。 每個 ABM 都會摧毀一個傳入的 IPM。',
    ],
    'interplanetary_missile' => [
        'title' => '星際導彈',
        'description' => '星際飛彈摧毀敵人的防禦。',
        'description_long' => '星際導彈能摧毀敵人一切的防禦力量. 您的星際導彈射程已覆蓋至 0 個太陽系.',
    ],
    'kraken' => [
        'title' => '克拉肯',
        'description' => '將目前正在建造的建築物的建造時間減少 <b>:duration</b>。',
    ],
    'detroid' => [
        'title' => '底特律',
        'description' => '將目前造船廠合約的建造時間縮短<b>:duration</b>。',
    ],
    'newtron' => [
        'title' => '紐創',
        'description' => '將目前正在進行的所有研究的研究時間縮短 <b>:duration</b>。',
    ],
];
