<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : cs (OGame: cz)
 * Source   : resources/lang/en/t_resources.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'metal_mine' => [
        'title' => 'Důl na Kov',
        'description' => 'V těchto dolech se těží rudy rozličných kovů. Ta se potom zušlechťuje na materiály, které jsou nejdůležitějšími surovinami pro všechna vznikající i zavedená impéria.',
        'description_long' => 'V těchto dolech se těží rudy rozličných kovů. Ta se potom zušlechťuje na materiály, které jsou nejdůležitějšími surovinami pro všechna vznikající i zavedená impéria.',
    ],
    'crystal_mine' => [
        'title' => 'Důl na krystaly',
        'description' => 'Krystaly jsou hlavní surovinou používanou na výrobu elektrických obvodů a určitých slitinových směsí.',
        'description_long' => 'Krystaly jsou hlavní surovinou používanou na výrobu elektrických obvodů a určitých slitinových směsí.',
    ],
    'deuterium_synthesizer' => [
        'title' => 'Syntetizér deuteria',
        'description' => 'Syntetizér deuteria vytahuje stopové množství deuteria z vody na planetě.',
        'description_long' => 'Syntetizér deuteria vytahuje stopové množství deuteria z vody na planetě.',
    ],
    'solar_plant' => [
        'title' => 'Solární elektrárna',
        'description' => 'Solární elektrárny vstřebávají energii ze slunečního záření. Všechny doly potřebují energii, aby správně fungovaly.',
        'description_long' => 'Solární elektrárny vstřebávají energii ze slunečního záření. Všechny doly potřebují energii, aby správně fungovaly.',
    ],
    'fusion_plant' => [
        'title' => 'Fúzní reaktor',
        'description' => 'Fúzní reaktor využívá deuteria k výrobě energie.',
        'description_long' => 'Fúzní reaktor využívá deuteria k výrobě energie.',
    ],
    'metal_store' => [
        'title' => 'Sklad kovu',
        'description' => 'Poskytuje uskladnění pro čerstvě natěžený kov.',
        'description_long' => 'Poskytuje uskladnění pro čerstvě natěžený kov.',
    ],
    'crystal_store' => [
        'title' => 'Sklad krystalu',
        'description' => 'Poskytuje uskladnění pro přebytečný krystal.',
        'description_long' => 'Poskytuje uskladnění pro přebytečný krystal.',
    ],
    'deuterium_store' => [
        'title' => 'Nádrž na deuterium',
        'description' => 'Obrovské nádrže pro skladování čerstvě syntetizovaného deuteria.',
        'description_long' => 'Obrovské nádrže pro skladování čerstvě syntetizovaného deuteria.',
    ],
    'robot_factory' => [
        'title' => 'Továrna na roboty',
        'description' => 'Továrny na roboty poskytují robokonstruktéry na pomoc při stavbách budov. Každá úroveň zvyšuje rychlost vylepšování budov.',
        'description_long' => 'Továrny na roboty poskytují robokonstruktéry na pomoc při stavbách budov. Každá úroveň zvyšuje rychlost vylepšování budov.',
    ],
    'shipyard' => [
        'title' => 'Hangár',
        'description' => 'V hangáru jsou stavěny veškeré typy lodí a obranných zařízení.',
        'description_long' => 'V hangáru jsou stavěny veškeré typy lodí a obranných zařízení.',
    ],
    'research_lab' => [
        'title' => 'Výzkumná laboratoř',
        'description' => 'Výzkumná laboratoř je nezbytná ke zkoumání nových technologií.',
        'description_long' => 'Výzkumná laboratoř je nezbytná ke zkoumání nových technologií.',
    ],
    'alliance_depot' => [
        'title' => 'Alianční sklad',
        'description' => 'Alianční sklad dodává palivo spřáteleným letkám, pomáhajícím s obranou v orbitě.',
        'description_long' => 'Alianční sklad dodává palivo spřáteleným letkám, pomáhajícím s obranou v orbitě.',
    ],
    'missile_silo' => [
        'title' => 'Raketové silo',
        'description' => 'Raketová sila se používají k uschování raket.',
        'description_long' => 'Raketová sila se používají k uschování raket.',
    ],
    'nano_factory' => [
        'title' => 'Továrna s nanoboty',
        'description' => 'Toto je ultimátní robotechnologie. Každá úroveň krátí čas výstavby budov, lodí a obranných konstrukcí.',
        'description_long' => 'Toto je ultimátní robotechnologie. Každá úroveň krátí čas výstavby budov, lodí a obranných konstrukcí.',
    ],
    'terraformer' => [
        'title' => 'Terraformer',
        'description' => 'Terraformer zvyšuje množství použitelného povrchu planety.',
        'description_long' => 'Terraformer zvyšuje množství použitelného povrchu planety.',
    ],
    'space_dock' => [
        'title' => 'Vesmírný dok',
        'description' => 'Ve vesmírném doku lze opravovat vraky lodí.',
        'description_long' => 'Ve vesmírném doku lze opravovat vraky lodí.',
    ],
    'lunar_base' => [
        'title' => 'Základna na měsíci',
        'description' => 'Vzhledem k tomu, že Měsíc nemá atmosféru, je k vytvoření obyvatelného prostoru zapotřebí měsíční základna.',
        'description_long' => 'Měsíc nemá vlastní atmosféru a tak základna musí vyrábět obyvatelné místo.',
    ],
    'sensor_phalanx' => [
        'title' => 'Senzor falangy',
        'description' => 'Pomocí senzorové falangy lze objevit a pozorovat flotily jiných říší. Čím větší je pole senzorové falangy, tím větší dosah může snímat.',
        'description_long' => 'Užitím senzoru falangy objevíte letky ostatních impérií. Dosah senzoru je závislý na velikosti jeho paprsku.',
    ],
    'jump_gate' => [
        'title' => 'Hyperprostorová brána',
        'description' => 'Skokové brány jsou obrovské transceivery schopné poslat i tu největší flotilu během okamžiku ke vzdálené skokové bráně.',
        'description_long' => 'Hyperprostorové brány jsou systém obrovských vysílačů, schopných posílat i ty největší letky do přijímací hyperprostorové brány, a to kdekoliv ve vesmíru, bez ztráty času.',
    ],
    'energy_technology' => [
        'title' => 'Energetická technologie',
        'description' => 'Znalost různých druhů energie je nezbytná pro mnoho nových technologií.',
        'description_long' => 'Znalost různých druhů energie je nezbytná pro mnoho nových technologií.',
    ],
    'laser_technology' => [
        'title' => 'Laserová technologie',
        'description' => 'Zaostřování světla produkuje paprsek který způsobuje poškození při zásahu objektu.',
        'description_long' => 'Zaostřování světla produkuje paprsek který způsobuje poškození při zásahu objektu.',
    ],
    'ion_technology' => [
        'title' => 'Iontová technologie',
        'description' => 'Koncentrace iontů ti umožní postavit kanóny, které mohou způsobit nesmírné škody. Každá úroveň také sníží náklady na zbourání budovy o 4 %.',
        'description_long' => 'Koncentrace iontů ti umožní postavit kanóny, které mohou způsobit nesmírné škody. Každá úroveň také sníží náklady na zbourání budovy o 4 %.',
    ],
    'hyperspace_technology' => [
        'title' => 'Hyperprostorová technologie',
        'description' => 'Integrací 4. a 5. dimenze je nyní možné zkoumat nový druh pohonu, který je ekonomičtější a efektivnější.',
        'description_long' => 'Pomocí integrace 4. a 5. dimenze je nyní možné zkoumat nový druh pohonu, který je ekonomičtější a výkonnější. S použitím čtvrté a páté dimenze je nyní možné zmenšit nakládací rampu Tvých lodí k ušetření místa.',
    ],
    'plasma_technology' => [
        'title' => 'Plasmová technologie',
        'description' => 'Další vývoj iontové technologie urychluje vysokoenergetické plazma, které tak dosahuje devastačních škod a navíc optimalizuje produkci kovu a krystalu (1 %/0,66 %/0,33 % za úroveň).',
        'description_long' => 'Další vývoj iontové technologie urychluje vysokoenergetické plazma, které tak dosahuje devastačních škod a navíc optimalizuje produkci kovu a krystalu (1 %/0,66 %/0,33 % za úroveň).',
    ],
    'combustion_drive' => [
        'title' => 'Spalovací pohon',
        'description' => 'Rozvoj tohoto pohonu některé lodě zrychlí, i když každá úroveň zvýší jejich rychlost pouze o 10 % ze základní hodnoty.',
        'description_long' => 'Rozvoj tohoto pohonu některé lodě zrychlí, i když každá úroveň zvýší jejich rychlost pouze o 10 % ze základní hodnoty.',
    ],
    'impulse_drive' => [
        'title' => 'Impulzní pohon',
        'description' => 'Impulzní pohon je založen na principu reakce. Další vývoj tohoto pohonu činí některé lodě rychlejšími, ačkoliv každá úroveň pouze zvyšuje rychlost o 20% ze základní hodnoty.',
        'description_long' => 'Impulzní pohon je založen na principu reakce. Další vývoj tohoto pohonu činí některé lodě rychlejšími, ačkoliv každá úroveň pouze zvyšuje rychlost o 20% ze základní hodnoty.',
    ],
    'hyperspace_drive' => [
        'title' => 'Hyperprostorový pohon',
        'description' => 'Hyperprostorový pohon deformuje vesmír okolo lodi. Rozvoj tohoto pohonu činí některé lodě rychlejšími, ačkoliv každá úroveň pouze zvyšuje rychlost o 30 % ze základní hodnoty.',
        'description_long' => 'Hyperprostorový pohon deformuje vesmír okolo lodi. Rozvoj tohoto pohonu činí některé lodě rychlejšími, ačkoliv každá úroveň pouze zvyšuje rychlost o 30 % ze základní hodnoty.',
    ],
    'espionage_technology' => [
        'title' => 'Špionážní technologie',
        'description' => 'Informace o ostatních planetách a měsících můžeš získat použitím této technologie.',
        'description_long' => 'Informace o ostatních planetách a měsících můžeš získat použitím této technologie.',
    ],
    'computer_technology' => [
        'title' => 'Počítačová technologie',
        'description' => 'Se zvyšováním kapacity tvých počítačů můžeš ovládat více letek. Každý úroveň počítačové technologie zvyšuje maximální počet letek o jednu.',
        'description_long' => 'Se zvyšováním kapacity tvých počítačů můžeš ovládat více letek. Každý úroveň počítačové technologie zvyšuje maximální počet letek o jednu.',
    ],
    'astrophysics' => [
        'title' => 'Astrofyzika',
        'description' => 'S astrofyzikálním výzkumným modulem mohou lodě podnikat dlouhé expedice. Za každé 2 úrovně této technologie můžeš obsadit další planetu.',
        'description_long' => 'S astrofyzikálním výzkumným modulem mohou lodě podnikat dlouhé expedice. Za každé 2 úrovně této technologie můžeš obsadit další planetu.',
    ],
    'intergalactic_research_network' => [
        'title' => 'Intergalaktická výzkumná síť',
        'description' => 'Výzkumníci na různých planetách komunikují pomocí této sítě.',
        'description_long' => 'Výzkumníci na různých planetách komunikují pomocí této sítě.',
    ],
    'graviton_technology' => [
        'title' => 'Gravitonová technologie',
        'description' => 'Vystřelení koncentrovaného paprsku gravitonových částic může vytvořit umělé gravitační pole, které může zničit lodě nebo dokonce měsíce.',
        'description_long' => 'Vystřelení koncentrovaného paprsku gravitonových částic může vytvořit umělé gravitační pole, které může zničit lodě nebo dokonce měsíce.',
    ],
    'weapon_technology' => [
        'title' => 'Zbraňové systémy',
        'description' => 'Zbraňové systémy činí zbraňové vybavení výkonnějším. Každá úroveň zbraňových systémů zvyšuje sílu zbraní jednotek o 10% ze základní hodnoty.',
        'description_long' => 'Zbraňové systémy činí zbraňové vybavení výkonnějším. Každá úroveň zbraňových systémů zvyšuje sílu zbraní jednotek o 10% ze základní hodnoty.',
    ],
    'shielding_technology' => [
        'title' => 'Technologie štítů',
        'description' => 'Díky technologii štítů jsou štíty na lodích a obranných zařízeních efektivnější. Každá úroveň technologie štítů zvyšuje sílu štítů o 10 % základní hodnoty.',
        'description_long' => 'Technologie štítů činí štíty na lodích a obranných zařízeních výkonnějšími. Každá úroveň štítové technologie zvyšuje sílu štítů o 10% ze základní hodnoty.',
    ],
    'armor_technology' => [
        'title' => 'Pancéřování',
        'description' => 'Speciální slitiny zdokonalují obrnění na lodích a obranných stavbách. Efektivita obrnění může být zvýšena o 10% za úroveň.',
        'description_long' => 'Speciální slitiny zdokonalují obrnění na lodích a obranných stavbách. Efektivita obrnění může být zvýšena o 10% za úroveň.',
    ],
    'small_cargo' => [
        'title' => 'Malý transportér',
        'description' => 'Malý transportér je hbitá loď, která je schopna rychle transportovat suroviny na jiné planety.',
        'description_long' => 'Malý transportér je hbitá loď, která je schopna rychle transportovat suroviny na jiné planety.',
    ],
    'large_cargo' => [
        'title' => 'Velký transportér',
        'description' => 'Tento transportér má mnohem větší nákladovou kapacitu než malý transportér a je zpravidla rychlejší díky vylepšenému pohonu.',
        'description_long' => 'Tento transportér má mnohem větší nákladovou kapacitu než malý transportér a je zpravidla rychlejší díky vylepšenému pohonu.',
    ],
    'colony_ship' => [
        'title' => 'Kolonizační loď',
        'description' => 'S touto lodí můžeš kolonizovat volné planety.',
        'description_long' => 'S touto lodí můžeš kolonizovat volné planety.',
    ],
    'recycler' => [
        'title' => 'Recyklátor',
        'description' => 'Recyklátory jsou jediné lodě schopné po boji sklízet pole trosek plovoucích na oběžné dráze planety.',
        'description_long' => 'Recyklátory jsou jediné lodě schopné vytěžit trosky, které se vznáší po bojích na oběžných drahách planet.',
    ],
    'espionage_probe' => [
        'title' => 'Špionážní sonda',
        'description' => 'Špionážní sondy jsou malé, hbité letouny, které poskytují data o letkách a planetách na obrovské vzdálenosti.',
        'description_long' => 'Špionážní sondy jsou malé, hbité letouny, které poskytují data o letkách a planetách na obrovské vzdálenosti.',
    ],
    'solar_satellite' => [
        'title' => 'Solární satelit',
        'description' => 'Solární satelity jsou jednoduché platformy solárních článků, které se nacházejí na vysoké, stacionární oběžné dráze. Shromažďují sluneční světlo a přenášejí je na pozemní stanici pomocí laseru.',
        'description_long' => 'Solární satelity jsou jednoduché plochy solárních panelů, umístěné vysoko ve stabilním orbitalu. Získávají sluneční světlo a přenášejí ho za pomoci laserů na pozemskou stanici. Solární satelity produkují  35 energie na této planetě.',
    ],
    'crawler' => [
        'title' => 'Crawler',
        'description' => 'Crawler zvyšuje produkci kovu, krystalu a deuteria o 0,02 %, 0,02 % a 0,02 %. Jako sběrateli se ti rovněž zvýší produkce. Maximální celkový bonus záleží na úrovni tvých dolů.',
        'description_long' => 'Crawler zvyšuje produkci kovu, krystalu a deuteria o 0,02 %, 0,02 % a 0,02 %. Jako sběrateli se ti rovněž zvýší produkce. Maximální celkový bonus záleží na úrovni tvých dolů.',
    ],
    'pathfinder' => [
        'title' => 'Průzkumník',
        'description' => 'Pathfinder je rychlá a obratná loď, určená pro výpravy do neznámých sektorů vesmíru.',
        'description_long' => 'Průzkumníci jsou velcí, prostorní a mohou na expedicích těžit pole trosek. Rovněž se zvyšuje celkový výnos.',
    ],
    'light_fighter' => [
        'title' => 'Lehký stíhač',
        'description' => 'Lehký stíhač je obratná loď, která je k nalezení na téměr každé planetě. Náklady nejsou příliš vysoké, nicméně síla štítů a nákladová kapacita jsou velmi nízké.',
        'description_long' => 'Lehký stíhač je obratná loď, která je k nalezení na téměr každé planetě. Náklady nejsou příliš vysoké, nicméně síla štítů a nákladová kapacita jsou velmi nízké.',
    ],
    'heavy_fighter' => [
        'title' => 'Těžký stíhač',
        'description' => 'Tento stíhač je lépe obrněný a má větší útočnou sílu než lehký stíhač.',
        'description_long' => 'Tento stíhač je lépe obrněný a má větší útočnou sílu než lehký stíhač.',
    ],
    'cruiser' => [
        'title' => 'Křižník',
        'description' => 'Křižníky jsou obrněné téměř třikrát více než těžké stíhačky a mají více než dvojnásobnou palebnou sílu. Navíc jsou velmi rychlé.',
        'description_long' => 'Křižníky jsou obrněné téměř třikrát více než těžké stíhačky a mají více než dvojnásobnou palebnou sílu. Navíc jsou velmi rychlé.',
    ],
    'battle_ship' => [
        'title' => 'Bitevní loď',
        'description' => 'Bitevní lodě tvoří páteř letky. Jejich těžká děla, vysoká rychlost a rozsáhlý nákladový prostor přiměly jejich protivníky brát je vážně.',
        'description_long' => 'Bitevní lodě tvoří páteř letky. Jejich těžká děla, vysoká rychlost a rozsáhlý nákladový prostor přiměly jejich protivníky brát je vážně.',
    ],
    'battlecruiser' => [
        'title' => 'Bitevní křižník',
        'description' => 'Největší specializací bitevního křižníku je zachycování nepřátelských letek.',
        'description_long' => 'Největší specializací bitevního křižníku je zachycování nepřátelských letek.',
    ],
    'bomber' => [
        'title' => 'Bombardér',
        'description' => 'Bombardér byl speciálně vyvinut pro ničení planetárních obranných systémů světa.',
        'description_long' => 'Bombardér byl speciálně vyvinut pro ničení planetárních obranných systémů světa.',
    ],
    'destroyer' => [
        'title' => 'Ničitel',
        'description' => 'Ničitel je král válečných lodí.',
        'description_long' => 'Ničitel je král válečných lodí.',
    ],
    'deathstar' => [
        'title' => 'Hvězda smrti',
        'description' => 'Zničující síla hvězdy smrti je dosud nepřekonaná.',
        'description_long' => 'Zničující síla hvězdy smrti je dosud nepřekonaná.',
    ],
    'reaper' => [
        'title' => 'Rozparovač',
        'description' => 'Reaper je výkonná bojová loď specializovaná na agresivní nájezdy a sklizeň trosek.',
        'description_long' => 'Loď třídy Rozparovače je mocný ničící nástroj, který může těžit pole trosek ihned po bitvě.',
    ],
    'rocket_launcher' => [
        'title' => 'Raketomet',
        'description' => 'Raketomet je obranné opatření, které je vhodné pro svou jednoduchost a pro výtečný poměr cena/výkon.',
        'description_long' => 'Raketomet je obranné opatření, které je vhodné pro svou jednoduchost a pro výtečný poměr cena/výkon.',
    ],
    'light_laser' => [
        'title' => 'Lehký laser',
        'description' => 'Koncentrovaná palba fotonů na cíl může způsobit znatelně větší poškození než obyčejné střelné zbraně.',
        'description_long' => 'Koncentrovaná palba fotonů na cíl může způsobit znatelně větší poškození než obyčejné střelné zbraně.',
    ],
    'heavy_laser' => [
        'title' => 'Těžký laser',
        'description' => 'Těžký laser je logickým stupněm vývoje lehkého laseru.',
        'description_long' => 'Těžký laser je logickým stupněm vývoje lehkého laseru.',
    ],
    'gauss_cannon' => [
        'title' => 'Gaussův kanón',
        'description' => 'Gaussův kanón pálí vysokou rychlostí tuny těžké projektily.',
        'description_long' => 'Gaussův kanón pálí vysokou rychlostí tuny těžké projektily.',
    ],
    'ion_cannon' => [
        'title' => 'Iontový kanón',
        'description' => 'Iontový kanón pálí nepřetržitý svazek zrychlených iontů, které zasaženým objektům způsobují značná poškození.',
        'description_long' => 'Iontový kanón pálí nepřetržitý svazek zrychlených iontů, které zasaženým objektům způsobují značná poškození.',
    ],
    'plasma_turret' => [
        'title' => 'Plasmová věž',
        'description' => 'Plasmové věže uvolňují energii o síle sluneční erupce, které v ničivosti předčí i Ničitele.',
        'description_long' => 'Plasmové věže uvolňují energii o síle sluneční erupce, které v ničivosti předčí i Ničitele.',
    ],
    'small_shield_dome' => [
        'title' => 'Malý planetární štít',
        'description' => 'Malý planetární štít chrání celou planetu polem, které dokáže absorbovat obrovské množství energie.',
        'description_long' => 'Malý planetární štít chrání celou planetu polem, které dokáže absorbovat obrovské množství energie.',
    ],
    'large_shield_dome' => [
        'title' => 'Velký planetární štít',
        'description' => 'Toto vylepšení malého obranného štítu může významně pomoci odolat útokům.',
        'description_long' => 'Toto vylepšení malého obranného štítu může významně pomoci odolat útokům.',
    ],
    'anti_ballistic_missile' => [
        'title' => 'Antibalistické rakety',
        'description' => 'Antibalistické rakety ničí útočící meziplanetární rakety',
        'description_long' => 'Antibalistické rakety ničí útočící meziplanetární rakety',
    ],
    'interplanetary_missile' => [
        'title' => 'Meziplanetární rakety',
        'description' => 'Meziplanetární rakety ničí nepřátelskou obranu.',
        'description_long' => 'Meziplanetární rakety ničí obranu nepřítele. Vaše meziplanetární rakety mají nyní dosah 0 systémů.',
    ],
    'kraken' => [
        'title' => 'KRAKEN',
        'description' => 'Zkracuje dobu výstavby budov aktuálně ve výstavbě o <b>:duration</b>.',
    ],
    'detroid' => [
        'title' => 'DETROID',
        'description' => 'Zkracuje dobu výstavby aktuálních smluv s loděnicemi o <b>:duration</b>.',
    ],
    'newtron' => [
        'title' => 'NEWTRON',
        'description' => 'Zkracuje dobu výzkumu u veškerého aktuálně probíhajícího výzkumu o <b>:duration</b>.',
    ],
];
