<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : fr (OGame: fr)
 * Source   : resources/lang/en/t_external.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'browser_warning' => [
        'title' => 'Votre navigateur n\'est pas à jour.',
        'desc1' => 'Votre version d\'Internet Explorer ne correspond pas aux standards existants et n\'est plus supportée par ce site.',
        'desc2' => 'Pour utiliser ce site Web, veuillez mettre à jour votre navigateur Web vers une version actuelle ou utiliser un autre navigateur Web. Si vous utilisez déjà la dernière version, veuillez recharger la page pour l\'afficher correctement.',
        'desc3' => 'Voici une liste des navigateurs les plus populaires. Cliquez sur l\'un des symboles pour accéder à la page de téléchargement :',
    ],
    'login' => [
        'page_title' => 'OGame - Conquérir l\'univers',
        'btn' => 'Se connecter',
        'email_label' => 'Adresse email:',
        'password_label' => 'Mot de passe:',
        'universe_label' => 'Univers de jeu',
        'universe_option_1' => '1. Univers',
        'submit' => 'Se connecter',
        'forgot_password' => 'Vous avez oublié votre mot de passe ?',
        'forgot_email' => 'Vous avez oublié votre adresse email ?',
        'terms_accept_html' => 'Avec la connexion, j\'accepte les <a class="" href="#" target="_blank" title="T&amp;Cs">T&Cs</a>',
    ],
    'register' => [
        'play_free' => 'JOUEZ GRATUITEMENT !',
        'email_label' => 'Adresse email:',
        'password_label' => 'Mot de passe:',
        'universe_label' => 'Univers de jeu',
        'distinctions' => 'Distinction',
        'terms_html' => 'Nos <a class="" target="_blank" href="#" title="T&amp;Cs"> Conditions générales </a> et <a class="" target="_blank" href="#" title="Politique de confidentialité"> Politique de confidentialité </a> s\'appliquent dans le jeu.',
        'submit' => 'Registre',
    ],
    'nav' => [
        'home' => 'Maison',
        'about' => 'À propos de OGame',
        'media' => 'Médias',
        'wiki' => 'Wiki',
    ],
    'home' => [
        'title' => 'OGame - Conquérir l\'univers',
        'description_html' => '<em>OGame</em> est un jeu de stratégie se déroulant dans l\'espace, dans lequel des milliers de joueurs du monde entier s\'affrontent en même temps. Vous n\'avez besoin que d\'un navigateur Web classique pour jouer.',
        'board_btn' => 'Conseil',
        'trailer_title' => 'Bande-annonce',
    ],
    'footer' => [
        'legal' => 'Mentions légales',
        'privacy_policy' => 'politique de confidentialité',
        'terms' => 'Conditions générales',
        'contact' => 'Contact',
        'rules' => 'Règles',
        'copyright' => '© OGameX. Tous droits réservés.',
    ],
    'js' => [
        'login' => 'Se connecter',
        'close' => 'Fermer',
        'age_check_failed' => 'Nous sommes désolés, mais vous n\'êtes pas éligible pour vous inscrire. Veuillez consulter nos conditions générales pour plus d\'informations.',
    ],
    'validation' => [
        'required' => 'Ce champ est obligatoire',
        'make_decision' => 'Prendre une décision',
        'accept_terms' => 'Vous devez accepter les CGV.',
        'length' => 'Entre 3 et 20 caractères autorisés.',
        'pw_length' => 'Entre 4 et 20 caractères autorisés.',
        'email' => 'Vous devez saisir une adresse email valide !',
        'invalid_chars' => 'Contient des caractères non valides.',
        'no_begin_end_underscore' => 'Votre nom ne peut pas commencer ou se terminer par un trait de soulignement.',
        'no_begin_end_whitespace' => 'Votre nom ne peut pas commencer ou se terminer par un espace.',
        'max_three_underscores' => 'Votre nom ne peut pas contenir plus de 3 traits de soulignement au total.',
        'max_three_whitespaces' => 'Votre nom ne peut pas contenir plus de 3 espaces au total.',
        'no_consecutive_underscores' => 'Vous ne pouvez pas utiliser deux ou plusieurs traits de soulignement l\'un après l\'autre.',
        'no_consecutive_whitespaces' => 'Vous ne pouvez pas utiliser deux ou plusieurs espaces l\'un après l\'autre.',
        'username_available' => 'Ce nom d\'utilisateur est disponible.',
        'username_loading' => 'Veuillez patienter, chargement...',
        'username_taken' => 'Ce nom d\'utilisateur n\'est plus disponible.',
        'only_letters' => 'Utilisez uniquement des caractères.',
    ],
    'forgot_password' => [
        'title' => 'Vous avez oublié votre mot de passe ?',
        'description' => 'Entrez votre adresse e-mail ci-dessous et nous vous enverrons un lien pour réinitialiser votre mot de passe.',
        'email_label' => 'Adresse email:',
        'submit' => 'Envoyer le lien de réinitialisation',
        'back_to_login' => '← Retour à la connexion',
    ],
    'reset_password' => [
        'title' => 'Réinitialisez votre mot de passe',
        'email_label' => 'Adresse email:',
        'password_label' => 'Nouveau mot de passe :',
        'confirm_label' => 'Confirmez le nouveau mot de passe :',
        'submit' => 'Réinitialiser le mot de passe',
    ],
    'forgot_email' => [
        'title' => 'Vous avez oublié votre adresse email ?',
        'description' => 'Entrez votre nom de commandant et nous vous enverrons un indice à l\'adresse e-mail enregistrée.',
        'username_label' => 'Nom du commandant :',
        'submit' => 'Envoyer un indice',
        'back_to_login' => '← Retour à la connexion',
        'sent' => 'Si un compte correspondant a été trouvé, un indice a été envoyé à l\'adresse e-mail enregistrée.',
    ],
    'mail' => [
        'reset_password' => [
            'subject' => 'Réinitialisez votre mot de passe OGameX',
            'heading' => 'Réinitialisation du mot de passe',
            'greeting' => 'Bonjour :nom d\'utilisateur,',
            'body' => 'Nous avons reçu une demande de réinitialisation du mot de passe de votre compte. Cliquez sur le bouton ci-dessous pour choisir un nouveau mot de passe.',
            'cta' => 'Réinitialiser le mot de passe',
            'expiry' => 'Ce lien expirera dans 60 minutes.',
            'no_action' => 'Si vous n\'avez pas demandé de réinitialisation du mot de passe, aucune autre action n\'est requise.',
            'url_fallback' => 'Si vous ne parvenez pas à cliquer sur le bouton, copiez et collez l\'URL ci-dessous dans votre navigateur :',
        ],
        'retrieve_email' => [
            'subject' => 'Votre adresse e-mail OGameX',
            'heading' => 'Indice d\'adresse e-mail',
            'greeting' => 'Bonjour :nom d\'utilisateur,',
            'body' => 'Vous avez demandé un indice pour l\'adresse e-mail associée à votre compte :',
            'cta' => 'Allez dans Connexion',
            'no_action' => 'Si vous n\'avez pas fait cette demande, vous pouvez ignorer cet e-mail en toute sécurité.',
        ],
    ],
    'universe_characteristics' => [
        'fleet_speed' => 'Vitesse de la flotte : plus la valeur est élevée, moins il vous reste de temps pour réagir à une attaque.',
        'economy_speed' => 'Vitesse économique : plus la valeur est élevée, plus les constructions et les recherches seront achevées et les ressources collectées rapidement.',
        'debris_ships' => 'Certains des navires détruits au combat entreront dans le champ de débris.',
        'debris_defence' => 'Certaines des structures défensives détruites au combat entreront dans le champ de débris.',
        'dark_matter_gift' => 'Vous recevrez Dark Matter en récompense pour avoir confirmé votre adresse e-mail.',
        'aks_on' => 'Système de combat de l\'Alliance activé',
        'planet_fields' => 'Le nombre maximum d\'emplacements de construction a été augmenté.',
        'wreckfield' => 'Space Dock activé : certains vaisseaux détruits peuvent être restaurés à l\'aide du Space Dock.',
        'universe_big' => 'Nombre de galaxies dans l\'univers',
    ],
];
