<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : sk (OGame: sk)
 * Source   : resources/lang/en/t_external.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'browser_warning' => [
        'title' => 'Váš prehliadač nie je aktuálny.',
        'desc1' => 'Vaša verzia prehliadača Internet Explorer nezodpovedá existujúcim štandardom a táto webová stránka ju už nepodporuje.',
        'desc2' => 'Ak chcete používať túto webovú stránku, aktualizujte svoj webový prehliadač na aktuálnu verziu alebo použite iný webový prehliadač. Ak už používate najnovšiu verziu, znova načítajte stránku, aby sa správne zobrazila.',
        'desc3' => 'Tu je zoznam najpopulárnejších prehliadačov. Kliknutím na jeden zo symbolov sa dostanete na stránku sťahovania:',
    ],
    'login' => [
        'page_title' => 'OGame - Dobite vesmír',
        'btn' => 'Prihláste sa',
        'email_label' => 'E-mailová adresa:',
        'password_label' => 'heslo:',
        'universe_label' => 'Vesmír',
        'universe_option_1' => '1. Vesmír',
        'submit' => 'Prihláste sa',
        'forgot_password' => 'Zabudli ste heslo?',
        'forgot_email' => 'Zabudli ste svoju e-mailovú adresu?',
        'terms_accept_html' => 'Prihlásením akceptujem <a class="" href="#" target="_blank" title="T&amp;Cs">T&amp;Cs</a>',
    ],
    'register' => [
        'play_free' => 'HRAJTE ZADARMO!',
        'email_label' => 'E-mailová adresa:',
        'password_label' => 'heslo:',
        'universe_label' => 'Vesmír',
        'distinctions' => 'Vyznamenania',
        'terms_html' => 'V hre platia naše <a class="" target="_blank" href="#" title="T&amp;Cs"> T&Cs </a> a <a class="" target="_blank" href="#" title="Zásady ochrany osobných údajov"> Zásady ochrany osobných údajov</a>',
        'submit' => 'Zaregistrujte sa',
    ],
    'nav' => [
        'home' => 'Domov',
        'about' => 'O hre OGame',
        'media' => 'Médiá',
        'wiki' => 'Wiki',
    ],
    'home' => [
        'title' => 'OGame - Dobite vesmír',
        'description_html' => '<em>OGame</em> je strategická hra odohrávajúca sa vo vesmíre, v ktorej súčasne súťažia tisíce hráčov z celého sveta. Na hranie vám stačí obyčajný webový prehliadač.',
        'board_btn' => 'rady',
        'trailer_title' => 'Trailer',
    ],
    'footer' => [
        'legal' => 'Tiráž',
        'privacy_policy' => 'Zásady ochrany osobných údajov',
        'terms' => 'VOP',
        'contact' => 'Kontaktovať',
        'rules' => 'Pravidlá',
        'copyright' => '© OGameX. Všetky práva vyhradené.',
    ],
    'js' => [
        'login' => 'Prihláste sa',
        'close' => 'Zavrieť',
        'age_check_failed' => 'Je nám ľúto, ale nemáte nárok na registráciu. Viac informácií nájdete v našich T&C.',
    ],
    'validation' => [
        'required' => 'Toto pole je povinné',
        'make_decision' => 'Rozhodnite sa',
        'accept_terms' => 'Musíte prijať VOP.',
        'length' => 'Povolených 3 až 20 znakov.',
        'pw_length' => 'Povolených 4 až 20 znakov.',
        'email' => 'Musíte zadať platnú e-mailovú adresu!',
        'invalid_chars' => 'Obsahuje neplatné znaky.',
        'no_begin_end_underscore' => 'Vaše meno nesmie začínať ani končiť podčiarkovníkom.',
        'no_begin_end_whitespace' => 'Vaše meno nesmie začínať ani končiť medzerou.',
        'max_three_underscores' => 'Vaše meno nesmie celkovo obsahovať viac ako 3 podčiarkovníky.',
        'max_three_whitespaces' => 'Vaše meno nesmie celkovo obsahovať viac ako 3 medzery.',
        'no_consecutive_underscores' => 'Nesmiete použiť dve alebo viac podčiarkovníkov za sebou.',
        'no_consecutive_whitespaces' => 'Nesmiete použiť dve alebo viac medzier za sebou.',
        'username_available' => 'Toto používateľské meno je k dispozícii.',
        'username_loading' => 'Čakajte prosím, načítava sa...',
        'username_taken' => 'Toto používateľské meno už nie je dostupné.',
        'only_letters' => 'Používajte iba znaky.',
    ],
    'forgot_password' => [
        'title' => 'Zabudli ste heslo?',
        'description' => 'Zadajte svoju e-mailovú adresu nižšie a my vám pošleme odkaz na obnovenie hesla.',
        'email_label' => 'E-mailová adresa:',
        'submit' => 'Odoslať odkaz na obnovenie',
        'back_to_login' => '← Späť na prihlásenie',
    ],
    'reset_password' => [
        'title' => 'Obnovte svoje heslo',
        'email_label' => 'E-mailová adresa:',
        'password_label' => 'Nové heslo:',
        'confirm_label' => 'Potvrďte nové heslo:',
        'submit' => 'Obnoviť heslo',
    ],
    'forgot_email' => [
        'title' => 'Zabudli ste svoju e-mailovú adresu?',
        'description' => 'Zadajte svoje meno veliteľa a my vám pošleme nápovedu na registrovanú e-mailovú adresu.',
        'username_label' => 'Meno veliteľa:',
        'submit' => 'Odoslať nápovedu',
        'back_to_login' => '← Späť na prihlásenie',
        'sent' => 'Ak sa našiel zodpovedajúci účet, na registrovanú e-mailovú adresu bola odoslaná nápoveda.',
    ],
    'mail' => [
        'reset_password' => [
            'subject' => 'Obnovte svoje heslo OGameX',
            'heading' => 'Obnovenie hesla',
            'greeting' => 'Dobrý deň: užívateľské meno,',
            'body' => 'Dostali sme žiadosť o obnovenie hesla k vášmu účtu. Kliknite na tlačidlo nižšie a vyberte si nové heslo.',
            'cta' => 'Obnoviť heslo',
            'expiry' => 'Platnosť tohto odkazu vyprší o 60 minút.',
            'no_action' => 'Ak ste nepožiadali o obnovenie hesla, nie je potrebná žiadna ďalšia akcia.',
            'url_fallback' => 'Ak máte problémy s kliknutím na tlačidlo, skopírujte nižšie uvedenú adresu URL a vložte ju do svojho prehliadača:',
        ],
        'retrieve_email' => [
            'subject' => 'Vaša e-mailová adresa OGameX',
            'heading' => 'Tip na e-mailovú adresu',
            'greeting' => 'Dobrý deň: užívateľské meno,',
            'body' => 'Požiadali ste o nápovedu pre e-mailovú adresu priradenú k vášmu účtu:',
            'cta' => 'Prejdite na Prihlásenie',
            'no_action' => 'Ak ste túto žiadosť neodoslali, môžete tento e-mail pokojne ignorovať.',
        ],
    ],
    'universe_characteristics' => [
        'fleet_speed' => 'Rýchlosť flotily: čím vyššia hodnota, tým menej času vám zostáva na reakciu na útok.',
        'economy_speed' => 'Hospodárnosť Rýchlosť: čím vyššia hodnota, tým rýchlejšie budú dokončené stavby a výskum a zhromaždené zdroje.',
        'debris_ships' => 'Niektoré z lodí zničených v boji vstúpia do poľa trosiek.',
        'debris_defence' => 'Niektoré z obranných štruktúr zničených v boji sa dostanú do poľa trosiek.',
        'dark_matter_gift' => 'Temnú hmotu dostanete ako odmenu za potvrdenie vašej e-mailovej adresy.',
        'aks_on' => 'Aktivovaný bojový systém Aliancie',
        'planet_fields' => 'Maximálny počet stavebných slotov sa zvýšil.',
        'wreckfield' => 'Space Dock aktivovaný: niektoré zničené lode je možné obnoviť pomocou Space Dock.',
        'universe_big' => 'Množstvo galaxií vo vesmíre',
    ],
];
