<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : sk (OGame: sk)
 * Source   : resources/lang/en/t_resources.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'metal_mine' => [
        'title' => 'Ťažobný komplex - kovy',
        'description' => 'Tento ťažobný komplex dobýva rudy rozličných kovov. Získané kovy sa následne ďalej spracovávajú a zušľachťujú na materiály, ktoré sú najdôležitejšími surovinami, slúžiacimi ako základ rozvoja impérií.',
        'description_long' => 'Tento ťažobný komplex dobýva rudy rozličných kovov. Získané kovy sa následne ďalej spracovávajú a zušľachťujú na materiály, ktoré sú najdôležitejšími surovinami, slúžiacimi ako základ rozvoja impérií.',
    ],
    'crystal_mine' => [
        'title' => 'Ťažobný komplex - kryštály',
        'description' => 'Kryštály sú hlavnou surovinou, používanou pri výrobe elektrických obvodov a tvorbe presných zliatinových zmesí.',
        'description_long' => 'Kryštály sú hlavnou surovinou, používanou pri výrobe elektrických obvodov a tvorbe presných zliatinových zmesí.',
    ],
    'deuterium_synthesizer' => [
        'title' => 'Syntetizéry deutéria',
        'description' => 'Deutérium sa používa ako palivo vesmírnych lodí. Získava sa z morských hĺbok. Ide o vzácnu látku, preto je relatívne drahá.',
        'description_long' => 'Deutérium sa používa ako palivo vesmírnych lodí. Získava sa z morských hĺbok. Ide o vzácnu látku, preto je relatívne drahá.',
    ],
    'solar_plant' => [
        'title' => 'Solárne elektrárne',
        'description' => 'Solárne elektrárne využívajú energiu zo slnečného žiarenia. Dostatok energie je predpokladom rozvoja technickej civilizácie. Väčšina budov je energeticky sebestačná, ale najmä ťažba a výroba vyžaduje pre efektívne fungovanie dodávky energie.',
        'description_long' => 'Solárne elektrárne využívajú energiu zo slnečného žiarenia. Dostatok energie je predpokladom rozvoja technickej civilizácie. Väčšina budov je energeticky sebestačná, ale najmä ťažba a výroba vyžaduje pre efektívne fungovanie dodávky energie.',
    ],
    'fusion_plant' => [
        'title' => 'Fúzne elektrárne',
        'description' => 'Fúzne elektrárne vyrábajú v reaktoroch energiu fúziou deutéria na hélium.',
        'description_long' => 'Fúzne elektrárne vyrábajú v reaktoroch energiu fúziou deutéria na hélium.',
    ],
    'metal_store' => [
        'title' => 'Sklady kovov',
        'description' => 'Miesta, kde sa uskladňujú nespracované kovy pred ďalším použitím.',
        'description_long' => 'Miesta, kde sa uskladňujú nespracované kovy pred ďalším použitím.',
    ],
    'crystal_store' => [
        'title' => 'Sklady kryštálov',
        'description' => 'Miesta, kde sa uskladňujú nespracované kryštály pred ďalším použitím.',
        'description_long' => 'Miesta, kde sa uskladňujú nespracované kryštály pred ďalším použitím.',
    ],
    'deuterium_store' => [
        'title' => 'Nádrže na deutérium',
        'description' => 'Obrovské nádrže na skladovanie čerstvo syntetizovaného deutéria.',
        'description_long' => 'Obrovské nádrže na skladovanie čerstvo syntetizovaného deutéria.',
    ],
    'robot_factory' => [
        'title' => 'Robotické továrne',
        'description' => 'Továreň na robotov produkuje robokonštruktérov, ktorí zefektívňujú výstavbu budov. Každá úroveň zvyšuje rýchlosť vylepšovania stavieb.',
        'description_long' => 'Továreň na robotov produkuje robokonštruktérov, ktorí zefektívňujú výstavbu budov. Každá úroveň zvyšuje rýchlosť vylepšovania stavieb.',
    ],
    'shipyard' => [
        'title' => 'Lodenice',
        'description' => 'V lodeniciach sú stavané všetky typy lodí a obranných zariadení.',
        'description_long' => 'V lodeniciach sú stavané všetky typy lodí a obranných zariadení.',
    ],
    'research_lab' => [
        'title' => 'Výskumné laboratóriá',
        'description' => 'Výskumné laboratóriá sú nutné pre objavovanie nových technólogií.',
        'description_long' => 'Výskumné laboratóriá sú nutné pre objavovanie nových technólogií.',
    ],
    'alliance_depot' => [
        'title' => 'Aliančný sklad',
        'description' => 'Aliančný sklad dodáva palivo spriateleným flotilám na obežnej dráhe, pomáhajúc im pri obrane.',
        'description_long' => 'Aliančný sklad dodáva palivo spriateleným flotilám na obežnej dráhe, pomáhajúc im pri obrane.',
    ],
    'missile_silo' => [
        'title' => 'Raketové silo',
        'description' => 'Raketové silá slúžia ako skladiská a palebné postavenia rakiet.',
        'description_long' => 'Raketové silá slúžia ako skladiská a palebné postavenia rakiet.',
    ],
    'nano_factory' => [
        'title' => 'Nanotechnologické továrne',
        'description' => 'Nanotechnologické továrne predstavujú vrchol robotických technológií. Každou úrovňou sa skracujú konštrukčné časy budov, lodí a obranných zariadení.',
        'description_long' => 'Nanotechnologické továrne predstavujú vrchol robotických technológií. Každou úrovňou sa skracujú konštrukčné časy budov, lodí a obranných zariadení.',
    ],
    'terraformer' => [
        'title' => 'Terraformer',
        'description' => 'Terraformer zväčšuje výmeru použiteľného povrchu planéty.',
        'description_long' => 'Terraformer zväčšuje výmeru použiteľného povrchu planéty.',
    ],
    'space_dock' => [
        'title' => 'Vesmírne doky',
        'description' => 'Vo vesmírnych dokoch je možné opravovať vraky lodí.',
        'description_long' => 'Vo vesmírnych dokoch je možné opravovať vraky lodí.',
    ],
    'lunar_base' => [
        'title' => 'Mesačná základňa',
        'description' => 'Keďže Mesiac nemá atmosféru, na vytvorenie obývateľného priestoru je potrebná lunárna základňa.',
        'description_long' => 'Vzhľadom na to, že mesiac nemá žiadnu atmosféru, je pre získanie osídliteľného priestoru nutné vybudovať Mesačnú základňu.',
    ],
    'sensor_phalanx' => [
        'title' => 'Parabolické teleskopy',
        'description' => 'Pomocou senzorovej falangy možno objaviť a pozorovať flotily iných impérií. Čím väčšie je pole senzorovej falangy, tým väčší rozsah dokáže skenovať.',
        'description_long' => 'Použitím parabolických teleskopov môžu byť odhalené a pozorované planéty alebo flotily. S ich  úrovňou rastie aj rozsah skenovania.',
    ],
    'jump_gate' => [
        'title' => 'Hyperpriestorová brána',
        'description' => 'Skokové brány sú obrovské transceivery schopné poslať aj tú najväčšiu flotilu v krátkom čase do vzdialenej skokovej brány.',
        'description_long' => 'Medzipriestorové brány sú vlastne veľké prevodníky, ktoré dokážu v nulovom čase premiestniť aj tú najväčšiu flotilu na svoj opačný koniec.',
    ],
    'energy_technology' => [
        'title' => 'Energetické technológie',
        'description' => 'Ovládnutie rôznych druhov energií je nevyhnutné pre rozvoj nových technológií.',
        'description_long' => 'Ovládnutie rôznych druhov energií je nevyhnutné pre rozvoj nových technológií.',
    ],
    'laser_technology' => [
        'title' => 'Laserové technológie',
        'description' => 'Koncentráciou a zaostrením svetla sa získava lúč vysokej energie, ktorý spôsobuje poškodenie, pri dopade na objekty.',
        'description_long' => 'Koncentráciou a zaostrením svetla sa získava lúč vysokej energie, ktorý spôsobuje poškodenie, pri dopade na objekty.',
    ],
    'ion_technology' => [
        'title' => 'Iónové technológie',
        'description' => 'Zbrane, využívajúce technológiu koncentrácie iónov, spôsobujú obrovské poškodenie cieľa. Každá úroveň vývoja tejto technológie navyše zníži náklady na demontáž budov o 4%.',
        'description_long' => 'Zbrane, využívajúce technológiu koncentrácie iónov, spôsobujú obrovské poškodenie cieľa. Každá úroveň vývoja tejto technológie navyše zníži náklady na demontáž budov o 4%.',
    ],
    'hyperspace_technology' => [
        'title' => 'Hyperpriestorové technológie',
        'description' => 'Integráciou 4. a 5. dimenzie je teraz možné skúmať nový druh pohonu, ktorý je hospodárnejší a efektívnejší.',
        'description_long' => 'Integráciou 4. a 5. dimenzie je teraz možné skúmať nový druh pohonu, ktorý je ekonomickejší a najmä efektívnejší. Využitím štvrtého a piateho rozmeru je teraz možné optimalizovať úložné priestory lodí a získať tak nový priestor.',
    ],
    'plasma_technology' => [
        'title' => 'Plazmové technológie',
        'description' => 'Ďalší vývojový stupeň iónových technológií, kde dochádza k urýchľovaniu vysokoenergetickej plazmy. Výsledkom je mimoriadne devastujúci účinok na zasahovaný objekt a tiež zvýšenie produkcie kovov, kryštálov a deutéria (o 1%/0,66%/0,33% za úroveň).',
        'description_long' => 'Ďalší vývojový stupeň iónových technológií, kde dochádza k urýchľovaniu vysokoenergetickej plazmy. Výsledkom je mimoriadne devastujúci účinok na zasahovaný objekt a tiež zvýšenie produkcie kovov, kryštálov a deutéria (o 1%/0,66%/0,33% za úroveň).',
    ],
    'combustion_drive' => [
        'title' => 'Spaľovací pohon',
        'description' => 'Základná pohonná jednotka. Ďalší vývoj vedie k zrýchleniu lodí. Každá úroveň zdokonalenia zvyšuje rýchlosť o 10% zo základnej hodnoty.',
        'description_long' => 'Základná pohonná jednotka. Ďalší vývoj vedie k zrýchleniu lodí. Každá úroveň zdokonalenia zvyšuje rýchlosť o 10% zo základnej hodnoty.',
    ],
    'impulse_drive' => [
        'title' => 'Impulzný pohon',
        'description' => 'Impulzný pohon vychádza zo spaľovacieho a je tiež založený na princípe akcie a reakcie. Ďalší rozvoj tohoto pohonu umožňuje lietať lodiam rýchlejšie. Každá úroveň zdokonalenia zvyšuje rýchlosť o 20% zo základnej hodnoty.',
        'description_long' => 'Impulzný pohon vychádza zo spaľovacieho a je tiež založený na princípe akcie a reakcie. Ďalší rozvoj tohoto pohonu umožňuje lietať lodiam rýchlejšie. Každá úroveň zdokonalenia zvyšuje rýchlosť o 20% zo základnej hodnoty.',
    ],
    'hyperspace_drive' => [
        'title' => 'Hyperpriestorový pohon',
        'description' => 'Hyperpriestorový pohon ohýba priestor okolo lode. Objavenie tohoto princípu pohonu výrazne zrýchlilo cestovanie vesmírom. Každým stupňom vylepšenia stúpa rýchlosť o 30% základnej hodnoty.',
        'description_long' => 'Hyperpriestorový pohon ohýba priestor okolo lode. Objavenie tohoto princípu pohonu výrazne zrýchlilo cestovanie vesmírom. Každým stupňom vylepšenia stúpa rýchlosť o 30% základnej hodnoty.',
    ],
    'espionage_technology' => [
        'title' => 'Špionážne technológie',
        'description' => 'Použitím tejto technológie môžeš získať informácie o ostatných planétach a mesiacoch.',
        'description_long' => 'Použitím tejto technológie môžeš získať informácie o ostatných planétach a mesiacoch.',
    ],
    'computer_technology' => [
        'title' => 'Počítačové technológie',
        'description' => 'Zvyšovaním kapacity počítačov máš možnosť veliť viacerým flotilám. Každá ďalšia úroveň počítačových  technológií zvyšuje maximálny počet flotíl o jednu.',
        'description_long' => 'Zvyšovaním kapacity počítačov máš možnosť veliť viacerým flotilám. Každá ďalšia úroveň počítačových  technológií zvyšuje maximálny počet flotíl o jednu.',
    ],
    'astrophysics' => [
        'title' => 'Astrofyzika',
        'description' => 'Lode sú vybavené prieskumnými modulmi a môžu podnikať výpravy do hlbokého vesmíru. Každé dve vyskúmané úrovne tejto technológie umožňujú kolonizovať ďalšiu planétu.',
        'description_long' => 'Lode sú vybavené prieskumnými modulmi a môžu podnikať výpravy do hlbokého vesmíru. Každé dve vyskúmané úrovne tejto technológie umožňujú kolonizovať ďalšiu planétu.',
    ],
    'intergalactic_research_network' => [
        'title' => 'Intergalaktická výskumná sieť',
        'description' => 'Prostredníctvom tejto vysokorýchlostnej siete komunikujú výskumníci z rôznych planét.',
        'description_long' => 'Prostredníctvom tejto vysokorýchlostnej siete komunikujú výskumníci z rôznych planét.',
    ],
    'graviton_technology' => [
        'title' => 'Gravitonové technológie',
        'description' => 'Vypálenie koncentrovaného paprsku gravitónových častíc môže vytvoriť umelé gravitačné pole, ktoré dokáže zničiť lode alebo dokonca aj mesiace.',
        'description_long' => 'Vypálenie koncentrovaného paprsku gravitónových častíc môže vytvoriť umelé gravitačné pole, ktoré dokáže zničiť lode alebo dokonca aj mesiace.',
    ],
    'weapon_technology' => [
        'title' => 'Zbrojárske technológie',
        'description' => 'Zbrojárske technológie zefektívňujú prácu zbraňových systémov. Každá úroveň zbrojárskej technológie zvyšuje sílu zbraní jednotiek o 10% zo základnej hodnoty.',
        'description_long' => 'Zbrojárske technológie zefektívňujú prácu zbraňových systémov. Každá úroveň zbrojárskej technológie zvyšuje sílu zbraní jednotiek o 10% zo základnej hodnoty.',
    ],
    'shielding_technology' => [
        'title' => 'Technológie štítov',
        'description' => 'Technológia štítov robí štíty na lodiach a obranných zariadeniach efektívnejšie. Každá úroveň technológie štítov zvyšuje pevnosť štítov o 10 % základnej hodnoty.',
        'description_long' => 'Technológie štítu zefektívňujú činnosť štítov na lodiach a obranných zariadeniach. Každá úroveň týchto technológií zvyšuje silu štítov o 10% zo základnej hodnoty.',
    ],
    'armor_technology' => [
        'title' => 'Pancierovanie',
        'description' => 'Špeciálne zliatiny zdokonaľujú pancierovanie na lodiach a obranných zariadeniach. Účinnosť obrnenia stúpa o 10% pri každom zvýšení úrovne.',
        'description_long' => 'Špeciálne zliatiny zdokonaľujú pancierovanie na lodiach a obranných zariadeniach. Účinnosť obrnenia stúpa o 10% pri každom zvýšení úrovne.',
    ],
    'small_cargo' => [
        'title' => 'Malý transportér',
        'description' => 'Malý transportér je obratná loď, ktorá dokáže rýchlo prevážať zdroje na iné planéty.',
        'description_long' => 'Malý transportér je obratná loď, ktorá dokáže rýchlo prevážať zdroje na iné planéty.',
    ],
    'large_cargo' => [
        'title' => 'Veľký transportér',
        'description' => 'Zdokonalenie malého transportéra sa vyznačuje podstatne väčšou nákladovou kapacitou a vďaka výkonnejšiemu pohonu aj vyššou rýchlosťou.',
        'description_long' => 'Zdokonalenie malého transportéra sa vyznačuje podstatne väčšou nákladovou kapacitou a vďaka výkonnejšiemu pohonu aj vyššou rýchlosťou.',
    ],
    'colony_ship' => [
        'title' => 'Kolonizačná loď',
        'description' => 'Pomocou tejto lode je možné kolonizovať neznáme planéty.',
        'description_long' => 'Pomocou tejto lode je možné kolonizovať neznáme planéty.',
    ],
    'recycler' => [
        'title' => 'Recyklátor',
        'description' => 'Recyklátory sú jediné lode, ktoré dokážu po boji zbierať polia s troskami plávajúcimi na obežnej dráhe planéty.',
        'description_long' => 'Recyklátory sú jediné lode, schopné zozbierať trosky, ktoré sa vznášajú po bojoch na obežných dráhach planét.',
    ],
    'espionage_probe' => [
        'title' => 'Špionážna sonda',
        'description' => 'Las sondas de espionaje son pequeños droides no tripulados con un sistema de propulsión excepcionalmente rápido usado para espiar en planetas enemigos.',
        'description_long' => 'Špionážne sondy sú malé, obratné stroje, zisťujúce údaje o flotilách a planétach a zasielajúce ich na veľké vzdialenosti.',
    ],
    'solar_satellite' => [
        'title' => 'Solárny satelit',
        'description' => 'Solárne satelity sú jednoduché platformy solárnych článkov, ktoré sa nachádzajú na vysokej, stacionárnej obežnej dráhe. Zhromažďujú slnečné svetlo a prenášajú ho na pozemnú stanicu pomocou lasera.',
        'description_long' => 'Solárne satelity sú jednoduché základne, zostavené zo solárnych panelov. Sú umiestnené na vysokej geostacionárnej obežnej dráhe. Zachytávajú energiu slnečného žiarenia a prenášajú ju pomocou lasera do pozemných staníc. Solárne satelity na tejto planéte produkujú 35 j. energie.',
    ],
    'crawler' => [
        'title' => 'Vrták',
        'description' => 'Los Taladradores aumentan la producción de metal, cristal y deuterio en el planeta en el que se utilicen en un 0.02 %, un 0.02 % y un 0.02 % respectivamente. Un Recolector también disfruta de un aumento de la producción. La bonificación total máxima depende del nivel total de tus minas.',
        'description_long' => 'Hĺbkové vrtáky zvyšujú produkciu kovov, kryštálov a deutéria na planéte nasadenia o 0,02%, 0,02% a 0,02%. Ako zberateľ máš tiež vyššiu produkciu. Maximálny celkový bonus závisí od úrovne rozšírenia ťažobných komplexov.',
    ],
    'pathfinder' => [
        'title' => 'Prieskumník',
        'description' => 'Pathfinder je rýchla a obratná loď, určená na výpravy do neznámych sektorov vesmíru.',
        'description_long' => 'Prieskumné lode sú rýchle, priestranné a dokážu na výpravách ťažiť troskové polia. Celkový výnos je tiež zvýšený.',
    ],
    'light_fighter' => [
        'title' => 'Ľahký stíhač',
        'description' => 'Ľahký stíhač je prvá loď, ktorú dokáže vybudovať každé impérium. Vyznačuje sa obratnosťou, no je ľahko zraniteľná. Vo veľkých počtoch môže predstavovať vážne nebezpečenstvo. Používa sa najmä ako doprovod pre malé a veľké transporty, pri misiách na planéty so slabou obranou.',
        'description_long' => 'Ľahký stíhač je prvá loď, ktorú dokáže vybudovať každé impérium. Vyznačuje sa obratnosťou, no je ľahko zraniteľná. Vo veľkých počtoch môže predstavovať vážne nebezpečenstvo. Používa sa najmä ako doprovod pre malé a veľké transporty, pri misiách na planéty so slabou obranou.',
    ],
    'heavy_fighter' => [
        'title' => 'Ťažký stíhač',
        'description' => 'Toto zdokonalenie ľahkého stíhača sa vyznačuje výkonnejšou pohonnou jednotkou, lepším pancierovaním a väčšou palebnou silou ako jeho predchodca.',
        'description_long' => 'Toto zdokonalenie ľahkého stíhača sa vyznačuje výkonnejšou pohonnou jednotkou, lepším pancierovaním a väčšou palebnou silou ako jeho predchodca.',
    ],
    'cruiser' => [
        'title' => 'Krížnik',
        'description' => 'Krížniky majú približne trikrát mohutnejšie pancierovanie, v porovnaní s ťažkými stíhačmi a disponujú viac než dvojnásobnou palebnou silou. Navyše, sú tiež veľmi rýchle.',
        'description_long' => 'Krížniky majú približne trikrát mohutnejšie pancierovanie, v porovnaní s ťažkými stíhačmi a disponujú viac než dvojnásobnou palebnou silou. Navyše, sú tiež veľmi rýchle.',
    ],
    'battle_ship' => [
        'title' => 'Bojová loď',
        'description' => 'Bojové lode tvoria obvykle chrbticu flotily. Ich ťažké kanóny, vysoká rýchlosť a veľký nákladový priestor z nich robia vážnych protivníkov.',
        'description_long' => 'Bojové lode tvoria obvykle chrbticu flotily. Ich ťažké kanóny, vysoká rýchlosť a veľký nákladový priestor z nich robia vážnych protivníkov.',
    ],
    'battlecruiser' => [
        'title' => 'Bojový krížnik',
        'description' => 'El Acorazado es una nave altamente especializada en la intercepción de flotas hostiles.',
        'description_long' => 'Bojový krížnik je úzko špecializovaný na prenasledovanie nepriateľských flotíl.',
    ],
    'bomber' => [
        'title' => 'Bombardér',
        'description' => 'El Bombardero es una nave de propósito especial, desarrollado para atravesar las defensas planetarias más pesadas.',
        'description_long' => 'Bombardér bol primárne vyvinutý na zničenie planetárnej obrany protivníka.',
    ],
    'destroyer' => [
        'title' => 'Devastátor',
        'description' => 'El destructor es la nave más pesada jamás vista y posee un potencial de ataque sin precedentes.',
        'description_long' => 'Devastátor je kráľom vojnových lodí.',
    ],
    'deathstar' => [
        'title' => 'Hviezda smrti',
        'description' => 'No hay nada tan grande y peligroso como una estrella de la muerte aproximándose.',
        'description_long' => 'Zničujúca sila Hviezdy smrti je neprekonateľná.',
    ],
    'reaper' => [
        'title' => 'Kosa',
        'description' => 'Reaper je výkonná bojová loď špecializovaná na agresívne nájazdy a zber trosiek na poli.',
        'description_long' => 'Loď triedy Kosa je mohutným prostriedkom deštrukcie, ktorý dokáže vyťažiť troskové pole ihneď po bitke.',
    ],
    'rocket_launcher' => [
        'title' => 'Raketový komplet',
        'description' => 'El lanzamisiles es un sistema de defensa sencillo, pero barato.',
        'description_long' => 'Raketový komplet je jednoduchá a cenovo efektívna voľba obrany.',
    ],
    'light_laser' => [
        'title' => 'Ľahký laser',
        'description' => 'Por medio de un rayo láser concentrado, se puede provocar más daño que con las armas balísticas normales.',
        'description_long' => 'Koncentrované ostreľovanie objektu fotónmi môže spôsobiť výrazne väčšie poškodenie než konvenčné strelné zbrane.',
    ],
    'heavy_laser' => [
        'title' => 'Ťažký laser',
        'description' => 'Los lásers grandes poseen una mejor producción de energía y una mayor integridad estructural que los lásers pequeños.',
        'description_long' => 'Ťažký laser je logickým vyústením vývoja ľahkých laserov.',
    ],
    'gauss_cannon' => [
        'title' => 'Gaussov kanón',
        'description' => 'Usando una inmensa aceleración electromagnética, los cañones gauss aceleran proyectiles pesados.',
        'description_long' => 'Gaussov kanón vystreľuje extrémne urýchlené projektily obrovskej hmotnosti.',
    ],
    'ion_cannon' => [
        'title' => 'Iónový kanón',
        'description' => 'Los cañones iónicos disparan rayos de iones altamente energizados contra su objetivo, desestabilizando los escudos y destruyendo los componentes electrónicos.',
        'description_long' => 'Iónový kanón emituje nepretržitý lúč zrýchlených iónov vysokej energie, ktoré spôsobujú značné poškodenie objektov, na ktoré dopadajú.',
    ],
    'plasma_turret' => [
        'title' => 'Plazmová veža',
        'description' => 'Los cañones de plasma liberan la energía de una pequeña erupción solar en una bala de plasma. La energía destructiva es incluso superior a la del Destructor.',
        'description_long' => 'Plazmové veže vystreľujú hmotu o teplote porovnateľnej so slnečnými erupciami a ničivým účinkom prekonávajú aj najvyššie triedy lodí.',
    ],
    'small_shield_dome' => [
        'title' => 'Malý planetárny štít',
        'description' => 'La cúpula pequeña de defensa cubre el planeta con un delgado campo protector que puede absorber inmensas cantidades de energía.',
        'description_long' => 'Malý planetárny štít chráni celú planétu silovým poľom, ktoré dokáže pohltiť obrovské množstvo energie.',
    ],
    'large_shield_dome' => [
        'title' => 'Veľký planetárny štít',
        'description' => 'La cúpula grande de protección proviene de una tecnología de defensa mejorada que absorbe incluso más energía antes de colapsar.',
        'description_long' => 'Pokračovaním vývoja malého štítu je tento štít, ktorý dokáže pohltiť významne väčšie energie a odolávať tak útokom.',
    ],
    'anti_ballistic_missile' => [
        'title' => 'Protiraketové strely',
        'description' => 'Los misiles de intercepción destruyen los misiles interplanetarios.',
        'description_long' => 'Protiraketové strely dokážu zničiť útočiace medziplanetárne rakety.',
    ],
    'interplanetary_missile' => [
        'title' => 'Medziplanetárne rakety',
        'description' => 'Medziplanetárne rakety ničia nepriateľskú obranu.',
        'description_long' => 'Medziplanetárne rakety ničia nepriateľskú obranu. Medziplanetárne rakety majú aktuálny dosah 0.',
    ],
    'kraken' => [
        'title' => 'KRAKEN',
        'description' => 'Skráti čas výstavby budov, ktoré sú momentálne vo výstavbe, o <b>:duration</b>.',
    ],
    'detroid' => [
        'title' => 'DETROID',
        'description' => 'Znižuje čas výstavby súčasných zmlúv s lodenicami o <b>:duration</b>.',
    ],
    'newtron' => [
        'title' => 'NEWTRON',
        'description' => 'Skracuje čas potrebný na výskum pre celý výskum, ktorý práve prebieha, o <b>:duration</b>.',
    ],
];
