<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : pl (OGame: pl)
 * Source   : resources/lang/en/t_external.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'browser_warning' => [
        'title' => 'Twoja przeglądarka nie jest aktualna.',
        'desc1' => 'Twoja wersja przeglądarki Internet Explorer nie odpowiada istniejącym standardom i nie jest już obsługiwana przez tę witrynę.',
        'desc2' => 'Aby móc korzystać z tej witryny prosimy o aktualizację przeglądarki internetowej do aktualnej wersji lub skorzystanie z innej przeglądarki internetowej. Jeśli korzystasz już z najnowszej wersji, załaduj stronę ponownie, aby wyświetlić ją poprawnie.',
        'desc3' => 'Oto lista najpopularniejszych przeglądarek. Kliknij jeden z symboli, aby przejść do strony pobierania:',
    ],
    'login' => [
        'page_title' => 'OGame – podbij wszechświat',
        'btn' => 'Login',
        'email_label' => 'Adres e-mail:',
        'password_label' => 'Hasło:',
        'universe_label' => 'Świat gry',
        'universe_option_1' => '1. Wszechświat',
        'submit' => 'Zaloguj się',
        'forgot_password' => 'Zapomniałeś hasła?',
        'forgot_email' => 'Nie pamiętasz swojego adresu e-mail?',
        'terms_accept_html' => 'Logując się, akceptuję <a class="" href="#" target="_blank" title="Warunki">Regulamin</a>',
    ],
    'register' => [
        'play_free' => 'GRAJ ZA DARMO!',
        'email_label' => 'Adres e-mail:',
        'password_label' => 'Hasło:',
        'universe_label' => 'Świat gry',
        'distinctions' => 'Wyróżnienia',
        'terms_html' => 'W grze obowiązują nasze <a class="" target="_blank" href="#" title="Warunki"> Regulamin </a> i <a class="" target="_blank" href="#" title="Privacy Policy"> Polityka prywatności </a>',
        'submit' => 'Rejestr',
    ],
    'nav' => [
        'home' => 'Dom',
        'about' => 'O OGame',
        'media' => 'Głoska bezdźwięczna',
        'wiki' => 'Wiki',
    ],
    'home' => [
        'title' => 'OGame – podbij wszechświat',
        'description_html' => '<em>OGame</em> to gra strategiczna osadzona w kosmosie, w której jednocześnie rywalizują tysiące graczy z całego świata. Do gry potrzebujesz jedynie zwykłej przeglądarki internetowej.',
        'board_btn' => 'Tablica',
        'trailer_title' => 'Przyczepa',
    ],
    'footer' => [
        'legal' => 'Impressum',
        'privacy_policy' => 'Polityka prywatności',
        'terms' => 'Regulamin',
        'contact' => 'Kontakt',
        'rules' => 'Zasady gry',
        'copyright' => '© OGameX. Wszelkie prawa zastrzeżone.',
    ],
    'js' => [
        'login' => 'Login',
        'close' => 'Zamknąć',
        'age_check_failed' => 'Przepraszamy, ale nie możesz się zarejestrować. Aby uzyskać więcej informacji, zapoznaj się z naszym Regulaminem.',
    ],
    'validation' => [
        'required' => 'To pole jest wymagane',
        'make_decision' => 'Podejmij decyzję',
        'accept_terms' => 'Musisz zaakceptować Regulamin.',
        'length' => 'Dozwolone jest od 3 do 20 znaków.',
        'pw_length' => 'Dozwolone jest od 4 do 20 znaków.',
        'email' => 'Musisz podać prawidłowy adres e-mail!',
        'invalid_chars' => 'Zawiera nieprawidłowe znaki.',
        'no_begin_end_underscore' => 'Twoje imię i nazwisko nie może zaczynać się ani kończyć podkreśleniem.',
        'no_begin_end_whitespace' => 'Twoje imię i nazwisko nie może zaczynać się ani kończyć spacją.',
        'max_three_underscores' => 'Twoje imię i nazwisko nie może zawierać łącznie więcej niż 3 podkreśleń.',
        'max_three_whitespaces' => 'Twoje imię i nazwisko nie może zawierać łącznie więcej niż 3 spacje.',
        'no_consecutive_underscores' => 'Nie można używać dwóch lub więcej podkreśleń jeden po drugim.',
        'no_consecutive_whitespaces' => 'Nie możesz używać dwóch lub więcej spacji jedna po drugiej.',
        'username_available' => 'Ta nazwa użytkownika jest dostępna.',
        'username_loading' => 'Proszę czekać, ładuję...',
        'username_taken' => 'Ta nazwa użytkownika nie jest już dostępna.',
        'only_letters' => 'Używaj tylko znaków.',
    ],
    'forgot_password' => [
        'title' => 'Zapomniałeś hasła?',
        'description' => 'Wpisz poniżej swój adres e-mail, a my wyślemy Ci link umożliwiający zresetowanie hasła.',
        'email_label' => 'Adres e-mail:',
        'submit' => 'Wyślij link resetujący',
        'back_to_login' => '← Powrót do logowania',
    ],
    'reset_password' => [
        'title' => 'Zresetuj swoje hasło',
        'email_label' => 'Adres e-mail:',
        'password_label' => 'Nowe hasło:',
        'confirm_label' => 'Potwierdź nowe hasło:',
        'submit' => 'Zresetuj hasło',
    ],
    'forgot_email' => [
        'title' => 'Nie pamiętasz swojego adresu e-mail?',
        'description' => 'Wpisz swoje imię i nazwisko dowódcy, a my wyślemy podpowiedź na zarejestrowany adres e-mail.',
        'username_label' => 'Imię dowódcy:',
        'submit' => 'Wyślij podpowiedź',
        'back_to_login' => '← Powrót do logowania',
        'sent' => 'Jeśli znaleziono pasujące konto, na zarejestrowany adres e-mail została wysłana wskazówka.',
    ],
    'mail' => [
        'reset_password' => [
            'subject' => 'Zresetuj swoje hasło do OGameX',
            'heading' => 'Resetowanie hasła',
            'greeting' => 'Witamy: nazwa użytkownika,',
            'body' => 'Otrzymaliśmy prośbę o zresetowanie hasła do Twojego konta. Kliknij przycisk poniżej, aby wybrać nowe hasło.',
            'cta' => 'Zresetuj hasło',
            'expiry' => 'Ten link wygaśnie za 60 minut.',
            'no_action' => 'Jeśli nie poprosiłeś o zresetowanie hasła, nie są wymagane żadne dalsze działania.',
            'url_fallback' => 'Jeśli masz problemy z kliknięciem przycisku, skopiuj i wklej poniższy adres URL do swojej przeglądarki:',
        ],
        'retrieve_email' => [
            'subject' => 'Twój adres e-mail OGameX',
            'heading' => 'Wskazówka dotycząca adresu e-mail',
            'greeting' => 'Witamy: nazwa użytkownika,',
            'body' => 'Prosiłeś o podpowiedź dotyczącą adresu e-mail powiązanego z Twoim kontem:',
            'cta' => 'Przejdź do logowania',
            'no_action' => 'Jeśli to nie Ty złożyłeś tę prośbę, możesz bezpiecznie zignorować tę wiadomość.',
        ],
    ],
    'universe_characteristics' => [
        'fleet_speed' => 'Szybkość floty: im wyższa wartość, tym mniej czasu pozostało na reakcję na atak.',
        'economy_speed' => 'Szybkość ekonomiczna: im wyższa wartość, tym szybciej zostaną ukończone konstrukcje i badania, a zasoby zostaną zebrane.',
        'debris_ships' => 'Część statków zniszczonych w bitwie trafi na pole gruzu.',
        'debris_defence' => 'Część zniszczonych w bitwie budowli obronnych trafi na pole gruzu.',
        'dark_matter_gift' => 'W nagrodę za potwierdzenie adresu e-mail otrzymasz Dark Matter.',
        'aks_on' => 'Aktywowano system walki Sojuszu',
        'planet_fields' => 'Zwiększono maksymalną liczbę miejsc na budynki.',
        'wreckfield' => 'Aktywowano Dok Kosmiczny: niektóre zniszczone statki można przywrócić za pomocą Doku Kosmicznego.',
        'universe_big' => 'Ilość galaktyk we wszechświecie',
    ],
];
