<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : pl (OGame: pl)
 * Source   : resources/lang/en/t_facilities.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'space_dock' => [
        'name' => 'Dok kosmiczny',
        'description' => 'W doku kosmicznym można naprawiać pola wrakowe.',
        'description_long' => 'Space Dock oferuje możliwość naprawy statków zniszczonych w bitwie, które pozostawiły po sobie wrak. Czas naprawy wynosi maksymalnie 12 godzin, ale zanim statki będą mogły zostać ponownie oddane do użytku, minie co najmniej 30 minut. 

Ponieważ Stacja Kosmiczna unosi się na orbicie, nie wymaga pola planetarnego.',
        'requirements' => 'Wymaga poziomu Stoczni 2',
        'field_consumption' => 'Nie zużywa pól planet (unosi się na orbicie)',
        'wreck_field_section' => 'Pole wraków',
        'no_wreck_field' => 'W tej lokalizacji nie ma pola wrakowego.',
        'wreck_field_info' => 'Dostępne jest pole wraków zawierające statki, które można naprawić.',
        'ships_available' => 'Statki dostępne do naprawy: {count}',
        'repair_capacity' => 'Zdolności naprawcze w oparciu o poziom doku kosmicznego {level}',
        'start_repair' => 'Rozpocznij naprawę pola wrakowego',
        'repair_in_progress' => 'Trwają naprawy',
        'repair_completed' => 'Naprawy zakończone',
        'deploy_ships' => 'Rozmieść naprawione statki',
        'burn_wreck_field' => 'Spalić pole wraku',
        'repair_time' => 'Szacowany czas naprawy: {time}',
        'repair_progress' => 'Postęp naprawy: {progress}%',
        'completion_time' => 'Ukończenie: {czas}',
        'auto_deploy_warning' => 'Statki zostaną automatycznie rozmieszczone w ciągu {godzin} godzin po zakończeniu naprawy, jeśli nie zostaną rozmieszczone ręcznie.',
        'level_effects' => [
            'repair_speed' => 'Szybkość naprawy zwiększona o {bonus}%',
            'capacity_increase' => 'Zwiększono maksymalną liczbę statków, które można naprawić',
        ],
        'status' => [
            'no_dock' => 'Dok kosmiczny wymagany do naprawy pól wrakowych',
            'level_too_low' => 'Dok kosmiczny poziomu 1 wymagany do naprawy pól wrakowych',
            'no_wreck_field' => 'Brak dostępnego pola wrakowego',
            'repairing' => 'Obecnie naprawiamy pole wrakowe',
            'ready_to_deploy' => 'Naprawy zakończone, statki gotowe do wdrożenia',
        ],
    ],
    'actions' => [
        'build' => 'Zbudować',
        'upgrade' => 'Przejdź na poziom {level}',
        'downgrade' => 'Przejdź na poziom {level}',
        'demolish' => 'Zburzyć',
        'cancel' => 'Anulować',
    ],
    'requirements' => [
        'met' => 'Wymagania spełnione',
        'not_met' => 'Wymagania nie zostały spełnione',
        'research' => 'Badania: {wymaganie}',
        'building' => 'Budynek: {wymaganie} poziom {poziom}',
    ],
    'cost' => [
        'metal' => 'Metal: {ilość}',
        'crystal' => 'Kryształ: {ilość}',
        'deuterium' => 'Deuter: {ilość}',
        'energy' => 'Energia: {ilość}',
        'dark_matter' => 'Ciemna Materia: {ilość}',
        'total' => 'Całkowity koszt: {kwota}',
    ],
    'construction_time' => 'Czas budowy: {czas}',
    'upgrade_time' => 'Czas aktualizacji: {time}',
];
