<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : ja (OGame: jp)
 * Source   : resources/lang/en/t_galaxy.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'planet' => [
        'description' => [
            'nearest' => '太陽に近いため、太陽エネルギーの収集効率が高くなります。 ただし、この位置にある惑星は小さい傾向があり、少量の重水素しか提供しません。',
            'normal' => '通常、この位置には、十分な重水素源、太陽エネルギーの十分な供給、および開発の十分な余地を備えたバランスのとれた惑星が存在します。',
            'biggest' => '一般に、太陽系の最大の惑星はこの位置にあります。 太陽は十分なエネルギーを提供し、十分な重水素源が期待できます。',
            'farthest' => '太陽までの距離が遠いため、太陽エネルギーの収集には限界があります。 ただし、これらの惑星は通常、重要な重水素源を提供します。',
        ],
    ],
    'mission' => [
        'colonize' => [
            'name' => '植民地化する',
            'no_ship' => '植民地船がなければ惑星に植民地を作ることはできません。',
        ],
    ],
    'discovery' => [
        'locked' => 'You haven\'t unlocked the research to discover new lifeforms yet.',
    ],
];
