<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : tr (OGame: tr)
 * Source   : resources/lang/en/t_galaxy.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'planet' => [
        'description' => [
            'nearest' => 'Güneşe yakınlığı nedeniyle güneş enerjisinin toplanması oldukça verimlidir. Ancak bu konumdaki gezegenler genellikle küçüktür ve yalnızca küçük miktarlarda döteryum sağlarlar.',
            'normal' => 'Normalde bu Konumda, yeterli döteryum kaynaklarına, iyi bir güneş enerjisi kaynağına ve gelişme için yeterli alana sahip dengeli gezegenler vardır.',
            'biggest' => 'Genellikle güneş sisteminin en büyük gezegenleri bu konumda bulunur. Güneş yeterli enerji sağlar ve yeterli döteryum kaynakları öngörülebilir.',
            'farthest' => 'Güneşe olan uzaklık nedeniyle güneş enerjisinin toplanması sınırlıdır. Ancak bu gezegenler genellikle önemli miktarda döteryum kaynağı sağlar.',
        ],
    ],
    'mission' => [
        'colonize' => [
            'name' => 'Kolonileştir',
            'no_ship' => 'Koloni gemisi olmadan bir gezegeni kolonileştirmek mümkün değildir.',
        ],
    ],
    'discovery' => [
        'locked' => 'You haven\'t unlocked the research to discover new lifeforms yet.',
    ],
];
