<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : tr (OGame: tr)
 * Source   : resources/lang/en/t_messages.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'welcome_message' => [
        'from' => 'OGameX',
        'subject' => 'OGameX\'e hoş geldiniz!',
        'body' => 'Selamlar İmparator :oyuncu! 

Şanlı kariyerinize başladığınız için tebrikler. İlk adımlarınızda size rehberlik etmek için burada olacağım. 

Solda galaktik imparatorluğunuzu denetlemenize ve yönetmenize olanak tanıyan menüyü görebilirsiniz. 

Genel Bakış\'ı zaten gördünüz. Kaynaklar ve Tesisler, imparatorluğunuzu genişletmenize yardımcı olacak binalar inşa etmenize olanak tanır. Madenleriniz için enerji toplamak amacıyla bir Güneş Enerjisi Santrali inşa ederek başlayın. 

Daha sonra hayati kaynaklar üretmek için Metal Madenini ve Kristal Madenini genişlet. Aksi takdirde, sadece kendinize bir bakın. Yakında kendinizi evinizde iyi hissedeceksiniz, eminim. 

Burada daha fazla yardım, ipucu ve taktik bulabilirsiniz: 

Discord Sohbeti: Discord Sunucusu 
Forum: OGameX Forumu 
Destek: Oyun Desteği 

Forumlarda yalnızca oyunla ilgili güncel duyuruları ve değişiklikleri bulacaksınız. 


Artık geleceğe hazırsınız. İyi şanlar! 

Bu mesaj 7 gün sonra silinecektir.',
    ],
    'return_of_fleet_with_resources' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Bir filonun dönüşü',
        'body' => 'Filonuz :from\'dan :to\'ya dönüyor ve mallarını teslim ediyor: 

metal: : metal 
Kristal: :kristal 
Döteryum: :döteryum',
    ],
    'return_of_fleet' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Bir filonun dönüşü',
        'body' => 'Filonuz :\'dan:\'ya geri dönüyor. 

Filo mal teslim etmiyor.',
    ],
    'fleet_deployment_with_resources' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Bir filonun dönüşü',
        'body' => ':from\'dan gelen filolarınızdan biri :to\'ya ulaştı ve mallarını teslim etti: 

metal: : metal 
Kristal: :kristal 
Döteryum: :döteryum',
    ],
    'fleet_deployment' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Bir filonun dönüşü',
        'body' => ':from\'dan gelen filolarınızdan biri :to\'ya ulaştı. Filo mal teslim etmiyor.',
    ],
    'transport_arrived' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Bir gezegene ulaşmak',
        'body' => 'Filonuz :from\'dan :to\'ya ulaşır ve mallarını teslim eder: 
Metal: :metal Kristal: :kristal Döteryum: :döteryum',
    ],
    'transport_received' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Gelen filo',
        'body' => ':from\'dan gelen bir filo gezegeninize :to\'ya ulaştı ve mallarını teslim etti: 
Metal: :metal Kristal: :kristal Döteryum: :döteryum',
    ],
    'acs_defend_arrival_host' => [
        'from' => 'Uzay İzleme',
        'subject' => 'Filo durduruluyor',
        'body' => 'Bir filo :to\'ya ulaştı.',
    ],
    'acs_defend_arrival_sender' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Filo durduruluyor',
        'body' => 'Bir filo :to\'ya ulaştı.',
    ],
    'colony_established' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Uzlaşma Raporu',
        'body' => 'Filo belirlenen koordinatlara ulaştı: koordinatlar, orada yeni bir gezegen buldu ve hemen onun üzerinde gelişmeye başlıyor.',
    ],
    'colony_establish_fail_astrophysics' => [
        'from' => 'Yerleşimciler',
        'subject' => 'Uzlaşma Raporu',
        'body' => 'Filo belirlenen koordinatlara ulaştı: koordinatlar ve gezegenin kolonizasyon için uygun olduğunu tespit ediyor. Gezegeni geliştirmeye başladıktan kısa bir süre sonra koloniciler, astrofizik bilgilerinin yeni bir gezegenin kolonileştirilmesini tamamlamak için yeterli olmadığını fark ederler.',
    ],
    'espionage_report' => [
        'from' => 'Filo Komutanlığı',
        'subject' => ':planet\'ten casusluk raporu',
    ],
    'espionage_detected' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Planet :planet\'ten casusluk raporu',
        'body' => ':planet (:attacker_name) gezegeninden yabancı bir filo gezegeninizin yakınında görüldü 
:savunma oyuncusu 
Karşı casusluk olasılığı: :chance%',
    ],
    'battle_report' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Savaş raporu: gezegen',
    ],
    'fleet_lost_contact' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Saldıran filoyla iletişim kesildi. :koordinatlar',
        'body' => '(Bu, ilk turda yok edildiği anlamına gelir.)',
    ],
    'debris_field_harvest' => [
        'from' => 'Filo',
        'subject' => 'DF\'den :koordinatlar hakkında hasat raporu',
        'body' => ':ship_name (:ship_amountships) dosyanızın toplam depolama kapasitesi :storage_capacity\'dir. Hedefte :to, :metal Metal, :crystal Crystal ve :döteryum Döteryum uzayda yüzüyor. :harvested_metal Metal, :harvested_crystal Kristal ve :harvested_deuterium Döteryum hasat ettiniz.',
    ],
    'expedition_resources_captured' => ':resource_type :resource_amount yakalandı.',
    'expedition_dark_matter_captured' => '(:dark_matter_amount Karanlık Madde)',
    'expedition_units_captured' => 'Aşağıdaki gemiler artık filonun bir parçası:',
    'expedition_unexplored_statement' => 'Haberleşme memurlarının kayıt defterinden giriş: Görünüşe göre evrenin bu kısmı henüz keşfedilmemiş.',
    'expedition_failed' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Sefer Sonucu',
        'body' => [
            '1' => 'Amiral gemisinin merkezi bilgisayarlarındaki arıza nedeniyle sefer görevi iptal edilmek zorunda kaldı. Ne yazık ki bilgisayar arızası sonucu filo eve eli boş döner.',
            '2' => 'Keşif geziniz neredeyse nötron yıldızlarının çekim alanına giriyordu ve kendini kurtarmak için biraz zamana ihtiyacı vardı. Bu nedenle çok fazla Döteryum tüketildi ve keşif filosu herhangi bir sonuç alamadan geri dönmek zorunda kaldı.',
            '3' => 'Bilinmeyen nedenlerden dolayı keşif gezisinin atlaması tamamen yanlış gitti. Neredeyse güneşin kalbine iniyordu. Neyse ki bilinen bir sisteme indi ancak geriye sıçrama sanıldığından daha uzun sürecek.',
            '4' => 'Amiral gemisinin reaktör çekirdeğindeki bir arıza neredeyse tüm keşif filosunu yok eder. Neyse ki teknisyenler fazlasıyla yetkindi ve en kötüsünü önleyebildiler. Onarımlar oldukça uzun sürdü ve keşif ekibinin amacına ulaşamadan geri dönmesine neden oldu.',
            '5' => 'Saf enerjiden yapılmış bir canlı varlık gemiye geldi ve tüm keşif ekibi üyelerini tuhaf bir transa soktu ve onların yalnızca bilgisayar ekranlarındaki hipnotize edici desenlere bakmalarına neden oldu. Çoğu sonunda hipnoza benzer durumdan kurtulduğunda, çok az Döteryuma sahip oldukları için keşif görevinin iptal edilmesi gerekti.',
            '6' => 'Yeni navigasyon modülü hala hatalı. Keşif gezisinin sıçraması onları sadece yanlış yöne yönlendirmekle kalmadı, aynı zamanda tüm Döteryum yakıtını da tüketti. Neyse ki filonun sıçraması onları ayrılış gezegeninin ayına yaklaştırdı. Keşif gezisinin artık itici güç olmadan geri dönmesi biraz hayal kırıklığı yarattı. Dönüş yolculuğu beklenenden uzun sürecek.',
            '7' => 'Keşif geziniz uzayın geniş boşluğunu öğrendi. Bu keşif gezisini ilginç kılabilecek tek bir küçük asteroit, radyasyon veya parçacık bile yoktu.',
            '8' => 'Artık bu kırmızı, 5. sınıf anormalliklerin sadece geminin navigasyon sistemleri üzerinde kaotik etkiler yaratmadığını, aynı zamanda mürettebatta büyük halüsinasyonlar yarattığını da biliyoruz. Keşif hiçbir şeyi geri getirmedi.',
            '9' => 'Keşif geziniz bir süper novanın muhteşem fotoğraflarını çekti. Keşif gezisinden yeni bir şey elde edilemedi ama en azından OGame dergisinin gelecek ayki sayısında "Evrenin En İyi Resmi" yarışmasını kazanma şansı yüksek.',
            '10' => 'Keşif filonuz bir süre tuhaf sinyalleri takip etti. Sonunda, bu sinyallerin nesiller önce yabancı türleri selamlamak için gönderilen eski bir sondadan gönderildiğini fark ettiler. Sonda kurtarıldı ve ana gezegeninizdeki bazı müzeler ilgilerini zaten dile getirdi.',
            '11' => 'Bu sektöre dair ilk ve çok umut verici taramalara rağmen ne yazık ki elimiz boş döndük.',
            '12' => 'Bilinmeyen bir bataklık gezegeninden gelen bazı ilginç, küçük evcil hayvanların yanı sıra, bu keşif gezisi, yolculuktan geriye heyecan verici hiçbir şey getirmiyor.',
            '13' => 'Keşif gemisinin amiral gemisi, herhangi bir uyarı yapmadan filoya giren yabancı bir gemiyle çarpıştı. Yabancı gemi patladı ve amiral gemisindeki hasar büyüktü. Bu koşullar altında seferin devam etmesi mümkün olmadığından filo, gerekli onarımların tamamlanmasının ardından geri dönüşe başlayacak.',
            '14' => 'Keşif ekibimiz çağlar önce terk edilmiş garip bir koloniyle karşılaştı. İnişin ardından mürettebatımız uzaylı bir virüsün neden olduğu yüksek ateş nedeniyle acı çekmeye başladı. Bu virüsün gezegendeki tüm medeniyeti yok ettiği öğrenildi. Keşif ekibimiz hasta mürettebatı tedavi etmek için eve gidiyor. Ne yazık ki görevi iptal etmek zorunda kaldık ve eve elimiz boş döndük.',
            '15' => 'Garip bir bilgisayar virüsü, ev sistemimizi ayırdıktan kısa bir süre sonra navigasyon sistemimize saldırdı. Bu, keşif filosunun daireler çizerek uçmasına neden oldu. Keşif gezisinin gerçekten başarılı olmadığını söylemeye gerek yok.',
        ],
    ],
    'expedition_gain_resources' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Sefer Sonucu',
        'body' => [
            '1' => 'İzole edilmiş bir gezegende kolayca erişilebilen bazı kaynak alanları bulduk ve bazılarını başarıyla topladık.',
            '2' => 'Keşif geziniz, bazı kaynakların toplanabileceği küçük bir asteroit keşfetti.',
            '3' => 'Keşif geziniz eski, tamamen dolu ama terk edilmiş bir yük gemisi konvoyu buldu. Kaynakların bir kısmı kurtarılabilir.',
            '4' => 'Keşif filonuz dev bir uzaylı gemisi enkazının keşfedildiğini bildiriyor. Sahip oldukları teknolojilerden ders alamadılar ama gemiyi ana bileşenlerine ayırmayı ve ondan bazı yararlı kaynaklar elde etmeyi başardılar.',
            '5' => 'Keşif geziniz, kendi atmosferine sahip küçük bir ayda devasa bir ham kaynak deposu buldu. Yerdeki ekip bu doğal hazineyi kaldırıp yüklemeye çalışıyor.',
            '6' => 'Bilinmeyen bir gezegenin etrafındaki mineral kuşakları sayısız kaynak içeriyordu. Keşif gemileri geri dönüyor ve depoları dolu!',
        ],
    ],
    'expedition_gain_dark_matter' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Sefer Sonucu',
        'body' => [
            '1' => 'Keşif gezisi bir asteroite giden bazı tuhaf sinyalleri takip etti. Asteroit çekirdeğinde az miktarda Karanlık Madde bulundu. Asteroit ele geçirildi ve kaşifler Karanlık Maddeyi çıkarmaya çalışıyor.',
            '2' => 'Keşif ekibi Karanlık Maddenin bir kısmını yakalayıp saklamayı başardı.',
            '3' => 'Küçük bir geminin rafında, bazı basit matematiksel hesaplamalar karşılığında bize Karanlık Madde ile ilgili bir kasa veren garip bir uzaylıyla karşılaştık.',
            '4' => 'Uzaylı bir geminin kalıntılarını bulduk. Kargo ambarındaki bir rafta içinde biraz Karanlık Madde bulunan küçük bir kap bulduk!',
            '5' => 'Keşif gezimiz özel bir yarışla ilk teması kurdu. Görünüşe göre kendine Legorian adını veren saf enerjiden oluşan bir yaratık, keşif gemileri arasında uçmuş ve daha sonra az gelişmiş türümüze yardım etmeye karar vermiş. Geminin kaptan köşkünde Karanlık Madde içeren bir kutu ortaya çıktı!',
            '6' => 'Keşif gezimiz az miktarda Karanlık Madde taşıyan bir hayalet gemiyi ele geçirdi. Geminin asıl mürettebatına ne olduğuna dair hiçbir ipucu bulamadık ancak teknisyenlerimiz Karanlık Maddeyi kurtarmayı başardı.',
            '7' => 'Keşif gezimiz eşsiz bir deneyi başardı. Ölmekte olan bir yıldızdan Karanlık Maddeyi toplamayı başardılar.',
            '8' => 'Keşif gezimiz, uzun süredir uzayda kontrolsüz bir şekilde süzülüyormuş gibi görünen paslı bir uzay istasyonunun yerini tespit etti. İstasyonun kendisi tamamen işe yaramazdı, ancak reaktörde bir miktar Karanlık Maddenin depolandığı keşfedildi. Teknisyenlerimiz mümkün olduğu kadar tasarruf etmeye çalışıyor.',
        ],
    ],
    'expedition_gain_ships' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Sefer Sonucu',
        'body' => [
            '1' => 'Keşif gezimiz belli bir savaş zinciri sırasında neredeyse yok olmuş bir gezegen buldu. Yörüngede farklı gemiler yüzüyor. Teknisyenler bazılarını onarmaya çalışıyor. Belki burada yaşananlar hakkında da bilgi alırız.',
            '2' => 'Terk edilmiş bir korsan istasyonu bulduk. Hangarda bazı eski gemiler var. Teknisyenlerimiz bazılarının hâlâ kullanışlı olup olmadığını araştırıyor.',
            '3' => 'Keşif geziniz çok uzun zaman önce terk edilmiş bir koloninin tersaneleriyle karşılaştı. Tersanenin hangarında kurtarılabilecek bazı gemiler keşfederler. Teknisyenler bazılarının tekrar uçmasını sağlamaya çalışıyor.',
            '4' => 'Önceki bir keşif gezisinin kalıntılarına rastladık! Teknisyenlerimiz gemilerden bazılarını tekrar çalışır hale getirmeye çalışacak.',
            '5' => 'Keşif gezimiz eski bir otomatik tersaneye rastladı. Gemilerden bazıları hâlâ üretim aşamasında ve teknisyenlerimiz şu anda tersanenin enerji jeneratörlerini yeniden etkinleştirmeye çalışıyor.',
            '6' => 'Bir donanmanın kalıntılarını bulduk. Teknisyenler, neredeyse hiç bozulmamış gemileri yeniden çalıştırmaya çalışmak için doğrudan onlara gittiler.',
            '7' => 'Soyu tükenmiş bir medeniyetin gezegenini bulduk. Yörüngede dönen dev bir bozulmamış uzay istasyonunu görebiliyoruz. Teknisyenlerinizden ve pilotlarınızdan bazıları yüzeye çıkıp hala kullanılabilecek gemileri aradılar.',
        ],
    ],
    'expedition_gain_item' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Sefer Sonucu',
        'body' => [
            '1' => 'Kaçan bir filo, kaçmalarına yardımcı olmak amacıyla dikkatimizi dağıtmak için geride bir eşya bıraktı.',
        ],
    ],
    'expedition_failed_and_speedup' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Sefer Sonucu',
        'body' => [
            '1' => 'Keşif gezileriniz, keşfedilen sektörde herhangi bir anormallik bildirmiyor. Ancak filo geri dönerken bir miktar güneş rüzgarıyla karşılaştı. Bu durum dönüş yolculuğunun hızlandırılmasına neden oldu. Keşif geziniz eve biraz daha erken dönüyor.',
            '2' => 'Yeni ve cesur komutan, dönüş uçuşunu kısaltmak için dengesiz bir solucan deliğinden başarıyla geçti! Ancak keşif gezisinin kendisi yeni bir şey getirmedi.',
            '3' => 'Motorların enerji makaralarındaki beklenmedik bir geri bağlantı, keşif gezisinin dönüşünü hızlandırdı; eve beklenenden daha erken dönüyor. İlk raporlar, açıklanacak heyecan verici bir şey olmadığını söylüyor.',
        ],
    ],
    'expedition_failed_and_delay' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Sefer Sonucu',
        'body' => [
            '1' => 'Keşif geziniz parçacık fırtınalarıyla dolu bir sektöre girdi. Bu, enerji depolarının aşırı yüklenmesine neden oldu ve gemilerin ana sistemlerinin çoğu çöktü. Teknisyenleriniz en kötüsünden kaçınmayı başardı ancak keşif gezisi büyük bir gecikmeyle geri dönecek.',
            '2' => 'Navigatörünüz hesaplamalarında keşif gezisinin atlayışının yanlış hesaplanmasına neden olan ciddi bir hata yaptı. Filo sadece hedefi tamamen kaçırmakla kalmadı, aynı zamanda dönüş yolculuğu da başlangıçta planlanandan çok daha fazla zaman alacak.',
            '3' => 'Kırmızı devin güneş rüzgarı keşif gezisinin atlayışını mahvetti ve geri dönüş sıçramasını hesaplamak oldukça zaman alacak. O sektörde yıldızların arasındaki boşluktan başka hiçbir şey yoktu. Filo beklenenden daha geç dönecek.',
        ],
    ],
    'expedition_battle' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Sefer Sonucu',
        'body' => [
            '1' => 'Bazı ilkel barbarlar, adı bile geçmeyen uzay gemileriyle üzerimize saldırıyor. Yangın ciddileşirse karşılık vermek zorunda kalacağız.',
            '2' => 'Neyse ki sayıları az olan bazı korsanlarla savaşmamız gerekiyordu.',
            '3' => 'Sarhoş korsanların bazı radyo yayınlarını yakaladık. Yakında saldırıya uğrayacağız gibi görünüyor.',
            '4' => 'Keşif gezimiz bilinmeyen gemilerden oluşan küçük bir grup tarafından saldırıya uğradı!',
            '5' => 'Gerçekten çaresiz bazı uzay korsanları keşif filomuzu ele geçirmeye çalıştı.',
            '6' => 'Bazı egzotik görünümlü gemiler, sefer filosuna haber vermeden saldırdı!',
            '7' => 'Keşif filonuz bilinmeyen bir türle düşmanca bir ilk temas yaşadı.',
        ],
    ],
    'expedition_battle_pirates' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Sefer Sonucu',
        'body' => [
            '1' => 'Bazı ilkel barbarlar, adı bile geçmeyen uzay gemileriyle üzerimize saldırıyor. Yangın ciddileşirse karşılık vermek zorunda kalacağız.',
            '2' => 'Neyse ki sayıları az olan bazı korsanlarla savaşmamız gerekiyordu.',
            '3' => 'Sarhoş korsanların bazı radyo yayınlarını yakaladık. Yakında saldırıya uğrayacağız gibi görünüyor.',
            '4' => 'Keşif gezimiz küçük bir grup uzay korsanının saldırısına uğradı!',
            '5' => 'Gerçekten çaresiz bazı uzay korsanları keşif filomuzu ele geçirmeye çalıştı.',
            '6' => 'Korsanlar keşif filosunu haber vermeden pusuya düşürdü!',
            '7' => 'Ayaktakımından oluşan bir uzay korsanları filosu haraç talep ederek yolumuzu kesti.',
        ],
    ],
    'expedition_battle_aliens' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Sefer Sonucu',
        'body' => [
            '1' => 'Bilinmeyen gemilerden garip sinyaller aldık. Düşman oldukları ortaya çıktı!',
            '2' => 'Bir uzaylı devriyesi keşif filomuzu tespit etti ve hemen saldırdı!',
            '3' => 'Keşif filonuz bilinmeyen bir türle düşmanca bir ilk temas yaşadı.',
            '4' => 'Bazı egzotik görünümlü gemiler, sefer filosuna haber vermeden saldırdı!',
            '5' => 'Hiperuzaydan bir uzaylı savaş gemisi filosu çıktı ve bizimle çatışmaya girdi!',
            '6' => 'Teknolojik olarak gelişmiş, barışçıl olmayan bir uzaylı türüyle karşılaştık.',
            '7' => 'Uzaylı gemileri saldırıya uğramadan önce sensörlerimiz bilinmeyen enerji imzalarını tespit etti!',
        ],
    ],
    'expedition_loss_of_fleet' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Sefer Sonucu',
        'body' => [
            '1' => 'Öncü geminin çekirdeğinin erimesi, zincirleme bir reaksiyona yol açar ve bu da tüm keşif filosunu muhteşem bir patlamayla yok eder.',
        ],
    ],
    'expedition_merchant_found' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Sefer Sonucu',
        'body' => [
            '1' => 'Keşif filonuz dost canlısı bir uzaylı ırkıyla temasa geçti. Dünyalarınıza ticaret yapmak üzere mallarla dolu bir temsilci göndereceklerini duyurdular.',
            '2' => 'Gizemli bir ticaret gemisi keşif gezinize yaklaştı. Tüccar gezegenlerinizi ziyaret etmeyi ve özel ticaret hizmetleri sağlamayı teklif etti.',
            '3' => 'Keşif gezisi galaksiler arası bir ticaret konvoyuyla karşılaştı. Tüccarlardan biri ticaret fırsatları sunmak için ana dünyanızı ziyaret etmeyi kabul etti.',
        ],
    ],
    'buddy_request_received' => [
        'from' => 'Arkadaşlar',
        'subject' => 'Arkadaşlık talebi',
        'body' => ':sender_name adlı kişiden yeni bir arkadaşlık isteği aldınız.<span style="display:none;">:buddy_request_id</span>',
    ],
    'buddy_request_accepted' => [
        'from' => 'Arkadaşlar',
        'subject' => 'Arkadaşlık isteği kabul edildi',
        'body' => 'Oyuncu :accepter_name sizi arkadaş listesine ekledi.',
    ],
    'buddy_removed' => [
        'from' => 'Arkadaşlar',
        'subject' => 'Arkadaş listesinden silindin',
        'body' => 'Oyuncu :remover_name sizi arkadaş listesinden çıkardı.',
    ],
    'missile_attack_report' => [
        'from' => 'Filo Komutanlığı',
        'subject' => ':target_coords\'a füze saldırısı',
        'body' => ':origin_planet_name :origin_planet_coords (ID: :origin_planet_id)\'deki gezegenler arası füzeleriniz :target_planet_name :target_coords (ID: :target_planet_id, Type: :target_type) adresindeki hedeflerine ulaştı. 

Fırlatılan füzeler: :missiles_sent 
Ele geçirilen füzeler: :missiles_intercepted 
Vurulan füzeler: :missiles_hit 

Savunmalar yok edildi: :defenses_destroyed',
        'missile_singular' => 'missile',
        'missile_plural' => 'missiles',
        'from_your_planet' => ' from your planet ',
        'smashed_into' => ' smashed into the planet ',
        'intercepted_label' => 'Missiles Intercepted:',
        'defenses_hit_label' => 'Defenses Hit',
        'none' => 'None',
    ],
    'missile_defense_report' => [
        'from' => 'Savunma Komutanlığı',
        'subject' => ':planet_coords\'a füze saldırısı',
        'body' => ':planet_coords (ID: :planet_id) adresindeki :planet_name gezegeniniz, :attacker_name tarafından gezegenler arası füzeler tarafından saldırıya uğradı! 

Gelen füzeler: :missiles_incoming 
Ele geçirilen füzeler: :missiles_intercepted 
Vurulan füzeler: :missiles_hit 

Savunmalar yok edildi: :defenses_destroyed',
        'your_planet' => 'Your planet ',
        'attacked_by_prefix' => ' has been attacked by interplanetary missiles from ',
        'incoming_label' => 'Incoming Missiles:',
        'intercepted_label' => 'Missiles Intercepted:',
        'defenses_hit_label' => 'Defenses Hit',
        'none' => 'None',
    ],
    'alliance_broadcast' => [
        'from' => ':gönderen_adı',
        'subject' => '[:alliance_tag] :sender_name tarafından gönderilen ittifak yayını',
        'body' => ':mesaj',
    ],
    'alliance_application_received' => [
        'from' => 'İttifak Yönetimi',
        'subject' => 'Yeni ittifak uygulaması',
        'body' => 'Oyuncu :applicant_name, ittifakınıza katılmak için başvurdu. 

Uygulama mesajı: 
:application_message',
    ],
    'planet_relocation_success' => [
        'from' => 'Kolonileri yönet',
        'subject' => ':planet_name\'in yeri başarıyla değiştirildi',
        'body' => ':planet_name gezegeni, [koordinatlar]:eski_koordinatlar[/koordinatlar] koordinatlarından [koordinatlar]:yeni_koordinatlar[/koordinatlar]\'a başarıyla taşındı.',
    ],
    'fleet_union_invite' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'İttifak savaşına davet',
        'body' => ':sender_name sizi [:target_coords] tarihinde :target_player\'a karşı :union_name görevine davet etti, filo :arrival_time için zamanlandı. 

DİKKAT: Filolara katılma nedeniyle varış saati değişebilir. Her yeni filo bu süreyi en fazla %30 oranında uzatabilir, aksi halde katılıma izin verilmeyecektir. 

NOT: Tüm katılımcıların toplam gücü, savunucuların toplam gücüne kıyasla bunun onurlu bir savaş olup olmayacağını belirler.',
    ],
    'Shipyard is being upgraded.' => 'Tersane yenileniyor.',
    'Nanite Factory is being upgraded.' => 'Nanite Fabrikası yükseltiliyor.',
    'moon_destruction_success' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Ay :moon_name [:moon_coords] yok edildi!',
        'body' => ':destruction_chance imha olasılığı ve :loss_chance Ölüm Yıldızı kayıp olasılığı ile filonuz :moon_coords konumundaki :moon_name ayını başarıyla yok etti.',
    ],
    'moon_destruction_failure' => [
        'from' => 'Filo Komutanlığı',
        'subject' => ':moon_coords noktasındaki Ay imhası başarısız oldu',
        'body' => ':destruction_chance imha olasılığı ve :loss_chance Ölüm Yıldızı kayıp olasılığı ile filonuz :moon_coords adresindeki :moon_name ayını yok etmeyi başaramadı. Filo geri dönüyor.',
    ],
    'moon_destruction_catastrophic' => [
        'from' => 'Filo Komutanlığı',
        'subject' => ':moon_coords\'da ayın yok olması sırasında büyük kayıp',
        'body' => ':destruction_chance imha olasılığı ve :loss_chance Ölüm Yıldızı kayıp olasılığı ile filonuz :moon_coords adresindeki :moon_name ayını yok etmeyi başaramadı. Ayrıca bu girişimde tüm Ölüm Yıldızları kaybedildi. Enkaz yok.',
    ],
    'moon_destruction_mission_failed' => [
        'from' => 'Filo Komutanlığı',
        'subject' => 'Ay yok etme görevi :koordinatlarda başarısız oldu',
        'body' => 'Filonuz :koordinatlara ulaştı ancak hedef konumda ay bulunamadı. Filo geri dönüyor.',
    ],
    'moon_destruction_repelled' => [
        'from' => 'Uzay İzleme',
        'subject' => 'Ay\'ı yok etme girişimi :moon_name [:moon_coords] püskürtüldü',
        'body' => ':attacker_name, :moon_coords noktasındaki ay\'ınıza :moon_name\'e, :destruction_chance imha olasılığı ve :loss_chance Ölüm Yıldızı kaybetme olasılığıyla saldırdı. Ayınız saldırıdan sağ kurtuldu!',
    ],
    'moon_destroyed' => [
        'from' => 'Uzay İzleme',
        'subject' => 'Ay :moon_name [:moon_coords] yok edildi!',
        'body' => ':moon_coords konumundaki ayınız :moon_name, :attacker_name\'e ait bir Ölüm Yıldızı filosu tarafından yok edildi!',
    ],
    'wreck_field_repair_completed' => [
        'from' => 'Sistem Mesajı',
        'subject' => 'Onarım tamamlandı',
        'body' => 'Planet :planet ile ilgili onarım talebiniz tamamlandı. 
:ship_count gemileri tekrar hizmete açıldı.',
    ],
];
