<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : pt_BR (OGame: br)
 * Source   : resources/lang/en/t_messages.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'welcome_message' => [
        'from' => 'OGameX',
        'subject' => 'Bem-vindo ao OGameX!',
        'body' => 'Saudações Imperador: jogador! 

Parabéns por iniciar sua ilustre carreira. Estarei aqui para guiá-lo nos primeiros passos. 

À esquerda você pode ver o menu que permite supervisionar e governar seu império galáctico. 

Você já viu a Visão Geral. Recursos e Instalações permitem que você construa edifícios para ajudá-lo a expandir seu império. Comece construindo uma Usina Solar para coletar energia para suas minas. 

Em seguida, expanda sua Mina de Metal e Mina de Cristal para produzir recursos vitais. Caso contrário, basta dar uma olhada por si mesmo. Em breve você se sentirá bem em casa, tenho certeza. 

Você pode encontrar mais ajuda, dicas e táticas aqui: 

Bate-papo do Discord: Servidor do Discord 
Fórum: Fórum OGameX 
Suporte: Suporte ao Jogo 

Você só encontrará anúncios atuais e mudanças no jogo nos fóruns. 


Agora você está pronto para o futuro. Boa sorte! 

Esta mensagem será excluída em 7 dias.',
    ],
    'return_of_fleet_with_resources' => [
        'from' => 'Comando da Frota',
        'subject' => 'Retorno de uma frota',
        'body' => 'Sua frota está retornando de :from para :to e entregou suas mercadorias: 

Metal: :metal 
Cristal: :cristal 
Deutério: :deutério',
    ],
    'return_of_fleet' => [
        'from' => 'Comando da Frota',
        'subject' => 'Retorno de uma frota',
        'body' => 'Sua frota está retornando de :from para :to. 

A frota não entrega mercadorias.',
    ],
    'fleet_deployment_with_resources' => [
        'from' => 'Comando da Frota',
        'subject' => 'Retorno de uma frota',
        'body' => 'Uma de suas frotas de :from chegou a :to e entregou suas mercadorias: 

Metal: :metal 
Cristal: :cristal 
Deutério: :deutério',
    ],
    'fleet_deployment' => [
        'from' => 'Comando da Frota',
        'subject' => 'Retorno de uma frota',
        'body' => 'Uma de suas frotas de :from alcançou :to. A frota não entrega mercadorias.',
    ],
    'transport_arrived' => [
        'from' => 'Comando da Frota',
        'subject' => 'Alcançando um planeta',
        'body' => 'Sua frota de :from chega a :to e entrega suas mercadorias: 
Metal: :metal Cristal: :cristal Deutério: :deutério',
    ],
    'transport_received' => [
        'from' => 'Comando da Frota',
        'subject' => 'Frota de entrada',
        'body' => 'Uma frota vinda de :from chegou ao seu planeta :to e entregou suas mercadorias: 
Metal: :metal Cristal: :cristal Deutério: :deutério',
    ],
    'acs_defend_arrival_host' => [
        'from' => 'Monitoramento Espacial',
        'subject' => 'Frota está parando',
        'body' => 'Uma frota chegou em :to.',
    ],
    'acs_defend_arrival_sender' => [
        'from' => 'Comando da Frota',
        'subject' => 'Frota está parando',
        'body' => 'Uma frota chegou em :to.',
    ],
    'colony_established' => [
        'from' => 'Comando da Frota',
        'subject' => 'Relatório de liquidação',
        'body' => 'A frota chegou às coordenadas atribuídas, encontrou um novo planeta lá e está começando a se desenvolver nele imediatamente.',
    ],
    'colony_establish_fail_astrophysics' => [
        'from' => 'Colonas',
        'subject' => 'Relatório de liquidação',
        'body' => 'A frota chegou às coordenadas atribuídas e verifica que o planeta é viável para colonização. Pouco depois de começarem a desenvolver o planeta, os colonos percebem que seus conhecimentos de astrofísica não são suficientes para completar a colonização de um novo planeta.',
    ],
    'espionage_report' => [
        'from' => 'Comando da Frota',
        'subject' => 'Relatório de espionagem de :planet',
    ],
    'espionage_detected' => [
        'from' => 'Comando da Frota',
        'subject' => 'Relatório de espionagem do Planet :planet',
        'body' => 'Uma frota estrangeira do planeta :planet (:attacker_name) foi avistada perto do seu planeta 
:defensor 
Chance de contra-espionagem: :chance%',
    ],
    'battle_report' => [
        'from' => 'Comando da Frota',
        'subject' => 'Relatório de combate: planeta',
    ],
    'fleet_lost_contact' => [
        'from' => 'Comando da Frota',
        'subject' => 'O contato com a frota atacante foi perdido. :coordenadas',
        'body' => '(Isso significa que foi destruído na primeira rodada.)',
    ],
    'debris_field_harvest' => [
        'from' => 'Frota',
        'subject' => 'Colhendo relatório do DF em:coordenadas',
        'body' => 'Seu :ship_name (:ship_amount navios) tem uma capacidade total de armazenamento de :storage_capacity. No alvo :to, :metal Metal, :crystal Crystal e :deuterium Deuterium estão flutuando no espaço. Você colheu :harvested_metal Metal, :harvested_crystal Crystal e :harvested_deuterium Deuterium.',
    ],
    'expedition_resources_captured' => ':resource_type :resource_amount foram capturados.',
    'expedition_dark_matter_captured' => '(:dark_matter_amount Matéria Escura)',
    'expedition_units_captured' => 'Os seguintes navios agora fazem parte da frota:',
    'expedition_unexplored_statement' => 'Registro do diário de bordo dos oficiais de comunicação: Parece que esta parte do universo ainda não foi explorada.',
    'expedition_failed' => [
        'from' => 'Comando da Frota',
        'subject' => 'Resultado da Expedição',
        'body' => [
            '1' => 'Devido a uma falha nos computadores centrais da nau capitânia, a missão da expedição teve que ser abortada. Infelizmente, devido ao mau funcionamento do computador, a frota volta para casa de mãos vazias.',
            '2' => 'Sua expedição quase colidiu com um campo gravitacional de estrelas de nêutrons e precisou de algum tempo para se libertar. Por causa disso, muito Deutério foi consumido e a frota da expedição teve que voltar sem nenhum resultado.',
            '3' => 'Por razões desconhecidas, o salto da expedição deu totalmente errado. Quase pousou no coração de um sol. Felizmente, ele pousou em um sistema conhecido, mas o salto de volta demorará mais do que se pensava.',
            '4' => 'Uma falha no núcleo do reator da capitânia quase destrói toda a frota da expedição. Felizmente os técnicos foram mais do que competentes e conseguiram evitar o pior. Os reparos demoraram bastante e obrigaram a expedição a retornar sem ter alcançado o objetivo.',
            '5' => 'Um ser vivo feito de pura energia subiu a bordo e induziu todos os membros da expedição a um estranho transe, fazendo com que apenas olhassem para os padrões hipnotizantes nas telas dos computadores. Quando a maioria deles finalmente saiu do estado hipnótico, a missão da expedição precisou ser abortada porque eles tinham muito pouco deutério.',
            '6' => 'O novo módulo de navegação ainda apresenta bugs. As expedições saltam não apenas os levaram na direção errada, mas também usaram todo o combustível de deutério. Felizmente, o salto da frota os aproximou da lua do planeta de partida. Um pouco decepcionada, a expedição agora retorna sem poder de impulso. A viagem de volta demorará mais do que o esperado.',
            '7' => 'Sua expedição aprendeu sobre o extenso vazio do espaço. Não houve sequer um pequeno asteróide, radiação ou partícula que pudesse ter tornado esta expedição interessante.',
            '8' => 'Bem, agora sabemos que essas anomalias vermelhas de classe 5 não só têm efeitos caóticos nos sistemas de navegação dos navios, mas também geram alucinações massivas na tripulação. A expedição não trouxe nada de volta.',
            '9' => 'Sua expedição tirou fotos lindas de uma supernova. Nada de novo foi obtido com a expedição, mas pelo menos há boas chances de ganhar o concurso de "Melhor Filme do Universo" na edição do próximo mês da revista OGame.',
            '10' => 'Sua frota de expedição seguiu sinais estranhos por algum tempo. No final notaram que esses sinais eram enviados por uma sonda antiga que foi enviada há gerações para saudar espécies estrangeiras. A sonda foi salva e alguns museus do vosso planeta natal já manifestaram o seu interesse.',
            '11' => 'Apesar das primeiras e muito promissoras varreduras deste setor, infelizmente voltamos de mãos vazias.',
            '12' => 'Além de alguns pequenos animais de estimação curiosos de um planeta pantanoso desconhecido, esta expedição não traz nada de emocionante da viagem.',
            '13' => 'A nau capitânia da expedição colidiu com um navio estrangeiro ao saltar para a frota sem qualquer aviso. O navio estrangeiro explodiu e os danos à nau capitânia foram substanciais. A expedição não pode continuar nestas condições, pelo que a frota começará a regressar assim que forem efectuados os reparos necessários.',
            '14' => 'Nossa equipe de expedição encontrou uma colônia estranha que havia sido abandonada há muito tempo. Após o pouso, nossa tripulação começou a sofrer de febre alta causada por um vírus alienígena. Descobriu-se que este vírus destruiu toda a civilização do planeta. Nossa equipe de expedição está voltando para casa para tratar dos tripulantes doentes. Infelizmente tivemos que abortar a missão e voltamos para casa de mãos vazias.',
            '15' => 'Um estranho vírus de computador atacou o sistema de navegação logo após separar nosso sistema doméstico. Isso fez com que a frota da expedição voasse em círculos. Escusado será dizer que a expedição não foi muito bem sucedida.',
        ],
    ],
    'expedition_gain_resources' => [
        'from' => 'Comando da Frota',
        'subject' => 'Resultado da Expedição',
        'body' => [
            '1' => 'Em um planetóide isolado, encontramos alguns campos de recursos facilmente acessíveis e colhemos alguns com sucesso.',
            '2' => 'Sua expedição descobriu um pequeno asteroide do qual alguns recursos poderiam ser extraídos.',
            '3' => 'Sua expedição encontrou um antigo comboio de cargueiros totalmente carregado, mas deserto. Alguns dos recursos poderiam ser resgatados.',
            '4' => 'Sua frota de expedição relata a descoberta de um naufrágio de uma nave alienígena gigante. Eles não foram capazes de aprender com suas tecnologias, mas foram capazes de dividir a nave em seus componentes principais e extrair dela alguns recursos úteis.',
            '5' => 'Em uma pequena lua com atmosfera própria, sua expedição encontrou um enorme armazenamento de recursos brutos. A tripulação em terra está tentando levantar e carregar aquele tesouro natural.',
            '6' => 'Os cinturões minerais ao redor de um planeta desconhecido continham inúmeros recursos. Os navios de expedição estão voltando e seus estoques estão cheios!',
        ],
    ],
    'expedition_gain_dark_matter' => [
        'from' => 'Comando da Frota',
        'subject' => 'Resultado da Expedição',
        'body' => [
            '1' => 'A expedição seguiu alguns sinais estranhos até um asteróide. No núcleo do asteróide foi encontrada uma pequena quantidade de matéria escura. O asteróide foi capturado e os exploradores estão tentando extrair a matéria escura.',
            '2' => 'A expedição conseguiu capturar e armazenar um pouco de matéria escura.',
            '3' => 'Conhecemos um estranho alienígena na plataforma de um pequeno navio que nos deu uma caixa com Dark Matter em troca de alguns cálculos matemáticos simples.',
            '4' => 'Encontramos os restos de uma nave alienígena. Encontramos um pequeno contêiner com matéria escura em uma prateleira no porão de carga!',
            '5' => 'Nossa expedição fez o primeiro contato com uma raça especial. Parece que uma criatura feita de pura energia, que se autodenominou Legorian, voou pelos navios da expedição e decidiu ajudar nossa espécie subdesenvolvida. Uma caixa contendo Dark Matter se materializou na ponte do navio!',
            '6' => 'Nossa expedição assumiu um navio fantasma que transportava uma pequena quantidade de matéria escura. Não encontramos nenhuma pista do que aconteceu com a tripulação original da nave, mas nossos técnicos conseguiram resgatar a Matéria Negra.',
            '7' => 'Nossa expedição realizou um experimento único. Eles foram capazes de colher matéria escura de uma estrela moribunda.',
            '8' => 'Nossa expedição localizou uma estação espacial enferrujada, que parecia estar flutuando descontroladamente no espaço sideral há muito tempo. A estação em si era totalmente inútil, porém, descobriu-se que alguma matéria escura está armazenada no reator. Nossos técnicos estão tentando economizar o máximo que podem.',
        ],
    ],
    'expedition_gain_ships' => [
        'from' => 'Comando da Frota',
        'subject' => 'Resultado da Expedição',
        'body' => [
            '1' => 'Nossa expedição encontrou um planeta que quase foi destruído durante uma certa cadeia de guerras. Existem diferentes naves flutuando na órbita. Os técnicos estão tentando consertar alguns deles. Talvez também obtenhamos informações sobre o que aconteceu aqui.',
            '2' => 'Encontramos uma estação pirata deserta. Existem alguns navios antigos no hangar. Nossos técnicos estão descobrindo se alguns deles ainda são úteis ou não.',
            '3' => 'Sua expedição encontrou os estaleiros de uma colônia que estava deserta há muito tempo. No hangar do estaleiro eles descobrem alguns navios que poderiam ser resgatados. Os técnicos estão tentando fazer com que alguns deles voltem a voar.',
            '4' => 'Deparamo-nos com os restos de uma expedição anterior! Nossos técnicos tentarão fazer com que alguns navios voltem a funcionar.',
            '5' => 'Nossa expedição encontrou um antigo estaleiro automático. Alguns navios ainda estão em fase de produção e nossos técnicos estão atualmente tentando reativar os geradores de energia do estaleiro.',
            '6' => 'Encontramos os restos de uma armada. Os técnicos dirigiram-se diretamente aos navios quase intactos para tentar fazê-los voltar a funcionar.',
            '7' => 'Encontramos o planeta de uma civilização extinta. Somos capazes de ver uma estação espacial gigante intacta, em órbita. Alguns de seus técnicos e pilotos foram à superfície em busca de algumas naves que ainda pudessem ser utilizadas.',
        ],
    ],
    'expedition_gain_item' => [
        'from' => 'Comando da Frota',
        'subject' => 'Resultado da Expedição',
        'body' => [
            '1' => 'Uma frota em fuga deixou um item para trás, a fim de nos distrair e ajudar na fuga.',
        ],
    ],
    'expedition_failed_and_speedup' => [
        'from' => 'Comando da Frota',
        'subject' => 'Resultado da Expedição',
        'body' => [
            '1' => 'Suas expedições não reportam nenhuma anomalia no setor explorado. Mas a frota enfrentou algum vento solar ao retornar. Isso resultou na aceleração da viagem de volta. Sua expedição volta para casa um pouco mais cedo.',
            '2' => 'O novo e ousado comandante viajou com sucesso através de um buraco de minhoca instável para encurtar o voo de volta! Porém, a expedição em si não trouxe nada de novo.',
            '3' => 'Um inesperado acoplamento traseiro nos carretéis de energia dos motores acelerou o retorno da expedição, que volta para casa mais cedo do que o esperado. Os primeiros relatórios dizem que eles não têm nada de emocionante para explicar.',
        ],
    ],
    'expedition_failed_and_delay' => [
        'from' => 'Comando da Frota',
        'subject' => 'Resultado da Expedição',
        'body' => [
            '1' => 'Sua expedição entrou em um setor cheio de tempestades de partículas. Isso sobrecarregou os estoques de energia e a maioria dos sistemas principais da nave caiu. Seus mecânicos conseguiram evitar o pior, mas a expedição retornará com grande atraso.',
            '2' => 'Seu navegador cometeu um grave erro em seus cálculos que fez com que o salto da expedição fosse mal calculado. Não só a frota errou completamente o alvo, mas a viagem de volta levará muito mais tempo do que o planejado originalmente.',
            '3' => 'O vento solar de uma gigante vermelha arruinou o salto da expedição e levará algum tempo para calcular o salto de retorno. Não havia nada além do vazio do espaço entre as estrelas daquele setor. A frota retornará mais tarde do que o esperado.',
        ],
    ],
    'expedition_battle' => [
        'from' => 'Comando da Frota',
        'subject' => 'Resultado da Expedição',
        'body' => [
            '1' => 'Alguns bárbaros primitivos estão nos atacando com naves espaciais que nem sequer podem ser nomeadas como tal. Se o incêndio se agravar, seremos forçados a contra-atacar.',
            '2' => 'Precisávamos combater alguns piratas que, felizmente, eram poucos.',
            '3' => 'Capturamos algumas transmissões de rádio de alguns piratas bêbados. Parece que estaremos sob ataque em breve.',
            '4' => 'Nossa expedição foi atacada por um pequeno grupo de navios desconhecidos!',
            '5' => 'Alguns piratas espaciais realmente desesperados tentaram capturar nossa frota de expedição.',
            '6' => 'Alguns navios de aparência exótica atacaram a frota da expedição sem avisar!',
            '7' => 'A sua frota de expedição teve um primeiro contacto hostil com uma espécie desconhecida.',
        ],
    ],
    'expedition_battle_pirates' => [
        'from' => 'Comando da Frota',
        'subject' => 'Resultado da Expedição',
        'body' => [
            '1' => 'Alguns bárbaros primitivos estão nos atacando com naves espaciais que nem sequer podem ser nomeadas como tal. Se o incêndio se agravar, seremos forçados a contra-atacar.',
            '2' => 'Precisávamos combater alguns piratas que, felizmente, eram poucos.',
            '3' => 'Capturamos algumas transmissões de rádio de alguns piratas bêbados. Parece que estaremos sob ataque em breve.',
            '4' => 'Nossa expedição foi atacada por um pequeno grupo de piratas espaciais!',
            '5' => 'Alguns piratas espaciais realmente desesperados tentaram capturar nossa frota de expedição.',
            '6' => 'Os piratas emboscaram a frota da expedição sem avisar!',
            '7' => 'Uma frota desorganizada de piratas espaciais nos interceptou, exigindo tributo.',
        ],
    ],
    'expedition_battle_aliens' => [
        'from' => 'Comando da Frota',
        'subject' => 'Resultado da Expedição',
        'body' => [
            '1' => 'Captamos sinais estranhos de naves desconhecidas. Eles acabaram sendo hostis!',
            '2' => 'Uma patrulha alienígena detectou nossa frota de expedição e atacou imediatamente!',
            '3' => 'A sua frota de expedição teve um primeiro contacto hostil com uma espécie desconhecida.',
            '4' => 'Alguns navios de aparência exótica atacaram a frota da expedição sem avisar!',
            '5' => 'Uma frota de naves de guerra alienígenas emergiu do hiperespaço e nos enfrentou!',
            '6' => 'Encontrámos uma espécie alienígena tecnologicamente avançada que não era pacífica.',
            '7' => 'Nossos sensores detectaram assinaturas de energia desconhecidas antes do ataque das naves alienígenas!',
        ],
    ],
    'expedition_loss_of_fleet' => [
        'from' => 'Comando da Frota',
        'subject' => 'Resultado da Expedição',
        'body' => [
            '1' => 'O colapso do núcleo da nave líder leva a uma reação em cadeia, que destrói toda a frota da expedição em uma explosão espetacular.',
        ],
    ],
    'expedition_merchant_found' => [
        'from' => 'Comando da Frota',
        'subject' => 'Resultado da Expedição',
        'body' => [
            '1' => 'Sua frota de expedição fez contato com uma raça alienígena amigável. Eles anunciaram que enviariam um representante com mercadorias para comercializar em seus mundos.',
            '2' => 'Um misterioso navio mercante se aproximou de sua expedição. O comerciante se ofereceu para visitar seus planetas e fornecer serviços comerciais especiais.',
            '3' => 'A expedição encontrou um comboio mercante intergaláctico. Um dos comerciantes concordou em visitar seu mundo natal para oferecer oportunidades de comércio.',
        ],
    ],
    'buddy_request_received' => [
        'from' => 'Amigos',
        'subject' => 'Pedido de amigo',
        'body' => 'Você recebeu uma nova solicitação de amizade de :sender_name.<span style="display:none;">:buddy_request_id</span>',
    ],
    'buddy_request_accepted' => [
        'from' => 'Amigos',
        'subject' => 'Pedido de amizade aceito',
        'body' => 'Jogador:accepter_name adicionou você à lista de amigos dele.',
    ],
    'buddy_removed' => [
        'from' => 'Amigos',
        'subject' => 'Você foi excluído de uma lista de amigos',
        'body' => 'Jogador :remover_name removeu você da lista de amigos.',
    ],
    'missile_attack_report' => [
        'from' => 'Comando da Frota',
        'subject' => 'Ataque de mísseis em :target_coords',
        'body' => 'Seus mísseis interplanetários de :origin_planet_name :origin_planet_coords (ID: :origin_planet_id) atingiram seu alvo em :target_planet_name :target_coords (ID: :target_planet_id, Type: :target_type). 

Mísseis lançados: :missiles_sent 
Mísseis interceptados: :missiles_intercepted 
Mísseis atingidos: :missiles_hit 

Defesas destruídas: :defenses_destroyed',
        'missile_singular' => 'missile',
        'missile_plural' => 'missiles',
        'from_your_planet' => ' from your planet ',
        'smashed_into' => ' smashed into the planet ',
        'intercepted_label' => 'Missiles Intercepted:',
        'defenses_hit_label' => 'Defenses Hit',
        'none' => 'None',
    ],
    'missile_defense_report' => [
        'from' => 'Comando de Defesa',
        'subject' => 'Ataque de mísseis em:planet_coords',
        'body' => 'Seu planeta :planet_name em :planet_coords (ID: :planet_id) foi atacado por mísseis interplanetários de :attacker_name! 

Mísseis chegando: :missiles_incoming 
Mísseis interceptados: :missiles_intercepted 
Mísseis atingidos: :missiles_hit 

Defesas destruídas: :defenses_destroyed',
        'your_planet' => 'Your planet ',
        'attacked_by_prefix' => ' has been attacked by interplanetary missiles from ',
        'incoming_label' => 'Incoming Missiles:',
        'intercepted_label' => 'Missiles Intercepted:',
        'defenses_hit_label' => 'Defenses Hit',
        'none' => 'None',
    ],
    'alliance_broadcast' => [
        'from' => ':nome_do_remetente',
        'subject' => '[:alliance_tag] Transmissão da aliança de:sender_name',
        'body' => ':mensagem',
    ],
    'alliance_application_received' => [
        'from' => 'Gestão de Aliança',
        'subject' => 'Novo aplicativo de aliança',
        'body' => 'Jogador :applicant_name se inscreveu para ingressar na sua aliança. 

Mensagem do aplicativo: 
:mensagem_aplicativo',
    ],
    'planet_relocation_success' => [
        'from' => 'Gerenciar colônias',
        'subject' => 'A realocação de :planet_name foi bem-sucedida',
        'body' => 'O planeta :planet_name foi realocado com sucesso das coordenadas [coordenadas]:coordenadas_antigas[/coordenadas] para [coordenadas]:novas_coordenadas[/coordenadas].',
    ],
    'fleet_union_invite' => [
        'from' => 'Comando da Frota',
        'subject' => 'Convite para combate de aliança',
        'body' => ':sender_name convidou você para a missão :union_name contra :target_player em [:target_coords], a frota foi cronometrada para :arrival_time. 

CUIDADO: O horário de chegada pode sofrer alterações devido à adesão de frotas. Cada nova frota poderá prorrogar esse prazo em no máximo 30%, caso contrário não será permitida a adesão. 

NOTA: A força total de todos os participantes comparada com a força total dos defensores determina se será uma batalha honrosa ou não.',
    ],
    'Shipyard is being upgraded.' => 'O estaleiro está sendo modernizado.',
    'Nanite Factory is being upgraded.' => 'A Fábrica Nanite está sendo atualizada.',
    'moon_destruction_success' => [
        'from' => 'Comando da Frota',
        'subject' => 'Lua :moon_name [:moon_coords] foi destruída!',
        'body' => 'Com uma probabilidade de destruição de :destruction_chance e uma probabilidade de perda da Estrela da Morte de :loss_chance, sua frota destruiu com sucesso a lua :moon_name em :moon_coords.',
    ],
    'moon_destruction_failure' => [
        'from' => 'Comando da Frota',
        'subject' => 'Destruição da Lua em:moon_coords falhou',
        'body' => 'Com uma probabilidade de destruição de :destruction_chance e uma probabilidade de perda da Estrela da Morte de :loss_chance, sua frota não conseguiu destruir a lua :moon_name em :moon_coords. A frota está retornando.',
    ],
    'moon_destruction_catastrophic' => [
        'from' => 'Comando da Frota',
        'subject' => 'Perda catastrófica durante a destruição da lua em :moon_coords',
        'body' => 'Com uma probabilidade de destruição de :destruction_chance e uma probabilidade de perda da Estrela da Morte de :loss_chance, sua frota não conseguiu destruir a lua :moon_name em :moon_coords. Além disso, todas as Deathstars foram perdidas na tentativa. Não há destroços.',
    ],
    'moon_destruction_mission_failed' => [
        'from' => 'Comando da Frota',
        'subject' => 'A missão de destruição da Lua falhou em:coordenadas',
        'body' => 'Sua frota chegou às coordenadas, mas nenhuma lua foi encontrada no local alvo. A frota está retornando.',
    ],
    'moon_destruction_repelled' => [
        'from' => 'Monitoramento Espacial',
        'subject' => 'Tentativa de destruição na lua :moon_name [:moon_coords] repelida',
        'body' => ':attacker_name atacou sua lua :moon_name em :moon_coords com uma probabilidade de destruição de :destruction_chance e uma probabilidade de perda da Estrela da Morte de :loss_chance. Sua lua sobreviveu ao ataque!',
    ],
    'moon_destroyed' => [
        'from' => 'Monitoramento Espacial',
        'subject' => 'Lua :moon_name [:moon_coords] foi destruída!',
        'body' => 'Sua lua :moon_name em :moon_coords foi destruída por uma frota Deathstar pertencente a :attacker_name!',
    ],
    'wreck_field_repair_completed' => [
        'from' => 'Mensagem do sistema',
        'subject' => 'Reparo concluído',
        'body' => 'Sua solicitação de reparo no planeta :planet foi concluída. 
:ship_count os navios foram colocados novamente em serviço.',
    ],
];
