<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : hu (OGame: hu)
 * Source   : resources/lang/en/t_external.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'browser_warning' => [
        'title' => 'A böngészője nem naprakész.',
        'desc1' => 'Az Ön Internet Explorer verziója nem felel meg a meglévő szabványoknak, és ezt a webhely már nem támogatja.',
        'desc2' => 'A webhely használatához frissítse böngészőjét egy aktuális verzióra, vagy használjon másik böngészőt. Ha már a legújabb verziót használja, kérjük, töltse be újra az oldalt a megfelelő megjelenítéshez.',
        'desc3' => 'Íme a legnépszerűbb böngészők listája. Kattintson az egyik szimbólumra a letöltési oldal eléréséhez:',
    ],
    'login' => [
        'page_title' => 'OGame – Hódítsd meg az univerzumot',
        'btn' => 'Bejelentkezés',
        'email_label' => 'E-mail cím:',
        'password_label' => 'Jelszó:',
        'universe_label' => 'Univerzum',
        'universe_option_1' => '1. Univerzum',
        'submit' => 'Jelentkezzen be',
        'forgot_password' => 'Elfelejtette jelszavát?',
        'forgot_email' => 'Elfelejtette az e-mail címét?',
        'terms_accept_html' => 'A bejelentkezéssel elfogadom az <a class="" href="#" target="_blank" title="T&amp;Cs">ÁSZF-et</a>',
    ],
    'register' => [
        'play_free' => 'INGYENES JÁTÉK!',
        'email_label' => 'E-mail cím:',
        'password_label' => 'Jelszó:',
        'universe_label' => 'Univerzum',
        'distinctions' => 'Megkülönböztetések',
        'terms_html' => '<a class="" target="_blank" href="#" title="T&amp;Cs"> Általános Szerződési Feltételeink </a> és <a class="" target="_blank" href="#" title="Privacy Policy"> Adatvédelmi irányelveink </a> érvényesek a játékra',
        'submit' => 'Nyilvántartás',
    ],
    'nav' => [
        'home' => 'Otthon',
        'about' => 'Az OGame-ről',
        'media' => 'Média',
        'wiki' => 'Wiki',
    ],
    'home' => [
        'title' => 'OGame – Hódítsd meg az univerzumot',
        'description_html' => 'Az <em>OGame</em> egy térben játszódó stratégiai játék, amelyben egyszerre több ezer játékos verseng a világ minden tájáról. Csak egy normál webböngészőre van szüksége a játékhoz.',
        'board_btn' => 'Bizottság',
        'trailer_title' => 'Utánfutó',
    ],
    'footer' => [
        'legal' => 'Impresszum',
        'privacy_policy' => 'Adatvédelmi szabályzat',
        'terms' => 'ÁSZF',
        'contact' => 'Érintkezés',
        'rules' => 'Szabályzat',
        'copyright' => '© OGameX. Minden jog fenntartva.',
    ],
    'js' => [
        'login' => 'Bejelentkezés',
        'close' => 'Közeli',
        'age_check_failed' => 'Sajnáljuk, de nem jogosult regisztrálni. További információért kérjük, tekintse meg Általános Szerződési Feltételeinket.',
    ],
    'validation' => [
        'required' => 'Ezt a mezőt kötelező kitölteni',
        'make_decision' => 'Hozz döntést',
        'accept_terms' => 'El kell fogadnia az Általános Szerződési Feltételeket.',
        'length' => '3 és 20 közötti karakter megengedett.',
        'pw_length' => '4 és 20 közötti karakter megengedett.',
        'email' => 'Érvényes email címet kell megadni!',
        'invalid_chars' => 'Érvénytelen karaktereket tartalmaz.',
        'no_begin_end_underscore' => 'A neve nem kezdődhet vagy végződhet aláhúzással.',
        'no_begin_end_whitespace' => 'A neve nem kezdődhet és nem végződhet szóközzel.',
        'max_three_underscores' => 'Az Ön neve összesen legfeljebb 3 aláhúzást tartalmazhat.',
        'max_three_whitespaces' => 'A név összesen legfeljebb 3 szóközt tartalmazhat.',
        'no_consecutive_underscores' => 'Nem használhat két vagy több aláhúzást egymás után.',
        'no_consecutive_whitespaces' => 'Nem használhat két vagy több szóközt egymás után.',
        'username_available' => 'Ez a felhasználónév elérhető.',
        'username_loading' => 'Kérjük, várjon, betöltés...',
        'username_taken' => 'Ez a felhasználónév már nem érhető el.',
        'only_letters' => 'Csak karaktereket használjon.',
    ],
    'forgot_password' => [
        'title' => 'Elfelejtette jelszavát?',
        'description' => 'Írja be e-mail címét alább, és küldünk egy linket a jelszó visszaállításához.',
        'email_label' => 'E-mail cím:',
        'submit' => 'Reset link küldése',
        'back_to_login' => '← Vissza a bejelentkezéshez',
    ],
    'reset_password' => [
        'title' => 'Állítsa vissza jelszavát',
        'email_label' => 'E-mail cím:',
        'password_label' => 'Új jelszó:',
        'confirm_label' => 'Új jelszó megerősítése:',
        'submit' => 'Jelszó visszaállítása',
    ],
    'forgot_email' => [
        'title' => 'Elfelejtette az e-mail címét?',
        'description' => 'Írja be a parancsnok nevét, és küldünk egy tippet a regisztrált e-mail címre.',
        'username_label' => 'Parancsnok neve:',
        'submit' => 'Tipp küldése',
        'back_to_login' => '← Vissza a bejelentkezéshez',
        'sent' => 'Ha talált egyező fiókot, a rendszer egy tippet küld a regisztrált e-mail címre.',
    ],
    'mail' => [
        'reset_password' => [
            'subject' => 'Állítsa vissza az OGameX jelszavát',
            'heading' => 'Jelszó visszaállítása',
            'greeting' => 'Szia :felhasználónév,',
            'body' => 'Megkaptuk a fiók jelszavának visszaállítására vonatkozó kérést. Új jelszó kiválasztásához kattintson az alábbi gombra.',
            'cta' => 'Jelszó visszaállítása',
            'expiry' => 'Ez a link 60 percen belül lejár.',
            'no_action' => 'Ha nem kérte a jelszó visszaállítását, nincs szükség további teendőkre.',
            'url_fallback' => 'Ha nem sikerül a gombra kattintania, másolja ki és illessze be az alábbi URL-t a böngészőbe:',
        ],
        'retrieve_email' => [
            'subject' => 'Az Ön OGameX e-mail címe',
            'heading' => 'E-mail cím tipp',
            'greeting' => 'Szia :felhasználónév,',
            'body' => 'Tanácsot kért a fiókjához társított e-mail címre:',
            'cta' => 'Lépjen a Bejelentkezés oldalra',
            'no_action' => 'Ha nem Ön küldte ezt a kérést, nyugodtan figyelmen kívül hagyhatja ezt az e-mailt.',
        ],
    ],
    'universe_characteristics' => [
        'fleet_speed' => 'Flotta sebessége: minél nagyobb az érték, annál kevesebb ideje van a támadásra reagálni.',
        'economy_speed' => 'Gazdasági sebesség: minél magasabb az érték, annál gyorsabban fejeződnek be az építkezések és a kutatások, és gyűjtik össze az erőforrásokat.',
        'debris_ships' => 'A csatában megsemmisült hajók egy része a törmelékmezőre kerül.',
        'debris_defence' => 'A csatában megsemmisült védelmi szerkezetek egy része a törmelékmezőbe kerül.',
        'dark_matter_gift' => 'Az e-mail címed megerősítéséért a Dark Mattert kapod jutalmul.',
        'aks_on' => 'A Szövetség harcrendszere aktiválva',
        'planet_fields' => 'Növelték az épületek maximális számát.',
        'wreckfield' => 'Space Dock aktiválva: néhány megsemmisült hajó helyreállítható a Space Dock segítségével.',
        'universe_big' => 'A galaxisok száma az Univerzumban',
    ],
];
