<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : hu (OGame: hu)
 * Source   : resources/lang/en/t_facilities.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'space_dock' => [
        'name' => 'Űrdokk',
        'description' => 'A roncsok megjavíthatók az Űrdokkban.',
        'description_long' => 'A Space Dock lehetőséget kínál a csatában elpusztult, roncsokat hagyó hajók javítására. A javítási idő maximum 12 órát vesz igénybe, de legalább 30 percet vesz igénybe, amíg a hajókat újra üzembe lehet helyezni. 

Mivel a Space Dock keringési pályán lebeg, nincs szükség bolygómezőre.',
        'requirements' => 'Hajógyári szint 2 szükséges',
        'field_consumption' => 'Nem fogyaszt bolygómezőket (pályán lebeg)',
        'wreck_field_section' => 'Roncsmező',
        'no_wreck_field' => 'Ezen a helyen nem áll rendelkezésre roncsmező.',
        'wreck_field_info' => 'Rendelkezésre áll egy roncsmező, amely javítható hajókat tartalmaz.',
        'ships_available' => 'Javításra elérhető szállítmányok: {count}',
        'repair_capacity' => 'Javítási kapacitás a Space Dock {level} szintje alapján',
        'start_repair' => 'Kezdje el a roncsmező javítását',
        'repair_in_progress' => 'Javítás folyamatban',
        'repair_completed' => 'Javítások befejezve',
        'deploy_ships' => 'Javított hajók telepítése',
        'burn_wreck_field' => 'Burn roncs mező',
        'repair_time' => 'Becsült javítási idő: {time}',
        'repair_progress' => 'Javítási folyamat: {progress}%',
        'completion_time' => 'Befejezés: {time}',
        'auto_deploy_warning' => 'Ha nem manuálisan telepítik, a hajókat a javítás befejezése után { óra} órával automatikusan telepítik.',
        'level_effects' => [
            'repair_speed' => 'A javítási sebesség {bonus}%-kal nőtt',
            'capacity_increase' => 'Megnövekedett a javítható hajók maximális száma',
        ],
        'status' => [
            'no_dock' => 'Space Dock szükséges a roncsmezők javításához',
            'level_too_low' => 'Space Dock 1. szint szükséges a roncsmezők javításához',
            'no_wreck_field' => 'Nem áll rendelkezésre roncsmező',
            'repairing' => 'Jelenleg a roncsmező javítás alatt áll',
            'ready_to_deploy' => 'A javítás befejeződött, a hajók bevetésre készen állnak',
        ],
    ],
    'actions' => [
        'build' => 'Épít',
        'upgrade' => 'Frissítés {level}. szintre',
        'downgrade' => 'Visszalépés a {level}. szintre',
        'demolish' => 'Lebontani',
        'cancel' => 'Mégsem',
    ],
    'requirements' => [
        'met' => 'A követelmények teljesültek',
        'not_met' => 'A követelmények nem teljesülnek',
        'research' => 'Kutatás: {requirement}',
        'building' => 'Épület: {requirement} szint {level}',
    ],
    'cost' => [
        'metal' => 'Fém: {amount}',
        'crystal' => 'Kristály: {összeg}',
        'deuterium' => 'Deutérium: {mennyiség}',
        'energy' => 'Energia: {amount}',
        'dark_matter' => 'Sötét anyag: {amount}',
        'total' => 'Teljes költség: {amount}',
    ],
    'construction_time' => 'Építési idő: {time}',
    'upgrade_time' => 'Frissítési idő: {time}',
];
