<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : hu (OGame: hu)
 * Source   : resources/lang/en/t_galaxy.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'planet' => [
        'description' => [
            'nearest' => 'A nap közelsége miatt a napenergia gyűjtése rendkívül hatékony. Az ebben a helyzetben lévő bolygók azonban általában kicsik, és csak kis mennyiségű deutériumot biztosítanak.',
            'normal' => 'Normális esetben ebben a helyzetben vannak kiegyensúlyozott bolygók elegendő deutériumforrással, jó napenergia-ellátással és elegendő térrel a fejlődéshez.',
            'biggest' => 'Általában a Naprendszer legnagyobb bolygói ebben a helyzetben helyezkednek el. A nap elegendő energiát biztosít, és elegendő deutériumforrás várható.',
            'farthest' => 'A Naptól való hatalmas távolság miatt a napenergia gyűjtése korlátozott. Azonban ezek a bolygók általában jelentős deutériumforrást biztosítanak.',
        ],
    ],
    'mission' => [
        'colonize' => [
            'name' => 'Gyarmatosítani',
            'no_ship' => 'Nem lehet gyarmatosítani egy bolygót kolóniahajó nélkül.',
        ],
    ],
    'discovery' => [
        'locked' => 'You haven\'t unlocked the research to discover new lifeforms yet.',
    ],
];
