<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : hu (OGame: hu)
 * Source   : resources/lang/en/t_messages.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'welcome_message' => [
        'from' => 'OGameX',
        'subject' => 'Üdvözöljük az OGameX-ben!',
        'body' => 'Üdv Császár :player! 

Gratulálunk jeles karrierjének megkezdéséhez. Itt leszek, hogy végigvezessem az első lépéseken. 

A bal oldalon látható a menü, amely lehetővé teszi, hogy felügyelje és irányítsa galaktikus birodalmát. 

Már láttad az Áttekintést. Az erőforrások és létesítmények lehetővé teszik, hogy olyan épületeket építs, amelyek segítenek a birodalmad kiterjesztésében. Kezdje egy Naperőmű építésével, hogy energiát gyűjtsön a bányáihoz. 

Ezután bővítse fémbányáját és kristálybányáját, hogy létfontosságú erőforrásokat állítson elő. Ellenkező esetben egyszerűen nézzen körül saját maga. Biztos vagyok benne, hogy hamarosan jól érzi majd magát otthon. 

További segítséget, tippeket és taktikákat itt talál: 

Discord Chat: Discord Server 
Fórum: OGameX fórum 
Támogatás: Játéktámogatás 

Csak a fórumon találja meg az aktuális bejelentéseket és a játékkal kapcsolatos változásokat. 


Most készen állsz a jövőre. Sok szerencsét! 

Ez az üzenet 7 napon belül törlődik.',
    ],
    'return_of_fleet_with_resources' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Egy flotta visszatérése',
        'body' => 'Az Ön flottája :honnan ide :hova tér vissza, és leszállította áruit: 

Fém: :fém 
Kristály: :kristály 
Deutérium: :deutérium',
    ],
    'return_of_fleet' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Egy flotta visszatérése',
        'body' => 'Flottája visszatér innen: :from ide: . 

A flotta nem szállít árut.',
    ],
    'fleet_deployment_with_resources' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Egy flotta visszatérése',
        'body' => 'Az egyik flottája innen: :honnan elérte a :ba és leszállította áruit: 

Fém: :fém 
Kristály: :kristály 
Deutérium: :deutérium',
    ],
    'fleet_deployment' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Egy flotta visszatérése',
        'body' => 'Az egyik flottája :fromtól elérte a :to-t. A flotta nem szállít árut.',
    ],
    'transport_arrived' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Egy bolygó elérése',
        'body' => 'Az Ön flottája :honnan elér :ig és szállítja áruit: 
Fém: :fém Kristály: :kristály Deutérium: :deutérium',
    ],
    'transport_received' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Bejövő flotta',
        'body' => 'A :honnan érkező flotta elérte a bolygótokat :to és szállította áruit: 
Fém: :fém Kristály: :kristály Deutérium: :deutérium',
    ],
    'acs_defend_arrival_host' => [
        'from' => 'Térfigyelés',
        'subject' => 'A flotta leáll',
        'body' => 'Egy flotta megérkezett a :to címre.',
    ],
    'acs_defend_arrival_sender' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'A flotta leáll',
        'body' => 'Egy flotta megérkezett a :to címre.',
    ],
    'colony_established' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Elszámolási Jelentés',
        'body' => 'A flotta megérkezett a kijelölt koordinátákhoz (koordináták), új bolygót talált ott, és azonnal elkezdett fejlődni rajta.',
    ],
    'colony_establish_fail_astrophysics' => [
        'from' => 'Telepesek',
        'subject' => 'Elszámolási Jelentés',
        'body' => 'A flotta elérte a kijelölt koordinátákat: koordinátákat, és megbizonyosodik arról, hogy a bolygó életképes a gyarmatosításra. Röviddel a bolygó fejlesztésének megkezdése után a telepesek rájönnek, hogy asztrofizikai ismereteik nem elegendőek egy új bolygó gyarmatosításának befejezéséhez.',
    ],
    'espionage_report' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Kémkedési jelentés a :planetről',
    ],
    'espionage_detected' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Kémkedési jelentés a Planet :planet-ről',
        'body' => 'A bolygód közelében egy idegen flottát észleltek a :planet (:támadó_neve) bolygóról 
:védő 
A kémelhárítás esélye: :chance%',
    ],
    'battle_report' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Harci jelentés: bolygó',
    ],
    'fleet_lost_contact' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Megszakadt a kapcsolat a támadó flottával. :koordináták',
        'body' => '(Ez azt jelenti, hogy az első körben megsemmisült.)',
    ],
    'debris_field_harvest' => [
        'from' => 'Flotta',
        'subject' => 'Betakarítási jelentés a DF-től a :koordinátákon',
        'body' => 'A :ship_name (:ship_amount ships) teljes tárolókapacitása :tárhelykapacitás. A célpontnál :to, :metal Fém, :kristály Kristály és :deutérium Deutérium lebeg az űrben. A :harvested_metal fémet, a :harvested_crystal kristályt és a :harvested_deuterium deutériumot gyűjtötte be.',
    ],
    'expedition_resources_captured' => ':resource_type :resource_amount rögzítve lett.',
    'expedition_dark_matter_captured' => '(:dark_matter_amount Sötét anyag)',
    'expedition_units_captured' => 'A következő hajók most a flotta részei:',
    'expedition_unexplored_statement' => 'Bejegyzés a kommunikációs tisztek naplójából: Úgy tűnik, hogy az univerzumnak ezt a részét még nem fedezték fel.',
    'expedition_failed' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Expedíció eredménye',
        'body' => [
            '1' => 'A zászlóshajó központi számítógépeinek meghibásodása miatt az expedíciós küldetést meg kellett szakítani. Sajnos a számítógép meghibásodása miatt a flotta üres kézzel tér haza.',
            '2' => 'Az expedíciója majdnem belefutott a neutroncsillagok gravitációs mezőjébe, és némi időre volt szüksége, hogy megszabaduljon. Emiatt sok deutérium fogyott el, és az expedíciós flottának eredmény nélkül kellett visszatérnie.',
            '3' => 'Ismeretlen okokból az expedíció ugrása teljesen rosszul sikerült. Majdnem a nap szívében landolt. Szerencsére egy ismert rendszerben landolt, de a visszaugrás tovább tart, mint gondolták.',
            '4' => 'A zászlóshajó reaktormagjának meghibásodása csaknem tönkreteszi a teljes expedíciós flottát. Szerencsére a technikusok több mint hozzáértőek voltak, és elkerülték a legrosszabbat. A javítások meglehetősen sokáig tartottak, és arra kényszerítették az expedíciót, hogy visszatérjen anélkül, hogy elérte volna célját.',
            '5' => 'Egy tiszta energiából készült élőlény felszállt a fedélzetre, és az expedíció minden tagját valami furcsa transzba késztette, amitől csak a számítógép képernyőjén megjelenő hipnotizáló mintákat bámulták. Amikor a legtöbbjük végre kipattant a hipnotikus állapotból, az expedíciós küldetést meg kellett szakítani, mivel túl kevés deutérium volt bennük.',
            '6' => 'Az új navigációs modul még mindig hibás. Az expedíciók nem csak rossz irányba vezették őket, de az összes deutérium üzemanyagot felhasználták. Szerencsére a flották ugrásszerűen közel vitték őket az induló bolygók holdjához. Kissé csalódottan az expedíció impulzuserő nélkül tér vissza. A visszaút a vártnál tovább tart.',
            '7' => 'Az Ön expedíciója megismerte a tér kiterjedt ürességét. Még csak egyetlen kis aszteroida, sugárzás vagy részecske sem tette volna érdekessé ezt az expedíciót.',
            '8' => 'Nos, most már tudjuk, hogy ezek a vörös, 5. osztályú anomáliák nem csak a hajók navigációs rendszerére gyakorolnak kaotikus hatást, hanem hatalmas hallucinációkat is generálnak a legénységben. Az expedíció nem hozott vissza semmit.',
            '9' => 'Az expedíciója gyönyörű képeket készített egy szupernóváról. Semmi újat nem sikerült szerezni az expedíción, de legalább jó esély van a "Best Picture Of The Universe" verseny megnyerésére az OGame magazin következő havi számában.',
            '10' => 'Az expedíciós flottája egy ideig furcsa jeleket követett. A végén észrevették, hogy a jeleket egy régi szonda küldte, amelyet generációkkal ezelőtt küldtek ki idegen fajok üdvözlésére. A szondát megmentették, és szülőbolygójának néhány múzeuma már jelezte érdeklődését.',
            '11' => 'Ennek a szektornak az első, nagyon ígéretes vizsgálatai ellenére sajnos üres kézzel tértünk vissza.',
            '12' => 'Egy ismeretlen mocsári bolygóról származó furcsa, kis háziállatok mellett ez az expedíció semmi izgalmasat nem hoz vissza az utazásból.',
            '13' => 'Az expedíció zászlóshajója egy külföldi hajóval ütközött, amikor minden figyelmeztetés nélkül a flottába ugrott. A külföldi hajó felrobbant, és a zászlóshajóban jelentős kár keletkezett. Az expedíció ilyen körülmények között nem folytatható, így a flotta a szükséges javítások elvégzése után visszafelé indul.',
            '14' => 'Expedíciós csapatunk egy furcsa kolóniára bukkant, amelyet eonokkal ezelőtt elhagytak. Leszállás után legénységünket egy idegen vírus okozta magas láz kezdte el gyötörni. Megtudták, hogy ez a vírus kiirtotta az egész civilizációt a bolygón. Expedíciós csapatunk hazafelé tart, hogy kezelje a legénység megbetegedett tagjait. Sajnos meg kellett szakítanunk a küldetést, és üres kézzel térünk haza.',
            '15' => 'Egy furcsa számítógépes vírus támadta meg a navigációs rendszert nem sokkal azután, hogy szétválasztotta otthoni rendszerünket. Emiatt az expedíciós flotta körbe repült. Mondanom sem kell, hogy az expedíció nem volt igazán sikeres.',
        ],
    ],
    'expedition_gain_resources' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Expedíció eredménye',
        'body' => [
            '1' => 'Egy elszigetelt planetoidon találtunk néhány könnyen hozzáférhető erőforrásmezőt, és néhányat sikeresen betakarítottunk.',
            '2' => 'Az Ön expedíciója felfedezett egy kis aszteroidát, amelyről bizonyos erőforrásokat lehetett betakarítani.',
            '3' => 'Az expedíció egy ősi, teljesen megrakott, de elhagyatott teherszállító konvojt talált. Az erőforrások egy része megmenthető.',
            '4' => 'Az expedíciós flottád egy óriási idegen hajóroncs felfedezéséről számol be. Nem tudtak tanulni a technológiáikból, de fel tudták osztani a hajót a főbb komponensekre, és hasznos erőforrásokat tudtak előállítani belőle.',
            '5' => 'Egy saját atmoszférájú apró holdon az expedíció hatalmas nyersanyagtárolót talált. A legénység a földön próbálja felemelni és berakni ezt a természeti kincset.',
            '6' => 'Az ismeretlen bolygó körüli ásványi övek számtalan erőforrást tartalmaztak. Az expedíciós hajók visszatérnek, és a tárolóik megteltek!',
        ],
    ],
    'expedition_gain_dark_matter' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Expedíció eredménye',
        'body' => [
            '1' => 'Az expedíció néhány furcsa jelet követett egy aszteroidának. Az aszteroidák magjában kis mennyiségű Sötét Anyagot találtak. Az aszteroidát elfoglalták, és a felfedezők megpróbálják kivonni a Sötét Anyagot.',
            '2' => 'Az expedíció képes volt rögzíteni és tárolni néhány sötét anyagot.',
            '3' => 'Egy kis hajó polcán találkoztunk egy furcsa idegennel, aki egy tokot adott nekünk a Sötét Anyaggal néhány egyszerű matematikai számításért cserébe.',
            '4' => 'Megtaláltuk egy idegen hajó maradványait. Találtunk egy kis konténert sötét anyaggal a raktér egyik polcán!',
            '5' => 'Expedíciónk először egy különleges fajjal került kapcsolatba. Úgy tűnik, hogy egy tiszta energiából álló lény, aki Legoriannak nevezte el magát, átrepült az expedíciós hajókon, majd úgy döntött, hogy segít fejletlen fajunknak. A Sötét Anyagot tartalmazó tok megvalósult a hajó hídján!',
            '6' => 'Expedíciónk átvett egy szellemhajót, amely kis mennyiségű Sötét Anyagot szállított. Nem találtunk utalást arra, hogy mi történt a hajó eredeti legénységével, de technikusaink képesek voltak megmenteni a Sötét Anyagot.',
            '7' => 'Expedíciónk egyedülálló kísérletet hajtott végre. Egy haldokló csillagról le tudták gyűjteni a sötét anyagot.',
            '8' => 'Expedíciónk egy rozsdás űrállomást talált, amely úgy tűnt, hogy hosszú ideig ellenőrizetlenül lebegett a világűrben. Maga az állomás teljesen használhatatlan volt, azonban kiderült, hogy a reaktorban sötét anyag tárolódik. Technikusaink igyekeznek minél többet spórolni.',
        ],
    ],
    'expedition_gain_ships' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Expedíció eredménye',
        'body' => [
            '1' => 'Expedíciónk talált egy bolygót, amely a háborúk bizonyos láncolata során majdnem megsemmisült. Különböző hajók lebegnek a pályán. A technikusok megpróbálnak néhányat megjavítani. Talán itt is kapunk majd információt a történtekről.',
            '2' => 'Találtunk egy elhagyatott kalózállomást. A hangárban néhány régi hajó hever. Technikusaink kitalálják, hogy ezek közül néhány még hasznos-e vagy sem.',
            '3' => 'Az expedíciód egy eonokkal ezelőtt elhagyott kolónia hajógyáraiba futott be. A hajógyári hangárban felfedeznek néhány hajót, amelyek megmenthetők. A technikusok megpróbálnak néhányat ismét repülésre bírni.',
            '4' => 'Egy korábbi expedíció maradványaira bukkantunk! Technikusaink megpróbálják újra működésre bírni néhány hajót.',
            '5' => 'Expedíciónk egy régi automata hajógyárba futott be. Néhány hajó még a gyártási fázisban van, és technikusaink jelenleg próbálják újraaktiválni a gyári energiatermelőket.',
            '6' => 'Megtaláltuk egy armada maradványait. A technikusok közvetlenül a szinte ép hajókhoz mentek, hogy megpróbálják újra munkába állni.',
            '7' => 'Megtaláltuk egy kihalt civilizáció bolygóját. Láthatunk egy óriási sértetlen űrállomást keringve. Néhány technikusa és pilóta felment a felszínre, és olyan hajókat keresett, amelyeket még használhatnának.',
        ],
    ],
    'expedition_gain_item' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Expedíció eredménye',
        'body' => [
            '1' => 'Egy menekülő flotta hátrahagyott egy tárgyat, hogy elterelje figyelmünket a menekülés érdekében.',
        ],
    ],
    'expedition_failed_and_speedup' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Expedíció eredménye',
        'body' => [
            '1' => 'Az expedíciói nem jelentenek anomáliákat a feltárt szektorban. De a flotta visszatérés közben napszélbe futott. Ennek eredményeként a visszaút felgyorsult. Az expedíció egy kicsit korábban tér haza.',
            '2' => 'Az új és merész parancsnok sikeresen átutazott egy instabil féreglyukon, hogy lerövidítse a visszarepülést! Maga az expedíció azonban semmi újat nem hozott.',
            '3' => 'A hajtóművek energiaorsóiban egy váratlan visszacsatolás meggyorsította az expedíciók visszatérését, a vártnál korábban tér haza. Az első jelentések azt mondják, nincs semmi izgalmas elszámolnivalójuk.',
        ],
    ],
    'expedition_failed_and_delay' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Expedíció eredménye',
        'body' => [
            '1' => 'Az expedíciód egy részecskeviharokkal teli szektorba ment. Ez túlterhelte az energiatárolókat, és a hajók legtöbb fő rendszere összeomlott. A szerelői el tudták kerülni a legrosszabbat, de az expedíció nagy késéssel tér vissza.',
            '2' => 'A navigátora súlyos hibát követett el a számításaiban, ami miatt az expedíciók ugrását rosszul számították ki. A flotta nem csak hogy teljesen célt tévesztett, de a visszaút is sokkal több időt vesz igénybe, mint az eredetileg tervezték.',
            '3' => 'Egy vörös óriás napszele tönkretette az expedíciós ugrást, és jó ideig tart a visszaugrás kiszámítása. Ebben a szektorban nem volt semmi, csak az üresség a csillagok között. A flotta a vártnál később tér vissza.',
        ],
    ],
    'expedition_battle' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Expedíció eredménye',
        'body' => [
            '1' => 'Néhány primitív barbár űrhajókkal támad ránk, amelyeket nem is lehet annak nevezni. Ha a tűz súlyos lesz, kénytelenek leszünk visszalőni.',
            '2' => 'Harcolnunk kellett néhány kalóz ellen, akik szerencsére csak néhányan voltak.',
            '3' => 'Elkaptunk néhány rádióadást néhány részeg kalóztól. Úgy tűnik, hamarosan támadások érnek bennünket.',
            '4' => 'Expedíciónkat ismeretlen hajók kis csoportja támadta meg!',
            '5' => 'Néhány igazán kétségbeesett űrkalóz megpróbálta elfogni az expedíciós flottánkat.',
            '6' => 'Néhány egzotikus kinézetű hajó figyelmeztetés nélkül megtámadta az expedíciós flottát!',
            '7' => 'Az expedíciós flottád barátságtalan első kapcsolatba került egy ismeretlen fajjal.',
        ],
    ],
    'expedition_battle_pirates' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Expedíció eredménye',
        'body' => [
            '1' => 'Néhány primitív barbár űrhajókkal támad ránk, amelyeket nem is lehet annak nevezni. Ha a tűz súlyos lesz, kénytelenek leszünk visszalőni.',
            '2' => 'Harcolnunk kellett néhány kalóz ellen, akik szerencsére csak néhányan voltak.',
            '3' => 'Elkaptunk néhány rádióadást néhány részeg kalóztól. Úgy tűnik, hamarosan támadások érnek bennünket.',
            '4' => 'Expedíciónkat megtámadta egy kis csoport űrkalóz!',
            '5' => 'Néhány igazán kétségbeesett űrkalóz megpróbálta elfogni az expedíciós flottánkat.',
            '6' => 'A kalózok figyelmeztetés nélkül megtámadták az expedíciós flottát!',
            '7' => 'Az űrkalózokból álló rongyos flotta feltartóztatott minket, és tisztelgést követelt.',
        ],
    ],
    'expedition_battle_aliens' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Expedíció eredménye',
        'body' => [
            '1' => 'Furcsa jeleket vettünk fel ismeretlen hajókról. Kiderült, hogy ellenségesek!',
            '2' => 'Egy idegen járőr észlelte expedíciós flottánkat és azonnal támadott!',
            '3' => 'Az expedíciós flottád barátságtalan első kapcsolatba került egy ismeretlen fajjal.',
            '4' => 'Néhány egzotikus kinézetű hajó figyelmeztetés nélkül megtámadta az expedíciós flottát!',
            '5' => 'Idegen hadihajók flottája bukkant elő a hiperűrből, és elfoglalt minket!',
            '6' => 'Technológiailag fejlett idegen fajjal találkoztunk, amely nem volt békés.',
            '7' => 'Érzékelőink ismeretlen energiajeleket észleltek az idegen hajók támadása előtt!',
        ],
    ],
    'expedition_loss_of_fleet' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Expedíció eredménye',
        'body' => [
            '1' => 'A vezető hajó magolvadása láncreakcióhoz vezet, amely egy látványos robbanásban elpusztítja a teljes expedíciós flottát.',
        ],
    ],
    'expedition_merchant_found' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Expedíció eredménye',
        'body' => [
            '1' => 'Az expedíciós flottád felvette a kapcsolatot egy barátságos idegen fajjal. Bejelentették, hogy küldenek egy képviselőt árukkal kereskedni a világotokra.',
            '2' => 'Egy titokzatos kereskedelmi hajó közeledett az expedíciójához. A kereskedő felajánlotta, hogy meglátogatja bolygóit, és speciális kereskedési szolgáltatásokat nyújt.',
            '3' => 'Az expedíció találkozott egy intergalaktikus kereskedő konvojjal. Az egyik kereskedő beleegyezett, hogy felkeresse szülőföldjét, hogy kereskedési lehetőségeket kínáljon.',
        ],
    ],
    'buddy_request_received' => [
        'from' => 'Barátok',
        'subject' => 'Barátkérelem',
        'body' => 'Új barátkérést kapott a következőtől: :sender_name.<span style="display:none;">:buddy_request_id</span>',
    ],
    'buddy_request_accepted' => [
        'from' => 'Barátok',
        'subject' => 'A baráti kérelem elfogadva',
        'body' => 'A játékos :accepter_name felvett téged a haverlistájára.',
    ],
    'buddy_removed' => [
        'from' => 'Barátok',
        'subject' => 'Töröltek egy barátlistáról',
        'body' => 'A játékos :remover_name eltávolított téged a haverlistájáról.',
    ],
    'missile_attack_report' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Rakétatámadás a :target_coords ellen',
        'body' => 'A :origin_planet_name :origin_planet_coords (ID: :origin_planet_id) nevű bolygóközi rakétái elérték céljukat a következő helyen: :target_planet_name :target_coords (ID: :target_planet_id, Type: :target_type). 

Fellőtt rakéták: :missiles_sent 
Elfogott rakéták: :missiles_intercepted 
Rakéták találata: :missiles_hit 

Védelem megsemmisült: :defenses_destroyed',
        'missile_singular' => 'missile',
        'missile_plural' => 'missiles',
        'from_your_planet' => ' from your planet ',
        'smashed_into' => ' smashed into the planet ',
        'intercepted_label' => 'Missiles Intercepted:',
        'defenses_hit_label' => 'Defenses Hit',
        'none' => 'None',
    ],
    'missile_defense_report' => [
        'from' => 'Védelmi Parancsnokság',
        'subject' => 'Rakétatámadás a :planet_coords ellen',
        'body' => 'Bolygóját :planet_name at :planet_coords (ID: :planet_id) bolygóközi rakéták támadták meg a :tattacker_name címről! 

Bejövő rakéták: :missiles_incoming 
Elfogott rakéták: :missiles_intercepted 
Rakéták találata: :missiles_hit 

Védelem megsemmisült: :defenses_destroyed',
        'your_planet' => 'Your planet ',
        'attacked_by_prefix' => ' has been attacked by interplanetary missiles from ',
        'incoming_label' => 'Incoming Missiles:',
        'intercepted_label' => 'Missiles Intercepted:',
        'defenses_hit_label' => 'Defenses Hit',
        'none' => 'None',
    ],
    'alliance_broadcast' => [
        'from' => ':feladó_neve',
        'subject' => '[:alliance_tag] A Szövetség közvetítése innen: :sender_name',
        'body' => ':üzenet',
    ],
    'alliance_application_received' => [
        'from' => 'Szövetség Menedzsment',
        'subject' => 'Új szövetségi alkalmazás',
        'body' => 'Játékos: pályázó_neve jelentkezett, hogy csatlakozzon a szövetségedhez. 

Pályázati üzenet: 
:alkalmazás_üzenet',
    ],
    'planet_relocation_success' => [
        'from' => 'Kolóniák kezelése',
        'subject' => 'A :bolygó_neve áthelyezése sikeres volt',
        'body' => 'A :bolygó_neve bolygót sikeresen áthelyeztük a [koordináták]:régi_koordináták[/koordináták] koordinátákról a [koordináták]:új_koordináták[/koordináták] helyre.',
    ],
    'fleet_union_invite' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Meghívás a szövetségi harcra',
        'body' => ':sender_name meghívott téged a :union_name küldetésre a :target_player ellen a [:target_coords]-on, a flotta :arrival_time időpontra lett időzítve. 

FIGYELEM: Az érkezési idő változhat a flották csatlakozása miatt. Minden új flotta legfeljebb 30%-kal meghosszabbíthatja ezt az időt, ellenkező esetben nem csatlakozhat. 

MEGJEGYZÉS: Az összes résztvevő összereje és a védők összereje határozza meg, hogy becsületes csata lesz-e vagy sem.',
    ],
    'Shipyard is being upgraded.' => 'A hajógyár korszerűsítése folyamatban van.',
    'Nanite Factory is being upgraded.' => 'A Nanite Factory fejlesztés alatt áll.',
    'moon_destruction_success' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'A Hold :moon_name [:moon_coords] megsemmisült!',
        'body' => 'A :destruction_chance pusztulási valószínűséggel és a :loss_chance Deathstar elvesztési valószínűséggel a flottád sikeresen elpusztította a holdat :moon_name a :moon_coords időpontban.',
    ],
    'moon_destruction_failure' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'A hold pusztítása a :moon_coords időpontban nem sikerült',
        'body' => 'A :destruction_chance pusztulási valószínűséggel és a :loss_chance Deathstar elvesztési valószínűségével a flottád nem tudta elpusztítani a holdat :moon_name a :moon_coords időpontban. A flotta visszatér.',
    ],
    'moon_destruction_catastrophic' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'Katasztrofális veszteség a hold pusztítása során a :moon_coords-nál',
        'body' => 'A :destruction_chance pusztulási valószínűséggel és a :loss_chance Deathstar elvesztési valószínűségével a flottád nem tudta elpusztítani a holdat :moon_name a :moon_coords időpontban. Ráadásul az összes Halálcsillag elveszett a kísérletben. Nincs roncs.',
    ],
    'moon_destruction_mission_failed' => [
        'from' => 'Flottaparancsnokság',
        'subject' => 'A holdpusztító küldetés meghiúsult a :coordinates időpontban',
        'body' => 'Flottája megérkezett a :koordinátákhoz, de a célhelyen nem található hold. A flotta visszatér.',
    ],
    'moon_destruction_repelled' => [
        'from' => 'Térfigyelés',
        'subject' => 'Megsemmisítési kísérlet a holdon :moon_name [:moon_coords] visszaverve',
        'body' => 'A :tattacker_name megtámadta a holdadat :hold_neve a :moon_coords-nál :pusztulási_esély pusztítási valószínűséggel és :veszteség_esélyességgel a Halálcsillag elvesztésének valószínűségével. A holdja túlélte a támadást!',
    ],
    'moon_destroyed' => [
        'from' => 'Térfigyelés',
        'subject' => 'A Hold :moon_name [:moon_coords] megsemmisült!',
        'body' => 'Az Ön holdját :moon_name itt: :moon_coords elpusztította a :attacker_name nevű Deathstar flotta!',
    ],
    'wreck_field_repair_completed' => [
        'from' => 'Rendszerüzenet',
        'subject' => 'Javítás befejeződött',
        'body' => 'A planet:planet javítási kérelme teljesítve. 
A :ship_count hajókat újra üzembe helyezték.',
    ],
];
