<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : hu (OGame: hu)
 * Source   : resources/lang/en/t_overview.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'overview' => 'Áttekintés',
    'temperature' => 'Hőmérséklet',
    'position' => 'Pozíció',
];
