<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : hr (OGame: hr)
 * Source   : resources/lang/en/t_facilities.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'space_dock' => [
        'name' => 'Svemirsko Pristanište',
        'description' => 'Ruševine mogu biti popravljene na Svemirskom Pristaništu.',
        'description_long' => 'Space Dock nudi mogućnost popravka brodova uništenih u bitci koji su za sobom ostavili olupine. Vrijeme popravka traje najviše 12 sati, ali potrebno je najmanje 30 minuta dok se brodovi ne mogu ponovno staviti u promet. 

Budući da Space Dock pluta u orbiti, nije mu potrebno polje planeta.',
        'requirements' => 'Zahtijeva razinu brodogradilišta 2',
        'field_consumption' => 'Ne troši polja planeta (lebdi u orbiti)',
        'wreck_field_section' => 'Polje olupina',
        'no_wreck_field' => 'Na ovoj lokaciji nema dostupnih polja olupina.',
        'wreck_field_info' => 'Dostupno je polje olupina koje sadrži brodove koji se mogu popraviti.',
        'ships_available' => 'Brodovi dostupni za popravak: {count}',
        'repair_capacity' => 'Kapacitet popravka na temelju razine {level} Space Docka',
        'start_repair' => 'Počnite popravljati polje olupine',
        'repair_in_progress' => 'Popravci u tijeku',
        'repair_completed' => 'Popravci završeni',
        'deploy_ships' => 'Rasporedite popravljene brodove',
        'burn_wreck_field' => 'Burn olupina polje',
        'repair_time' => 'Procijenjeno vrijeme popravka: {time}',
        'repair_progress' => 'Napredak popravka: {progress}%',
        'completion_time' => 'Završetak: {vrijeme}',
        'auto_deploy_warning' => 'Brodovi će se automatski rasporediti {hours} sati nakon završetka popravka ako nisu ručno raspoređeni.',
        'level_effects' => [
            'repair_speed' => 'Brzina popravka povećana je za {bonus}%',
            'capacity_increase' => 'Povećan je najveći broj brodova koji se mogu popraviti',
        ],
        'status' => [
            'no_dock' => 'Space Dock potreban za popravak polja olupina',
            'level_too_low' => 'Za popravak polja olupina potrebna je razina 1 svemirskog doka',
            'no_wreck_field' => 'Nema dostupnih polja olupina',
            'repairing' => 'Trenutno se popravlja polje olupine',
            'ready_to_deploy' => 'Popravci su završeni, brodovi spremni za upotrebu',
        ],
    ],
    'actions' => [
        'build' => 'Izgraditi',
        'upgrade' => 'Nadogradi na razinu {level}',
        'downgrade' => 'Prijeđi na razinu {level}',
        'demolish' => 'rušiti',
        'cancel' => 'Otkazati',
    ],
    'requirements' => [
        'met' => 'Zahtjevi ispunjeni',
        'not_met' => 'Zahtjevi nisu ispunjeni',
        'research' => 'Istraživanje: {requirement}',
        'building' => 'Zgrada: {requirement} razina {level}',
    ],
    'cost' => [
        'metal' => 'Metal: {iznos}',
        'crystal' => 'Kristal: {iznos}',
        'deuterium' => 'Deuterij: {količina}',
        'energy' => 'Energija: {amount}',
        'dark_matter' => 'Tamna tvar: {iznos}',
        'total' => 'Ukupni trošak: {amount}',
    ],
    'construction_time' => 'Vrijeme izgradnje: {time}',
    'upgrade_time' => 'Vrijeme nadogradnje: {time}',
];
