<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : fi (OGame: fi)
 * Source   : resources/lang/en/t_external.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'browser_warning' => [
        'title' => 'Selaimesi ei ole ajan tasalla.',
        'desc1' => 'Internet Explorer -versiosi ei vastaa olemassa olevia standardeja, eikä tämä verkkosivusto enää tue sitä.',
        'desc2' => 'Käyttääksesi tätä verkkosivustoa päivitä selaimesi nykyiseen versioon tai käytä toista verkkoselainta. Jos käytät jo uusinta versiota, lataa sivu uudelleen, jotta se näkyy oikein.',
        'desc3' => 'Tässä on luettelo suosituimmista selaimista. Napsauta yhtä symboleista päästäksesi lataussivulle:',
    ],
    'login' => [
        'page_title' => 'OGame - Valloita universumi',
        'btn' => 'Kirjaudu sisään',
        'email_label' => 'Sähköpostiosoite:',
        'password_label' => 'Salasana:',
        'universe_label' => 'Universe',
        'universe_option_1' => '1. Universumi',
        'submit' => 'Kirjaudu sisään',
        'forgot_password' => 'Unohditko salasanasi?',
        'forgot_email' => 'Unohditko sähköpostiosoitteesi?',
        'terms_accept_html' => 'Kirjautumalla hyväksyn <a class="" href="#" target="_blank" title="T&amp;Cs">ehdot</a>',
    ],
    'register' => [
        'play_free' => 'PELAA ILMAISEKSI!',
        'email_label' => 'Sähköpostiosoite:',
        'password_label' => 'Salasana:',
        'universe_label' => 'Universe',
        'distinctions' => 'Erot',
        'terms_html' => '<a class="" target="_blank" href="#" title="T&amp;Cs"> Ehdot </a> ja <a class="" target="_blank" href="#" title="Privacy Policy"> Tietosuojakäytäntömme </a> pätevät pelissä',
        'submit' => 'Rekisteröidy',
    ],
    'nav' => [
        'home' => 'Kotiin',
        'about' => 'Tietoja OGamesta',
        'media' => 'Media',
        'wiki' => 'Wiki',
    ],
    'home' => [
        'title' => 'OGame - Valloita universumi',
        'description_html' => '<em>OGame</em> on avaruuteen sijoittuva strategiapeli, jossa tuhansia pelaajia eri puolilta maailmaa kilpailee samanaikaisesti. Tarvitset vain tavallisen verkkoselaimen pelataksesi.',
        'board_btn' => 'hallitus',
        'trailer_title' => 'Traileri',
    ],
    'footer' => [
        'legal' => 'Legal',
        'privacy_policy' => 'Tietosuojakäytäntö',
        'terms' => 'Käyttöehdot',
        'contact' => 'Ota yhteyttä',
        'rules' => 'Rules',
        'copyright' => '© OGameX. Kaikki oikeudet pidätetään.',
    ],
    'js' => [
        'login' => 'Kirjaudu sisään',
        'close' => 'Lähellä',
        'age_check_failed' => 'Olemme pahoillamme, mutta et voi rekisteröityä. Katso lisätietoja käyttöehdoistamme.',
    ],
    'validation' => [
        'required' => 'Tämä kenttä on pakollinen',
        'make_decision' => 'Tee päätös',
        'accept_terms' => 'Sinun on hyväksyttävä käyttöehdot.',
        'length' => 'Sallittu 3–20 merkkiä.',
        'pw_length' => 'Sallittu 4–20 merkkiä.',
        'email' => 'Sinun on syötettävä kelvollinen sähköpostiosoite!',
        'invalid_chars' => 'Sisältää virheellisiä merkkejä.',
        'no_begin_end_underscore' => 'Nimesi ei saa alkaa tai päättyä alaviivaan.',
        'no_begin_end_whitespace' => 'Nimesi ei saa alkaa tai päättyä välilyöntiin.',
        'max_three_underscores' => 'Nimessäsi saa olla yhteensä enintään 3 alaviivaa.',
        'max_three_whitespaces' => 'Nimessäsi saa olla yhteensä enintään 3 välilyöntiä.',
        'no_consecutive_underscores' => 'Et saa käyttää kahta tai useampaa alaviivaa peräkkäin.',
        'no_consecutive_whitespaces' => 'Et saa käyttää kahta tai useampaa välilyöntiä peräkkäin.',
        'username_available' => 'Tämä käyttäjätunnus on saatavilla.',
        'username_loading' => 'Odota, ladataan...',
        'username_taken' => 'Tämä käyttäjätunnus ei ole enää saatavilla.',
        'only_letters' => 'Käytä vain merkkejä.',
    ],
    'forgot_password' => [
        'title' => 'Unohditko salasanasi?',
        'description' => 'Kirjoita sähköpostiosoitteesi alle, niin lähetämme sinulle linkin salasanasi vaihtamiseen.',
        'email_label' => 'Sähköpostiosoite:',
        'submit' => 'Lähetä nollauslinkki',
        'back_to_login' => '← Takaisin kirjautumiseen',
    ],
    'reset_password' => [
        'title' => 'Palauta salasanasi',
        'email_label' => 'Sähköpostiosoite:',
        'password_label' => 'Uusi salasana:',
        'confirm_label' => 'Vahvista uusi salasana:',
        'submit' => 'Palauta salasana',
    ],
    'forgot_email' => [
        'title' => 'Unohditko sähköpostiosoitteesi?',
        'description' => 'Syötä komentajasi nimesi, niin lähetämme vihjeen rekisteröityyn sähköpostiosoitteeseen.',
        'username_label' => 'Komentajan nimi:',
        'submit' => 'Lähetä vihje',
        'back_to_login' => '← Takaisin kirjautumiseen',
        'sent' => 'Jos vastaava tili löytyi, rekisteröityyn sähköpostiosoitteeseen on lähetetty vihje.',
    ],
    'mail' => [
        'reset_password' => [
            'subject' => 'Palauta OGameX-salasanasi',
            'heading' => 'Salasanan palautus',
            'greeting' => 'Hei :käyttäjänimi,',
            'body' => 'Saimme pyynnön vaihtaa tilisi salasana. Napsauta alla olevaa painiketta valitaksesi uuden salasanan.',
            'cta' => 'Palauta salasana',
            'expiry' => 'Tämä linkki vanhenee 60 minuutin kuluttua.',
            'no_action' => 'Jos et pyytänyt salasanan vaihtoa, muita toimia ei tarvita.',
            'url_fallback' => 'Jos sinulla on vaikeuksia napsauttaa painiketta, kopioi ja liitä alla oleva URL-osoite selaimeesi:',
        ],
        'retrieve_email' => [
            'subject' => 'OGameX-sähköpostiosoitteesi',
            'heading' => 'Sähköpostiosoite vihje',
            'greeting' => 'Hei :käyttäjänimi,',
            'body' => 'Pyysit vihjettä tiliisi liitetylle sähköpostiosoitteelle:',
            'cta' => 'Siirry kohtaan Kirjautuminen',
            'no_action' => 'Jos et tehnyt tätä pyyntöä, voit jättää tämän sähköpostin huomiotta.',
        ],
    ],
    'universe_characteristics' => [
        'fleet_speed' => 'Laivaston nopeus: mitä suurempi arvo, sitä vähemmän sinulla on aikaa reagoida hyökkäykseen.',
        'economy_speed' => 'Talousnopeus: mitä korkeampi arvo, sitä nopeammin rakentaminen ja tutkimus valmistuvat ja resurssit kerätään.',
        'debris_ships' => 'Osa taistelussa tuhoutuneista aluksista saapuu roskakentälle.',
        'debris_defence' => 'Osa taistelussa tuhoutuneista puolustusrakenteista joutuu romukentälle.',
        'dark_matter_gift' => 'Saat Dark Matterin palkinnoksi sähköpostiosoitteesi vahvistamisesta.',
        'aks_on' => 'Alliancen taistelujärjestelmä aktivoitu',
        'planet_fields' => 'Rakennuspaikkojen enimmäismäärää on lisätty.',
        'wreckfield' => 'Space Dock aktivoitu: jotkin tuhoutuneet alukset voidaan palauttaa käyttämällä Space Dockia.',
        'universe_big' => 'Galaksien määrä universumissa',
    ],
];
