<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : fi (OGame: fi)
 * Source   : resources/lang/en/t_galaxy.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'planet' => [
        'description' => [
            'nearest' => 'Auringon läheisyyden ansiosta aurinkoenergian kerääminen on erittäin tehokasta. Tässä asennossa olevat planeetat ovat kuitenkin yleensä pieniä ja tarjoavat vain pieniä määriä deuteriumia.',
            'normal' => 'Normaalisti tässä asennossa on tasapainoisia planeettoja, joilla on riittävästi deuteriumlähteitä, hyvä aurinkoenergian saanti ja riittävästi tilaa kehittyä.',
            'biggest' => 'Yleensä aurinkokunnan suurimmat planeetat sijaitsevat tässä paikassa. Aurinko antaa riittävästi energiaa ja riittävästi deuteriumlähteitä voidaan ennakoida.',
            'farthest' => 'Auringon suuren etäisyyden vuoksi aurinkoenergian kerääminen on rajoitettua. Nämä planeetat tarjoavat kuitenkin yleensä merkittäviä deuteriumin lähteitä.',
        ],
    ],
    'mission' => [
        'colonize' => [
            'name' => 'Asuttaa',
            'no_ship' => 'Ei ole mahdollista kolonisoida planeettaa ilman siirtomaa-alusta.',
        ],
    ],
    'discovery' => [
        'locked' => 'You haven\'t unlocked the research to discover new lifeforms yet.',
    ],
];
