<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : fi (OGame: fi)
 * Source   : resources/lang/en/t_messages.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'welcome_message' => [
        'from' => 'OGameX',
        'subject' => 'Tervetuloa OGameX:ään!',
        'body' => 'Tervehdys keisari :player! 

Onnittelut upean urasi aloittamisesta. Olen täällä opastamassa sinua ensimmäisten askelidesi läpi. 

Vasemmalla näet valikon, jonka avulla voit valvoa ja hallita galaktista valtakuntaasi. 

Olet jo nähnyt yleiskatsauksen. Resurssien ja tilojen avulla voit rakentaa rakennuksia, jotka auttavat sinua laajentamaan valtakuntaasi. Aloita rakentamalla aurinkovoimala kerätäksesi energiaa kaivosillesi. 

Laajenna sitten metallikaivoksiasi ja kristallikaivostasi tuottaaksesi tärkeitä resursseja. Muussa tapauksessa katso vain itseäsi. Tunnet olosi pian hyvin kotona, olen varma. 

Lisää ohjeita, vinkkejä ja taktiikoita löydät täältä: 

Discord Chat: Discord-palvelin 
Foorumi: OGameX Forum 
Tuki: Pelituki 

Löydät vain ajankohtaiset ilmoitukset ja peliin tehdyt muutokset foorumeilta. 


Nyt olet valmis tulevaisuuteen. Onnea! 

Tämä viesti poistetaan 7 päivän kuluttua.',
    ],
    'return_of_fleet_with_resources' => [
        'from' => 'Laivaston komento',
        'subject' => 'Laivaston palautus',
        'body' => 'Laivastosi palaa paikasta :from to :to ja on toimittanut tavaransa: 

Metalli: :metalli 
Kristalli: :kristalli 
Deuterium: :deuterium',
    ],
    'return_of_fleet' => [
        'from' => 'Laivaston komento',
        'subject' => 'Laivaston palautus',
        'body' => 'Laivastosi palaa kohteesta :from kohteeseen :to. 

Laivasto ei toimita tavaroita.',
    ],
    'fleet_deployment_with_resources' => [
        'from' => 'Laivaston komento',
        'subject' => 'Laivaston palautus',
        'body' => 'Yksi kalustoistasi osoitteesta :from on saapunut :to ja toimittanut tavaransa: 

Metalli: :metalli 
Kristalli: :kristalli 
Deuterium: :deuterium',
    ],
    'fleet_deployment' => [
        'from' => 'Laivaston komento',
        'subject' => 'Laivaston palautus',
        'body' => 'Yksi laivastosi osoitteesta :from on saavuttanut :to. Laivasto ei toimita tavaroita.',
    ],
    'transport_arrived' => [
        'from' => 'Laivaston komento',
        'subject' => 'Planeetan saavuttaminen',
        'body' => 'Laivastosi osoitteesta :from tavoittaa :to ja toimittaa tavaransa: 
Metalli: :metalli Kristalli: :kide Deuterium: :deuterium',
    ],
    'transport_received' => [
        'from' => 'Laivaston komento',
        'subject' => 'Saapuva laivasto',
        'body' => 'Saapuva laivasto osoitteesta :from on saapunut planeetallesi :to ja toimittanut tavaransa: 
Metalli: :metalli Kristalli: :kide Deuterium: :deuterium',
    ],
    'acs_defend_arrival_host' => [
        'from' => 'Avaruuden seuranta',
        'subject' => 'Laivasto pysähtyy',
        'body' => 'Laivasto on saapunut osoitteeseen :to.',
    ],
    'acs_defend_arrival_sender' => [
        'from' => 'Laivaston komento',
        'subject' => 'Laivasto pysähtyy',
        'body' => 'Laivasto on saapunut osoitteeseen :to.',
    ],
    'colony_established' => [
        'from' => 'Laivaston komento',
        'subject' => 'Sovintoratkaisuraportti',
        'body' => 'Laivasto on saapunut määrättyihin koordinaatteihin: koordinaatit, löytänyt sieltä uuden planeetan ja alkaa kehittyä sille välittömästi.',
    ],
    'colony_establish_fail_astrophysics' => [
        'from' => 'uudisasukkaat',
        'subject' => 'Sovintoratkaisuraportti',
        'body' => 'Laivasto on saavuttanut osoitetut koordinaatit: koordinaatit ja varmistaa, että planeetta on elinkelpoinen kolonisaatiolle. Pian planeetan kehittämisen aloittamisen jälkeen kolonistit ymmärtävät, että heidän astrofysiikkatietonsa eivät riitä uuden planeetan kolonisaation loppuun saattamiseen.',
    ],
    'espionage_report' => [
        'from' => 'Laivaston komento',
        'subject' => 'Vakoiluraportti :planetista',
    ],
    'espionage_detected' => [
        'from' => 'Laivaston komento',
        'subject' => 'Vakoiluraportti Planet:planetista',
        'body' => 'Vieras laivasto planeetalta :planet (:hyökkääjän_nimi) havaittiin lähellä planeettasi 
:puolustaja 
Vastavakoilun mahdollisuus: :chance%',
    ],
    'battle_report' => [
        'from' => 'Laivaston komento',
        'subject' => 'Taisteluraportti :planeetta',
    ],
    'fleet_lost_contact' => [
        'from' => 'Laivaston komento',
        'subject' => 'Yhteys hyökkäävään laivastoon on katkennut. :koordinaatit',
        'body' => '(Se tarkoittaa, että se tuhoutui ensimmäisellä kierroksella.)',
    ],
    'debris_field_harvest' => [
        'from' => 'Fleet',
        'subject' => 'Hakkuuraportti DF:ltä :coordinates',
        'body' => 'Sinun :ship_name (:ship_amount ships) kokonaistallennuskapasiteetti on :storage_capacity. Kohteessa :to, :metalli Metal, :crystal Crystal ja :deuterium Deuterium kelluu avaruudessa. Olet kerännyt :harvested_metal Metallia, :harvested_crystal Crystalia ja :harvested_deuterium Deuteriumia.',
    ],
    'expedition_resources_captured' => ':resurssin_tyyppi :resurssin_määrä on kaapattu.',
    'expedition_dark_matter_captured' => '(:dark_matter_amount Dark Matter)',
    'expedition_units_captured' => 'Seuraavat alukset ovat nyt osa laivastoa:',
    'expedition_unexplored_statement' => 'Viestintäupseerien lokikirjasta: Näyttää siltä, ​​että tätä universumin osaa ei ole vielä tutkittu.',
    'expedition_failed' => [
        'from' => 'Laivaston komento',
        'subject' => 'Tutkimusmatkan tulos',
        'body' => [
            '1' => 'Lippulaivan keskustietokoneiden vian vuoksi tutkimusmatka jouduttiin keskeyttämään. Valitettavasti tietokonevian seurauksena laivasto palaa kotiin tyhjin käsin.',
            '2' => 'Tutkimusmatkasi melkein törmäsi neutronitähtien gravitaatiokenttään ja tarvitsi jonkin aikaa vapautuakseen. Tästä johtuen paljon Deuteriumia kului ja retkikunnan laivaston täytyi palata ilman tuloksia.',
            '3' => 'Tuntemattomista syistä retkikunnan hyppy meni täysin pieleen. Se melkein laskeutui auringon sydämeen. Onneksi se laskeutui tunnettuun järjestelmään, mutta takaisinhyppy kestää luultua kauemmin.',
            '4' => 'Vika lippulaivan reaktorin sydämessä melkein tuhoaa koko tutkimusmatkan laivaston. Onneksi teknikot olivat enemmän kuin päteviä ja pystyivät välttämään pahimman. Korjaustyöt kestivät jonkin aikaa ja pakottivat retkikunnan palaamaan saavuttamatta tavoitettaan.',
            '5' => 'Elävä olento, joka tehtiin puhtaasta energiasta, tuli kyytiin ja sai kaikki retkikunnan jäsenet johonkin outoon transsiin, jolloin he vain katselivat tietokoneen näytöillä olevia hypnotisoivia kuvioita. Kun useimmat heistä lopulta päätyivät hypnoottisesta tilasta, tutkimusmatka piti keskeyttää, koska heillä oli liian vähän deuteriumia.',
            '6' => 'Uusi navigointimoduuli on edelleen buginen. Tutkimusmatkat eivät ainoastaan ​​johdaneet heitä väärään suuntaan, vaan ne käyttivät kaiken Deuterium-polttoaineen. Onneksi laivastojen hyppy sai heidät lähelle lähtöplaneettojen kuuta. Hieman pettynyt retkikunta palaa nyt ilman impulssivoimaa. Paluumatka kestää odotettua kauemmin.',
            '7' => 'Tutkimusmatkasi on oppinut avaruuden laajasta tyhjyydestä. Ei ollut edes yhtä pientä asteroidia tai säteilyä tai hiukkasta, joka olisi voinut tehdä tästä tutkimusmatkasta mielenkiintoisen.',
            '8' => 'No, nyt tiedämme, että niillä punaisilla, luokan 5 poikkeavuuksilla ei ole vain kaoottisia vaikutuksia laivojen navigointijärjestelmiin, vaan ne myös aiheuttavat massiivisia hallusinaatioita miehistöön. Retki ei tuonut mitään takaisin.',
            '9' => 'Tutkimusmatkasi otti upeita kuvia supernovasta. Tutkimusmatkalta ei saatu mitään uutta, mutta OGame-lehden seuraavan kuukauden numerossa on ainakin hyvät mahdollisuudet voittaa "Best Picture Of The Universe" -kilpailu.',
            '10' => 'Retkikuntasi laivastosi seurasi outoja signaaleja jonkin aikaa. Lopulta he huomasivat, että nuo signaalit lähetettiin vanhasta luotain, joka lähetettiin sukupolvia sitten tervehtimään vieraita lajeja. Luotain pelastettiin ja jotkut kotiplaneettasi museot ovat jo ilmaisseet kiinnostuksensa.',
            '11' => 'Huolimatta tämän alan ensimmäisistä, erittäin lupaavista skannauksista, palasimme valitettavasti tyhjin käsin.',
            '12' => 'Tuntemattomalta suoplaneetalta peräisin olevien viehättävien, pienten lemmikkien lisäksi tämä retkikunta ei tuo matkalta mitään jännittävää.',
            '13' => 'Retkikunnan lippulaiva törmäsi vieraaseen alukseen, kun se hyppäsi laivastoon ilman varoitusta. Ulkomainen alus räjähti ja lippulaivavauriot olivat huomattavia. Retki ei voi jatkua näissä olosuhteissa, joten laivasto alkaa palata, kun tarvittavat korjaukset on tehty.',
            '14' => 'Retkikuntamme törmäsi outoon siirtokuntaan, joka oli hylätty aikoja sitten. Laskeutumisen jälkeen miehistömme alkoi kärsiä muukalaisviruksen aiheuttamasta korkeasta kuumeesta. On opittu, että tämä virus pyyhkäisi pois koko sivilisaation planeetalta. Retkikuntamme on matkalla kotiin hoitamaan sairaita miehistön jäseniä. Valitettavasti jouduimme keskeyttämään tehtävän ja tulemme kotiin tyhjin käsin.',
            '15' => 'Outo tietokonevirus hyökkäsi navigointijärjestelmään pian kotijärjestelmän erotuksen jälkeen. Tämä sai retkikunnan laivaston lentämään ympyrää. Tarpeetonta sanoa, että tutkimusmatka ei todellakaan onnistunut.',
        ],
    ],
    'expedition_gain_resources' => [
        'from' => 'Laivaston komento',
        'subject' => 'Tutkimusmatkan tulos',
        'body' => [
            '1' => 'Eristetyltä planetoidilta löysimme helposti saatavilla olevia luonnonvarakenttiä ja korjasimme osan onnistuneesti.',
            '2' => 'Retkikuntasi löysi pienen asteroidin, josta voitiin kerätä resursseja.',
            '3' => 'Retkikuntasi löysi ikivanhan, täyteen lastatun mutta aution rahtialussaattueen. Osa resursseista voitaisiin pelastaa.',
            '4' => 'Retkikuntasi laivasto raportoi valtavan avaruusaluksen hylkystä. He eivät pystyneet oppimaan tekniikoistaan, mutta he pystyivät jakamaan laivan pääkomponentteihinsa ja hankkimaan siitä hyödyllisiä resursseja.',
            '5' => 'Pieneltä kuulta, jolla oli oma tunnelma, retkikuntasi löysi valtavan raaka-ainevaraston. Maan päällä oleva miehistö yrittää nostaa ja lastata tuota luonnonaarretta.',
            '6' => 'Tuntemattoman planeetan ympärillä olevat mineraalivyöhykkeet sisälsivät lukemattomia luonnonvaroja. Retkikunnan alukset tulevat takaisin ja niiden varastot ovat täynnä!',
        ],
    ],
    'expedition_gain_dark_matter' => [
        'from' => 'Laivaston komento',
        'subject' => 'Tutkimusmatkan tulos',
        'body' => [
            '1' => 'Retkikunta seurasi joitain outoja signaaleja asteroidille. Asteroidien ytimestä löydettiin pieni määrä pimeää ainetta. Asteroidi valloitettiin ja tutkijat yrittävät poimia pimeää ainetta.',
            '2' => 'Retkikunta pystyi vangitsemaan ja tallentamaan pimeää ainetta.',
            '3' => 'Tapasimme pienen laivan hyllyllä oudon alienin, joka antoi meille Dark Matterin kotelon vastineeksi yksinkertaisista matemaattisista laskelmista.',
            '4' => 'Löysimme avaruusaluksen jäänteet. Löysimme tavaratilan hyllyltä pienen kontin, jossa oli pimeää ainetta!',
            '5' => 'Retkikuntamme otti ensimmäisen kosketuksen erikoiskilpailuun. Näyttää siltä, ​​että puhtaasta energiasta tehty olento, joka nimesi itsensä Legorianiksi, olisi lentänyt retkikunnan alusten läpi ja päättänyt sitten auttaa alikehittyneitä lajejamme. Pimeää ainetta sisältävä kotelo toteutui aluksen komentosillalla!',
            '6' => 'Retkikuntamme otti haltuunsa aave-aluksen, joka kuljetti pientä määrää Dark Materia. Emme löytäneet mitään vihjeitä siitä, mitä aluksen alkuperäiselle miehistölle tapahtui, mutta teknikot pystyivät pelastamaan Dark Matterin.',
            '7' => 'Retkikuntamme suoritti ainutlaatuisen kokeen. He pystyivät keräämään pimeää ainetta kuolevasta tähdestä.',
            '8' => 'Retkikuntamme löysi ruosteisen avaruusaseman, joka näytti kelluneen hallitsemattomasti ulkoavaruudessa pitkään. Asema itsessään oli täysin hyödytön, mutta havaittiin, että reaktoriin oli varastoitu jonkin verran pimeää ainetta. Teknikkomme yrittävät säästää niin paljon kuin pystyvät.',
        ],
    ],
    'expedition_gain_ships' => [
        'from' => 'Laivaston komento',
        'subject' => 'Tutkimusmatkan tulos',
        'body' => [
            '1' => 'Retkikuntamme löysi planeetan, joka melkein tuhoutui tietyn sotaketjun aikana. Radalla kelluu erilaisia ​​aluksia. Teknikot yrittävät korjata joitakin niistä. Ehkä täältä saa myös tietoa tapahtuneesta.',
            '2' => 'Löysimme aution merirosvoaseman. Hallissa makaa vanhoja laivoja. Teknikkomme selvittävät, ovatko jotkut niistä edelleen hyödyllisiä vai eivät.',
            '3' => 'Retkikuntasi törmäsi siirtokunnan telakoihin, joka oli autio ikuisuus sitten. Telakkahallissa he löytävät joitain aluksia, jotka voitaisiin pelastaa. Teknikot yrittävät saada osan niistä taas lentämään.',
            '4' => 'Löysimme edellisen tutkimusmatkan jäännökset! Teknikkomme yrittävät saada osan laivoista taas toimimaan.',
            '5' => 'Retkikuntamme törmäsi vanhaan automaattiseen telakkaan. Osa laivoista on vielä tuotantovaiheessa ja teknikot yrittävät parhaillaan aktivoida telakan energiageneraattoreita.',
            '6' => 'Löysimme armadan jäänteet. Teknikot menivät suoraan lähes ehjiin aluksiin saadakseen ne taas töihin.',
            '7' => 'Löysimme sukupuuttoon kuolleen sivilisaation planeetan. Pystymme näkemään jättiläismäisen ehjän avaruusaseman kiertämässä. Jotkut teknikot ja luotsit menivät pintaan etsimään joitain aluksia, joita voitaisiin vielä käyttää.',
        ],
    ],
    'expedition_gain_item' => [
        'from' => 'Laivaston komento',
        'subject' => 'Tutkimusmatkan tulos',
        'body' => [
            '1' => 'Pakeneva laivasto jätti jälkeensä esineen häiritäkseen meidän huomiomme auttamaan heitä pakenemaan.',
        ],
    ],
    'expedition_failed_and_speedup' => [
        'from' => 'Laivaston komento',
        'subject' => 'Tutkimusmatkan tulos',
        'body' => [
            '1' => 'Tutkimusmatkasi eivät raportoi mitään poikkeavuuksia tutkitulla alalla. Mutta laivasto törmäsi aurinkotuulen palatessaan. Tämä johti siihen, että paluumatka nopeutui. Retkikuntasi palaa kotiin hieman aikaisemmin.',
            '2' => 'Uusi ja rohkea komentaja kulki onnistuneesti epävakaan madonreiän läpi lyhentääkseen paluulentoa! Itse tutkimusmatka ei kuitenkaan tuonut mitään uutta.',
            '3' => 'Odottamaton takaisinkytkentä moottoreiden energiapuolissa nopeuttai tutkimusmatkojen paluuta, se palaa kotiin odotettua aikaisemmin. Ensimmäiset raportit kertovat, ettei heillä ole mitään jännittävää.',
        ],
    ],
    'expedition_failed_and_delay' => [
        'from' => 'Laivaston komento',
        'subject' => 'Tutkimusmatkan tulos',
        'body' => [
            '1' => 'Retkikuntasi meni sektorille, joka on täynnä hiukkasmyrskyjä. Tämä sai energiavarastot ylikuormitettua ja suurin osa laivojen pääjärjestelmistä kaatui. Mekaniikkasi onnistuivat välttämään pahimman, mutta retkikunta palaa suurella viiveellä.',
            '2' => 'Navigaattorisi teki vakavan virheen laskelmissaan, minkä vuoksi tutkimusmatkat laskettiin väärin. Laivasto ei vain missannut tavoitetta kokonaan, vaan paluumatka vie paljon enemmän aikaa kuin alun perin oli suunniteltu.',
            '3' => 'Punaisen jättiläisen aurinkotuuli tuhosi tutkimusmatkan hypyn ja paluuhypyn laskeminen kestää melko kauan. Siinä sektorissa ei ollut mitään muuta kuin avaruuden tyhjyys tähtien välillä. Laivasto palaa odotettua myöhemmin.',
        ],
    ],
    'expedition_battle' => [
        'from' => 'Laivaston komento',
        'subject' => 'Tutkimusmatkan tulos',
        'body' => [
            '1' => 'Jotkut primitiiviset barbaarit hyökkäävät kimppuumme avaruusaluksilla, joita ei voida edes nimetä sellaisiksi. Jos tuli pahenee vakavaksi, meidän on ammuttava takaisin.',
            '2' => 'Meidän piti taistella joitakin merirosvoja vastaan, joita oli onneksi vain muutama.',
            '3' => 'Saimme joitain radiolähetyksiä humalaisilta merirosvoilta. Näyttää siltä, ​​että olemme pian hyökkäyksen kohteena.',
            '4' => 'Pieni ryhmä tuntemattomia aluksia hyökkäsi tutkimusmatkamme kimppuun!',
            '5' => 'Jotkut todella epätoivoiset avaruusmerirosvot yrittivät vangita retkikuntamme.',
            '6' => 'Jotkut eksoottisen näköiset alukset hyökkäsivät retkikunnan laivaston kimppuun ilman varoitusta!',
            '7' => 'Retkikuntanne laivastolla oli epäystävällinen ensimmäinen kosketus tuntemattomaan lajiin.',
        ],
    ],
    'expedition_battle_pirates' => [
        'from' => 'Laivaston komento',
        'subject' => 'Tutkimusmatkan tulos',
        'body' => [
            '1' => 'Jotkut primitiiviset barbaarit hyökkäävät kimppuumme avaruusaluksilla, joita ei voida edes nimetä sellaisiksi. Jos tuli pahenee vakavaksi, meidän on ammuttava takaisin.',
            '2' => 'Meidän piti taistella joitakin merirosvoja vastaan, joita oli onneksi vain muutama.',
            '3' => 'Saimme joitain radiolähetyksiä humalaisilta merirosvoilta. Näyttää siltä, ​​että olemme pian hyökkäyksen kohteena.',
            '4' => 'Pieni ryhmä avaruusmerirosvoja hyökkäsi retkikuntaamme!',
            '5' => 'Jotkut todella epätoivoiset avaruusmerirosvot yrittivät vangita retkikuntamme.',
            '6' => 'Merirosvot väijyttivät tutkimusmatkan laivaston varoittamatta!',
            '7' => 'Avaruusmerirosvojen räjähdysmäinen laivasto sieppasi meidät vaatien kunnianosoitusta.',
        ],
    ],
    'expedition_battle_aliens' => [
        'from' => 'Laivaston komento',
        'subject' => 'Tutkimusmatkan tulos',
        'body' => [
            '1' => 'Poimimme outoja signaaleja tuntemattomilta aluksilta. He osoittautuivat vihamielisiksi!',
            '2' => 'Muukalaispartio havaitsi retkikuntamme laivastomme ja hyökkäsi välittömästi!',
            '3' => 'Retkikuntanne laivastolla oli epäystävällinen ensimmäinen kosketus tuntemattomaan lajiin.',
            '4' => 'Jotkut eksoottisen näköiset alukset hyökkäsivät retkikunnan laivaston kimppuun ilman varoitusta!',
            '5' => 'Muukalaisten sotalaivasto nousi hyperavaruudesta ja otti meidät mukaansa!',
            '6' => 'Tapasimme teknisesti edistyneen vieraslajin, joka ei ollut rauhallinen.',
            '7' => 'Anturimme havaitsivat tuntemattomat energiatunnisteet ennen avaruusalusten hyökkäämistä!',
        ],
    ],
    'expedition_loss_of_fleet' => [
        'from' => 'Laivaston komento',
        'subject' => 'Tutkimusmatkan tulos',
        'body' => [
            '1' => 'Johtavan aluksen ydinsulaminen johtaa ketjureaktioon, joka tuhoaa koko retkikunnan laivaston mahtavassa räjähdyksessä.',
        ],
    ],
    'expedition_merchant_found' => [
        'from' => 'Laivaston komento',
        'subject' => 'Tutkimusmatkan tulos',
        'body' => [
            '1' => 'Retkikuntasi laivasto otti yhteyttä ystävälliseen avaruusolioon. He ilmoittivat lähettävänsä edustajan tavaroineen kauppaan teidän maailmoihinne.',
            '2' => 'Salaperäinen kauppa-alus lähestyi tutkimusmatkaasi. Kauppias tarjoutui vierailemaan planeetoillasi ja tarjoamaan erityisiä kaupankäyntipalveluita.',
            '3' => 'Retkikunta kohtasi galaktisten kauppasaattueen. Yksi kauppiaista on suostunut vierailemaan kotimaailmassasi tarjotakseen kaupankäyntimahdollisuuksia.',
        ],
    ],
    'buddy_request_received' => [
        'from' => 'Buddies',
        'subject' => 'Buddy request',
        'body' => 'Olet saanut uuden kaveripyynnön lähettäjältä :sender_name.<span style="display:none;">:buddy_request_id</span>',
    ],
    'buddy_request_accepted' => [
        'from' => 'Buddies',
        'subject' => 'Kaveripyyntö hyväksytty',
        'body' => 'Pelaaja :accepter_name lisäsi sinut kaveriluetteloonsa.',
    ],
    'buddy_removed' => [
        'from' => 'Buddies',
        'subject' => 'Sinut poistettiin kaveriluettelosta',
        'body' => 'Player :remover_name poisti sinut kaveriluettelostaan.',
    ],
    'missile_attack_report' => [
        'from' => 'Laivaston komento',
        'subject' => 'Ohjushyökkäys kohteelle :target_coords',
        'body' => 'Planeettojen väliset ohjukset kohteesta :alkuperäplaneetan_nimi :alkuperäplanetin_koordinaatit (ID: :alkuperäplaneetan_id) ovat saavuttaneet tavoitteensa osoitteessa :target_planet_name :target_coords (ID: :target_planet_id, Tyyppi: :target_type). 

Ohjukset laukaistiin: :missiles_sent 
Siepatut ohjukset: :missiles_intercepted 
Ohjusten osuma: :missiles_hit 

Puolustus tuhottu: :defenses_destroyed',
        'missile_singular' => 'missile',
        'missile_plural' => 'missiles',
        'from_your_planet' => ' from your planet ',
        'smashed_into' => ' smashed into the planet ',
        'intercepted_label' => 'Missiles Intercepted:',
        'defenses_hit_label' => 'Defenses Hit',
        'none' => 'None',
    ],
    'missile_defense_report' => [
        'from' => 'Puolustusjohto',
        'subject' => 'Ohjushyökkäys :planet_coordsiin',
        'body' => 'Planeetaasi :planet_name osoitteessa :planet_coords (ID: :planet_id) on hyökännyt planeettojen välisillä ohjuksilla käyttäjältä :attacker_name! 

Saapuvat ohjukset: :missiles_incoming 
Siepatut ohjukset: :missiles_intercepted 
Ohjusten osuma: :missiles_hit 

Puolustus tuhottu: :defenses_destroyed',
        'your_planet' => 'Your planet ',
        'attacked_by_prefix' => ' has been attacked by interplanetary missiles from ',
        'incoming_label' => 'Incoming Missiles:',
        'intercepted_label' => 'Missiles Intercepted:',
        'defenses_hit_label' => 'Defenses Hit',
        'none' => 'None',
    ],
    'alliance_broadcast' => [
        'from' => ':lähettäjän_nimi',
        'subject' => '[:alliance_tag] Alliance-lähetys lähettäjältä :sender_name',
        'body' => ':viesti',
    ],
    'alliance_application_received' => [
        'from' => 'Allianssin hallinta',
        'subject' => 'Uusi allianssihakemus',
        'body' => 'Pelaaja :hakijan_nimi on hakenut liittymistä liittoutumaan. 

Sovellusviesti: 
:sovellus_viesti',
    ],
    'planet_relocation_success' => [
        'from' => 'Hallitse pesäkkeitä',
        'subject' => ':planeetan_nimi siirto on onnistunut',
        'body' => 'Planeetta :planeetan_nimi on siirretty onnistuneesti koordinaateista [koordinaatit]:vanhat_koordinaatit[/koordinaatit] kohtaan [koordinaatit]:uudet_koordinaatit[/koordinaatit].',
    ],
    'fleet_union_invite' => [
        'from' => 'Laivaston komento',
        'subject' => 'Kutsu liittoutumaan taisteluun',
        'body' => ':sender_name kutsui sinut tehtävään :union_name vastaan ​​:target_player [:target_coords], laivasto on ajoitettu :arrival_timeen. 

VAROITUS: Saapumisaika voi muuttua laivastojen liittymisen vuoksi. Jokainen uusi laivasto voi pidentää tätä aikaa enintään 30 %, muuten se ei voi liittyä. 

HUOMAA: Kaikkien osallistujien kokonaisvoima verrattuna puolustajien kokonaisvoimakkuuteen määrää, tuleeko siitä kunniallinen taistelu vai ei.',
    ],
    'Shipyard is being upgraded.' => 'Telakkaa kunnostetaan.',
    'Nanite Factory is being upgraded.' => 'Nanite Factoryä päivitetään.',
    'moon_destruction_success' => [
        'from' => 'Laivaston komento',
        'subject' => 'Kuu :moon_name [:moon_coords] on tuhottu!',
        'body' => 'Tuhotodennäköisyydellä :destruction_chance ja Kuolemantähden menetyksen todennäköisyydellä :loss_chance laivastosi on onnistuneesti tuhonnut kuun :moon_name osoitteessa :moon_coords.',
    ],
    'moon_destruction_failure' => [
        'from' => 'Laivaston komento',
        'subject' => 'Kuun tuhoaminen :moon_coords epäonnistui',
        'body' => 'Tuhotodennäköisyydellä :destruction_chance ja Kuolemantähden menetyksen todennäköisyydellä :loss_chance laivastosi ei onnistunut tuhoamaan kuuta :moon_name klo :moon_coords. Laivasto palaa.',
    ],
    'moon_destruction_catastrophic' => [
        'from' => 'Laivaston komento',
        'subject' => 'Katastrofaalinen menetys kuun tuhon aikana osoitteessa :moon_coords',
        'body' => 'Tuhotodennäköisyydellä :destruction_chance ja Kuolemantähden menetyksen todennäköisyydellä :loss_chance laivastosi ei onnistunut tuhoamaan kuuta :moon_name klo :moon_coords. Lisäksi kaikki Deathstars menetettiin yrityksessä. Ei ole hylkyä.',
    ],
    'moon_destruction_mission_failed' => [
        'from' => 'Laivaston komento',
        'subject' => 'Kuun tuhoamistehtävä epäonnistui :coordinates',
        'body' => 'Laivastosi saapui :koordinaatteihin, mutta kohdesijainnista ei löytynyt kuuta. Laivasto palaa.',
    ],
    'moon_destruction_repelled' => [
        'from' => 'Avaruuden seuranta',
        'subject' => 'Tuhoyritys kuussa :moon_name [:moon_coords] torjuttiin',
        'body' => ':hyökkääjän_nimi hyökkäsi kuutasi :kuun_nimi klo :moon_coords tuhoutumistodennäköisyydellä :destruction_chance ja Kuolemantähden menetyksen todennäköisyydellä :loss_chance. Kuusi on selvinnyt hyökkäyksestä!',
    ],
    'moon_destroyed' => [
        'from' => 'Avaruuden seuranta',
        'subject' => 'Kuu :moon_name [:moon_coords] on tuhottu!',
        'body' => 'Kuusi :moon_name osoitteessa :moon_coords on tuhonnut Deathstar-laivaston, joka kuuluu käyttäjälle :attacker_name!',
    ],
    'wreck_field_repair_completed' => [
        'from' => 'Järjestelmäviesti',
        'subject' => 'Korjaus suoritettu',
        'body' => 'Korjauspyyntösi planeetalla :planet on suoritettu. 
:ship_count alukset on otettu takaisin käyttöön.',
    ],
];
