<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : fi (OGame: fi)
 * Source   : resources/lang/en/t_resources.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'metal_mine' => [
        'title' => 'Metal Mine',
        'description' => 'Used in the extraction of metal ore, metal mines are of primary importance to all emerging and established empires.',
        'description_long' => 'Metal is the primary resource used in the foundation of your Empire. At greater depths, the mines can produce more output of viable metal for use in the construction of buildings, ships, defence systems, and research. As the mines drill deeper, more energy is required for maximum production. As metal is the most abundant of all resources available, its value is considered to be the lowest of all resources for trading.',
    ],
    'crystal_mine' => [
        'title' => 'Crystal Mine',
        'description' => 'Crystals are the main resource used to build electronic circuits and form certain alloy compounds.',
        'description_long' => 'Crystal mines supply the main resource used to produce electronic circuits and from certain alloy compounds. Mining crystal consumes some one and half times more energy than a mining metal, making crystal more valuable. Almost all ships and all buildings require crystal. Most crystals required to build spaceships, however, are very rare, and like metal can only be found at a certain depth. Therefore, building mines in deeper strata will increase the amount of crystal produced.',
    ],
    'deuterium_synthesizer' => [
        'title' => 'Deuterium Synthesizer',
        'description' => 'Deuterium Synthesizers draw the trace Deuterium content from the water on a planet.',
        'description_long' => 'Deuterium is also called heavy hydrogen. It is a stable isotope of hydrogen with a natural abundance in the oceans of colonies of approximately one atom in 6500 of hydrogen (~154 PPM). Deuterium thus accounts for approximately 0.015% (on a weight basis, 0.030%) of all. Deuterium is processed by special synthesizers which can separate the water from the Deuterium using specially designed centrifuges. The upgrade of the synthesizer allows for increasing the amount of Deuterium deposits processed. Deuterium is used when carrying out sensor phalanx scans, viewing galaxies, as fuel for ships, and performing specialized research upgrades.',
    ],
    'solar_plant' => [
        'title' => 'Solar Plant',
        'description' => 'Solar power plants absorb energy from solar radiation. All mines need energy to operate.',
        'description_long' => 'Gigantic solar arrays are used to generate power for the mines and the deuterium synthesizer. As the solar plant is upgraded, the surface area of the photovoltaic cells covering the planet increases, resulting in a higher energy output across the power grids of your planet.',
    ],
    'fusion_plant' => [
        'title' => 'Fusion Reactor',
        'description' => 'The fusion reactor uses deuterium to produce energy.',
        'description_long' => 'Fuusiovoimalaitoksissa vetyytimet fuusioidaan heliumytimiksi valtavassa lämpötilassa ja paineessa, jolloin vapautuu valtavia määriä energiaa. Jokaista kulutettua deuteriumgrammaa kohti voidaan tuottaa jopa 41,32*10^-13 joulea energiaa; 1 g:lla pystyt tuottamaan 172 MWh energiaa. 

Suuremmat reaktorikompleksit käyttävät enemmän deuteriumia ja voivat tuottaa enemmän energiaa tunnissa. Energiatehokkuutta voitaisiin lisätä tutkimalla energiateknologiaa. 

Fuusiolaitoksen energiantuotanto lasketaan seuraavasti: 
30 * [Level Fusion Plant] * (1,05 + [Level Energy Technology] * 0,01) ^ [Level Fusion Plant]',
    ],
    'metal_store' => [
        'title' => 'Metal Storage',
        'description' => 'Provides storage for excess metal.',
        'description_long' => 'Tätä jättimäistä varastotilaa käytetään metallimalmin varastointiin. Jokainen parannustaso lisää varastoitavan metallimalmin määrää. Jos myymälät ovat täynnä, metallia ei louhita enempää. 

Metallivarasto suojaa tiettyä prosenttiosuutta kaivoksen päivittäisestä tuotannosta (max. 10 prosenttia).',
    ],
    'crystal_store' => [
        'title' => 'Crystal Storage',
        'description' => 'Provides storage for excess crystal.',
        'description_long' => 'Käsittelemätöntä kristallia säilytetään sillä välin näissä jättiläisvarastohalleissa. Jokaisella päivitystasolla se lisää varastoitavan kiteen määrää. Jos kristallivarastot ovat täynnä, enempää kiteitä ei louhita. 

Crystal Storage suojaa tiettyä prosenttiosuutta kaivoksen päivittäisestä tuotannosta (max. 10 prosenttia).',
    ],
    'deuterium_store' => [
        'title' => 'Deuterium Tank',
        'description' => 'Giant tanks for storing newly-extracted deuterium.',
        'description_long' => 'Deuterium-säiliö on tarkoitettu vastasyntetisoidun deuteriumin varastointiin. Kun syntetisaattori on käsitellyt sen, se johdetaan tähän säiliöön myöhempää käyttöä varten. Jokaisella säiliön päivityksellä kokonaisvarastointikapasiteetti kasvaa. Kun kapasiteetti on saavutettu, deuteriumia ei enää syntetisoidu. 

Deuterium Tank suojaa tietyn prosenttiosuuden syntetisaattorin päivittäisestä tuotannosta (max. 10 prosenttia).',
    ],
    'robot_factory' => [
        'title' => 'Robotics Factory',
        'description' => 'Robotic factories provide construction robots to aid in the construction of buildings. Each level increases the speed of the upgrade of buildings.',
        'description_long' => 'The Robotics Factory primary goal is the production of State of the Art construction robots. Each upgrade to the robotics factory results in the production of faster robots, which is used to reduce the time needed to construct buildings.',
    ],
    'shipyard' => [
        'title' => 'Shipyard',
        'description' => 'All types of ships and defensive facilities are built in the planetary shipyard.',
        'description_long' => 'The planetary shipyard is responsible for the construction of spacecraft and defensive mechanisms. As the shipyard is upgraded, it can produce a wider variety of vehicles at a much greater rate of speed. If a nanite factory is present on the planet, the speed at which ships are constructed is massively increased.',
    ],
    'research_lab' => [
        'title' => 'Research Lab',
        'description' => 'A research lab is required in order to conduct research into new technologies.',
        'description_long' => 'An essential part of any empire, Research Labs are where new technologies are discovered and older technologies are improved upon. With each level of the Research Lab constructed, the speed in which new technologies are researched is increased, while also unlocking newer technologies to research. In order to conduct research as quickly as possible, research scientists are immediately dispatched to the colony to begin work and development. In this way, knowledge about new technologies can easily be disseminated throughout the empire.',
    ],
    'alliance_depot' => [
        'title' => 'Alliance Depot',
        'description' => 'The alliance depot supplies fuel to friendly fleets in orbit helping with defence.',
        'description_long' => 'The alliance depot supplies fuel to friendly fleets in orbit helping with defence. For each upgrade level of the alliance depot, a special demand of deuterium per hour can be sent to an orbiting fleet.',
    ],
    'missile_silo' => [
        'title' => 'Missile Silo',
        'description' => 'Missile silos are used to store missiles.',
        'description_long' => 'Missile silos are used to construct, store and launch interplanetary and anti-ballistic missiles. With each level of the silo, five interplanetary missiles or ten anti-ballistic missiles can be stored. One Interplanetary missile uses the same space as two Anti-Ballistic missiles. Storage of both Interplanetary missiles and Anti-Ballistic missiles in the same silo is allowed.',
    ],
    'nano_factory' => [
        'title' => 'Nanite Factory',
        'description' => 'This is the ultimate in robotics technology. Each level cuts the construction time for buildings, ships, and defences.',
        'description_long' => 'A nanomachine, also called a nanite, is a mechanical or electromechanical device whose dimensions are measured in nanometers (millionths of a millimeter, or units of 10^-9 meter). The microscopic size of nanomachines translates into higher operational speed. This factory produces nanomachines that are the ultimate evolution in robotics technology. Once constructed, each upgrade significantly decreases production time for buildings, ships, and defensive structures.',
    ],
    'terraformer' => [
        'title' => 'Terraformer',
        'description' => 'The terraformer increases the usable surface of planets.',
        'description_long' => 'Planeettojen rakentamisen lisääntyessä jopa siirtokunnan elintilasta tulee yhä rajallisempi. Perinteiset menetelmät, kuten kerros- ja maanalainen rakentaminen, ovat yhä riittämättömämpiä. Pieni ryhmä korkean energian fyysikoita ja nanoinsinöörejä päätyi lopulta ratkaisuun: terraformointiin. 
Valtavia energiamääriä käyttävä terraformeri voi tehdä kokonaisia ​​maa-alueita tai jopa maanosia peltokäyttöön. Tässä rakennuksessa valmistetaan erityisesti tätä tarkoitusta varten luotuja naniitteja, jotka takaavat tasaisen maanlaadun kaikkialla. 

Kullakin terraformer-tasolla voidaan viljellä 5 peltoa. Jokaisella tasolla terraformer miehittää yhden kentän. Joka 2 terraformer-tasoa kohden saat yhden bonuskentän. 

Kun terraformeri on rakennettu, sitä ei voi purkaa.',
    ],
    'space_dock' => [
        'title' => 'Space Dock',
        'description' => 'Wreckages can be repaired in the Space Dock.',
        'description_long' => 'Space Dock tarjoaa mahdollisuuden korjata taistelussa tuhoutuneita aluksia, jotka jättivät hylkyjä. Korjausaika kestää enintään 12 tuntia, mutta kestää vähintään 30 minuuttia ennen kuin laivat voidaan ottaa uudelleen käyttöön. 

Korjaustyöt on aloitettava 3 päivän kuluessa hylyn syntymisestä. Korjatut alukset tulee palauttaa töihin manuaalisesti korjauksen päätyttyä. Jos näin ei tehdä, minkä tahansa tyyppiset yksittäiset alukset palautetaan käyttöön 3 päivän kuluttua. 

Hylyt näkyvät vain, jos yli 150 000 yksikköä on tuhottu mukaan lukien omat taisteluun osallistuneet alukset arvolla vähintään 5 % laivapisteistä. 

Koska Space Dock kelluu kiertoradalla, se ei vaadi planeettakenttää.',
    ],
    'lunar_base' => [
        'title' => 'Kuutukikohta',
        'description' => 'Koska kuussa ei ole ilmakehää, asumiskelpoisen tilan luomiseen tarvitaan kuun tukikohta.',
        'description_long' => 'Kuulla ei ole ilmakehää, joten kuun tukikohta on ensin rakennettava ennen kuin siirtokunta voidaan perustaa. Tämä tuottaa sitten happea, lämpöä ja painovoimaa. Jokaisen tason rakentamisen yhteydessä biosfääriin tarjotaan suurempi asuin- ja kehitysalue. Jokainen rakennettu taso sallii kolme kenttää muille rakennuksille. Jokaisella tasolla Kuun tukikohta miehittää yhden kentän. 
Kun kuun tukikohta on rakennettu, sitä ei voi purkaa.',
    ],
    'sensor_phalanx' => [
        'title' => 'Anturifaalanks',
        'description' => 'Anturifalangin avulla voidaan löytää ja tarkkailla muiden imperiumien laivastoja. Mitä suurempi anturin phalanx-ryhmä, sitä suuremman alueen se voi skannata.',
        'description_long' => 'Korkearesoluutioisia antureita hyödyntäen Sensor Phalanx skannaa ensin valon spektrin, kaasujen koostumuksen ja säteilypäästöt kaukaisesta maailmasta ja lähettää tiedot supertietokoneeseen käsittelyä varten. Kun tiedot on saatu, supertietokone vertaa spektrin, kaasun koostumuksen ja säteilypäästöjen muutoksia perusviivakaavioon tunnetuista spektrin muutoksista, jotka ovat aiheutuneet eri laivojen liikkeistä. Tuloksena saadut tiedot näyttävät sitten minkä tahansa phalanxin alueella olevan laivaston toiminnan. Jotta supertietokone ei ylikuumene prosessin aikana, se jäähdytetään käyttämällä 5k prosessoitua deuteriumia. 
Jos haluat käyttää Phalanxia, ​​napsauta mitä tahansa planeettaa Galaxy View\'ssa anturien kantaman sisällä.',
    ],
    'jump_gate' => [
        'title' => 'Jump Gate',
        'description' => 'Hyppyportit ovat valtavia lähetin-vastaanottimia, jotka pystyvät lähettämään suurimmankin laivaston hetkessä kaukaiselle hyppyportille.',
        'description_long' => 'Jump Gate on jättimäisten lähetin-vastaanottimien järjestelmä, joka pystyy lähettämään suurimmatkin laivastot vastaanottavalle portille minne tahansa universumissa ilman ajanhukkaa. Hyödyntämällä tekniikkaa, joka on samanlainen kuin Worm Hole -hypyn saavuttamiseksi, deuteriumia ei tarvita. Hyppyjen välillä on oltava muutaman minuutin latausjakso, jotta uusiutuminen tapahtuu. Resurssien kuljettaminen portin läpi ei myöskään ole mahdollista. Jokaisella päivitystasolla hyppyportin jäähtymisaikaa voidaan lyhentää.',
    ],
    'energy_technology' => [
        'title' => 'Energy Technology',
        'description' => 'The command of different types of energy is necessary for many new technologies.',
        'description_long' => 'Eri tutkimusalojen edetessä havaittiin, että nykyinen energianjakeluteknologia ei riitä aloittamaan tiettyä erikoistutkimusta. Jokaisen energiateknologiasi päivityksen myötä voidaan tehdä uutta tutkimusta, joka avaa kehittyneempien alusten ja puolustusjärjestelmien kehittämisen.',
    ],
    'laser_technology' => [
        'title' => 'Laser Technology',
        'description' => 'Focusing light produces a beam that causes damage when it strikes an object.',
        'description_long' => 'Laserit (valon vahvistus stimuloidulla säteilyemissiolla) tuottavat intensiivisen, energiarikkaan koherentin valon. Näitä laitteita voidaan käyttää kaikilla alueilla, optisista tietokoneista raskaisiin laseraseisiin, jotka leikkaavat vaivattomasti panssariteknologian läpi. Laserteknologia tarjoaa tärkeän perustan muiden asetekniikoiden tutkimukselle.',
    ],
    'ion_technology' => [
        'title' => 'Ion Technology',
        'description' => 'The concentration of ions allows for the construction of cannons, which can inflict enormous damage and reduce the deconstruction costs per level by 4%.',
        'description_long' => 'Ionit voidaan keskittää ja kiihdyttää tappavaksi säteeksi. Nämä palkit voivat sitten aiheuttaa valtavia vahinkoja. Tutkijamme ovat myös kehittäneet tekniikan, joka vähentää selvästi rakennusten ja järjestelmien purkamiskustannuksia. Kullakin tutkimustasolla purkukustannukset laskevat 4 %.',
    ],
    'hyperspace_technology' => [
        'title' => 'Hyperspace Technology',
        'description' => 'Integroimalla 4. ja 5. ulottuvuus on nyt mahdollista tutkia uudenlaista, taloudellisempaa ja tehokkaampaa käyttölaitetta.',
        'description_long' => 'Teoriassa ajatus hyperavaruusmatkailusta perustuu erillisen ja vierekkäisen ulottuvuuden olemassaoloon. Aktivoituna hyperavaruusasema ohjaa tähtialuksen tähän toiseen ulottuvuuteen, jossa se voi kattaa valtavia matkoja ajassa, joka on huomattavasti lyhyempi kuin "normaalissa" tilassa. Kun se saavuttaa hyperavaruuden pisteen, joka vastaa sen määränpäätä todellisessa avaruudessa, se ilmaantuu uudelleen. 
Kun riittävä Hyperspace-teknologian taso on tutkittu, Hyperspace Drive ei ole enää vain teoria. Jokainen tämän aseman parannus lisää alustesi kantavuutta 5 % perusarvosta.',
    ],
    'plasma_technology' => [
        'title' => 'Plasma Technology',
        'description' => 'A further development of ion technology which accelerates high-energy plasma, which then inflicts devastating damage and additionally optimises the production of metal, crystal and deuterium (1%/0.66%/0.33% per level).',
        'description_long' => 'Ioniteknologian jatkokehitys, joka ei nopeuta ioneja, vaan sen sijaan korkeaenergistä plasmaa, joka voi sitten aiheuttaa tuhoisia vahinkoja törmäyksessä esineeseen. Tutkijamme ovat myös löytäneet tavan parantaa huomattavasti metallin ja kristallin louhintaa tällä tekniikalla. 

Plasmateknologian rakennustasoa kohden metallin tuotanto kasvaa 1 %, kiteiden tuotanto 0,66 % ja deuteriumtuotanto 0,33 %.',
    ],
    'combustion_drive' => [
        'title' => 'Combustion Drive',
        'description' => 'The development of this drive makes some ships faster, although each level increases speed by only 10 % of the base value.',
        'description_long' => 'Polttomoottori on vanhin teknologia, mutta se on edelleen käytössä. Polttomoottorilla pakokaasut muodostuvat laivassa kuljetettavista ponneaineista ennen käyttöä. Suljetussa kammiossa paineet ovat samat kumpaankin suuntaan, eikä kiihtymistä tapahdu. Jos kammion pohjassa on aukko, paine ei enää vastusta tällä puolella. Jäljellä oleva paine antaa tuloksena työntövoiman aukkoa vastakkaiselle puolelle, mikä työntää laivaa eteenpäin työntämällä pakokaasun taaksepäin äärimmäisen suurella nopeudella. 

Jokaisella kehitetyllä Combustion Drive -tasolla pienten ja suurten rahtilaivojen, kevyiden hävittäjien, kierrättäjien ja vakoiluluotainten nopeus kasvaa 10 %.',
    ],
    'impulse_drive' => [
        'title' => 'Impulse Drive',
        'description' => 'The impulse drive is based on the reaction principle. Further development of this drive makes some ships faster, although each level increases speed by only 20 % of the base value.',
        'description_long' => 'Impulssikäyttö perustuu rekyyliperiaatteeseen, jonka avulla stimuloitu säteilyemissio tuotetaan pääasiassa ydinfuusion jätetuotteena energian saamiseksi. Lisäksi voidaan ruiskuttaa muita massoja. Jokaisella Impulse Driven kehitetyllä tasolla pommittajien, risteilijöiden, raskaiden hävittäjien ja siirtomaa-alusten nopeus kasvaa 20 % perusarvosta. Lisäksi pienet kuljettimet varustetaan impulssikäytöillä heti, kun niiden tutkimustaso saavuttaa 5. Heti kun Impulse Drive -tutkimus on saavuttanut tason 17, kierrättäjiin asennetaan uudelleen Impulse Drives. 

Planeettojenväliset ohjukset kulkevat myös pidemmälle kullakin tasolla.',
    ],
    'hyperspace_drive' => [
        'title' => 'Hyperspace Drive',
        'description' => 'Hyperspace drive warps space around a ship. The development of this drive makes some ships faster, although each level increases speed by only 30 % of the base value.',
        'description_long' => 'Laivan välittömässä läheisyydessä tila on vääntynyt niin, että pitkiä matkoja voidaan ajaa erittäin nopeasti. Mitä enemmän Hyperspace Drivea kehitetään, sitä vahvempi on tilan vääntynyt luonne, jolloin sillä varustettujen alusten (Battlecruisers, Battleships, Destroyers, Deathstars, Pathfinders ja Reapers) nopeus kasvaa 30 % tasoa kohden. Lisäksi pommikoneeseen rakennetaan Hyperspace Drive heti, kun tutkimus saavuttaa tason 8. Heti kun Hyperspace Drive -tutkimus saavuttaa tason 15, kierrätyskoneeseen asennetaan Hyperspace Drive.',
    ],
    'espionage_technology' => [
        'title' => 'Espionage Technology',
        'description' => 'Information about other planets and moons can be gained using this technology.',
        'description_long' => 'Espionage Technology is, in the first instance, an advancement of sensor technology. The more advanced this technology is, the more information the user receives about activities in his environment. 
The differences between your own spy level and opposing spy levels is crucial for probes. The more advanced your own espionage technology is, the more information the report can gather and the smaller the chance is that your espionage activities are discovered. The more probes that you send on one mission, the more details they can gather from the target planet. But at the same time it also increases the chance of discovery. 
Espionage technology also improves the chance of locating foreign fleets. The espionage level is vital in determining this. From level 2 onwards, the exact total number of attacking ships is displayed as well as the normal attack notification. And from level 4 onwards, the type of attacking ships as well as the total number is shown and from level 8 onwards the exact number of different ship types is shown.
This technology is indispensable for an upcoming attack, as it informs you whether the victim fleet has defence available or not. That is why this technology should be researched very early on.',
    ],
    'computer_technology' => [
        'title' => 'Computer Technology',
        'description' => 'More fleets can be commanded by increasing computer capacities. Each level of computer technology increases the maximum number of fleets by one.',
        'description_long' => 'Once launched on any mission, fleets are controlled primarily by a series of computers located on the originating planet. These massive computers calculate the exact time of arrival, controls course corrections as needed, calculates trajectories, and regulates flight speeds. With each level researched, the flight computer is upgraded to allow an additional slot to be launched. Computer technology should be continuously developed throughout the building of your empire.',
    ],
    'astrophysics' => [
        'title' => 'Astrophysics',
        'description' => 'With an astrophysics research module, ships can undertake long expeditions. Every second level of this technology will allow you to colonise an extra planet.',
        'description_long' => 'Lisähavainnot astrofysiikan alalla mahdollistavat laboratorioiden rakentamisen, jotka voidaan asentaa yhä useammille laivoille. Tämä mahdollistaa pitkät tutkimusmatkat kauas avaruuden tutkimattomille alueille. Lisäksi näitä edistysaskeleita voidaan käyttää universumin kolonisoimiseen entisestään. Jokaista tämän tekniikan kahta tasoa kohden voidaan tehdä lisäplaneetta käyttökelpoiseksi.',
    ],
    'intergalactic_research_network' => [
        'title' => 'Intergalactic Research Network',
        'description' => 'Researchers on different planets communicate via this network.',
        'description_long' => 'Tämä on syväavaruusverkostosi, jonka avulla voit välittää tutkimustuloksia siirtokuntillesi. IRN:n avulla voidaan saavuttaa nopeampia tutkimusaikoja yhdistämällä korkeimman tason tutkimuslaboratoriot, jotka vastaavat kehitetyn IRN:n tasoa. 
Toimiakseen jokaisen pesäkkeen on kyettävä suorittamaan tutkimusta itsenäisesti.',
    ],
    'graviton_technology' => [
        'title' => 'Graviton Technology',
        'description' => 'Firing a concentrated charge of graviton particles can create an artificial gravity field, which can destroy ships or even moons.',
        'description_long' => 'Gravitoni on alkuainehiukkanen, joka on massaton ja jolla ei ole lastia. Se määrittää painovoiman. Polttamalla tiivistettyä gravitonikuormaa voidaan rakentaa keinotekoinen gravitaatiokenttä. Ei toisin kuin musta aukko, se vetää massaa itseensä. Siten se voi tuhota laivoja ja jopa kokonaisia ​​kuita. Riittävän määrän gravitonien tuottaminen vaatii valtavia määriä energiaa. Graviton-tutkimusta tarvitaan tuhoavan Kuolemantähden rakentamiseen.',
    ],
    'weapon_technology' => [
        'title' => 'Weapons Technology',
        'description' => 'Weapons technology makes weapons systems more efficient. Each level of weapons technology increases the weapon strength of units by 10 % of the base value.',
        'description_long' => 'Weapons Technology is a key research technology and is critical to your survival against enemy Empires. With each level of Weapons Technology researched, the weapons systems on ships and your defence mechanisms become increasingly more efficient. Each level increases the base strength of your weapons by 10% of the base value.',
    ],
    'shielding_technology' => [
        'title' => 'Shielding Technology',
        'description' => 'Kilpiteknologia tekee laivojen ja puolustuslaitosten suojat tehokkaampia. Jokainen suojateknologian taso lisää suojusten lujuutta 10 % perusarvosta.',
        'description_long' => 'With the invention of the magnetosphere generator, scientists learned that an artificial shield could be produced to protect the crew in space ships not only from the harsh solar radiation environment in deep space, but also provide protection from enemy fire during an attack. Once scientists finally perfected the technology, a magnetosphere generator was installed on all ships and defence systems. As the technology is advanced to each level, the magnetosphere generator is upgraded which provides an additional 10% strength to the shields base value.',
    ],
    'armor_technology' => [
        'title' => 'Armour Technology',
        'description' => 'Special alloys improve the armour on ships and defensive structures. The effectiveness of the armour can be increased by 10 % per level.',
        'description_long' => 'Syvän avaruuden ympäristö on ankara. Eri tehtävien lentäjät ja miehistö kohtasivat paitsi voimakasta auringonsäteilyä, myös avaruusromun osumia tai vihollisen tulen tuhoamista hyökkäyksessä. Alumiini-litium-titaanikarbidiseoksen löytäminen, jonka todettiin olevan sekä kevyt että kestävä, antoi miehistölle tietyn suojan. Jokaisella kehitetyllä panssariteknologian tasolla tuotetaan laadukkaampaa metalliseosta, mikä lisää panssarin lujuutta 10%.',
    ],
    'small_cargo' => [
        'title' => 'Small Cargo',
        'description' => 'The small cargo is an agile ship which can quickly transport resources to other planets.',
        'description_long' => 'Kuljetuskoneet ovat suunnilleen yhtä suuria kuin hävittäjät, mutta silti ne luopuvat tehokkaista vetolaitteista ja laivoissa olevista aseista rahtikapasiteettinsa kasvattamiseksi. Tämän seurauksena kuljetuskone tulisi lähettää taisteluihin vain, kun sen mukana on taisteluvalmiita aluksia. 

Heti kun Impulse Drive saavuttaa tutkimustason 5, pieni kuljetin kulkee suuremmalla perusnopeudella ja on varustettu Impulse Drivella.',
    ],
    'large_cargo' => [
        'title' => 'Large Cargo',
        'description' => 'This cargo ship has a much larger cargo capacity than the small cargo, and is generally faster thanks to an improved drive.',
        'description_long' => 'Ajan myötä siirtokuntien hyökkäykset johtivat yhä suurempien resurssien kaappaamiseen. Tämän seurauksena pieniä lastia lähetettiin massamäärinä kompensoimaan suurempia saaliita. Pian opittiin, että tarvittiin uusi alusluokka maksimoimaan hyökkäyksissä vangitut resurssit, mutta myös kustannustehokas. Pitkän kehityksen jälkeen Large Cargo syntyi. 

Maksimoidakseen ruumassa säilytettävien resurssien, tällä aluksella on vähän aseita tai panssareita. Asennetun pitkälle kehitetyn polttomoottorin ansiosta se toimii edullisimpana resurssien toimittajana planeettojen välillä ja tehokkaimpana hyökkäyksissä vihamielisiin maailmoihin.',
    ],
    'colony_ship' => [
        'title' => 'Colony Ship',
        'description' => 'Vacant planets can be colonised with this ship.',
        'description_long' => '1900-luvulla ihminen päätti mennä tähtiin. Ensin se laskeutui Kuuhun. Sen jälkeen rakennettiin avaruusasema. Pian sen jälkeen Mars kolonisoitiin. Pian päätettiin, että kasvumme riippui muiden maailmojen kolonisoimisesta. Tiedemiehet ja insinöörit kaikkialta maailmasta kokoontuivat yhteen kehittämään ihmisen kaikkien aikojen suurinta saavutusta. Colony Ship on syntynyt. 

Tätä alusta käytetään äskettäin löydetyn planeetan valmistelemiseen kolonisaatiota varten. Kun alus saapuu määränpäähän, se muuttuu välittömästi tavalliseksi asuintilaksi, joka auttaa asuttamaan ja louhimaan uutta maailmaa. Planeettojen enimmäismäärä määräytyy siten astrofysiikan tutkimuksen edistymisen perusteella. Astroteknologian kaksi uutta tasoa mahdollistavat yhden lisäplaneetan kolonisoinnin.',
    ],
    'recycler' => [
        'title' => 'Recycler',
        'description' => 'Kierrättimet ovat ainoita aluksia, jotka pystyvät korjaamaan planeetan kiertoradalla kelluvia roskakenttiä taistelun jälkeen.',
        'description_long' => 'Taistelu avaruudessa otti yhä suurempia mittakaavoja. Tuhansia laivoja tuhoutui ja niiden jäänteiden resurssit näyttivät kadonneen romukentille ikuisiksi ajoiksi. Normaalit rahtialukset eivät päässeet tarpeeksi lähelle näitä kenttiä vaarantamatta merkittäviä vahinkoja. 
Viimeaikainen suojateknologian kehitys ohitti tämän ongelman tehokkaasti. Luotiin uusi luokka laivoja, jotka olivat samanlaisia ​​kuin Transporters: Recyclers. Heidän ponnistelunsa auttoivat keräämään ajatuksiltaan kadonneita resursseja ja sitten pelastamaan ne. Roskat eivät enää aiheuttaneet todellista vaaraa uusien kilpien ansiosta. 

Heti kun Impulse Drive -tutkimus on saavuttanut tason 17, kierrättäjiin asennetaan uudelleen Impulse Drives. Heti kun Hyperspace Drive -tutkimus on saavuttanut tason 15, kierrättäjiin asennetaan Hyperspace Drives.',
    ],
    'espionage_probe' => [
        'title' => 'Espionage Probe',
        'description' => 'Espionage probes are small, agile drones that provide data on fleets and planets over great distances.',
        'description_long' => 'Vakoiluluotaimet ovat pieniä, ketteriä droneja, jotka tarjoavat tietoa laivastoista ja planeetoista. Varustettu erityisesti suunnitelluilla moottoreilla, se mahdollistaa suuret etäisyydet vain muutamassa minuutissa. Kohdeplaneetan kiertoradalla he keräävät nopeasti tietoja ja lähettävät raportin takaisin Deep Space Networkin kautta arvioitavaksi. Mutta älykkääseen keräämiseen liittyy riski. Sinä aikana, kun raportti lähetetään takaisin verkkoosi, kohde voi havaita signaalin ja anturit voivat tuhoutua.',
    ],
    'solar_satellite' => [
        'title' => 'Solar Satellite',
        'description' => 'Aurinkosatelliitit ovat yksinkertaisia ​​aurinkokennojen alustoja, jotka sijaitsevat korkealla, kiinteällä kiertoradalla. Ne keräävät auringonvaloa ja välittävät sen maa-asemalle laserilla.',
        'description_long' => 'Tutkijat löysivät menetelmän sähköenergian siirtämiseksi siirtokuntaan käyttämällä erityisesti suunniteltuja satelliitteja geosynkronisella kiertoradalla. Aurinkosatelliitit keräävät aurinkoenergiaa ja lähettävät sen maa-asemalle kehittynyttä lasertekniikkaa käyttäen. Aurinkosatelliitin tehokkuus riippuu sen vastaanottaman auringonsäteilyn voimakkuudesta. Periaatteessa energiantuotanto lähempänä aurinkoa olevilla kiertoradoilla on suurempi kuin auringosta kaukana olevilla planeetoilla. 
Hyvän kustannus/suorituskykysuhteensa ansiosta aurinkosatelliitit voivat ratkaista monia energiaongelmia. Mutta varokaa: aurinkosatelliitit voidaan helposti tuhota taistelussa.',
    ],
    'crawler' => [
        'title' => 'Crawler',
        'description' => 'Crawlers increase the production of metal, crystal and Deuterium on their tasked planet each by 0.02%, 0.02% and 0.02% respectively. As a collector, production also increases. The maximum total bonus depends on the overall level of your mines.',
        'description_long' => 'The Crawler is a large trench vehicle that increases the production of mines and synthesizers. It is more agile than it looks but it is not particularly robust. Each Crawler increases metal production by 0.02%, crystal production by 0.02% and Deuterium production by 0.02%. As a collector, production also increases. The maximum total bonus depends on the overall level of your mines.',
    ],
    'pathfinder' => [
        'title' => 'Pathfinder',
        'description' => 'Pathfinder on nopea ja ketterä alus, joka on suunniteltu tutkimusmatkoja varten tuntemattomille avaruuden sektoreille.',
        'description_long' => 'Pathfinders are fast and spacious. Their construction method is optimised for pushing into unknown territory. They are capable of discovering and mining debris fields during expeditions. Additionally they can find items out on expeditions. Total yield also increases.',
    ],
    'light_fighter' => [
        'title' => 'Light Fighter',
        'description' => 'This is the first fighting ship all emperors will build. The light fighter is an agile ship, but vulnerable on its own. In mass numbers, they can become a great threat to any empire. They are the first to accompany small and large cargoes to hostile planets with minor defences.',
        'description_long' => 'Tämä on ensimmäinen taistelulaiva, jonka kaikki keisarit rakentavat. Kevythävittäjä on ketterä alus, mutta haavoittuvainen yksin ollessaan. Massalukuina niistä voi tulla suuri uhka mille tahansa valtakunnalle. He ovat ensimmäiset, jotka seuraavat pieniä ja suuria lastia vihamielisille planeetoille vähäisellä puolustuksella.',
    ],
    'heavy_fighter' => [
        'title' => 'Heavy Fighter',
        'description' => 'This fighter is better armoured and has a higher attack strength than the light fighter.',
        'description_long' => 'Raskasta hävittäjää kehittäessään tutkijat saavuttivat pisteen, jossa perinteiset vetolaitteet eivät enää antaneet riittävää suorituskykyä. Laivan liikuttamiseksi optimaalisesti, impulssikäyttöä käytettiin ensimmäistä kertaa. Tämä lisäsi kustannuksia, mutta avasi myös uusia mahdollisuuksia. Tätä asemaa käyttämällä jäi enemmän energiaa aseille ja kilpeille; Lisäksi tässä uudessa hävittäjäperheessä käytettiin korkealaatuisia materiaaleja. Näillä muutoksilla raskas hävittäjä edustaa uutta aikakautta laivatekniikassa ja on risteilijätekniikan perusta. 

Hieman kevyessä hävittäjässä suuremmassa raskaassa hävittäjässä on paksummat rungot, jotka tarjoavat enemmän suojaa ja vahvemmat aseet.',
    ],
    'cruiser' => [
        'title' => 'Cruiser',
        'description' => 'Cruisers are armoured almost three times as heavily as heavy fighters and have more than twice the firepower. In addition, they are very fast.',
        'description_long' => 'Raskaan laserin ja ionitykin kehittämisen myötä kevyet ja raskaat hävittäjät kohtasivat hälyttävän suuren määrän tappioita, jotka lisääntyivät jokaisen hyökkäyksen myötä. Huolimatta monista muutoksista, aseiden vahvuudesta ja panssarin muutoksista, sitä ei voitu lisätä tarpeeksi nopeasti vastustaakseen tehokkaasti näitä uusia puolustustoimenpiteitä. Siksi päätettiin rakentaa uusi alusluokka, jossa yhdistyi enemmän panssaria ja enemmän tulivoimaa. Vuosien tutkimuksen ja kehityksen tuloksena Cruiser syntyi. 

Risteilijät ovat panssaroituja lähes kolme kertaa raskaat hävittäjiin verrattuna, ja niillä on yli kaksi kertaa enemmän tulivoimaa kuin millään olemassa olevalla taistelulaivalla. Niillä on myös nopeuksia, jotka ylittivät reilusti kaikki koskaan tehdyt avaruusalukset. Risteilyalukset hallitsivat maailmankaikkeutta lähes vuosisadan ajan. Gauss-tykkien ja plasmatornien kehityksen myötä niiden valta kuitenkin päättyi. Niitä käytetään edelleen taistelijaryhmiä vastaan, mutta ei niin valtaosin kuin ennen.',
    ],
    'battle_ship' => [
        'title' => 'Battleship',
        'description' => 'Battleships form the backbone of a fleet. Their heavy cannons, high speed, and large cargo holds make them opponents to be taken seriously.',
        'description_long' => 'Kun kävi ilmi, että risteilijä oli menettämässä jalansijaa sen edessä olevien puolustusrakenteiden lisääntymiselle, ja koska alusten menetys tehtävien aikana oli kohtuuton, päätettiin rakentaa alus, joka voisi kohdata samantyyppiset puolustusrakenteet mahdollisimman pienillä tappioilla. Laajan kehityksen jälkeen Battleship syntyi. Taistelulaiva on rakennettu kestämään suurimpiakin taisteluita, ja siinä on suuret lastitilat, raskaat tykit ja suuri hyperajonopeus. Kun se oli kehitetty, se lopulta osoittautui jokaisen hyökkäävän keisarin laivaston selkärangaksi.',
    ],
    'battlecruiser' => [
        'title' => 'Battlecruiser',
        'description' => 'The Battlecruiser is highly specialized in the interception of hostile fleets.',
        'description_long' => 'Tämä alus on yksi edistyneimmistä koskaan kehitetyistä taistelualuksista, ja se on erityisen tappava hyökkäävien laivastojen tuhoamisessa. Paranneltujen laserkanuunien ja edistyneen Hyperspace-moottorin ansiosta Battlecruiser on vakava voima, jota vastaan ​​on kohdattava missä tahansa hyökkäyksessä. Aluksen suunnittelusta ja suuresta asejärjestelmästä johtuen lastiruuma jouduttiin leikkaamaan, mutta sen kompensoi alentunut polttoaineenkulutus.',
    ],
    'bomber' => [
        'title' => 'Bomber',
        'description' => 'The bomber was developed especially to destroy the planetary defences of a world.',
        'description_long' => 'Vuosisatojen kuluessa, kun puolustus alkoi kasvaa ja kehittyä, laivastoja alkoi tuhoutua hälyttävää vauhtia. Päätettiin, että uusi alus tarvitaan murtamaan puolustukset parhaan tuloksen varmistamiseksi. Vuosien tutkimuksen ja kehityksen jälkeen Bomber luotiin. 

Käyttämällä laserohjattuja kohdistuslaitteita ja plasmapommeja pommikone etsii ja tuhoaa kaikki löytämänsä puolustusmekanismit. Heti kun hyperavaruusasema on kehitetty tasolle 8, Bomberissa on hyperavaruusmoottori ja se voi lentää suuremmilla nopeuksilla.',
    ],
    'destroyer' => [
        'title' => 'Destroyer',
        'description' => 'The destroyer is the king of the warships.',
        'description_long' => 'Destroyer on vuosien työn ja kehityksen tulos. Deathstarsin kehityksen myötä päätettiin, että tällaista massiivista aseesta puolustautumiseen tarvitaan alusluokka. Paranneltujen kohdistusanturien, monifalanksi-ionikanuunoiden, Gauss-tykkien ja plasmatornien ansiosta Destroyer osoittautui yhdeksi pelottavimmista luoduista aluksista. 

Koska hävittäjä on erittäin suuri, sen ohjattavuus on erittäin rajoitettu, mikä tekee siitä enemmän taisteluaseman kuin taistelulaivan. Ohjattavuuden puute korvataan sen pelkällä tulivoimalla, mutta sen rakentaminen ja käyttö maksaa myös huomattavia määriä deuteriumia.',
    ],
    'deathstar' => [
        'title' => 'Deathstar',
        'description' => 'The destructive power of the deathstar is unsurpassed.',
        'description_long' => 'Deathstar on tehokkain koskaan luotu alus. Tämä kuun kokoinen alus on ainoa alus, joka voidaan nähdä paljaalla silmällä maassa. Kun huomaat sen, valitettavasti on liian myöhäistä tehdä mitään. 

Tämä massiivinen alus on aseistettu jättimäisellä gravitonitykillä, kehittyneimmällä asejärjestelmällä, joka on koskaan luotu universumissa. Sen lisäksi se kykenee tuhoamaan kokonaisia ​​laivastoja ja puolustuksia, vaan sillä on myös kyky tuhota kokonaisia ​​kuita. Vain kehittyneimmät imperiumit pystyvät rakentamaan tämän mammuttikokoisen laivan.',
    ],
    'reaper' => [
        'title' => 'Reaper',
        'description' => 'Reaper on tehokas taistelualus, joka on erikoistunut aggressiiviseen hyökkäykseen ja roskien korjuuseen.',
        'description_long' => 'There’s hardly anything more destructive than a ship of the Reaper class. These vessels combine fire power, strong shields, speed and capacity along with the unique ability to mine a portion of the created debris field directly after a battle. However this ability doesn’t apply to combat against pirates or aliens.',
    ],
    'rocket_launcher' => [
        'title' => 'Rocket Launcher',
        'description' => 'The rocket launcher is a simple, cost-effective defensive option.',
        'description_long' => 'Ensimmäinen peruspuolustuslinjasi. Nämä ovat yksinkertaisia ​​maapohjaisia ​​laukaisulaitteita, jotka ampuvat tavanomaisia ​​taistelukärkikärjeisiä ohjuksia hyökkääviä vihollisen kohteita vastaan. Koska ne ovat halpoja rakentaa ja tutkimusta ei vaadita, ne soveltuvat hyvin hyökkäyksiä puolustamiseen, mutta menettävät tehokkuutensa puolustautua laajemmilta hyökkäyksiltä. Kun aloitat kehittyneempien puolustusasejärjestelmien rakentamisen, raketinheittimistä tulee yksinkertaista rehua, jotta vahingollisemmat aseesi voivat aiheuttaa suurempaa vahinkoa pidemmän aikaa. 

Taistelun jälkeen on jopa 70 % todennäköisyys, että epäonnistuneet puolustustilat voidaan palauttaa käyttöön.',
    ],
    'light_laser' => [
        'title' => 'Light Laser',
        'description' => 'Concentrated firing at a target with photons can produce significantly greater damage than standard ballistic weapons.',
        'description_long' => 'Kun tekniikka kehittyi ja kehittyneempiä aluksia luotiin, päätettiin, että hyökkäyksiä vastaan ​​tarvitaan vahvempi puolustuslinja. Lasertekniikan kehittyessä uusi ase suunniteltiin tarjoamaan seuraavan tason puolustusta. Light Lasers ovat yksinkertaisia ​​maa-aseita, jotka käyttävät erityisiä kohdistusjärjestelmiä vihollisen jäljittämiseen ja korkean intensiteetin laserin ampumiseen, joka on suunniteltu leikkaamaan kohteen rungon läpi. Kustannustehokkuuden säilyttämiseksi ne varustettiin parannetulla suojajärjestelmällä, mutta rakenteellinen eheys on sama kuin raketinheittimessä. 

Taistelun jälkeen on jopa 70 % todennäköisyys, että epäonnistuneet puolustustilat voidaan palauttaa käyttöön.',
    ],
    'heavy_laser' => [
        'title' => 'Heavy Laser',
        'description' => 'The heavy laser is the logical development of the light laser.',
        'description_long' => 'Heavy Laser on käytännöllinen, parannettu versio Light Laserista. Koska se on tasapainoisempi kuin Light Laser, jossa on parannettu seoskoostumus, se käyttää vahvempia, tiheämmin pakattuja säteitä ja vielä parempia sisäisiä kohdistusjärjestelmiä. 

Taistelun jälkeen on jopa 70 % todennäköisyys, että epäonnistuneet puolustustilat voidaan palauttaa käyttöön.',
    ],
    'gauss_cannon' => [
        'title' => 'Gauss Cannon',
        'description' => 'The Gauss Cannon fires projectiles weighing tons at high speeds.',
        'description_long' => 'Pitkään ammusaseita pidettiin vanhentuneina nykyaikaisen lämpöydin- ja energiateknologian sekä hyperajon ja parannetun panssarin kehityksen ansiosta. Se oli siihen asti, kunnes tarkka energiateknologia, joka oli sitä kerran vanhentanut, auttoi sitä saavuttamaan uudelleen vakiintuneen asemansa. 
Gauss-tykki on suuri versio hiukkaskiihdyttimestä. Äärimmäisen raskaita ohjuksia kiihdytetään valtavalla sähkömagneettisella voimalla, ja niiden suunopeudet saavat ohjusta ympäröivän lian palamaan taivaalla. Tämä ase on ammuttaessa niin voimakas, että se saa aikaan äänibuumin. Nykyaikaiset panssarit ja kilvet kestävät tuskin voimaa, usein ohjuksen voima läpäisee kohteen kokonaan. Puolustusrakenteet deaktivoituvat heti, kun ne ovat vaurioituneet liian pahasti. 

Taistelun jälkeen on jopa 70 % todennäköisyys, että epäonnistuneet puolustustilat voidaan palauttaa käyttöön.',
    ],
    'ion_cannon' => [
        'title' => 'Ion Cannon',
        'description' => 'The Ion Cannon fires a continuous beam of accelerating ions, causing considerable damage to objects it strikes.',
        'description_long' => 'Ionikanuuna on ase, joka ampuu ionisäteitä (positiivisesti tai negatiivisesti varautuneita hiukkasia). Ion Cannon on itse asiassa eräänlainen hiukkaskatuoni; vain käytetyt hiukkaset ovat ionisoituja. Sähkövaraustensa vuoksi ne voivat myös poistaa käytöstä elektroniset laitteet ja kaikki muut, joissa on sähköinen tai vastaava virtalähde, käyttämällä ilmiötä, joka tunnetaan nimellä Electromagetic Pulse (EMP-ilmiö). Kanuunoiden erittäin parannetun suojausjärjestelmän ansiosta tämä tykki tarjoaa paremman suojan suuremmille, tuhoisammille puolustusaseillesi. 

Taistelun jälkeen on jopa 70 % todennäköisyys, että epäonnistuneet puolustustilat voidaan palauttaa käyttöön.',
    ],
    'plasma_turret' => [
        'title' => 'Plasma Turret',
        'description' => 'Plasma Turrets release the energy of a solar flare and surpass even the destroyer in destructive effect.',
        'description_long' => 'Yksi kehittyneimmistä puolustusasejärjestelmistä, joka on koskaan kehitetty, Plasma Turret käyttää suurta ydinreaktorin polttokennoa sähkömagneettisen kiihdytin, joka laukaisee plasmapulssin tai toroidin. Käytön aikana plasmatorni lukittuu ensin maaliin ja aloittaa laukaisuprosessin. Tornien ytimeen syntyy plasmapallo ylikuumentamalla ja puristamalla kaasuja poistaen niistä ionejaan. Kun kaasu on tulistettu, puristettu ja plasmapallo on luotu, se ladataan sitten sähkömagneettiseen kiihdyttimeen, joka saa virtaa. Kun kiihdytin on aktivoitu täysin, se aktivoituu, mikä johtaa siihen, että plasmapallo laukeaa erittäin suurella nopeudella aiottuun kohteeseen. Kohteiden näkökulmasta lähestyvä sinertävä plasmapallo on vaikuttava, mutta kun se iskee, se aiheuttaa välittömän tuhon. 

Puolustustilat deaktivoituvat heti, kun ne ovat vaurioituneet liian voimakkaasti. Taistelun jälkeen on jopa 70 % todennäköisyys, että epäonnistuneet puolustustilat voidaan palauttaa käyttöön.',
    ],
    'small_shield_dome' => [
        'title' => 'Small Shield Dome',
        'description' => 'The small shield dome covers an entire planet with a field which can absorb a tremendous amount of energy.',
        'description_long' => 'Uusien maailmojen kolonisointi aiheutti uuden vaaran, avaruusromun. Suuri asteroidi voisi helposti pyyhkiä pois maailman ja kaikki sen asukkaat. Suojaustekniikan edistyminen tarjosi tutkijoille tavan kehittää kilpi, joka suojelee koko planeettaa paitsi avaruusromuilta, myös, kuten opittiin, vihollisen hyökkäykseltä. Luomalla suuri sähkömagneettinen kenttä planeetan ympärille, avaruusromut, jotka normaalisti olisivat tuhonneet planeetan, käännettiin pois ja vihollisvaltakuntien hyökkäykset estettiin. Ensimmäiset generaattorit olivat suuria ja kilpi tarjosi kohtuullisen suojan, mutta myöhemmin havaittiin, että pienet kilvet eivät antaneet suojaa suuremmilta hyökkäyksiltä. Pieni kilpikupoli oli alkusoitto vahvemmalle, kehittyneemmälle planeetan suojausjärjestelmälle. 

Taistelun jälkeen on jopa 70 % todennäköisyys, että epäonnistuneet puolustustilat voidaan palauttaa käyttöön.',
    ],
    'large_shield_dome' => [
        'title' => 'Large Shield Dome',
        'description' => 'The evolution of the small shield dome can employ significantly more energy to withstand attacks.',
        'description_long' => 'Large Shield Dome on seuraava askel planetaaristen kilpien kehityksessä, se on tulosta vuosien työstä Small Shield Dome -kupolin parantamiseksi. Suuret kupolit, jotka on rakennettu kestämään suurempia vihollisen tulipaloja tarjoamalla korkeamman sähkömagneettisen kentän, tarjoavat pidemmän suojan ennen romahtamista. 

Taistelun jälkeen on jopa 70 % todennäköisyys, että epäonnistuneet puolustustilat voidaan palauttaa käyttöön.',
    ],
    'anti_ballistic_missile' => [
        'title' => 'Anti-Ballistic Missiles',
        'description' => 'Anti-Ballistic Missiles destroy attacking interplanetary missiles',
        'description_long' => 'Anti Ballistiset ohjukset (ABM) ovat ainoa puolustuslinjasi, kun planeetallasi tai kuussasi hyökkäävät planeettojenväliset ohjukset (IPM). Kun IPM:n laukaisu havaitaan, nämä ohjukset virittyvät automaattisesti, käsittelevät laukaisukoodin lentotietokoneissaan, kohdistavat saapuvan IPM:n ja laukaisevat siepatakseen. Lennon aikana kohde-IPM:ää seurataan jatkuvasti ja kurssikorjauksia sovelletaan, kunnes ABM saavuttaa kohteen ja tuhoaa hyökkäävän IPM:n. Jokainen ABM tuhoaa yhden saapuvan IPM:n.',
    ],
    'interplanetary_missile' => [
        'title' => 'Interplanetary Missiles',
        'description' => 'Planeettojenväliset ohjukset tuhoavat vihollisen puolustuksen.',
        'description_long' => 'Interplanetaariset ohjukset (IPM) ovat hyökkäävä aseesi tuhotaksesi kohteensi puolustuksen. Uusinta seurantatekniikkaa käyttämällä jokainen ohjus kohdistaa tietyn määrän puolustusta tuhoamista varten. Anti-ainepommin kärjessä ne tuottavat niin ankaran tuhovoiman, että tuhoutuneita kilpiä ja puolustusta ei voida korjata. Ainoa tapa torjua näitä ohjuksia on ABM:illä.',
    ],
    'kraken' => [
        'title' => 'KRAKEN',
        'description' => 'Lyhentää parhaillaan rakenteilla olevien rakennusten rakennusaikaa <b>:duration</b>.',
    ],
    'detroid' => [
        'title' => 'DETROID',
        'description' => 'Lyhentää nykyisten telakkasopimusten rakennusaikaa <b>:duration</b>.',
    ],
    'newtron' => [
        'title' => 'NEWTRON',
        'description' => 'Vähentää kaikkien parhaillaan käynnissä olevien tutkimusten tutkimusaikaa <b>:duration</b>.',
    ],
];
