<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : sl (OGame: si)
 * Source   : resources/lang/en/t_resources.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'metal_mine' => [
        'title' => 'Rudnik metala',
        'description' => 'Uporablja se za pridobivanje metala, rudniki metala so primarni za vse nastajajoče in ustanovljene imperije.',
        'description_long' => 'Uporablja se za pridobivanje metala, rudniki metala so primarni za vse nastajajoče in ustanovljene imperije.',
    ],
    'crystal_mine' => [
        'title' => 'Rudnik kristala',
        'description' => 'Kristal je glavna surovina pri gradnji električnih omrežij in oblikovanju nekaterih zlitin.',
        'description_long' => 'Kristal je glavna surovina pri gradnji električnih omrežij in oblikovanju nekaterih zlitin.',
    ],
    'deuterium_synthesizer' => [
        'title' => 'Rafinerija Deuteriuma',
        'description' => 'Deuterium se uporablja kot gorivo za vesoljske ladje in se pridobiva globoko v morju. Ker je tako redka surovina je razlog za njegovo visoko ceno jasen.',
        'description_long' => 'Deuterium se uporablja kot gorivo za vesoljske ladje in se pridobiva globoko v morju. Ker je tako redka surovina je razlog za njegovo visoko ceno jasen.',
    ],
    'solar_plant' => [
        'title' => 'Sončna Elektrarna',
        'description' => 'Solarna elektrarna absorbira energijo iz sončnega sevanja. Vsi rudniki jo potrebujejo za pravilno delovanje.',
        'description_long' => 'Solarna elektrarna absorbira energijo iz sončnega sevanja. Vsi rudniki jo potrebujejo za pravilno delovanje.',
    ],
    'fusion_plant' => [
        'title' => 'Fuzijska elektrarna',
        'description' => 'Fuzijski reaktor potrebuje deuterium za proizvodnjo energije.',
        'description_long' => 'Fuzijski reaktor potrebuje deuterium za proizvodnjo energije.',
    ],
    'metal_store' => [
        'title' => 'Skladišče Metala',
        'description' => 'Nudi skladišče za dodaten metal.',
        'description_long' => 'Nudi skladišče za dodaten metal.',
    ],
    'crystal_store' => [
        'title' => 'Skladišče Kristala',
        'description' => 'Nudi skladišče za dodaten kristal.',
        'description_long' => 'Nudi skladišče za dodaten kristal.',
    ],
    'deuterium_store' => [
        'title' => 'Rezervoarji Deuteriuma',
        'description' => 'Ogromni rezervoarji nudijo skladišče za dodaten deuterium.',
        'description_long' => 'Ogromni rezervoarji nudijo skladišče za dodaten deuterium.',
    ],
    'robot_factory' => [
        'title' => 'Tovarna Robotov',
        'description' => 'Tovarna robotov proizvaja enostavne robote, ki kasneje sodelujejo pri gradnji infrastrukture na planetu.',
        'description_long' => 'Tovarna robotov proizvaja enostavne robote, ki kasneje sodelujejo pri gradnji infrastrukture na planetu.',
    ],
    'shipyard' => [
        'title' => 'Ladjedelnica',
        'description' => 'Ladje vseh vrst so zgrajene v ladjedelnici planeta.',
        'description_long' => 'Ladje vseh vrst so zgrajene v ladjedelnici planeta.',
    ],
    'research_lab' => [
        'title' => 'Laboratorij',
        'description' => 'Laboratorij je potreben za raziskave novih tehnologij.',
        'description_long' => 'Laboratorij je potreben za raziskave novih tehnologij.',
    ],
    'alliance_depot' => [
        'title' => 'Zavezniško skladišče',
        'description' => 'Zavezniško skladišče dobavlja deuterium prijateljskim flotam v orbiti.',
        'description_long' => 'Zavezniško skladišče dobavlja deuterium prijateljskim flotam v orbiti.',
    ],
    'missile_silo' => [
        'title' => 'Izstrelišče',
        'description' => 'Izstrelišče je skladišče za shranjevanje in lansiranje raket.',
        'description_long' => 'Izstrelišče je skladišče za shranjevanje in lansiranje raket.',
    ],
    'nano_factory' => [
        'title' => 'Tovarna Nanorobotov',
        'description' => 'Predstavlja nadgradnjo tovarne robotov. Vsaka stopnja prepolovi čas gradnje zgradb, ladij in obrambe.',
        'description_long' => 'Predstavlja nadgradnjo tovarne robotov. Vsaka stopnja prepolovi čas gradnje zgradb, ladij in obrambe.',
    ],
    'terraformer' => [
        'title' => 'Terraformer',
        'description' => 'Terraformer doda dodatna polja za gradnjo na površini planeta.',
        'description_long' => 'Terraformer doda dodatna polja za gradnjo na površini planeta.',
    ],
    'space_dock' => [
        'title' => 'Vesoljski dok',
        'description' => 'Razbitine so lahko popravljene v vesoljskem doku.',
        'description_long' => 'Razbitine so lahko popravljene v vesoljskem doku.',
    ],
    'lunar_base' => [
        'title' => 'Lunarna baza',
        'description' => 'Ker luna nima atmosfere, je za ustvarjanje bivalnega prostora potrebna lunarna baza.',
        'description_long' => 'Ker luna nima atmosfere, je lunarna baza zahtevana za nadaljno gradnjo zgradb.',
    ],
    'sensor_phalanx' => [
        'title' => 'Senzorska Falanga',
        'description' => 'Z uporabo senzorske falange je mogoče odkriti in opazovati flote drugih imperijev. Večji kot je senzorski niz falange, večji obseg lahko skenira.',
        'description_long' => 'Z uporabo falange lahko opazujemo premike flot ostalih igralcev. Večja stopnja falange nam zagotavlja večji razpon kje lahko skeniramo.',
    ],
    'jump_gate' => [
        'title' => 'Odskočna Vrata',
        'description' => 'Vrata za skoke so ogromni oddajniki-sprejemniki, ki lahko v hipu pošljejo tudi največjo floto do oddaljenih vrat za skok.',
        'description_long' => 'Zvezdna vrata je ogromna platforma, ki je v stanju transformacije flot med lunami brez izgube časa.',
    ],
    'energy_technology' => [
        'title' => 'Energijska tehnologija',
        'description' => 'Različne vrste energije so potrebne za nove raziskave.',
        'description_long' => 'Različne vrste energije so potrebne za nove raziskave.',
    ],
    'laser_technology' => [
        'title' => 'Laserska tehnologija',
        'description' => 'Žarek usmerjene svetlobe ob stiku s predmetom povzroči uničenje.',
        'description_long' => 'Žarek usmerjene svetlobe ob stiku s predmetom povzroči uničenje.',
    ],
    'ion_technology' => [
        'title' => 'Ionska tehnologija',
        'description' => 'Koncentracija ionov omogoča gradnjo topov, ki lahko povzročijo ogromno škodo in lahko zmanjšajo stroške dekonstrukcije na stopnjo za 4%.',
        'description_long' => 'Koncentracija ionov omogoča gradnjo topov, ki lahko povzročijo ogromno škodo in lahko zmanjšajo stroške dekonstrukcije na stopnjo za 4%.',
    ],
    'hyperspace_technology' => [
        'title' => 'Hiperprostorska tehnologija',
        'description' => 'Z integracijo 4. in 5. dimenzije je zdaj mogoče raziskati novo vrsto pogona, ki je bolj ekonomičen in učinkovit.',
        'description_long' => 'Z integracijo 4. in 5. dimenzije je zdaj mogoče raziskati pogon, ki je veliko hitrejši in učinkovitejši. Z uporabo četrte in pete dimenzije je zdaj mogoče zmečkati doke za nalaganje, da prihranimo prostor.',
    ],
    'plasma_technology' => [
        'title' => 'Plazemska tehnologija',
        'description' => 'Nadaljnji razvoj ionske tehnologije, ki pospešuje visoko energijsko plazmo, ki potem povzroči ogromno škodo in dodatno optimizira proizvodnjo metala, kristala in deuteriuma (1%/0.66%/0.33% na stopnjo).',
        'description_long' => 'Nadaljnji razvoj ionske tehnologije, ki pospešuje visoko energijsko plazmo, ki potem povzroči ogromno škodo in dodatno optimizira proizvodnjo metala, kristala in deuteriuma (1%/0.66%/0.33% na stopnjo).',
    ],
    'combustion_drive' => [
        'title' => 'Pogon izgorevanja',
        'description' => 'Razvoj pogona doda hitrost nekaterim ladjam, vendar le 10% osnovne vrednosti.',
        'description_long' => 'Razvoj pogona doda hitrost nekaterim ladjam, vendar le 10% osnovne vrednosti.',
    ],
    'impulse_drive' => [
        'title' => 'Impulzni pogon',
        'description' => 'Impulzni pogon temelji na principu reakcije. Razvoj vsake stopnje pogona doda 20% osnovne hitrosti nekaterim ladjam.',
        'description_long' => 'Impulzni pogon temelji na principu reakcije. Razvoj vsake stopnje pogona doda 20% osnovne hitrosti nekaterim ladjam.',
    ],
    'hyperspace_drive' => [
        'title' => 'Hiperprostorski pogon',
        'description' => 'Hiper pogon poganja ladje po vesolju. Razvoj vsake stopnje doda 30% osnovne hitrosti nekaterim ladjam.',
        'description_long' => 'Hiper pogon poganja ladje po vesolju. Razvoj vsake stopnje doda 30% osnovne hitrosti nekaterim ladjam.',
    ],
    'espionage_technology' => [
        'title' => 'Vohunska tehnologija',
        'description' => 'S pomočjo te tehnologije lahko pridobiš informacije o ostalih planetih in lunah.',
        'description_long' => 'S pomočjo te tehnologije lahko pridobiš informacije o ostalih planetih in lunah.',
    ],
    'computer_technology' => [
        'title' => 'Računalniška tehnologija',
        'description' => 'Z višanjem računalniške tehnologije lahko upravljaš več flot hkrati. Vsaka stopnja ti prinese dodaten slot.',
        'description_long' => 'Z višanjem računalniške tehnologije lahko upravljaš več flot hkrati. Vsaka stopnja ti prinese dodaten slot.',
    ],
    'astrophysics' => [
        'title' => 'Astrofizika',
        'description' => 'Z astrofizikalnim raziskovalnim modelom lahko ladje potujejo globoko v vesolje na ekspedicije. Vsaka druga stopnja te raziskave ti omogoča kolonizacijo novega planeta.',
        'description_long' => 'Z astrofizikalnim raziskovalnim modelom lahko ladje potujejo globoko v vesolje na ekspedicije. Vsaka druga stopnja te raziskave ti omogoča kolonizacijo novega planeta.',
    ],
    'intergalactic_research_network' => [
        'title' => 'Medgalaktična raziskovalna mreža',
        'description' => 'Raziskovalci na različnih planetih komunicirajo preko tega omrežja.',
        'description_long' => 'Raziskovalci na različnih planetih komunicirajo preko tega omrežja.',
    ],
    'graviton_technology' => [
        'title' => 'Gravitonska tehnologija',
        'description' => 'Sprožitev koncentriranih gravitonskih delcev lahko povzroči umetno gravitacijo, kar lahko uniči ladje ali celo lune.',
        'description_long' => 'Sprožitev koncentriranih gravitonskih delcev lahko povzroči umetno gravitacijo, kar lahko uniči ladje ali celo lune.',
    ],
    'weapon_technology' => [
        'title' => 'Tehnologija orožja',
        'description' => 'Tehnologija orožja poskrbi za boljše delovanje orožja na tvojih ladjah in obrambi. Vsaka stopnja ti doda 10% osnovne vrednosti.',
        'description_long' => 'Tehnologija orožja poskrbi za boljše delovanje orožja na tvojih ladjah in obrambi. Vsaka stopnja ti doda 10% osnovne vrednosti.',
    ],
    'shielding_technology' => [
        'title' => 'Tehnologija ščita',
        'description' => 'Tehnologija ščitov naredi ščite na ladjah in obrambnih objektih učinkovitejše. Vsaka stopnja tehnologije ščitov poveča moč ščitov za 10 % osnovne vrednosti.',
        'description_long' => 'Tehnologija ščita naredi ščit na ladjah in obrambi bolj učinkovit. Vsaka stopnja mu doda 10% osnovne vrednosti.',
    ],
    'armor_technology' => [
        'title' => 'Tehnologija oklepa',
        'description' => 'Posebna zlitina izboljša oklep na ladjah in obrambnih strukturah. Vsaka stopnja doprinese 10% osnovne vrednosti.',
        'description_long' => 'Posebna zlitina izboljša oklep na ladjah in obrambnih strukturah. Vsaka stopnja doprinese 10% osnovne vrednosti.',
    ],
    'small_cargo' => [
        'title' => 'Majhna tovorna ladja',
        'description' => 'Majhna tovorna ladja je enostavna ladja za prevoz surovin med planeti.',
        'description_long' => 'Majhna tovorna ladja je enostavna ladja za prevoz surovin med planeti.',
    ],
    'large_cargo' => [
        'title' => 'Velika tovorna ladja',
        'description' => 'Ta tovorna ladja ima veliko več prostora kot majhna tovorna ladja in je v normalnih pogojih hitrejša kot majhna tovorna ladja zahvaljujoč naprednemu pogonu.',
        'description_long' => 'Ta tovorna ladja ima veliko več prostora kot majhna tovorna ladja in je v normalnih pogojih hitrejša kot majhna tovorna ladja zahvaljujoč naprednemu pogonu.',
    ],
    'colony_ship' => [
        'title' => 'Kolonizacijska ladja',
        'description' => 'S to ladjo se lahko kolonizira prazne planete.',
        'description_long' => 'S to ladjo se lahko kolonizira prazne planete.',
    ],
    'recycler' => [
        'title' => 'Recikler',
        'description' => 'Reciklatorji so edine ladje, ki lahko po boju poberejo polja odpadkov, ki lebdijo v orbiti planeta.',
        'description_long' => 'Reciklerji so edina ladja, ki lahko pobere ruševine v orbitah planetov.',
    ],
    'espionage_probe' => [
        'title' => 'Vohunska sonda',
        'description' => 'Vohunske sonde so majhne, gibčne ladje, ki te oskrbujejo z informacijami o drugih planetih.',
        'description_long' => 'Vohunske sonde so majhne, gibčne ladje, ki te oskrbujejo z informacijami o drugih planetih.',
    ],
    'solar_satellite' => [
        'title' => 'Sončni satelit',
        'description' => 'Solarni sateliti so preproste platforme sončnih celic, ki se nahajajo v visoki stacionarni orbiti. Zbirajo sončno svetlobo in jo z laserjem prenašajo na zemeljsko postajo.',
        'description_long' => 'Sončni sateliti so enostavne plošče iz sončnih celic, ki so vedno v orbiti. Zbirajo sončno svetlobo in jo pretvarjajo v energijo. Sončni satelit proizvaja 35 energije na tem planetu.',
    ],
    'crawler' => [
        'title' => 'Plazilec',
        'description' => 'Plazilci povečajo proizvodnjo metala, kristala in Deuteriuma na določenem planetu za 0.02%, 0.02% in 0.02%. Kot pri zbiralcu se poveča tudi proizvodnja. Najvišji možen bonus je odvisen od splošne stopnje tvojih rudnikov.',
        'description_long' => 'Plazilci povečajo proizvodnjo metala, kristala in Deuteriuma na določenem planetu za 0.02%, 0.02% in 0.02%. Kot pri zbiralcu se poveča tudi proizvodnja. Najvišji možen bonus je odvisen od splošne stopnje tvojih rudnikov.',
    ],
    'pathfinder' => [
        'title' => 'Iskalec sledi',
        'description' => 'Pathfinder je hitra in okretna ladja, namensko zgrajena za odprave v neznane sektorje vesolja.',
        'description_long' => 'Iskalci sledi so hitri, prostorni in lahko odkrivajo in rudarijo polja razbitin med ekspedicijami. Skupni pridelek se poveča.',
    ],
    'light_fighter' => [
        'title' => 'Lahek lovec',
        'description' => 'Lahki lovec je okretna ladja, ki je prisotna na skoraj vsakem planetu. Stroški niso posebej veliki, moč ščita in tovorna kapaciteta pa sta zelo majhni.',
        'description_long' => 'Lahki lovec je okretna ladja, ki je prisotna na skoraj vsakem planetu. Stroški niso posebej veliki, moč ščita in tovorna kapaciteta pa sta zelo majhni.',
    ],
    'heavy_fighter' => [
        'title' => 'Težki lovec',
        'description' => 'Ta lovec je bolje oborožen in ima večjo moč kot lahki lovec.',
        'description_long' => 'Ta lovec je bolje oborožen in ima večjo moč kot lahki lovec.',
    ],
    'cruiser' => [
        'title' => 'Križarka',
        'description' => 'Križarke imajo skoraj trikrat boljši oklep kot težki lovci in skoraj dvakratno strelno moč. Kot dodatek, so tudi zelo hitre.',
        'description_long' => 'Križarke imajo skoraj trikrat boljši oklep kot težki lovci in skoraj dvakratno strelno moč. Kot dodatek, so tudi zelo hitre.',
    ],
    'battle_ship' => [
        'title' => 'Bojna ladja',
        'description' => 'Bojne ladje predstavljajo hrbtenico tvoje flote. Težki kanoni, velika hitrost in veliko skladišče jih naredijo resne nasprotnike.',
        'description_long' => 'Bojne ladje predstavljajo hrbtenico tvoje flote. Težki kanoni, velika hitrost in veliko skladišče jih naredijo resne nasprotnike.',
    ],
    'battlecruiser' => [
        'title' => 'Bojna križarka',
        'description' => 'Bojne križarke so specializirane za prestrezanje sovražnih flot.',
        'description_long' => 'Bojne križarke so specializirane za prestrezanje sovražnih flot.',
    ],
    'bomber' => [
        'title' => 'Bombnik',
        'description' => 'Bombnik je bil izumljen posebno za uničevanje obrambe nekega planeta.',
        'description_long' => 'Bombnik je bil izumljen posebno za uničevanje obrambe nekega planeta.',
    ],
    'destroyer' => [
        'title' => 'Uničevalec',
        'description' => 'Uničevalec je kralj bojnih ladij.',
        'description_long' => 'Uničevalec je kralj bojnih ladij.',
    ],
    'deathstar' => [
        'title' => 'Zvezda smrti',
        'description' => 'Uničujoča moč zvezd smrti se ne more primerjati z ničemer.',
        'description_long' => 'Uničujoča moč zvezd smrti se ne more primerjati z ničemer.',
    ],
    'reaper' => [
        'title' => 'Kombajn',
        'description' => 'Reaper je zmogljiva bojna ladja, specializirana za agresivne napade in žetev odpadkov.',
        'description_long' => 'Ladja razreda Kombajn je mogočen uničujoč instrument, ki lahko pleni polja razbitin po bitki.',
    ],
    'rocket_launcher' => [
        'title' => 'Raketnik',
        'description' => 'Raketnik je najpreprostejša in najcenejša obrambna struktura.',
        'description_long' => 'Raketnik je najpreprostejša in najcenejša obrambna struktura.',
    ],
    'light_laser' => [
        'title' => 'Lahki laser',
        'description' => 'Usmerjeno streljanje fotonov povzroči veliko večjo škodo kot normalno balistično orožje.',
        'description_long' => 'Usmerjeno streljanje fotonov povzroči veliko večjo škodo kot normalno balistično orožje.',
    ],
    'heavy_laser' => [
        'title' => 'Težek laser',
        'description' => 'Težki laser je logičen razvoj lahkega laserja.',
        'description_long' => 'Težki laser je logičen razvoj lahkega laserja.',
    ],
    'gauss_cannon' => [
        'title' => 'Gaussov top',
        'description' => 'Gaussov top ima nekaj tonske izstrelke, ki jih izstreli z veliko hitrostjo.',
        'description_long' => 'Gaussov top ima nekaj tonske izstrelke, ki jih izstreli z veliko hitrostjo.',
    ],
    'ion_cannon' => [
        'title' => 'Ionski top',
        'description' => 'The Ion Cannon fires a continuous beam of accelerating ions, causing considerable damage to objects it strikes.',
        'description_long' => 'Ionski top ustreli konstanten curek pospešujočih se ionov, kar povzroča ogromno škodo na tarčah.',
    ],
    'plasma_turret' => [
        'title' => 'Plazemski top',
        'description' => 'Plasma Turrets release the energy of a solar flare and surpass even the destroyer in destructive effect.',
        'description_long' => 'Plazemski top sprošča sončno energijo in tako uniči vse pred seboj.',
    ],
    'small_shield_dome' => [
        'title' => 'Majhen ščit',
        'description' => 'The small shield dome covers an entire planet with a field which can absorb a tremendous amount of energy.',
        'description_long' => 'Majhen ščit obdaja celoten planeta, kar pomeni da absorbira ogromno energijo.',
    ],
    'large_shield_dome' => [
        'title' => 'Velik ščit',
        'description' => 'The evolution of the small shield dome can employ significantly more energy to withstand attacks.',
        'description_long' => 'Evolucija majhnega ščita nam s svojo energijo lahko zelo pomaga pri obrambi.',
    ],
    'anti_ballistic_missile' => [
        'title' => 'Protibalistične rakete',
        'description' => 'Anti-Ballistic Missiles destroy attacking interplanetary missiles',
        'description_long' => 'Protibalistične rakete uničujejo nasprotnikove medplanetarne rakete.',
    ],
    'interplanetary_missile' => [
        'title' => 'Medplanetarne rakete',
        'description' => 'Medplanetarne rakete uničijo sovražnikovo obrambo.',
        'description_long' => 'Medplanetarne rakete uničujejo sovražno obrambo. Tvoje rakete imajo domet v obsegu 0 sistemov.',
    ],
    'kraken' => [
        'title' => 'KRAKEN',
        'description' => 'Skrajša čas gradnje stavb, ki so trenutno v gradnji, za <b>:duration</b>.',
    ],
    'detroid' => [
        'title' => 'DETROID',
        'description' => 'Skrajša čas gradnje trenutnih ladjedelniških pogodb za <b>:trajanje</b>.',
    ],
    'newtron' => [
        'title' => 'NEWTRON',
        'description' => 'Skrajša čas raziskovanja za vse raziskave, ki trenutno potekajo, za <b>:duration</b>.',
    ],
];
