<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : cs (OGame: cz)
 * Source   : resources/lang/en/t_external.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'browser_warning' => [
        'title' => 'Váš prohlížeč není aktuální.',
        'desc1' => 'Vaše verze Internet Exploreru neodpovídá stávajícím standardům a tato webová stránka ji již nepodporuje.',
        'desc2' => 'Chcete-li používat tento web, aktualizujte svůj webový prohlížeč na aktuální verzi nebo použijte jiný webový prohlížeč. Pokud již používáte nejnovější verzi, znovu načtěte stránku, aby se správně zobrazila.',
        'desc3' => 'Zde je seznam nejoblíbenějších prohlížečů. Kliknutím na jeden ze symbolů se dostanete na stránku stahování:',
    ],
    'login' => [
        'page_title' => 'OGame - Dobýt vesmír',
        'btn' => 'Přihlášení',
        'email_label' => 'E-mailová adresa:',
        'password_label' => 'Heslo:',
        'universe_label' => 'Vesmír',
        'universe_option_1' => '1. Vesmír',
        'submit' => 'Přihlaste se',
        'forgot_password' => 'Zapomněli jste heslo?',
        'forgot_email' => 'Zapomněli jste svou e-mailovou adresu?',
        'terms_accept_html' => 'Přihlášením přijímám <a class="" href="#" target="_blank" title="T&amp;Cs">T&Cs</a>',
    ],
    'register' => [
        'play_free' => 'HRAJTE ZDARMA!',
        'email_label' => 'E-mailová adresa:',
        'password_label' => 'Heslo:',
        'universe_label' => 'Vesmír',
        'distinctions' => 'Rozdíly',
        'terms_html' => 'Ve hře platí naše <a class="" target="_blank" href="#" title="T&amp;Cs"> T&amp;Cs </a> a <a class="" target="_blank" href="#" title="Zásady ochrany osobních údajů"> Zásady ochrany osobních údajů</a>',
        'submit' => 'Rejstřík',
    ],
    'nav' => [
        'home' => 'Domov',
        'about' => 'O hře OGame',
        'media' => 'Média',
        'wiki' => 'Wiki',
    ],
    'home' => [
        'title' => 'OGame - Dobýt vesmír',
        'description_html' => '<em>OGame</em> je strategická hra odehrávající se ve vesmíru, ve které současně soutěží tisíce hráčů z celého světa. K hraní potřebujete pouze běžný webový prohlížeč.',
        'board_btn' => 'Rada',
        'trailer_title' => 'Přívěs',
    ],
    'footer' => [
        'legal' => 'Tiráž',
        'privacy_policy' => 'Zásady ochrany osobních údajů',
        'terms' => 'VOP',
        'contact' => 'Kontakt',
        'rules' => 'Pravidla',
        'copyright' => '© OGameX. Všechna práva vyhrazena.',
    ],
    'js' => [
        'login' => 'Přihlášení',
        'close' => 'Blízko',
        'age_check_failed' => 'Je nám líto, ale nemáte nárok na registraci. Další informace naleznete v našich podmínkách.',
    ],
    'validation' => [
        'required' => 'Toto pole je povinné',
        'make_decision' => 'Udělejte rozhodnutí',
        'accept_terms' => 'Musíte přijmout T&C.',
        'length' => 'Povoleno 3 až 20 znaků.',
        'pw_length' => 'Povoleno 4 až 20 znaků.',
        'email' => 'Musíte zadat platnou e-mailovou adresu!',
        'invalid_chars' => 'Obsahuje neplatné znaky.',
        'no_begin_end_underscore' => 'Vaše jméno nesmí začínat ani končit podtržítkem.',
        'no_begin_end_whitespace' => 'Vaše jméno nesmí začínat ani končit mezerou.',
        'max_three_underscores' => 'Vaše jméno nesmí celkem obsahovat více než 3 podtržítka.',
        'max_three_whitespaces' => 'Vaše jméno nesmí obsahovat celkem více než 3 mezery.',
        'no_consecutive_underscores' => 'Nesmíte používat dvě nebo více podtržítek za sebou.',
        'no_consecutive_whitespaces' => 'Nesmíte použít dvě nebo více mezer za sebou.',
        'username_available' => 'Toto uživatelské jméno je k dispozici.',
        'username_loading' => 'Čekejte prosím, načítání...',
        'username_taken' => 'Toto uživatelské jméno již není dostupné.',
        'only_letters' => 'Používejte pouze znaky.',
    ],
    'forgot_password' => [
        'title' => 'Zapomněli jste heslo?',
        'description' => 'Níže zadejte svou e-mailovou adresu a my vám zašleme odkaz pro obnovení hesla.',
        'email_label' => 'E-mailová adresa:',
        'submit' => 'Odeslat odkaz pro reset',
        'back_to_login' => '← Zpět na přihlášení',
    ],
    'reset_password' => [
        'title' => 'Obnovte heslo',
        'email_label' => 'E-mailová adresa:',
        'password_label' => 'Nové heslo:',
        'confirm_label' => 'Potvrďte nové heslo:',
        'submit' => 'Obnovit heslo',
    ],
    'forgot_email' => [
        'title' => 'Zapomněli jste svou e-mailovou adresu?',
        'description' => 'Zadejte své jméno velitele a my vám zašleme nápovědu na registrovanou e-mailovou adresu.',
        'username_label' => 'Jméno velitele:',
        'submit' => 'Pošlete nápovědu',
        'back_to_login' => '← Zpět na přihlášení',
        'sent' => 'Pokud byl nalezen odpovídající účet, byla na registrovanou e-mailovou adresu zaslána nápověda.',
    ],
    'mail' => [
        'reset_password' => [
            'subject' => 'Resetujte své heslo OGameX',
            'heading' => 'Obnovení hesla',
            'greeting' => 'Dobrý den: uživatelské jméno,',
            'body' => 'Obdrželi jsme žádost o resetování hesla k vašemu účtu. Klikněte na tlačítko níže a vyberte si nové heslo.',
            'cta' => 'Obnovit heslo',
            'expiry' => 'Platnost tohoto odkazu vyprší za 60 minut.',
            'no_action' => 'Pokud jste o reset hesla nepožádali, není vyžadována žádná další akce.',
            'url_fallback' => 'Pokud máte potíže s kliknutím na tlačítko, zkopírujte a vložte níže uvedenou adresu URL do svého prohlížeče:',
        ],
        'retrieve_email' => [
            'subject' => 'Vaše e-mailová adresa OGameX',
            'heading' => 'Nápověda k e-mailové adrese',
            'greeting' => 'Dobrý den: uživatelské jméno,',
            'body' => 'Požádali jste o nápovědu pro e-mailovou adresu spojenou s vaším účtem:',
            'cta' => 'Přejděte na Přihlášení',
            'no_action' => 'Pokud jste tento požadavek nepodali, můžete tento e-mail bezpečně ignorovat.',
        ],
    ],
    'universe_characteristics' => [
        'fleet_speed' => 'Rychlost flotily: čím vyšší hodnota, tím méně času vám zbývá na reakci na útok.',
        'economy_speed' => 'Ekonomická rychlost: čím vyšší hodnota, tím rychleji budou dokončeny stavby a výzkum a shromážděny zdroje.',
        'debris_ships' => 'Některé z lodí zničených v bitvě vstoupí na pole trosek.',
        'debris_defence' => 'Některé z obranných struktur zničených v bitvě se dostanou na pole trosek.',
        'dark_matter_gift' => 'Temnou hmotu dostanete jako odměnu za potvrzení vaší e-mailové adresy.',
        'aks_on' => 'Bojový systém Aliance aktivován',
        'planet_fields' => 'Maximální počet stavebních slotů byl zvýšen.',
        'wreckfield' => 'Space Dock aktivován: některé zničené lodě lze obnovit pomocí Space Dock.',
        'universe_big' => 'Množství galaxií ve vesmíru',
    ],
];
