<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : cs (OGame: cz)
 * Source   : resources/lang/en/t_galaxy.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'planet' => [
        'description' => [
            'nearest' => 'Díky blízkosti slunce je sběr solární energie vysoce účinný. Planety v této poloze však bývají malé a poskytují pouze malé množství deuteria.',
            'normal' => 'Normálně jsou v této Pozici vyvážené planety s dostatečnými zdroji deuteria, dobrou zásobou sluneční energie a dostatečným prostorem pro rozvoj.',
            'biggest' => 'Obecně největší planety sluneční soustavy leží v této poloze. Slunce poskytuje dostatek energie a lze předpokládat dostatečné zdroje deuteria.',
            'farthest' => 'Vzhledem k velké vzdálenosti od Slunce je sběr sluneční energie omezený. Tyto planety však obvykle poskytují významné zdroje deuteria.',
        ],
    ],
    'mission' => [
        'colonize' => [
            'name' => 'Kolonizovat',
            'no_ship' => 'Není možné kolonizovat planetu bez kolonizační lodi.',
        ],
    ],
    'discovery' => [
        'locked' => 'You haven\'t unlocked the research to discover new lifeforms yet.',
    ],
];
