<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : pt (OGame: pt)
 * Source   : resources/lang/en/t_external.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'browser_warning' => [
        'title' => 'Seu navegador não está atualizado.',
        'desc1' => 'A sua versão do Internet Explorer não corresponde aos padrões existentes e não é mais suportada por este site.',
        'desc2' => 'Para usar este site, atualize seu navegador para uma versão atual ou use outro navegador. Se você já estiver usando a versão mais recente, recarregue a página para exibi-la corretamente.',
        'desc3' => 'Aqui está uma lista dos navegadores mais populares. Clique em um dos símbolos para acessar a página de download:',
    ],
    'login' => [
        'page_title' => 'OGame - Conquiste o universo',
        'btn' => 'Conecte-se',
        'email_label' => 'Endereço de email:',
        'password_label' => 'Senha:',
        'universe_label' => 'Universo',
        'universe_option_1' => '1. Universo',
        'submit' => 'Conecte-se',
        'forgot_password' => 'Esqueceu sua senha?',
        'forgot_email' => 'Esqueceu seu endereço de e-mail?',
        'terms_accept_html' => 'Com o login eu aceito os <a class="" href="#" target="_blank" title="T&amp;Cs">T&amp;Cs</a>',
    ],
    'register' => [
        'play_free' => 'JOGUE DE GRAÇA!',
        'email_label' => 'Endereço de email:',
        'password_label' => 'Senha:',
        'universe_label' => 'Universo',
        'distinctions' => 'Distinções',
        'terms_html' => 'Nossos <a class="" target="_blank" href="#" title="T&amp;Cs"> T&Cs </a> e <a class="" target="_blank" href="#" title="Privacy Policy"> Política de Privacidade </a> se aplicam ao jogo',
        'submit' => 'Cadastre-se',
    ],
    'nav' => [
        'home' => 'Lar',
        'about' => 'Sobre OGame',
        'media' => 'Mídia',
        'wiki' => 'Wikipédia',
    ],
    'home' => [
        'title' => 'OGame - Conquiste o universo',
        'description_html' => '<em>OGame</em> é um jogo de estratégia ambientado no espaço, com milhares de jogadores de todo o mundo competindo ao mesmo tempo. Você só precisa de um navegador normal para jogar.',
        'board_btn' => 'Quadro',
        'trailer_title' => 'Reboque',
    ],
    'footer' => [
        'legal' => 'Nota Legal',
        'privacy_policy' => 'política de Privacidade',
        'terms' => 'Termos e Condições',
        'contact' => 'Contato',
        'rules' => 'Regras',
        'copyright' => '©OGameX. Todos os direitos reservados.',
    ],
    'js' => [
        'login' => 'Conecte-se',
        'close' => 'Fechar',
        'age_check_failed' => 'Lamentamos, mas você não está qualificado para se registrar. Consulte nossos T&C para obter mais informações.',
    ],
    'validation' => [
        'required' => 'Este campo é obrigatório',
        'make_decision' => 'Tome uma decisão',
        'accept_terms' => 'Você deve aceitar os T&Cs.',
        'length' => 'São permitidos entre 3 e 20 caracteres.',
        'pw_length' => 'São permitidos entre 4 e 20 caracteres.',
        'email' => 'Você precisa inserir um endereço de e-mail válido!',
        'invalid_chars' => 'Contém caracteres inválidos.',
        'no_begin_end_underscore' => 'Seu nome não pode começar ou terminar com sublinhado.',
        'no_begin_end_whitespace' => 'Seu nome não pode começar ou terminar com espaço.',
        'max_three_underscores' => 'Seu nome não pode conter mais de 3 sublinhados no total.',
        'max_three_whitespaces' => 'Seu nome não pode incluir mais de 3 espaços no total.',
        'no_consecutive_underscores' => 'Você não pode usar dois ou mais sublinhados, um após o outro.',
        'no_consecutive_whitespaces' => 'Você não pode usar dois ou mais espaços um após o outro.',
        'username_available' => 'Este nome de usuário está disponível.',
        'username_loading' => 'Aguarde, carregando...',
        'username_taken' => 'Este nome de usuário não está mais disponível.',
        'only_letters' => 'Use apenas caracteres.',
    ],
    'forgot_password' => [
        'title' => 'Esqueceu sua senha?',
        'description' => 'Digite seu endereço de e-mail abaixo e enviaremos um link para redefinir sua senha.',
        'email_label' => 'Endereço de email:',
        'submit' => 'Enviar link de redefinição',
        'back_to_login' => '← Voltar ao login',
    ],
    'reset_password' => [
        'title' => 'Redefinir sua senha',
        'email_label' => 'Endereço de email:',
        'password_label' => 'Nova Senha:',
        'confirm_label' => 'Confirme a nova senha:',
        'submit' => 'Redefinir senha',
    ],
    'forgot_email' => [
        'title' => 'Esqueceu seu endereço de e-mail?',
        'description' => 'Digite seu nome de comandante e enviaremos uma dica para o endereço de e-mail cadastrado.',
        'username_label' => 'Nome do comandante:',
        'submit' => 'Enviar dica',
        'back_to_login' => '← Voltar ao login',
        'sent' => 'Se uma conta correspondente for encontrada, uma dica será enviada para o endereço de e-mail registrado.',
    ],
    'mail' => [
        'reset_password' => [
            'subject' => 'Redefinir sua senha OGameX',
            'heading' => 'Redefinição de senha',
            'greeting' => 'Olá: nome de usuário,',
            'body' => 'Recebemos uma solicitação para redefinir a senha da sua conta. Clique no botão abaixo para escolher uma nova senha.',
            'cta' => 'Redefinir senha',
            'expiry' => 'Este link irá expirar em 60 minutos.',
            'no_action' => 'Se você não solicitou uma redefinição de senha, nenhuma ação adicional será necessária.',
            'url_fallback' => 'Se você tiver problemas para clicar no botão, copie e cole o URL abaixo em seu navegador:',
        ],
        'retrieve_email' => [
            'subject' => 'Seu endereço de e-mail OGameX',
            'heading' => 'Dica de endereço de e-mail',
            'greeting' => 'Olá: nome de usuário,',
            'body' => 'Você solicitou uma dica para o endereço de e-mail associado à sua conta:',
            'cta' => 'Vá para Entrar',
            'no_action' => 'Se você não fez essa solicitação, pode ignorar este e-mail com segurança.',
        ],
    ],
    'universe_characteristics' => [
        'fleet_speed' => 'Velocidade da Frota: quanto maior o valor, menos tempo resta para você reagir a um ataque.',
        'economy_speed' => 'Velocidade da Economia: quanto maior o valor, mais rápidas serão as construções e pesquisas concluídas e os recursos reunidos.',
        'debris_ships' => 'Alguns dos navios destruídos em batalha entrarão no campo de destroços.',
        'debris_defence' => 'Algumas das estruturas defensivas destruídas em batalha entrarão no campo de destroços.',
        'dark_matter_gift' => 'Você receberá Dark Matter como recompensa por confirmar seu endereço de e-mail.',
        'aks_on' => 'Sistema de batalha da aliança ativado',
        'planet_fields' => 'A quantidade máxima de slots de construção foi aumentada.',
        'wreckfield' => 'Doca Espacial ativada: algumas naves destruídas podem ser restauradas usando a Doca Espacial.',
        'universe_big' => 'Quantidade de galáxias no universo',
    ],
];
