<div class="rawMessageData"
     data-raw-messagetype="25"
     data-raw-timestamp="1722700829"
     data-raw-date="2024-08-03T16:00:29.000Z"
     data-raw-hashcode="cr-en-253-e78bede029a3f05b36a5fe7e2da62327f5e06dce"
     data-raw-coords="7:257:9"
     data-raw-defenderspaceobject="{&quot;id&quot;:33728059,&quot;type&quot;:&quot;planet&quot;,&quot;name&quot;:&quot;Oh yes oh yes3&quot;,&quot;coordinates&quot;:{&quot;galaxy&quot;:7,&quot;system&quot;:257,&quot;position&quot;:9},&quot;owner&quot;:{&quot;type&quot;:&quot;player&quot;,&quot;id&quot;:114582,&quot;name&quot;:&quot;Lieutenant Nusakan&quot;,&quot;alliance&quot;:{&quot;id&quot;:500612,&quot;name&quot;:&quot;Fairly Average Rocket Techs&quot;,&quot;tag&quot;:&quot;FART&quot;,&quot;classId&quot;:1},&quot;rankId&quot;:null,&quot;status&quot;:[],&quot;classId&quot;:3}}"
     data-raw-fleets="[{&quot;side&quot;:&quot;defender&quot;,&quot;fleetId&quot;:0,&quot;player&quot;:{&quot;type&quot;:&quot;player&quot;,&quot;id&quot;:114582,&quot;name&quot;:&quot;Lieutenant Nusakan&quot;,&quot;alliance&quot;:{&quot;id&quot;:500612,&quot;name&quot;:&quot;Fairly Average Rocket Techs&quot;,&quot;tag&quot;:&quot;FART&quot;,&quot;classId&quot;:1},&quot;rankId&quot;:null,&quot;status&quot;:[],&quot;classId&quot;:3},&quot;spaceObject&quot;:{&quot;id&quot;:33728059,&quot;name&quot;:&quot;Oh yes oh yes3&quot;,&quot;type&quot;:&quot;planet&quot;,&quot;coordinates&quot;:{&quot;galaxy&quot;:7,&quot;system&quot;:257,&quot;position&quot;:9}},&quot;combatResearchPercentage&quot;:[{&quot;id&quot;:109,&quot;percentage&quot;:30},{&quot;id&quot;:110,&quot;percentage&quot;:60},{&quot;id&quot;:111,&quot;percentage&quot;:90}],&quot;combatTechnologies&quot;:[{&quot;technologyId&quot;:401,&quot;amount&quot;:1},{&quot;technologyId&quot;:403,&quot;amount&quot;:1}]},{&quot;side&quot;:&quot;attacker&quot;,&quot;fleetId&quot;:6286101,&quot;player&quot;:{&quot;type&quot;:&quot;player&quot;,&quot;id&quot;:108483,&quot;name&quot;:&quot;The Sinner&quot;,&quot;alliance&quot;:null,&quot;rankId&quot;:&quot;rank_starlord2&quot;,&quot;status&quot;:[&quot;strong&quot;,&quot;honorable-target&quot;],&quot;classId&quot;:3},&quot;spaceObject&quot;:{&quot;id&quot;:33751070,&quot;name&quot;:&quot;Azmodan3&quot;,&quot;type&quot;:&quot;moon&quot;,&quot;coordinates&quot;:{&quot;galaxy&quot;:3,&quot;system&quot;:344,&quot;position&quot;:12}},&quot;combatResearchPercentage&quot;:[{&quot;id&quot;:109,&quot;percentage&quot;:210},{&quot;id&quot;:110,&quot;percentage&quot;:210},{&quot;id&quot;:111,&quot;percentage&quot;:210}],&quot;combatTechnologies&quot;:[{&quot;technologyId&quot;:211,&quot;amount&quot;:1},{&quot;technologyId&quot;:203,&quot;amount&quot;:1}]}]"
     data-raw-combatrounds="[{&quot;statistics&quot;:[{&quot;side&quot;:&quot;defender&quot;,&quot;strength&quot;:445653,&quot;hits&quot;:2294,&quot;absorbedDamage&quot;:193327},{&quot;side&quot;:&quot;attacker&quot;,&quot;strength&quot;:56025800,&quot;hits&quot;:19068,&quot;absorbedDamage&quot;:294176}],&quot;fleets&quot;:[{&quot;side&quot;:&quot;defender&quot;,&quot;fleetId&quot;:0,&quot;technologies&quot;:[{&quot;technologyId&quot;:401,&quot;destroyed&quot;:1356,&quot;destroyedTotal&quot;:1356,&quot;remaining&quot;:1},{&quot;technologyId&quot;:403,&quot;destroyed&quot;:937,&quot;destroyedTotal&quot;:937,&quot;remaining&quot;:0}]},{&quot;side&quot;:&quot;attacker&quot;,&quot;fleetId&quot;:6286101,&quot;technologies&quot;:[{&quot;technologyId&quot;:211,&quot;destroyed&quot;:0,&quot;destroyedTotal&quot;:0,&quot;remaining&quot;:1228},{&quot;technologyId&quot;:203,&quot;destroyed&quot;:1,&quot;destroyedTotal&quot;:1,&quot;remaining&quot;:999}]}]},{&quot;statistics&quot;:[{&quot;side&quot;:&quot;defender&quot;,&quot;strength&quot;:104,&quot;hits&quot;:1,&quot;absorbedDamage&quot;:32},{&quot;side&quot;:&quot;attacker&quot;,&quot;strength&quot;:3821785,&quot;hits&quot;:2227,&quot;absorbedDamage&quot;:104}],&quot;fleets&quot;:[{&quot;side&quot;:&quot;defender&quot;,&quot;fleetId&quot;:0,&quot;technologies&quot;:[{&quot;technologyId&quot;:401,&quot;destroyed&quot;:1,&quot;destroyedTotal&quot;:1357,&quot;remaining&quot;:0},{&quot;technologyId&quot;:403,&quot;destroyed&quot;:0,&quot;destroyedTotal&quot;:937,&quot;remaining&quot;:0}]},{&quot;side&quot;:&quot;attacker&quot;,&quot;fleetId&quot;:6286101,&quot;technologies&quot;:[{&quot;technologyId&quot;:211,&quot;destroyed&quot;:0,&quot;destroyedTotal&quot;:0,&quot;remaining&quot;:1228},{&quot;technologyId&quot;:203,&quot;destroyed&quot;:0,&quot;destroyedTotal&quot;:1,&quot;remaining&quot;:999}]}]}]"
     data-raw-result="{&quot;winner&quot;:&quot;attacker&quot;,&quot;loot&quot;:{&quot;percentage&quot;:75,&quot;resources&quot;:[{&quot;resource&quot;:&quot;metal&quot;,&quot;amount&quot;:11832461},{&quot;resource&quot;:&quot;crystal&quot;,&quot;amount&quot;:2190000},{&quot;resource&quot;:&quot;deuterium&quot;,&quot;amount&quot;:363279},{&quot;resource&quot;:&quot;food&quot;,&quot;amount&quot;:0}]},&quot;debris&quot;:{&quot;resources&quot;:[{&quot;resource&quot;:&quot;metal&quot;,&quot;total&quot;:1769600,&quot;recycled&quot;:0,&quot;remaining&quot;:1769600},{&quot;resource&quot;:&quot;crystal&quot;,&quot;total&quot;:358400,&quot;recycled&quot;:0,&quot;remaining&quot;:358400}],&quot;requiredShips&quot;:[{&quot;technologyId&quot;:209,&quot;amount&quot;:93}],&quot;shipsUsedForRecycling&quot;:[],&quot;totalRequiredShips&quot;:[{&quot;technologyId&quot;:209,&quot;amount&quot;:93}]},&quot;totalValueOfUnitsLost&quot;:[{&quot;side&quot;:&quot;defender&quot;,&quot;value&quot;:10210000},{&quot;side&quot;:&quot;attacker&quot;,&quot;value&quot;:12000}],&quot;deathStarDestroyed&quot;:false,&quot;repairedTechnologies&quot;:[{&quot;technologyId&quot;:401,&quot;amount&quot;:855},{&quot;technologyId&quot;:403,&quot;amount&quot;:684}],&quot;moonCreation&quot;:null,&quot;honor&quot;:null,&quot;tacticalRetreat&quot;:{&quot;by&quot;:&quot;none&quot;,&quot;supremacy&quot;:113520000}}">
</div>

<div class="combatInfo">
        <div class="basicInfo">
            <span class="msg_ctn msg_ctn2 {{ $attacker_class }} tooltipLeft" data-tooltip-title="12,000">@lang('Attacker'): ({{ $attacker_name }}): {{ $attacker_losses }}</span>
            <span class="msg_ctn msg_ctn3">@lang('Resources'): {{ $loot }}, @lang('Loot'): {{ $loot_percentage }}%</span>
            <span class="msg_ctn msg_ctn3 tooltipLeft" data-tooltip-title="{{ $debris_sum_formatted }}">@lang('Debris field (newly created)'): {{ $debris_sum_formatted }}</span>
        </div>
        <div class="miscInfo">
            <span class="msg_ctn msg_ctn2 {{ $defender_class }} tooltipRight" data-tooltip-title="10,210,000">@lang('Defender'): ({{ $defender_name }}): {{ $defender_losses }}</span>
            <span class="msg_ctn msg_ctn3 tooltipRight" data-tooltip-title="1,539">@lang('Actually repaired'): {{ $repaired_defenses_count }}</span>
@if (!$moon_existed)
            <span class="msg_ctn msg_ctn3 tooltipRight" data-tooltip-title="1,539">@lang('Moon Chance'): {{ $moon_chance }}%</span>
@endif
        </div>
    </div>