<?php

/**
 * AUTO-GENERATED by `php artisan i18n:generate-locales`. DO NOT EDIT BY HAND.
 *
 * Language : ar
 * Source   : resources/lang/en/t_overview.php
 * Built    : 2026-04-11T21:17:54+00:00
 *
 * Untranslated leaves fall back to the english source string.
 * See _TRANSLATION_STATUS.md in this directory for the list of
 * keys still needing manual translation.
 */

return [
    'overview' => 'Resumen',
    'temperature' => 'Temperatura',
    'position' => 'Posición',
];
