<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : sl (OGame: si)
 * Source   : resources/lang/en/t_messages.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'welcome_message' => [
        'from' => 'OGameX',
        'subject' => 'Dobrodošli v OGameX!',
        'body' => 'Lep pozdrav cesar :player! 

Čestitke za začetek vaše slavne kariere. Tukaj bom, da vas vodim skozi vaše prve korake. 

Na levi lahko vidite meni, ki vam omogoča nadzor in upravljanje vašega galaktičnega imperija. 

Pregled ste že videli. Viri in zmogljivosti vam omogočajo gradnjo zgradb, ki vam bodo pomagale razširiti vaš imperij. Začnite z gradnjo sončne elektrarne za pridobivanje energije za svoje rudnike. 

Nato razširite svoj rudnik kovin in rudnik kristalov za pridobivanje vitalnih virov. V nasprotnem primeru se preprosto oglejte sami. Prepričan sem, da se boste kmalu dobro počutili doma. 

Več pomoči, nasvetov in taktik najdete tukaj: 

Klepet v Discordu: strežnik Discord 
Forum: Forum OGameX 
Podpora: Podpora za igre 

Na forumih boste našli samo trenutne objave in spremembe igre. 


Zdaj ste pripravljeni na prihodnost. vso srečo! 

To sporočilo bo izbrisano v 7 dneh.',
    ],
    'return_of_fleet_with_resources' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Vrnitev flote',
        'body' => 'Vaša flota se vrača iz :od do :do in je dostavila blago: 

Kovina: :kovina 
Kristal: :kristal 
Devterij: :devterij',
    ],
    'return_of_fleet' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Vrnitev flote',
        'body' => 'Vaša flota se vrača iz :from v :to. 

Vozni park ne dostavlja blaga.',
    ],
    'fleet_deployment_with_resources' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Vrnitev flote',
        'body' => 'Ena od vaših flot iz :from je dosegla :to in dostavila svoje blago: 

Kovina: :kovina 
Kristal: :kristal 
Devterij: :devterij',
    ],
    'fleet_deployment' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Vrnitev flote',
        'body' => 'Ena od vaših flot iz :from je dosegla :to. Vozni park ne dostavlja blaga.',
    ],
    'transport_arrived' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Doseči planet',
        'body' => 'Vaša flota od :od doseže :do in dostavi blago: 
Kovina: :kovina Kristal: :kristal Devterij: :devterij',
    ],
    'transport_received' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Dohodna flota',
        'body' => 'Prihajajoča flota iz :from je dosegla vaš planet :to in dostavila svoje blago: 
Kovina: :kovina Kristal: :kristal Devterij: :devterij',
    ],
    'acs_defend_arrival_host' => [
        'from' => 'Spremljanje vesolja',
        'subject' => 'Flota se ustavlja',
        'body' => 'Flota je prispela v :to.',
    ],
    'acs_defend_arrival_sender' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Flota se ustavlja',
        'body' => 'Flota je prispela v :to.',
    ],
    'colony_established' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Poročilo o poravnavi',
        'body' => 'Flota je prispela na dodeljene koordinate :koordinate, tam našla nov planet in se takoj začela razvijati na njem.',
    ],
    'colony_establish_fail_astrophysics' => [
        'from' => 'Naseljenci',
        'subject' => 'Poročilo o poravnavi',
        'body' => 'Flota je prispela na dodeljene koordinate: koordinate in ugotovila, da je planet primeren za kolonizacijo. Kmalu po začetku razvoja planeta kolonisti ugotovijo, da njihovo znanje astrofizike ne zadostuje za dokončanje kolonizacije novega planeta.',
    ],
    'espionage_report' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Poročilo o vohunjenju iz :planet',
    ],
    'espionage_detected' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Vohunsko poročilo iz Planeta :planet',
        'body' => 'Tuja flota s planeta :planet (:attacker_name) je bila opažena blizu vašega planeta 
:branilec 
Možnost protivohunjenja: :% možnosti',
    ],
    'battle_report' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Bojno poročilo: planet',
    ],
    'fleet_lost_contact' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Stik z napadalno floto je bil izgubljen. :koordinate',
        'body' => '(To pomeni, da je bil uničen v prvem krogu.)',
    ],
    'debris_field_harvest' => [
        'from' => 'Flota',
        'subject' => 'Poročilo o sečnji iz DF na :koordinatah',
        'body' => 'Vaša :ship_name (:ship_amount pošilja) ima skupno kapaciteto :storage_capacity. Na tarči :to, :metal Kovina, :crystal Kristal in :devterij Devterij lebdijo v vesolju. Poželi ste :harvested_metal Metal, :harvested_crystal Kristal in :harvested_deuterium Devterij.',
    ],
    'expedition_resources_captured' => ':resource_type :resource_amount so bili zajeti.',
    'expedition_dark_matter_captured' => '(:dark_matter_amount Temna snov)',
    'expedition_units_captured' => 'Naslednje ladje so zdaj del flote:',
    'expedition_unexplored_statement' => 'Zapis iz dnevnika uradnikov za zveze: Zdi se, da ta del vesolja še ni raziskan.',
    'expedition_failed' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Rezultat ekspedicije',
        'body' => [
            '1' => 'Zaradi okvare v centralnih računalnikih paradne ladje so morali misijo odprave prekiniti. Na žalost se zaradi okvare računalnika flota vrne domov praznih rok.',
            '2' => 'Vaša ekspedicija je skoraj naletela na gravitacijsko polje nevtronskih zvezd in potrebovala je nekaj časa, da se je osvobodila. Zaradi tega je bilo porabljenega veliko devterija in flota odprave se je morala vrniti brez rezultatov.',
            '3' => 'Iz neznanih razlogov je bil ekspedicijski skok popolnoma napačen. Skoraj je pristal v osrčju sonca. Na srečo je pristal v znanem sistemu, vendar bo skok nazaj trajal dlje, kot se je mislilo.',
            '4' => 'Napaka v glavnem jedru reaktorja skoraj uniči celotno floto odprave. Na srečo so bili tehniki več kot kompetentni in so se lahko izognili najhujšemu. Popravila so trajala kar nekaj časa in prisilila odpravo, da se je vrnila, ne da bi izpolnila svoj cilj.',
            '5' => 'Živo bitje, sestavljeno iz čiste energije, je prišlo na krov in vse člane odprave spravilo v nenavaden trans, zaradi česar so le gledali v hipnotizirajoče vzorce na računalniških zaslonih. Ko se jih je večina končno izvila iz hipnotičnega stanja, je bilo treba misijo odprave prekiniti, saj so imeli premalo devterija.',
            '6' => 'Novi navigacijski modul je še vedno hrošč. Skok ekspedicij jih ne le vodi v napačno smer, ampak je porabil vse gorivo devterija. Na srečo jih je skok flote pripeljal blizu lune odhodnih planetov. Malce razočarana se odprava zdaj vrača brez impulzne moči. Povratek bo trajal dlje, kot je bilo pričakovano.',
            '7' => 'Vaša odprava je izvedela za veliko praznino vesolja. Ni bilo niti enega majhnega asteroida ali sevanja ali delcev, ki bi to odpravo lahko naredili zanimivo.',
            '8' => 'No, zdaj vemo, da te rdeče anomalije razreda 5 nimajo samo kaotičnih učinkov na ladijske navigacijske sisteme, ampak povzročajo tudi ogromne halucinacije pri posadki. Ekspedicija ni prinesla ničesar nazaj.',
            '9' => 'Vaša odprava je posnela čudovite slike super nove. Iz odprave ni bilo mogoče pridobiti nič novega, vendar obstaja vsaj dobra možnost za zmago na tekmovanju "Najboljša slika vesolja" v naslednji mesečni številki revije OGame.',
            '10' => 'Vaša flota odprave je nekaj časa sledila čudnim signalom. Na koncu so opazili, da so bili ti signali poslani iz stare sonde, ki je bila poslana pred več generacijami, da bi pozdravila tuje vrste. Sondo so rešili in nekateri muzeji vašega domačega planeta so že izrazili zanimanje.',
            '11' => 'Kljub prvim, zelo obetavnim pregledom tega sektorja, smo se žal vrnili praznih rok.',
            '12' => 'Poleg nekaj čudnih, majhnih hišnih ljubljenčkov z neznanega močvirnega planeta ta odprava s potovanja ne prinaša nič vznemirljivega.',
            '13' => 'Vodilna ladja odprave je trčila v tujo ladjo, ko je brez opozorila skočila v floto. Tuja ladja je eksplodirala in škoda na paradni ladji je bila precejšnja. Odprave v teh razmerah ni mogoče nadaljevati, zato se bo flota začela vračati, ko bodo opravljena potrebna popravila.',
            '14' => 'Naša ekipa odprave je naletela na nenavadno kolonijo, ki je bila zapuščena pred eoni. Po pristanku je naša posadka začela trpeti zaradi visoke vročine, ki jo je povzročil tuji virus. Ugotovljeno je bilo, da je ta virus izbrisal celotno civilizacijo na planetu. Naša ekipa odprave se odpravlja domov, da bi oskrbela bolne člane posadke. Na žalost smo morali misijo prekiniti in domov smo prišli praznih rok.',
            '15' => 'Nenavaden računalniški virus je kmalu po ločitvi našega domačega sistema napadel navigacijski sistem. To je povzročilo, da je flota odprave letela v krogih. Ni treba posebej poudarjati, da odprava ni bila zares uspešna.',
        ],
    ],
    'expedition_gain_resources' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Rezultat ekspedicije',
        'body' => [
            '1' => 'Na izoliranem planetoidu smo našli nekaj lahko dostopnih polj virov in jih nekaj uspešno pobrali.',
            '2' => 'Vaša ekspedicija je odkrila majhen asteroid, iz katerega bi lahko pridobili nekaj virov.',
            '3' => 'Vaša ekspedicija je našla starodaven, polno natovorjen, a zapuščen konvoj tovornih ladij. Nekatere vire bi lahko rešili.',
            '4' => 'Flota vaše ekspedicije poroča o odkritju razbitine velikanske tuje ladje. Niso se mogli učiti iz njihovih tehnologij, vendar so lahko ladjo razdelili na glavne sestavne dele in iz nje naredili nekaj uporabnih virov.',
            '5' => 'Na majhni luni z lastno atmosfero je vaša odprava našla ogromno skladišče surovin. Posadka na tleh poskuša dvigniti in naložiti ta naravni zaklad.',
            '6' => 'Mineralni pasovi okoli neznanega planeta so vsebovali neštete vire. Ekspedicijske ladje se vračajo in njihova skladišča so polna!',
        ],
    ],
    'expedition_gain_dark_matter' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Rezultat ekspedicije',
        'body' => [
            '1' => 'Ekspedicija je sledila nekaterim čudnim signalom do asteroida. V jedru asteroida so našli majhno količino temne snovi. Asteroid je bil zajet in raziskovalci poskušajo izločiti temno snov.',
            '2' => 'Ekspediciji je uspelo zajeti in shraniti nekaj temne snovi.',
            '3' => 'Na polici majhne ladje smo srečali nenavadnega tujca, ki nam je podaril kovček s temno snovjo v zameno za nekaj preprostih matematičnih izračunov.',
            '4' => 'Našli smo ostanke tuje ladje. Našli smo majhno posodo z nekaj temne snovi na polici v prtljažnem prostoru!',
            '5' => 'Naša odprava je imela prvi stik s posebno dirko. Videti je, kot da je bitje iz čiste energije, ki se je poimenoval Legorian, preletelo ekspedicijske ladje in se nato odločilo pomagati naši nerazviti vrsti. Zaboj s temno snovjo se je materializiral na mostu ladje!',
            '6' => 'Naša ekspedicija je prevzela ladjo duhov, ki je prevažala majhno količino temne snovi. Nismo našli nobenih namigov o tem, kaj se je zgodilo s prvotno posadko ladje, vendar so naši tehniki uspeli rešiti temno snov.',
            '7' => 'Naša odprava je izvedla edinstven poskus. Uspelo jim je pridobiti temno snov iz umirajoče zvezde.',
            '8' => 'Naša ekspedicija je locirala zarjavelo vesoljsko postajo, za katero se je zdelo, da že dolgo nenadzorovano lebdi po vesolju. Sama postaja je bila popolnoma neuporabna, vendar je bilo ugotovljeno, da je nekaj temne snovi shranjene v reaktorju. Naši tehniki se trudijo prihraniti, kolikor lahko.',
        ],
    ],
    'expedition_gain_ships' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Rezultat ekspedicije',
        'body' => [
            '1' => 'Naša ekspedicija je našla planet, ki je bil med določeno verigo vojn skoraj uničen. V orbiti lebdijo različne ladje. Tehniki poskušajo nekatere od njih popraviti. Morda bomo tudi pri nas dobili informacije o tem, kaj se je zgodilo.',
            '2' => 'Našli smo zapuščeno piratsko postajo. V hangarju leži nekaj starih ladij. Naši tehniki ugotavljajo, ali so nekateri še uporabni ali ne.',
            '3' => 'Vaša ekspedicija je naletela na ladjedelnice kolonije, ki je bila pred eoni zapuščena. V hangarju ladjedelnice odkrijejo nekaj ladij, ki bi jih lahko rešili. Tehniki se trudijo, da bi nekateri od njih znova poleteli.',
            '4' => 'Naleteli smo na ostanke prejšnje odprave! Naši tehniki bodo poskušali nekatere ladje ponovno vzpostaviti.',
            '5' => 'Naša ekspedicija je naletela na staro avtomatsko ladjedelnico. Nekatere ladje so še vedno v proizvodni fazi in naši tehniki trenutno poskušajo znova aktivirati generatorje energije v ladjedelnicah.',
            '6' => 'Našli smo ostanke armade. Tehniki so šli neposredno do skoraj nepoškodovanih ladij, da bi jih poskusili znova pripraviti do dela.',
            '7' => 'Našli smo planet izumrle civilizacije. Vidimo lahko ogromno nedotaknjeno vesoljsko postajo v orbiti. Nekateri vaši tehniki in piloti so šli na površje in iskali nekaj ladij, ki bi jih še lahko uporabili.',
        ],
    ],
    'expedition_gain_item' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Rezultat ekspedicije',
        'body' => [
            '1' => 'Bežeča flota je za seboj pustila predmet, da bi nas zmotila in jim pomagala pri begu.',
        ],
    ],
    'expedition_failed_and_speedup' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Rezultat ekspedicije',
        'body' => [
            '1' => 'Vaše odprave ne poročajo o nobenih anomalijah v raziskanem sektorju. Toda flota je med vračanjem naletela na sončni veter. Posledica tega je bila hitra povratna pot. Vaša ekspedicija se vrne domov nekoliko prej.',
            '2' => 'Novi in ​​drzni poveljnik je uspešno potoval skozi nestabilno črvino, da bi skrajšal let nazaj! Sama odprava pa ni prinesla nič novega.',
            '3' => 'Nepričakovana povratna sklopka v energetskih kolutih motorjev je pospešila vrnitev odprave, domov se vrne prej, kot je bilo pričakovano. Prva poročila pravijo, da nimajo nič vznemirljivega za račun.',
        ],
    ],
    'expedition_failed_and_delay' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Rezultat ekspedicije',
        'body' => [
            '1' => 'Vaša odprava je šla v sektor, poln neviht z delci. To je povzročilo preobremenitev zalog energije in večina glavnih sistemov ladij se je zrušila. Vaši mehaniki so se lahko izognili najhujšemu, a odprava se bo vrnila z veliko zamudo.',
            '2' => 'Vaš navigator je naredil hudo napako v svojih izračunih, zaradi česar je bil skok ekspedicije napačno izračunan. Ne samo, da je flota popolnoma zgrešila cilj, ampak bo povratna pot trajala veliko dlje, kot je bilo prvotno načrtovano.',
            '3' => 'Sončni veter rdečega orjaka je pokvaril skok odprave in bo trajalo kar nekaj časa, da se izračuna povratni skok. V tem sektorju ni bilo ničesar razen praznine med zvezdami. Flota se bo vrnila kasneje, kot je bilo pričakovano.',
        ],
    ],
    'expedition_battle' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Rezultat ekspedicije',
        'body' => [
            '1' => 'Nekateri primitivni barbari nas napadajo z vesoljskimi ladjami, ki jih sploh ne moremo poimenovati. Če bo požar resen, bomo prisiljeni streljati nazaj.',
            '2' => 'Morali smo se boriti z nekaterimi pirati, ki jih je bilo na srečo le nekaj.',
            '3' => 'Ujeli smo nekaj radijskih oddaj pijanih piratov. Zdi se, da bomo kmalu napadeni.',
            '4' => 'Našo odpravo je napadla majhna skupina neznanih ladij!',
            '5' => 'Nekaj ​​res obupanih vesoljskih piratov je poskušalo ujeti našo ekspedicijsko floto.',
            '6' => 'Nekatere ladje eksotičnega videza so brez opozorila napadle ekspedicijsko floto!',
            '7' => 'Vaša flota odprave je imela neprijazen prvi stik z neznano vrsto.',
        ],
    ],
    'expedition_battle_pirates' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Rezultat ekspedicije',
        'body' => [
            '1' => 'Nekateri primitivni barbari nas napadajo z vesoljskimi ladjami, ki jih sploh ne moremo poimenovati. Če bo požar resen, bomo prisiljeni streljati nazaj.',
            '2' => 'Morali smo se boriti z nekaterimi pirati, ki jih je bilo na srečo le nekaj.',
            '3' => 'Ujeli smo nekaj radijskih oddaj pijanih piratov. Zdi se, da bomo kmalu napadeni.',
            '4' => 'Našo odpravo je napadla majhna skupina vesoljskih piratov!',
            '5' => 'Nekaj ​​res obupanih vesoljskih piratov je poskušalo ujeti našo ekspedicijsko floto.',
            '6' => 'Pirati brez opozorila napadli floto ekspedicije!',
            '7' => 'Raztrgana flota vesoljskih piratov nas je prestregla in zahtevala davek.',
        ],
    ],
    'expedition_battle_aliens' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Rezultat ekspedicije',
        'body' => [
            '1' => 'Ujeli smo čudne signale neznanih ladij. Izkazalo se je, da so sovražni!',
            '2' => 'Nezemljanska patrulja je zaznala našo odpravo in jo takoj napadla!',
            '3' => 'Vaša flota odprave je imela neprijazen prvi stik z neznano vrsto.',
            '4' => 'Nekatere ladje eksotičnega videza so brez opozorila napadle ekspedicijsko floto!',
            '5' => 'Flota nezemljanskih vojnih ladij je prišla iz hipervesolja in se spopadla z nami!',
            '6' => 'Naleteli smo na tehnološko napredno tujerodno vrsto, ki ni bila miroljubna.',
            '7' => 'Naši senzorji so zaznali neznane energijske podpise, preden so napadle ladje nezemljanov!',
        ],
    ],
    'expedition_loss_of_fleet' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Rezultat ekspedicije',
        'body' => [
            '1' => 'Taljenje jedra vodilne ladje povzroči verižno reakcijo, ki v spektakularni eksploziji uniči celotno floto odprave.',
        ],
    ],
    'expedition_merchant_found' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Rezultat ekspedicije',
        'body' => [
            '1' => 'Vaša flota odprave je vzpostavila stik s prijazno nezemljansko raso. Napovedali so, da bodo poslali predstavnika z blagom za trgovanje v vaše svetove.',
            '2' => 'Vaši odpravi se je približala skrivnostna trgovska ladja. Trgovec je ponudil, da obišče vaše planete in zagotovi posebne storitve trgovanja.',
            '3' => 'Odprava je naletela na medgalaktični trgovski konvoj. Eden od trgovcev se je strinjal, da bo obiskal vaš domači svet in ponudil možnosti trgovanja.',
        ],
    ],
    'buddy_request_received' => [
        'from' => 'Prijatelji',
        'subject' => 'Zahteva za prijateljstvo',
        'body' => 'Prejeli ste novo prošnjo za prijateljstvo od :sender_name.<span style="display:none;">:buddy_request_id</span>',
    ],
    'buddy_request_accepted' => [
        'from' => 'Prijatelji',
        'subject' => 'Zahteva za prijatelja sprejeta',
        'body' => 'Igralec :accepter_name te je dodal na svoj seznam prijateljev.',
    ],
    'buddy_removed' => [
        'from' => 'Prijatelji',
        'subject' => 'Izbrisan si bil s seznama prijateljev',
        'body' => 'Igralec :remover_name vas je odstranil s svojega seznama prijateljev.',
    ],
    'missile_attack_report' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Raketni napad na :target_coords',
        'body' => 'Vaše medplanetarne rakete iz :origin_planet_name :origin_planet_coords (ID: :origin_planet_id) so dosegle svoj cilj na :target_planet_name :target_coords (ID: :target_planet_id, Type: :target_type). 

Izstreljene rakete: :missiles_sent 
Prestreženi izstrelki: :missiles_intercepted 
Zadetek izstrelkov: :missiles_hit 

Obrambe uničene: :defenses_destroyed',
        'missile_singular' => 'missile',
        'missile_plural' => 'missiles',
        'from_your_planet' => ' from your planet ',
        'smashed_into' => ' smashed into the planet ',
        'intercepted_label' => 'Missiles Intercepted:',
        'defenses_hit_label' => 'Defenses Hit',
        'none' => 'None',
    ],
    'missile_defense_report' => [
        'from' => 'poveljstvo obrambe',
        'subject' => 'Raketni napad na :planet_coords',
        'body' => 'Vaš planet :planet_name na :planet_coords (ID: :planet_id) so napadle medplanetarne rakete :attacker_name! 

Prihajajoči izstrelki: :missiles_incoming 
Prestreženi izstrelki: :missiles_intercepted 
Zadetek izstrelkov: :missiles_hit 

Obrambe uničene: :defenses_destroyed',
        'your_planet' => 'Your planet ',
        'attacked_by_prefix' => ' has been attacked by interplanetary missiles from ',
        'incoming_label' => 'Incoming Missiles:',
        'intercepted_label' => 'Missiles Intercepted:',
        'defenses_hit_label' => 'Defenses Hit',
        'none' => 'None',
    ],
    'alliance_broadcast' => [
        'from' => ':ime_pošiljatelja',
        'subject' => '[:alliance_tag] Oddaja zavezništva od :sender_name',
        'body' => ':sporočilo',
    ],
    'alliance_application_received' => [
        'from' => 'Upravljanje zavezništva',
        'subject' => 'Nova aplikacija za zavezništvo',
        'body' => 'Igralec :applicant_name se je prijavil za pridružitev vaši zvezi. 

Sporočilo aplikacije: 
:application_message',
    ],
    'planet_relocation_success' => [
        'from' => 'Upravljajte kolonije',
        'subject' => 'Premestitev :planet_name je bila uspešna',
        'body' => 'Planet :planet_name je bil uspešno prestavljen s koordinat [coordinates]:old_coordinates[/coordinates] na [coordinates]:new_coordinates[/coordinates].',
    ],
    'fleet_union_invite' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Povabilo v boj v zavezništvu',
        'body' => ':sender_name vas je povabil na misijo :union_name proti :target_player na [:target_coords], flota je bila tempirana na :arrival_time. 

POZOR: Čas prihoda se lahko spremeni zaradi združevanja flot. Vsaka nova flota lahko ta čas podaljša za največ 30 %, sicer se ne bo smela pridružiti. 

OPOMBA: Skupna moč vseh udeležencev v primerjavi s skupno močjo branilcev določa, ali bo to častna bitka ali ne.',
    ],
    'Shipyard is being upgraded.' => 'Ladjedelnica se posodablja.',
    'Nanite Factory is being upgraded.' => 'Tovarna Nanite se nadgrajuje.',
    'moon_destruction_success' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Luna :moon_name [:moon_coords] je bila uničena!',
        'body' => 'Z verjetnostjo uničenja :destruction_chance in verjetnostjo izgube Deathstar :loss_chance je vaša flota uspešno uničila luno :moon_name pri :moon_coords.',
    ],
    'moon_destruction_failure' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Uničenje lune na :moon_coords ni uspelo',
        'body' => 'Z verjetnostjo uničenja :destruction_chance in verjetnostjo izgube Deathstar :loss_chance vaša flota ni uspela uničiti lune :moon_name pri :moon_coords. Flota se vrača.',
    ],
    'moon_destruction_catastrophic' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Katastrofalna izguba med uničenjem lune na :moon_coords',
        'body' => 'Z verjetnostjo uničenja :destruction_chance in verjetnostjo izgube Deathstar :loss_chance vaša flota ni uspela uničiti lune :moon_name pri :moon_coords. Poleg tega so bile med poskusom izgubljene vse Deathstars. Razbitin ni.',
    ],
    'moon_destruction_mission_failed' => [
        'from' => 'Poveljstvo flote',
        'subject' => 'Misija uničenja Lune ni uspela pri :koordinatah',
        'body' => 'Vaša flota je prispela na :coordinates, vendar na ciljni lokaciji ni bila najdena luna. Flota se vrača.',
    ],
    'moon_destruction_repelled' => [
        'from' => 'Spremljanje vesolja',
        'subject' => 'Poskus uničenja na luni :moon_name [:moon_coords] je bil odbit',
        'body' => ':attacker_name je napadel vašo luno :moon_name pri :moon_coords z verjetnostjo uničenja :destruction_chance in verjetnostjo izgube Deathstar :loss_chance. Vaša luna je preživela napad!',
    ],
    'moon_destroyed' => [
        'from' => 'Spremljanje vesolja',
        'subject' => 'Luna :moon_name [:moon_coords] je bila uničena!',
        'body' => 'Tvojo luno :moon_name na :moon_coords je uničila flota Deathstar, ki pripada :attacker_name!',
    ],
    'wreck_field_repair_completed' => [
        'from' => 'Sistemsko sporočilo',
        'subject' => 'Popravilo končano',
        'body' => 'Vaša zahteva za popravilo na planetu :planet je bila zaključena. 
:ship_count Ladje so ponovno začele obratovati.',
    ],
];
