<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : es (OGame: es)
 * Source   : resources/lang/en/t_external.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'browser_warning' => [
        'title' => 'Su navegador no está actualizado.',
        'desc1' => 'Su versión de Internet Explorer no se corresponde con los estándares existentes y ya no es compatible con este sitio web.',
        'desc2' => 'Para utilizar este sitio web, actualice su navegador web a una versión actual o utilice otro navegador web. Si ya está utilizando la última versión, vuelva a cargar la página para mostrarla correctamente.',
        'desc3' => 'Aquí hay una lista de los navegadores más populares. Haga clic en uno de los símbolos para acceder a la página de descarga:',
    ],
    'login' => [
        'page_title' => 'OGame - Conquista el universo',
        'btn' => 'Acceso',
        'email_label' => 'Dirección de correo electrónico:',
        'password_label' => 'Contraseña:',
        'universe_label' => 'Universo',
        'universe_option_1' => '1. Universo',
        'submit' => 'Acceso',
        'forgot_password' => '¿Olvidaste tu contraseña?',
        'forgot_email' => '¿Olvidaste tu dirección de correo electrónico?',
        'terms_accept_html' => 'Con el inicio de sesión acepto los <a class="" href="#" target="_blank" title="T&amp;Cs">T&Cs</a>',
    ],
    'register' => [
        'play_free' => '¡JUEGA GRATIS!',
        'email_label' => 'Dirección de correo electrónico:',
        'password_label' => 'Contraseña:',
        'universe_label' => 'Universo',
        'distinctions' => 'Distinciones',
        'terms_html' => 'Nuestros <a class="" target="_blank" href="#" title="T&amp;Cs"> Términos y condiciones </a> y <a class="" target="_blank" href="#" title="Política de privacidad"> Política de privacidad </a> se aplican en el juego.',
        'submit' => 'Registro',
    ],
    'nav' => [
        'home' => 'Hogar',
        'about' => 'Acerca de OGame',
        'media' => 'Medios de comunicación',
        'wiki' => 'wiki',
    ],
    'home' => [
        'title' => 'OGame - Conquista el universo',
        'description_html' => '<em>OGame</em> es un juego de estrategia ambientado en el espacio, en el que miles de jugadores de todo el mundo compiten al mismo tiempo. Sólo necesitas un navegador web normal para jugar.',
        'board_btn' => 'Tablero',
        'trailer_title' => 'Tráiler',
    ],
    'footer' => [
        'legal' => 'Aviso legal',
        'privacy_policy' => 'política de privacidad',
        'terms' => 'Términos y condiciones',
        'contact' => 'Contacto',
        'rules' => 'Reglas',
        'copyright' => '© OGameX. Reservados todos los derechos.',
    ],
    'js' => [
        'login' => 'Acceso',
        'close' => 'Cerrar',
        'age_check_failed' => 'Lo sentimos, pero no eres elegible para registrarte. Consulte nuestros T&C para obtener más información.',
    ],
    'validation' => [
        'required' => 'Este campo es obligatorio',
        'make_decision' => 'tomar una decisión',
        'accept_terms' => 'Debes aceptar las T&C.',
        'length' => 'Se permiten entre 3 y 20 caracteres.',
        'pw_length' => 'Se permiten entre 4 y 20 caracteres.',
        'email' => '¡Debes ingresar una dirección de correo electrónico válida!',
        'invalid_chars' => 'Contiene caracteres no válidos.',
        'no_begin_end_underscore' => 'Su nombre no puede comenzar ni terminar con un guión bajo.',
        'no_begin_end_whitespace' => 'Su nombre no puede comenzar ni terminar con un espacio.',
        'max_three_underscores' => 'Su nombre no puede contener más de 3 guiones bajos en total.',
        'max_three_whitespaces' => 'Su nombre no podrá incluir más de 3 espacios en total.',
        'no_consecutive_underscores' => 'No puedes utilizar dos o más guiones bajos uno tras otro.',
        'no_consecutive_whitespaces' => 'No se pueden utilizar dos o más espacios uno tras otro.',
        'username_available' => 'Este nombre de usuario está disponible.',
        'username_loading' => 'Por favor espera, cargando...',
        'username_taken' => 'Este nombre de usuario ya no está disponible.',
        'only_letters' => 'Utilice únicamente caracteres.',
    ],
    'forgot_password' => [
        'title' => '¿Olvidaste tu contraseña?',
        'description' => 'Ingrese su dirección de correo electrónico a continuación y le enviaremos un enlace para restablecer su contraseña.',
        'email_label' => 'Dirección de correo electrónico:',
        'submit' => 'Enviar enlace de reinicio',
        'back_to_login' => '← Volver al inicio de sesión',
    ],
    'reset_password' => [
        'title' => 'Restablece tu contraseña',
        'email_label' => 'Dirección de correo electrónico:',
        'password_label' => 'Nueva contraseña:',
        'confirm_label' => 'Confirmar nueva contraseña:',
        'submit' => 'Restablecer contraseña',
    ],
    'forgot_email' => [
        'title' => '¿Olvidaste tu dirección de correo electrónico?',
        'description' => 'Ingrese el nombre de su comandante y le enviaremos una pista a la dirección de correo electrónico registrada.',
        'username_label' => 'Nombre del comandante:',
        'submit' => 'Enviar pista',
        'back_to_login' => '← Volver al inicio de sesión',
        'sent' => 'Si se encontró una cuenta coincidente, se envió una pista a la dirección de correo electrónico registrada.',
    ],
    'mail' => [
        'reset_password' => [
            'subject' => 'Restablece tu contraseña de OGameX',
            'heading' => 'Restablecer contraseña',
            'greeting' => 'Hola: nombre de usuario,',
            'body' => 'Recibimos una solicitud para restablecer la contraseña de su cuenta. Haga clic en el botón a continuación para elegir una nueva contraseña.',
            'cta' => 'Restablecer contraseña',
            'expiry' => 'Este enlace caducará en 60 minutos.',
            'no_action' => 'Si no solicitó un restablecimiento de contraseña, no es necesario realizar ninguna otra acción.',
            'url_fallback' => 'Si tiene problemas para hacer clic en el botón, copie y pegue la siguiente URL en su navegador:',
        ],
        'retrieve_email' => [
            'subject' => 'Su dirección de correo electrónico de OGameX',
            'heading' => 'Sugerencia de dirección de correo electrónico',
            'greeting' => 'Hola: nombre de usuario,',
            'body' => 'Solicitó una pista para la dirección de correo electrónico asociada con su cuenta:',
            'cta' => 'Ir a Iniciar sesión',
            'no_action' => 'Si no realizó esta solicitud, puede ignorar este correo electrónico con seguridad.',
        ],
    ],
    'universe_characteristics' => [
        'fleet_speed' => 'Velocidad de flota: cuanto mayor sea el valor, menos tiempo te quedará para reaccionar ante un ataque.',
        'economy_speed' => 'Velocidad económica: cuanto mayor sea el valor, más rápido se completarán las construcciones, las investigaciones y se reunirán los recursos.',
        'debris_ships' => 'Algunos de los barcos destruidos en batalla entrarán en el campo de escombros.',
        'debris_defence' => 'Algunas de las estructuras defensivas destruidas en la batalla entrarán en el campo de escombros.',
        'dark_matter_gift' => 'Recibirás Dark Matter como recompensa por confirmar tu dirección de correo electrónico.',
        'aks_on' => 'Sistema de batalla de la Alianza activado',
        'planet_fields' => 'Se ha aumentado la cantidad máxima de espacios de construcción.',
        'wreckfield' => 'Muelle espacial activado: algunas naves destruidas se pueden restaurar usando el Muelle espacial.',
        'universe_big' => 'Cantidad de galaxias en el universo',
    ],
];
