<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : zh_TW (OGame: tw)
 * Source   : resources/lang/en/t_facilities.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'space_dock' => [
        'name' => '宇宙港',
        'description' => '艦隊遺骸可在宇宙港內被修復.',
        'description_long' => '太空船塢提供了修復在戰鬥中被摧毀並留下殘骸的船隻的可能性。 修復時間最多需要12個小時，但至少需要30分鐘才能讓船隻重新投入使用。 

由於太空船塢漂浮在軌道上，因此不需要行星場。',
        'requirements' => '需要造船廠等級 2',
        'field_consumption' => '不消耗行星場（漂浮在軌道上）',
        'wreck_field_section' => '沉船場',
        'no_wreck_field' => '該位置沒有可用的沉船場。',
        'wreck_field_info' => '沉船場內有可以修復的船隻。',
        'ships_available' => '可供維修的船舶：{count}',
        'repair_capacity' => '基於太空船塢等級 {level} 的維修能力',
        'start_repair' => '開始修復沉船場',
        'repair_in_progress' => '修復工作正在進行中',
        'repair_completed' => '維修完成',
        'deploy_ships' => '部署修復後的船隻',
        'burn_wreck_field' => '燒毀殘骸場',
        'repair_time' => '預計修復時間：{time}',
        'repair_progress' => '修復進度：{progress}%',
        'completion_time' => '完成：{時間}',
        'auto_deploy_warning' => '如果不手動部署，船舶將在修復完成後 {hours} 小時自動部署。',
        'level_effects' => [
            'repair_speed' => '修復速度提高 {bonus}%',
            'capacity_increase' => '最大可修復船數量增加',
        ],
        'status' => [
            'no_dock' => '修復沉船殘骸需要太空船塢',
            'level_too_low' => '修復殘骸區域需要 1 級太空船塢',
            'no_wreck_field' => '沒有可用的沉船場',
            'repairing' => '目前正在修復沉船場',
            'ready_to_deploy' => '維修完成，船舶準備部署',
        ],
    ],
    'actions' => [
        'build' => '建造',
        'upgrade' => '升級到等級 {level}',
        'downgrade' => '降級至等級 {level}',
        'demolish' => '拆除',
        'cancel' => '取消',
    ],
    'requirements' => [
        'met' => '滿足要求',
        'not_met' => '未滿足要求',
        'research' => '研究：{要求}',
        'building' => '建築：{要求} 等級 {level}',
    ],
    'cost' => [
        'metal' => '金屬：{數量}',
        'crystal' => '水晶：{數量}',
        'deuterium' => '氘：{數量}',
        'energy' => '能量：{數量}',
        'dark_matter' => '暗物質：{數量}',
        'total' => '總費用：{金額}',
    ],
    'construction_time' => '施工時間：{時間}',
    'upgrade_time' => '升級時間：{time}',
];
