<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : zh_TW (OGame: tw)
 * Source   : resources/lang/en/t_messages.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'welcome_message' => [
        'from' => '奧遊戲X',
        'subject' => '歡迎來到OGameX！',
        'body' => '皇帝陛下您好：玩家！ 

恭喜您開始輝煌的職業生涯。 我將在這裡指導您完成您的第一步。 

在左邊你可以看到菜單，它允許你監督和管理你的銀河帝國。 

您已經看過概述。 資源和設施允許您建造建築物來幫助您擴展您的帝國。 首先建造一座太陽能發電廠來為您的礦場收集能量。 

然後擴展您的金屬礦和水晶礦以生產重要資源。 否則，就自己四處看看吧。 我相信你很快就會在家裡感覺良好。 

您可以在這裡找到更多幫助、提示和策略：

Discord 聊天：Discord 伺服器
論壇：OGameX 論壇
支援： 遊戲支援

您只能在論壇中找到遊戲的最新公告和更改。 


現在您已為未來做好準備。 祝你好運！ 

此訊息將在 7 天後刪除。',
    ],
    'return_of_fleet_with_resources' => [
        'from' => '艦隊司令部',
        'subject' => '艦隊歸來',
        'body' => '您的車隊正在從 :from 返回 :to 並交付貨物：

金屬: :金屬
水晶: :水晶
氘: :氘',
    ],
    'return_of_fleet' => [
        'from' => '艦隊司令部',
        'subject' => '艦隊歸來',
        'body' => '您的艦隊將從 :from 返回 :to。 

車隊不運送貨物。',
    ],
    'fleet_deployment_with_resources' => [
        'from' => '艦隊司令部',
        'subject' => '艦隊歸來',
        'body' => '您的一支艦隊已從 :from 到達 :to 並交付了貨物：

金屬: :金屬
水晶: :水晶
氘: :氘',
    ],
    'fleet_deployment' => [
        'from' => '艦隊司令部',
        'subject' => '艦隊歸來',
        'body' => '您的一支艦隊從 :from 已到達 :to。 車隊不運送貨物。',
    ],
    'transport_arrived' => [
        'from' => '艦隊司令部',
        'subject' => '到達一個星球',
        'body' => '您的車隊從 :from 到達 :to 並交付貨物：
金屬: :金屬 結晶: :水晶 氘: :氘',
    ],
    'transport_received' => [
        'from' => '艦隊司令部',
        'subject' => '進港機隊',
        'body' => '來自 :from 的進港艦隊已抵達您的星球 :to 並交付了貨物：
金屬: :金屬 結晶: :水晶 氘: :氘',
    ],
    'acs_defend_arrival_host' => [
        'from' => '空間監控',
        'subject' => '艦隊正在停止',
        'body' => '一支艦隊已抵達：to。',
    ],
    'acs_defend_arrival_sender' => [
        'from' => '艦隊司令部',
        'subject' => '艦隊正在停止',
        'body' => '一支艦隊已抵達：to。',
    ],
    'colony_established' => [
        'from' => '艦隊司令部',
        'subject' => '結算報告',
        'body' => '艦隊已抵達指定座標：座標，在那裡發現了一顆新行星，並立即開始在其上發展。',
    ],
    'colony_establish_fail_astrophysics' => [
        'from' => '定居者',
        'subject' => '結算報告',
        'body' => '艦隊已抵達指定座標：座標並確定星球適合殖民。 在開始開發星球後不久，殖民者意識到他們的天文物理知識不足以完成新星球的殖民。',
    ],
    'espionage_report' => [
        'from' => '艦隊司令部',
        'subject' => '來自 :planet 的間諜報告',
    ],
    'espionage_detected' => [
        'from' => '艦隊司令部',
        'subject' => '來自星球的間諜報告：星球',
        'body' => '在您的星球附近發現了來自行星 :planet (:attacker_name) 的外國艦隊
：後衛
反間諜幾率：:chance%',
    ],
    'battle_report' => [
        'from' => '艦隊司令部',
        'subject' => '戰鬥報告：星球',
    ],
    'fleet_lost_contact' => [
        'from' => '艦隊司令部',
        'subject' => '與攻擊艦隊的聯繫已失去。 ：座標',
        'body' => '（這意味著它在第一輪就被摧毀了。）',
    ],
    'debris_field_harvest' => [
        'from' => '艦隊',
        'subject' => 'DF 的收穫報告：座標',
        'body' => '您的 :ship_name (:ship_amount 船舶) 的總儲存容量為 :storage_capacity。 在目標 :to、:metal 金屬、:crystal 水晶和 :deuterium 氘漂浮在太空中。 您已收穫 :harvested_metal 金屬、:harvested_crystal 水晶和 :harvested_deuterium 氘。',
    ],
    'expedition_resources_captured' => ':resource_type :resource_amount 已被捕獲。',
    'expedition_dark_matter_captured' => '(:dark_matter_amount 暗物質)',
    'expedition_units_captured' => '以下船隻現已成為艦隊的一部分：',
    'expedition_unexplored_statement' => '通訊官員日誌中的條目：看來宇宙的這一部分還沒有被探索過。',
    'expedition_failed' => [
        'from' => '艦隊司令部',
        'subject' => '探險結果',
        'body' => [
            '1' => '由於旗艦的中央計算機故障，探險任務不得不中止。 不幸的是，由於電腦故障，艦隊空手而歸。',
            '2' => '您的探險隊差點陷入中子星引力場，需要一些時間才能擺脫束縛。 因此消耗了大量的氘，探險艦隊只能無功而返。',
            '3' => '由於未知的原因，探險隊的跳躍完全出錯了。 它幾乎落在了一顆太陽的中心。 幸運的是，它降落在一個已知的系統中，但跳回所需的時間將比想像的要長。',
            '4' => '旗艦反應器核心的故障幾乎摧毀了整個探險艦隊。 幸運的是，技術人員非常有能力，可以避免最壞的情況。 修復工作花費了相當長的時間，迫使探險隊未能完成目標而返回。',
            '5' => '一個純粹能量構成的生命體登上了飛船，讓所有探險隊員陷入了一種奇怪的恍惚狀態，讓他們只能盯著電腦螢幕上催眠的圖案。 當他們中的大多數人最終從催眠狀態中清醒過來時，探險任務需要中止，因為他們的氘太少了。',
            '6' => '新的導航模組仍然有問題。 探險隊的跳躍不僅將他們引向錯誤的方向，而且還耗盡了所有的氘燃料。 幸運的是，艦隊的跳躍使他們接近了出發行星的衛星。 有點失望的是，探險隊現在返回時沒有動力。 回程時間將比預期更長。',
            '7' => '你的探險隊已經了解了廣闊的太空。 甚至沒有一顆小行星、輻射或粒子能讓這次探險變得有趣。',
            '8' => '好吧，現在我們知道那些紅色的 5 級異常不僅會對船舶導航系統產生混亂影響，還會對船員產生巨大的幻覺。 這次探險沒有帶回任何東西。',
            '9' => '您的探險隊拍攝了超新星的精美照片。 這次探險並沒有帶來什麼新的收穫，但至少有很好的機會贏得下個月出版的《OGame》雜誌的「宇宙最佳圖片」競賽。',
            '10' => '一段時間以來，你的探險艦隊一直遵循著奇怪的訊號。 最後，他們注意到這些訊號是從一個舊探測器發出的，該探測器是幾代前發出的，用於迎接外來物種。 探測器被保存下來了，你們家鄉的一些博物館已經表達了他們的興趣。',
            '11' => '儘管對該區域進行了第一次非常有希望的掃描，但不幸的是我們空手而歸。',
            '12' => '除了一些來自未知沼澤星球的古怪小寵物外，這次探險並沒有帶來任何令人興奮的東西。',
            '13' => '探險隊的旗艦在沒有任何警告的情況下跳入艦隊，與一艘外國船隻相撞。 外國船隻爆炸，旗艦受損嚴重。 在這種情況下探險無法繼續，因此一旦進行了必要的維修，艦隊將開始返回。',
            '14' => '我們的探險隊發現了一個很久以前就被遺棄的奇怪殖民地。 著陸後，我們的機組人員開始出現由外來病毒引起的高燒。 據了解，這種病毒消滅了地球上的整個文明。 我們的探險隊正在回家治療生病的船員。 不幸的是我們不得不中止任務，我們空手而歸。',
            '15' => '與我們的家庭系統分離後不久，一種奇怪的電腦病毒就攻擊了導航系統。 這讓遠徵艦隊繞圈圈。 不用說，這次探險並沒有真正成功。',
        ],
    ],
    'expedition_gain_resources' => [
        'from' => '艦隊司令部',
        'subject' => '探險結果',
        'body' => [
            '1' => '在一顆孤立的小行星上，我們發現了一些容易到達的資源田，並成功收穫了一些。',
            '2' => '你的探險隊發現了一顆小行星，可以從中獲得一些資源。',
            '3' => '你的探險隊發現了一個古老的、滿載但廢棄的貨輪船隊。 一些資源可以被拯救。',
            '4' => '你的探險艦隊報告發現了一艘巨大的外星沉船殘骸。 他們無法從他們的技術中學習，但他們能夠將船分成主要部件，並從中獲得一些有用的資源。',
            '5' => '在一顆擁有自己大氣層的小衛星上，您的探險隊發現了一些龐大的原料儲存庫。 地面上的工作人員正在嘗試抬起並裝載這一天然寶藏。',
            '6' => '一顆未知星球周圍的礦帶蘊藏著無數的資源。 探險船回來了，倉庫已經滿了！',
        ],
    ],
    'expedition_gain_dark_matter' => [
        'from' => '艦隊司令部',
        'subject' => '探險結果',
        'body' => [
            '1' => '探險隊追蹤到了一顆小行星的一些奇怪訊號。 在小行星核心中發現了少量暗物質。 小行星被奪走，探險家正試圖提取暗物質。',
            '2' => '這次探險隊捕獲並儲存了一些暗物質。',
            '3' => '我們在一艘小船上的架子上遇到了一個奇怪的外星人，他給了我們一個裝有暗物質的箱子，以換取一些簡單的數學計算。',
            '4' => '我們發現了一艘外星飛船的殘骸。 我們在貨艙的架子上發現了一個裝有一些暗物質的小容器！',
            '5' => '我們的探險隊第一次接觸到了一個特殊的種族。 看起來就像是一個由純粹能量組成的生物，自稱為勒格里安，飛過探險船，然後決定幫助我們不發達的物種。 一個裝有暗物質的箱子出現在船橋上！',
            '6' => '我們的探險隊佔領了一艘運送少量暗物質的幽靈船。 我們沒有發現任何關於這艘船的原始船員發生了什麼的線索，但我們的技術人員能夠營救暗物質。',
            '7' => '我們的探險隊完成了一項獨特的實驗。 他們能夠從垂死的恆星中收穫暗物質。',
            '8' => '我們的探險隊發現了一個生鏽的太空站，它似乎在外太空不受控制地漂浮了很長時間。 該太空站本身完全無用，然而，人們發現反應爐中儲存了一些暗物質。 我們的技術人員正在盡力節省開支。',
        ],
    ],
    'expedition_gain_ships' => [
        'from' => '艦隊司令部',
        'subject' => '探險結果',
        'body' => [
            '1' => '我們的探險隊發現了一顆在一系列戰爭中幾乎被摧毀的星球。 軌道上漂浮著不同的船隻。 技術人員正在嘗試修復其中一些。 也許我們還會得到有關這裡發生的事情的資訊。',
            '2' => '我們發現了一個廢棄的海盜站。 機庫裡躺著一些舊船。 我們的技術人員正在弄清楚其中一些是否仍然有用。',
            '3' => '你的探險隊遇到了一個很久以前就被遺棄的殖民地的造船廠。 在造船廠的機庫中，他們發現了一些可以打撈的船隻。 技術人員正在努力讓其中一些再次飛行。',
            '4' => '我們發現了之前探險隊的遺跡！ 我們的技術人員將嘗試讓部分船隻重新投入使用。',
            '5' => '我們的探險隊遇到了一個古老的自動造船廠。 一些船舶仍處於生產階段，我們的技術人員目前正在嘗試重新啟動船廠的發電機。',
            '6' => '我們發現了一支無敵艦隊的殘骸。 技術人員直接前往幾乎完好無損的船隻上，試圖讓它們重新工作。',
            '7' => '我們發現了一個已滅絕文明的星球。 我們能夠看到一個巨大的完整空間站，正在軌道上運行。 你們的一些技術人員和飛行員前往地面尋找仍然可以使用的船隻。',
        ],
    ],
    'expedition_gain_item' => [
        'from' => '艦隊司令部',
        'subject' => '探險結果',
        'body' => [
            '1' => '一支逃跑的艦隊留下了一件物品，目的是為了分散我們的注意力，幫助他們逃跑。',
        ],
    ],
    'expedition_failed_and_speedup' => [
        'from' => '艦隊司令部',
        'subject' => '探險結果',
        'body' => [
            '1' => '您的探險隊沒有報告已探索區域的任何異常情況。 但艦隊在返回時遇到了一些太陽風。 這導致回程加快。 您的探險隊提前返回家園。',
            '2' => '勇敢的新指揮官成功穿越不穩定的蟲洞，縮短了回程時間！ 然而，這次探險本身並沒有帶來任何新東西。',
            '3' => '引擎能量軸中意外的後耦合加速了探險隊的返回，它比預期更早返回。 第一份報告顯示，他們沒有任何令人興奮的事情可以解釋。',
        ],
    ],
    'expedition_failed_and_delay' => [
        'from' => '艦隊司令部',
        'subject' => '探險結果',
        'body' => [
            '1' => '你的探險隊進入了一個充滿粒子風暴的區域。 這使得能量儲存器過載，並且大多數船舶的主要係統崩潰。 你的機械師能夠避免最壞的情況，但探險隊的返回將會有很長的延遲。',
            '2' => '你的航海家在計算中犯了一個嚴重錯誤，導致探險隊的跳躍被錯誤計算。 艦隊不僅完全偏離了目標，而且返程所需的時間也比原計劃要長很多。',
            '3' => '紅巨星的太陽風破壞了遠徵跳躍，需要相當長的時間來計算返回跳躍。 那個區域除了星辰之間的虛空之外什麼也沒有。 艦隊返回時間將比預期晚。',
        ],
    ],
    'expedition_battle' => [
        'from' => '艦隊司令部',
        'subject' => '探險結果',
        'body' => [
            '1' => '一些原始野蠻人正在用甚至無法命名的太空船攻擊我們。 如果火勢嚴重，我們將被迫還擊。',
            '2' => '我們需要與一些海盜作戰，幸運的是，海盜只是少數。',
            '3' => '我們收到了一些醉酒海盜的無線電通訊。 看來我們很快就會受到攻擊。',
            '4' => '我們的探險隊遭到了一小群不明船隻的攻擊！',
            '5' => '一些真正絕望的太空海盜試圖捕獲我們的遠徵艦隊。',
            '6' => '一些外型奇特的船隻在毫無預警的情況下襲擊了遠徵艦隊！',
            '7' => '您的探險艦隊與未知物種進行了不友善的首次接觸。',
        ],
    ],
    'expedition_battle_pirates' => [
        'from' => '艦隊司令部',
        'subject' => '探險結果',
        'body' => [
            '1' => '一些原始野蠻人正在用甚至無法命名的太空船攻擊我們。 如果火勢嚴重，我們將被迫還擊。',
            '2' => '我們需要與一些海盜作戰，幸運的是，海盜只是少數。',
            '3' => '我們收到了一些醉酒海盜的無線電通訊。 看來我們很快就會受到攻擊。',
            '4' => '我們的探險隊遭到了一小群太空海盜的襲擊！',
            '5' => '一些真正絕望的太空海盜試圖捕獲我們的遠徵艦隊。',
            '6' => '海盜毫無預警地伏擊了遠徵艦隊！',
            '7' => '一群烏合之眾的太空海盜艦隊攔截了我們，要求進貢。',
        ],
    ],
    'expedition_battle_aliens' => [
        'from' => '艦隊司令部',
        'subject' => '探險結果',
        'body' => [
            '1' => '我們從未知的船隻上收到了奇怪的信號。 原來他們是敵對的！',
            '2' => '一支外星巡邏隊發現了我們的遠徵艦隊，立即發動攻擊！',
            '3' => '您的探險艦隊與未知物種進行了不友善的首次接觸。',
            '4' => '一些外型奇特的船隻在毫無預警的情況下襲擊了遠徵艦隊！',
            '5' => '一支外星戰艦艦隊從超空間中出現並與我們交戰！',
            '6' => '我們遇到了一個技術先進但並不和平的外來物種。',
            '7' => '在外星飛船攻擊之前，我們的感測器偵測到了未知的能量訊號！',
        ],
    ],
    'expedition_loss_of_fleet' => [
        'from' => '艦隊司令部',
        'subject' => '探險結果',
        'body' => [
            '1' => '領頭艦的核心熔毀導致連鎖反應，在一場壯觀的爆炸中摧毀了整個探險艦隊。',
        ],
    ],
    'expedition_merchant_found' => [
        'from' => '艦隊司令部',
        'subject' => '探險結果',
        'body' => [
            '1' => '你的探險艦隊與一個友善的外星種族取得了聯繫。 他們宣布將派出一名代表帶著貨物到你們的世界交易。',
            '2' => '一艘神秘的商船接近你的探險隊。 交易者提出訪問你們的行星並提供特殊的交易服務。',
            '3' => '探險隊遇到了一支星際商船隊。 其中一位商人同意訪問您的家鄉以提供交易機會。',
        ],
    ],
    'buddy_request_received' => [
        'from' => '好友名單',
        'subject' => '交友請求',
        'body' => '您收到了來自 :sender_name 的新好友請求。 <span style="display:none;">:buddy_request_id</span>',
    ],
    'buddy_request_accepted' => [
        'from' => '好友名單',
        'subject' => '好友請求已接受',
        'body' => '玩家 :accepter_name 將您加入他的好友清單。',
    ],
    'buddy_removed' => [
        'from' => '好友名單',
        'subject' => '您已從好友清單中刪除',
        'body' => 'Player :remover_name 將您從他們的好友清單中刪除。',
    ],
    'missile_attack_report' => [
        'from' => '艦隊司令部',
        'subject' => '對 :target_coords 的導彈攻擊',
        'body' => '您來自 :origin_planet_name :origin_planet_coords (ID: :origin_planet_id) 的星際飛彈已到達目標 :target_planet_name :target_coords (ID: :target_planet_id，類型： :target_type)。 

飛彈發射：：missiles_sent
攔截的飛彈：:missiles_intercepted
飛彈擊中：：missiles_hit

防禦被摧毀：:defenses_destroyed',
        'missile_singular' => 'missile',
        'missile_plural' => 'missiles',
        'from_your_planet' => ' from your planet ',
        'smashed_into' => ' smashed into the planet ',
        'intercepted_label' => 'Missiles Intercepted:',
        'defenses_hit_label' => 'Defenses Hit',
        'none' => 'None',
    ],
    'missile_defense_report' => [
        'from' => '國防司令部',
        'subject' => '對 :planet_coords 的飛彈攻擊',
        'body' => '您的行星 :planet_name 位於 :planet_coords (ID: :planet_id) 已被來自 :attacker_name 的星際導彈攻擊！ 

來襲飛彈：:missiles_incoming
攔截的飛彈：:missiles_intercepted
飛彈擊中：：missiles_hit

防禦被摧毀：:defenses_destroyed',
        'your_planet' => 'Your planet ',
        'attacked_by_prefix' => ' has been attacked by interplanetary missiles from ',
        'incoming_label' => 'Incoming Missiles:',
        'intercepted_label' => 'Missiles Intercepted:',
        'defenses_hit_label' => 'Defenses Hit',
        'none' => 'None',
    ],
    'alliance_broadcast' => [
        'from' => ':寄件人姓名',
        'subject' => '[:alliance_tag] 來自 :sender_name 的聯盟廣播',
        'body' => ':訊息',
    ],
    'alliance_application_received' => [
        'from' => '聯盟管理',
        'subject' => '新聯盟申請',
        'body' => '玩家：applicant_name 已申請加入您的聯盟。 

申請留言：
:應用程式訊息',
    ],
    'planet_relocation_success' => [
        'from' => '管理殖民地',
        'subject' => ':planet_name的搬遷已成功',
        'body' => '行星 :planet_name 已成功從座標 [座標]:舊座標[/座標] 重新定位到 [座標]:新座標[/座標]。',
    ],
    'fleet_union_invite' => [
        'from' => '艦隊司令部',
        'subject' => '邀請參加聯盟戰鬥',
        'body' => ':sender_name 邀請您在 [:target_coords] 上執行 :union_name 對抗 :target_player 的任務，艦隊已計時為 :arrival_time。 

注意：到達時間可能會因加入車隊而改變。 每個新艦隊最多可以延長30%的時間，否則將不被允許加入。 

注意：所有參與者的總實力與防禦者的總​​實力相比，決定了這是否是一場光榮的戰鬥。',
    ],
    'Shipyard is being upgraded.' => '造船廠正在進行升級改造。',
    'Nanite Factory is being upgraded.' => '奈米工廠正在升級。',
    'moon_destruction_success' => [
        'from' => '艦隊司令部',
        'subject' => '月亮 :moon_name [:moon_coords] 已被摧毀！',
        'body' => '摧毀機率為 :destruction_chance 且死星損失機率為 :loss_chance，您的艦隊已成功摧毀位於 :moon_coords 的衛星 :moon_name。',
    ],
    'moon_destruction_failure' => [
        'from' => '艦隊司令部',
        'subject' => '月亮毀滅：moon_coords 失敗',
        'body' => '由於毀滅機率為 :destruction_chance 且死星損失機率為 :loss_chance，你的艦隊未能摧毀位於 :moon_coords 的月球 :moon_name 。 艦隊正在返回。',
    ],
    'moon_destruction_catastrophic' => [
        'from' => '艦隊司令部',
        'subject' => '月球毀滅期間的災難性損失：moon_coords',
        'body' => '由於毀滅機率為 :destruction_chance 且死星損失機率為 :loss_chance，你的艦隊未能摧毀位於 :moon_coords 的月球 :moon_name 。 此外，所有死星都在這次嘗試中損失殆盡。 沒有殘骸。',
    ],
    'moon_destruction_mission_failed' => [
        'from' => '艦隊司令部',
        'subject' => '月球毀滅任務失敗於：座標',
        'body' => '您的艦隊到達：座標，但在目標位置沒有發現月亮。 艦隊正在返回。',
    ],
    'moon_destruction_repelled' => [
        'from' => '空間監控',
        'subject' => '對月球的破壞企圖：moon_name [:moon_coords] 被擊退',
        'body' => ':attacker_name 在 :moon_coords 攻擊了你的衛星 :moon_name，破壞機率為 :destruction_chance，死星損失機率為 :loss_chance。 你的月亮在攻擊中倖存下來了！',
    ],
    'moon_destroyed' => [
        'from' => '空間監控',
        'subject' => '月亮 :moon_name [:moon_coords] 已被摧毀！',
        'body' => '您位於 :moon_coords 的衛星 :moon_name 已被屬於 :attacker_name 的死亡之星艦隊摧毀！',
    ],
    'wreck_field_repair_completed' => [
        'from' => '系統訊息',
        'subject' => '修復完成',
        'body' => '您對 Planet :planet 的維修請求已完成。 
:ship_count 艘船舶已重新投入使用。',
    ],
];
