<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : sv (OGame: se)
 * Source   : resources/lang/en/t_external.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'browser_warning' => [
        'title' => 'Din webbläsare är inte uppdaterad.',
        'desc1' => 'Din Internet Explorer-version motsvarar inte befintliga standarder och stöds inte längre av denna webbplats.',
        'desc2' => 'För att använda denna webbplats, uppdatera din webbläsare till en aktuell version eller använd en annan webbläsare. Om du redan använder den senaste versionen, ladda om sidan för att visa den korrekt.',
        'desc3' => 'Här är en lista över de mest populära webbläsarna. Klicka på en av symbolerna för att komma till nedladdningssidan:',
    ],
    'login' => [
        'page_title' => 'OGame - Erövra universum',
        'btn' => 'Inloggning',
        'email_label' => 'E-postadress:',
        'password_label' => 'Lösenord:',
        'universe_label' => 'Universum',
        'universe_option_1' => '1. Universum',
        'submit' => 'Logga in',
        'forgot_password' => 'Glömt ditt lösenord?',
        'forgot_email' => 'Har du glömt din e-postadress?',
        'terms_accept_html' => 'Med inloggningen accepterar jag <a class="" href="#" target="_blank" title="T&amp;Cs">T&amp;Cs</a>',
    ],
    'register' => [
        'play_free' => 'SPELA GRATIS!',
        'email_label' => 'E-postadress:',
        'password_label' => 'Lösenord:',
        'universe_label' => 'Universum',
        'distinctions' => 'Distinktioner',
        'terms_html' => 'Våra <a class="" target="_blank" href="#" title="T&amp;Cs"> T&amp;Cs </a> och <a class="" target="_blank" href="#" title="Sekretesspolicy"> Sekretesspolicy </a> gäller i spelet',
        'submit' => 'Register',
    ],
    'nav' => [
        'home' => 'Hem',
        'about' => 'Om OGame',
        'media' => 'Media',
        'wiki' => 'Wiki',
    ],
    'home' => [
        'title' => 'OGame - Erövra universum',
        'description_html' => '<em>OGame</em> är ett strategispel som utspelar sig i rymden, med tusentals spelare från hela världen som tävlar samtidigt. Du behöver bara en vanlig webbläsare för att spela.',
        'board_btn' => 'Styrelse',
        'trailer_title' => 'Trailer',
    ],
    'footer' => [
        'legal' => 'Om oss',
        'privacy_policy' => 'Sekretesspolicy',
        'terms' => 'Villkor',
        'contact' => 'Kontakta',
        'rules' => 'Regler',
        'copyright' => '© OGameX. Alla rättigheter reserverade.',
    ],
    'js' => [
        'login' => 'Inloggning',
        'close' => 'Nära',
        'age_check_failed' => 'Vi är ledsna, men du är inte berättigad att registrera dig. Se våra allmänna villkor för mer information.',
    ],
    'validation' => [
        'required' => 'Detta fält är obligatoriskt',
        'make_decision' => 'Fatta ett beslut',
        'accept_terms' => 'Du måste acceptera villkoren.',
        'length' => 'Mellan 3 och 20 tecken tillåtna.',
        'pw_length' => 'Mellan 4 och 20 tecken tillåtna.',
        'email' => 'Du måste ange en giltig e-postadress!',
        'invalid_chars' => 'Innehåller ogiltiga tecken.',
        'no_begin_end_underscore' => 'Ditt namn får inte börja eller sluta med ett understreck.',
        'no_begin_end_whitespace' => 'Ditt namn får inte börja eller sluta med ett mellanslag.',
        'max_three_underscores' => 'Ditt namn får inte innehålla mer än 3 understreck totalt.',
        'max_three_whitespaces' => 'Ditt namn får inte innehålla mer än 3 blanksteg totalt.',
        'no_consecutive_underscores' => 'Du får inte använda två eller flera understreck efter varandra.',
        'no_consecutive_whitespaces' => 'Du får inte använda två eller flera mellanslag efter varandra.',
        'username_available' => 'Detta användarnamn är tillgängligt.',
        'username_loading' => 'Vänta, laddar...',
        'username_taken' => 'Detta användarnamn är inte tillgängligt längre.',
        'only_letters' => 'Använd endast tecken.',
    ],
    'forgot_password' => [
        'title' => 'Glömt ditt lösenord?',
        'description' => 'Ange din e-postadress nedan så skickar vi en länk för att återställa ditt lösenord.',
        'email_label' => 'E-postadress:',
        'submit' => 'Skicka återställningslänk',
        'back_to_login' => '← Tillbaka till inloggning',
    ],
    'reset_password' => [
        'title' => 'Återställ ditt lösenord',
        'email_label' => 'E-postadress:',
        'password_label' => 'Nytt lösenord:',
        'confirm_label' => 'Bekräfta nytt lösenord:',
        'submit' => 'Återställ lösenord',
    ],
    'forgot_email' => [
        'title' => 'Har du glömt din e-postadress?',
        'description' => 'Ange ditt befälhavares namn så skickar vi ett tips till den registrerade e-postadressen.',
        'username_label' => 'Befälhavarens namn:',
        'submit' => 'Skicka tips',
        'back_to_login' => '← Tillbaka till inloggning',
        'sent' => 'Om ett matchande konto hittades har ett tips skickats till den registrerade e-postadressen.',
    ],
    'mail' => [
        'reset_password' => [
            'subject' => 'Återställ ditt OGameX-lösenord',
            'heading' => 'Återställ lösenord',
            'greeting' => 'Hej :användarnamn,',
            'body' => 'Vi fick en begäran om att återställa lösenordet för ditt konto. Klicka på knappen nedan för att välja ett nytt lösenord.',
            'cta' => 'Återställ lösenord',
            'expiry' => 'Den här länken upphör att gälla om 60 minuter.',
            'no_action' => 'Om du inte begärde en lösenordsåterställning krävs ingen ytterligare åtgärd.',
            'url_fallback' => 'Om du har problem med att klicka på knappen, kopiera och klistra in webbadressen nedan i din webbläsare:',
        ],
        'retrieve_email' => [
            'subject' => 'Din OGameX e-postadress',
            'heading' => 'Tips om e-postadress',
            'greeting' => 'Hej :användarnamn,',
            'body' => 'Du har begärt ett tips om e-postadressen som är kopplad till ditt konto:',
            'cta' => 'Gå till Logga in',
            'no_action' => 'Om du inte gjorde denna begäran kan du lugnt ignorera det här e-postmeddelandet.',
        ],
    ],
    'universe_characteristics' => [
        'fleet_speed' => 'Fleet Speed: ju högre värde, desto mindre tid har du kvar att reagera på en attack.',
        'economy_speed' => 'Ekonomi Hastighet: ju högre värde, desto snabbare kommer konstruktioner och forskning att slutföras och resurser samlas in.',
        'debris_ships' => 'Några av fartygen som förstördes i strid kommer in i skräpfältet.',
        'debris_defence' => 'Några av de defensiva strukturerna som förstördes i strid kommer in i skräpfältet.',
        'dark_matter_gift' => 'Du kommer att få Dark Matter som belöning för att du bekräftar din e-postadress.',
        'aks_on' => 'Alliansens stridssystem aktiverat',
        'planet_fields' => 'Det maximala antalet byggnadsplatser har ökats.',
        'wreckfield' => 'Space Dock aktiverad: vissa förstörda fartyg kan återställas med Space Dock.',
        'universe_big' => 'Antalet galaxer i universum',
    ],
];
