<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : sv (OGame: se)
 * Source   : resources/lang/en/t_messages.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'welcome_message' => [
        'from' => 'OGameX',
        'subject' => 'Välkommen till OGameX!',
        'body' => 'Hälsningar Emperor :player! 

Grattis till att du har börjat din lysande karriär. Jag kommer att vara här för att guida dig genom dina första steg. 

Till vänster kan du se menyn som låter dig övervaka och styra ditt galaktiska imperium. 

Du har redan sett översikten. Med resurser och faciliteter kan du bygga byggnader som hjälper dig att expandera ditt imperium. Börja med att bygga en solcellsanläggning för att skörda energi till dina gruvor. 

Utvidga sedan din metallgruva och kristallgruva för att producera viktiga resurser. Annars är det bara att titta runt själv. Du kommer snart att känna dig bra hemma, det är jag säker på. 

Du kan hitta mer hjälp, tips och taktik här: 

Discord Chat: Discord Server 
Forum: OGameX Forum 
Support: Spelsupport 

Du hittar bara aktuella meddelanden och ändringar av spelet i forumen. 


Nu är du redo för framtiden. Lycka till! 

Detta meddelande kommer att raderas om 7 dagar.',
    ],
    'return_of_fleet_with_resources' => [
        'from' => 'Flottans kommando',
        'subject' => 'Återlämnande av en flotta',
        'body' => 'Din flotta återvänder från :from till :to och levererade sina varor: 

Metall: :metall 
Kristall: :kristall 
Deuterium: :deuterium',
    ],
    'return_of_fleet' => [
        'from' => 'Flottans kommando',
        'subject' => 'Återlämnande av en flotta',
        'body' => 'Din flotta återvänder från :from till :to. 

Flottan levererar inga varor.',
    ],
    'fleet_deployment_with_resources' => [
        'from' => 'Flottans kommando',
        'subject' => 'Återlämnande av en flotta',
        'body' => 'En av dina flottor från :from har nått :to och levererat sina varor: 

Metall: :metall 
Kristall: :kristall 
Deuterium: :deuterium',
    ],
    'fleet_deployment' => [
        'from' => 'Flottans kommando',
        'subject' => 'Återlämnande av en flotta',
        'body' => 'En av dina flottor från :from har nått :to. Flottan levererar inte varor.',
    ],
    'transport_arrived' => [
        'from' => 'Flottans kommando',
        'subject' => 'Att nå en planet',
        'body' => 'Din flotta från :from når :to och levererar sina varor: 
Metall: :metall Kristall: :kristall Deuterium: :deuterium',
    ],
    'transport_received' => [
        'from' => 'Flottans kommando',
        'subject' => 'Inkommande flotta',
        'body' => 'En inkommande flotta från :from har nått din planet :to och levererat sina varor: 
Metall: :metall Kristall: :kristall Deuterium: :deuterium',
    ],
    'acs_defend_arrival_host' => [
        'from' => 'Rymdövervakning',
        'subject' => 'Flottan stannar',
        'body' => 'En flotta har anlänt till :to.',
    ],
    'acs_defend_arrival_sender' => [
        'from' => 'Flottans kommando',
        'subject' => 'Flottan stannar',
        'body' => 'En flotta har anlänt till :to.',
    ],
    'colony_established' => [
        'from' => 'Flottans kommando',
        'subject' => 'Avräkningsrapport',
        'body' => 'Flottan har kommit fram till de tilldelade koordinaterna:koordinater, hittat en ny planet där och börjar utvecklas på den omedelbart.',
    ],
    'colony_establish_fail_astrophysics' => [
        'from' => 'Nybyggare',
        'subject' => 'Avräkningsrapport',
        'body' => 'Flottan har kommit fram till tilldelade koordinater: koordinerar och konstaterar att planeten är livskraftig för kolonisering. Kort efter att ha börjat utveckla planeten inser kolonisterna att deras kunskap om astrofysik inte är tillräcklig för att fullborda koloniseringen av en ny planet.',
    ],
    'espionage_report' => [
        'from' => 'Flottans kommando',
        'subject' => 'Spionagerapport från :planet',
    ],
    'espionage_detected' => [
        'from' => 'Flottans kommando',
        'subject' => 'Spionagerapport från Planet :planet',
        'body' => 'En främmande flotta från planeten :planet (:attacker_name) sågs nära din planet 
:försvarare 
Risk för kontraspionage: :chance%',
    ],
    'battle_report' => [
        'from' => 'Flottans kommando',
        'subject' => 'Stridsrapport :planet',
    ],
    'fleet_lost_contact' => [
        'from' => 'Flottans kommando',
        'subject' => 'Kontakten med den attackerande flottan har tappats. :koordinater',
        'body' => '(Det betyder att den förstördes i första omgången.)',
    ],
    'debris_field_harvest' => [
        'from' => 'Flotta',
        'subject' => 'Skörderapport från DF om :koordinater',
        'body' => 'Ditt :ship_name (:ship_amount ships) har en total lagringskapacitet på :storage_capacity. Vid målet :to, :metall Metall, :kristallkristall och :deuterium svävar deuterium i rymden. Du har skördat :harvested_metal Metal, :harvested_crystal Crystal och :harvested_deuterium Deuterium.',
    ],
    'expedition_resources_captured' => ':resource_type :resource_amount har fångats.',
    'expedition_dark_matter_captured' => '(:dark_matter_amount Mörk materia)',
    'expedition_units_captured' => 'Följande fartyg ingår nu i flottan:',
    'expedition_unexplored_statement' => 'Anteckning från kommunikationsofficerarnas loggbok: Det verkar som om denna del av universum inte har utforskats ännu.',
    'expedition_failed' => [
        'from' => 'Flottans kommando',
        'subject' => 'Expeditionens resultat',
        'body' => [
            '1' => 'På grund av ett fel i flaggskeppets centrala datorer fick expeditionsuppdraget avbrytas. Tyvärr som ett resultat av datorfelet återvänder flottan hem tomhänt.',
            '2' => 'Din expedition sprang nästan in i ett gravitationsfält för neutronstjärnor och behövde lite tid för att frigöra sig. På grund av det förbrukades mycket Deuterium och expeditionsflottan fick komma tillbaka utan resultat.',
            '3' => 'Av okänd anledning gick expeditionshoppet helt fel. Den landade nästan i hjärtat av en sol. Lyckligtvis landade den i ett känt system, men hoppet tillbaka kommer att ta längre tid än tänkt.',
            '4' => 'Ett fel i flaggskeppets reaktorkärna förstör nästan hela expeditionsflottan. Lyckligtvis var teknikerna mer än kompetenta och kunde undvika det värsta. Reparationerna tog ganska lång tid och tvingade expeditionen att återvända utan att ha uppnått sitt mål.',
            '5' => 'En levande varelse gjord av ren energi kom ombord och fick alla expeditionsmedlemmar till någon konstig trans, vilket fick dem att bara titta på de hypnotiserande mönstren på datorskärmarna. När de flesta av dem äntligen tog sig ur det hypnotiska tillståndet behövde expeditionsuppdraget avbrytas eftersom de hade alldeles för lite Deuterium.',
            '6' => 'Den nya navigationsmodulen är fortfarande buggig. Expeditionshoppen leder dem inte bara åt fel håll, utan de använde allt Deuterium-bränsle. Lyckligtvis fick flottorna hoppa dem nära avgångsplanetens måne. Lite besviken återvänder nu expeditionen utan impulskraft. Återresan kommer att ta längre tid än beräknat.',
            '7' => 'Din expedition har lärt sig om rymdens omfattande tomhet. Det fanns inte ens en liten asteroid eller strålning eller partikel som kunde ha gjort denna expedition intressant.',
            '8' => 'Nåväl, nu vet vi att dessa röda, klass 5 anomalier inte bara har kaotiska effekter på fartygets navigationssystem utan också genererar massiva hallucinationer hos besättningen. Expeditionen förde inte tillbaka något.',
            '9' => 'Din expedition tog underbara bilder av en supernova. Inget nytt kunde erhållas från expeditionen, men det finns åtminstone goda chanser att vinna den där "Best Picture Of The Universe"-tävlingen i nästa månads nummer av OGame magazine.',
            '10' => 'Din expeditionsflotta följde udda signaler under en tid. I slutet märkte de att dessa signaler skickades från en gammal sond som sändes ut för generationer sedan för att hälsa på främmande arter. Sonden räddades och några museer på din hemplanet har redan uttryckt sitt intresse.',
            '11' => 'Trots de första, mycket lovande skanningarna av denna sektor, återvände vi tyvärr tomhänta.',
            '12' => 'Förutom några pittoreska, små husdjur från en okänd kärrplanet, ger den här expeditionen inget spännande tillbaka från resan.',
            '13' => 'Expeditionens flaggskepp kolliderade med ett främmande fartyg när det hoppade in i flottan utan någon förvarning. Det utländska fartyget exploderade och skadorna på flaggskeppet var betydande. Expeditionen kan inte fortsätta under dessa förhållanden, och därför kommer flottan att börja ta sig tillbaka när de nödvändiga reparationerna har utförts.',
            '14' => 'Vårt expeditionsteam stötte på en märklig koloni som hade övergivits för evigheter sedan. Efter landning började vår besättning lida av hög feber orsakad av ett främmande virus. Man har lärt sig att detta virus utplånade hela civilisationen på planeten. Vårt expeditionsteam är på väg hem för att behandla de sjuka besättningsmedlemmarna. Tyvärr var vi tvungna att avbryta uppdraget och vi kommer hem tomhänta.',
            '15' => 'Ett märkligt datavirus attackerade navigationssystemet kort efter att ha skiljt vårt hemsystem. Detta fick expeditionsflottan att flyga i cirklar. Onödigt att säga att expeditionen inte var riktigt framgångsrik.',
        ],
    ],
    'expedition_gain_resources' => [
        'from' => 'Flottans kommando',
        'subject' => 'Expeditionens resultat',
        'body' => [
            '1' => 'På en isolerad planetoid hittade vi några lättillgängliga resursfält och skördade några framgångsrikt.',
            '2' => 'Din expedition upptäckte en liten asteroid från vilken vissa resurser kunde skördas.',
            '3' => 'Din expedition hittade en gammal, fullastad men övergiven fraktkonvoj. En del av resurserna kunde räddas.',
            '4' => 'Din expeditionsflotta rapporterar upptäckten av ett gigantiskt utomjordiskt skeppsvrak. De kunde inte lära sig av sin teknik men de kunde dela upp fartyget i dess huvudkomponenter och skapade några användbara resurser av det.',
            '5' => 'På en liten måne med sin egen atmosfär hittade din expedition några enorma råresurser. Besättningen på marken försöker lyfta och lasta den naturskatten.',
            '6' => 'Mineralbälten runt en okänd planet innehöll otaliga resurser. Expeditionsfartygen kommer tillbaka och deras förråd är fulla!',
        ],
    ],
    'expedition_gain_dark_matter' => [
        'from' => 'Flottans kommando',
        'subject' => 'Expeditionens resultat',
        'body' => [
            '1' => 'Expeditionen följde några udda signaler till en asteroid. I asteroidernas kärna hittades en liten mängd mörk materia. Asteroiden togs och upptäcktsresande försöker utvinna den mörka materien.',
            '2' => 'Expeditionen kunde fånga och lagra lite mörk materia.',
            '3' => 'Vi träffade en udda utomjording på hyllan av ett litet skepp som gav oss ett fall med Dark Matter i utbyte mot några enkla matematiska beräkningar.',
            '4' => 'Vi hittade resterna av ett främmande skepp. Vi hittade en liten container med lite mörk materia på en hylla i lastrummet!',
            '5' => 'Vår expedition fick första kontakten med en speciell ras. Det ser ut som om en varelse gjord av ren energi, som kallade sig Legorian, flög genom expeditionsfartygen och sedan bestämde sig för att hjälpa vår underutvecklade art. Ett fodral med mörk materia materialiserades vid skeppets brygga!',
            '6' => 'Vår expedition tog över ett spökskepp som transporterade en liten mängd mörk materia. Vi hittade inga antydningar om vad som hände med den ursprungliga besättningen på fartyget, men våra tekniker kunde rädda den mörka materien.',
            '7' => 'Vår expedition genomförde ett unikt experiment. De kunde skörda mörk materia från en döende stjärna.',
            '8' => 'Vår expedition lokaliserade en rostig rymdstation, som verkade ha svävat okontrollerat genom yttre rymden under en lång tid. Stationen i sig var totalt värdelös, men det upptäcktes att en del mörk materia är lagrad i reaktorn. Våra tekniker försöker spara så mycket de kan.',
        ],
    ],
    'expedition_gain_ships' => [
        'from' => 'Flottans kommando',
        'subject' => 'Expeditionens resultat',
        'body' => [
            '1' => 'Vår expedition hittade en planet som nästan förstördes under en viss kedja av krig. Det finns olika skepp som flyter runt i omloppsbanan. Teknikerna försöker reparera några av dem. Kanske får vi också information om vad som hänt här.',
            '2' => 'Vi hittade en öde piratstation. Det ligger några gamla skepp i hangaren. Våra tekniker funderar på om några av dem fortfarande är användbara eller inte.',
            '3' => 'Din expedition sprang in i skeppsvarven i en koloni som var öde för evigheter sedan. I varvets hangar upptäcker de några fartyg som kunde räddas. Teknikerna försöker få några av dem att flyga igen.',
            '4' => 'Vi stötte på resterna av en tidigare expedition! Våra tekniker ska försöka få några av fartygen att fungera igen.',
            '5' => 'Vår expedition sprang in i ett gammalt automatiskt varv. Några av fartygen är fortfarande i produktionsfasen och våra tekniker försöker för närvarande att återaktivera varvets energigeneratorer.',
            '6' => 'Vi hittade resterna av en armada. Teknikerna gick direkt till de nästan intakta fartygen för att försöka få dem att fungera igen.',
            '7' => 'Vi hittade planeten för en utdöd civilisation. Vi kan se en gigantisk intakt rymdstation i omloppsbana. Några av dina tekniker och piloter gick till ytan och letade efter några fartyg som fortfarande kunde användas.',
        ],
    ],
    'expedition_gain_item' => [
        'from' => 'Flottans kommando',
        'subject' => 'Expeditionens resultat',
        'body' => [
            '1' => 'En flyende flotta lämnade ett föremål efter sig för att distrahera oss till hjälp för deras flykt.',
        ],
    ],
    'expedition_failed_and_speedup' => [
        'from' => 'Flottans kommando',
        'subject' => 'Expeditionens resultat',
        'body' => [
            '1' => 'Dina expeditioner rapporterar inga anomalier i den utforskade sektorn. Men flottan stötte på lite solvind när den återvände. Detta resulterade i att hemresan påskyndades. Din expedition kommer hem lite tidigare.',
            '2' => 'Den nya och vågade befälhavaren reste framgångsrikt genom ett instabilt maskhål för att förkorta flyget tillbaka! Expeditionen i sig förde dock inte med sig något nytt.',
            '3' => 'En oväntad bakkoppling i motorernas energispolar påskyndade expeditionens återkomst, den återvänder hem tidigare än väntat. De första rapporterna säger att de inte har något spännande att redogöra för.',
        ],
    ],
    'expedition_failed_and_delay' => [
        'from' => 'Flottans kommando',
        'subject' => 'Expeditionens resultat',
        'body' => [
            '1' => 'Din expedition gick in i en sektor full av partikelstormar. Detta gjorde att energilagren blev överbelastade och de flesta av fartygens huvudsystem kraschade. Din mekanik kunde undvika det värsta, men expeditionen kommer att återvända med en stor försening.',
            '2' => 'Din navigator gjorde ett allvarligt fel i sina beräkningar som gjorde att expeditionshoppet blev felberäknat. Inte nog med att flottan missade målet helt, utan återresan kommer att ta mycket längre tid än vad som ursprungligen planerats.',
            '3' => 'Solvinden från en röd jätte förstörde expeditionshoppet och det kommer att ta ganska lång tid att beräkna returhoppet. Det fanns ingenting förutom tomheten i rymden mellan stjärnorna i den sektorn. Flottan kommer tillbaka senare än väntat.',
        ],
    ],
    'expedition_battle' => [
        'from' => 'Flottans kommando',
        'subject' => 'Expeditionens resultat',
        'body' => [
            '1' => 'Vissa primitiva barbarer attackerar oss med rymdskepp som inte ens kan namnges som sådana. Om branden blir allvarlig kommer vi att tvingas skjuta tillbaka.',
            '2' => 'Vi behövde bekämpa några pirater som lyckligtvis bara var ett fåtal.',
            '3' => 'Vi fångade några radiosändningar från några berusade pirater. Det verkar som om vi kommer att attackeras snart.',
            '4' => 'Vår expedition attackerades av en liten grupp okända fartyg!',
            '5' => 'Några riktigt desperata rymdpirater försökte fånga vår expeditionsflotta.',
            '6' => 'Några exotiska fartyg attackerade expeditionsflottan utan förvarning!',
            '7' => 'Din expeditionsflotta hade en ovänlig första kontakt med en okänd art.',
        ],
    ],
    'expedition_battle_pirates' => [
        'from' => 'Flottans kommando',
        'subject' => 'Expeditionens resultat',
        'body' => [
            '1' => 'Vissa primitiva barbarer attackerar oss med rymdskepp som inte ens kan namnges som sådana. Om branden blir allvarlig kommer vi att tvingas skjuta tillbaka.',
            '2' => 'Vi behövde bekämpa några pirater som lyckligtvis bara var ett fåtal.',
            '3' => 'Vi fångade några radiosändningar från några berusade pirater. Det verkar som om vi kommer att attackeras snart.',
            '4' => 'Vår expedition attackerades av en liten grupp rymdpirater!',
            '5' => 'Några riktigt desperata rymdpirater försökte fånga vår expeditionsflotta.',
            '6' => 'Pirater överföll expeditionsflottan utan förvarning!',
            '7' => 'En trasig flotta av rymdpirater snappade upp oss och krävde hyllning.',
        ],
    ],
    'expedition_battle_aliens' => [
        'from' => 'Flottans kommando',
        'subject' => 'Expeditionens resultat',
        'body' => [
            '1' => 'Vi fick upp konstiga signaler från okända fartyg. De visade sig vara fientliga!',
            '2' => 'En utomjordisk patrull upptäckte vår expeditionsflotta och attackerade omedelbart!',
            '3' => 'Din expeditionsflotta hade en ovänlig första kontakt med en okänd art.',
            '4' => 'Några exotiska fartyg attackerade expeditionsflottan utan förvarning!',
            '5' => 'En flotta av främmande krigsskepp dök upp från hyperrymden och engagerade oss!',
            '6' => 'Vi mötte en tekniskt avancerad främmande art som inte var fredlig.',
            '7' => 'Våra sensorer upptäckte okända energisignaturer innan främmande skepp attackerade!',
        ],
    ],
    'expedition_loss_of_fleet' => [
        'from' => 'Flottans kommando',
        'subject' => 'Expeditionens resultat',
        'body' => [
            '1' => 'En kärnsmälta av blyskeppet leder till en kedjereaktion, som förstör hela expeditionsflottan i en spektakulär explosion.',
        ],
    ],
    'expedition_merchant_found' => [
        'from' => 'Flottans kommando',
        'subject' => 'Expeditionens resultat',
        'body' => [
            '1' => 'Din expeditionsflotta fick kontakt med en vänlig utomjordisk ras. De meddelade att de skulle skicka en representant med varor för att handla till era världar.',
            '2' => 'Ett mystiskt handelsfartyg närmade sig din expedition. Handlaren erbjöd sig att besöka dina planeter och tillhandahålla speciella handelstjänster.',
            '3' => 'Expeditionen mötte en intergalaktisk handelskonvoj. En av köpmännen har gått med på att besöka din hemvärld för att erbjuda handelsmöjligheter.',
        ],
    ],
    'buddy_request_received' => [
        'from' => 'Vänner',
        'subject' => 'Bli vän med',
        'body' => 'Du har fått en ny kompisförfrågan från :sender_name.<span style="display:none;">:buddy_request_id</span>',
    ],
    'buddy_request_accepted' => [
        'from' => 'Vänner',
        'subject' => 'Kompisförfrågan accepteras',
        'body' => 'Spelaren :accepter_name lade till dig på sin kompislista.',
    ],
    'buddy_removed' => [
        'from' => 'Vänner',
        'subject' => 'Du togs bort från en kompislista',
        'body' => 'Player :remover_name tog bort dig från sin kompislista.',
    ],
    'missile_attack_report' => [
        'from' => 'Flottans kommando',
        'subject' => 'Missil attack mot :target_coords',
        'body' => 'Dina interplanetära missiler från :origin_planet_name :origin_planet_coords (ID: :origin_planet_id) har nått sitt mål vid :target_planet_name :target_coords (ID: :target_planet_id, Typ: :target_type). 

Missiler avfyrade: :missiles_sent 
Missiler avlyssnade: :missiles_intercepted 
Missiles hit: :missiles_hit 

Försvar förstört: :defenses_destroyed',
        'missile_singular' => 'missile',
        'missile_plural' => 'missiles',
        'from_your_planet' => ' from your planet ',
        'smashed_into' => ' smashed into the planet ',
        'intercepted_label' => 'Missiles Intercepted:',
        'defenses_hit_label' => 'Defenses Hit',
        'none' => 'None',
    ],
    'missile_defense_report' => [
        'from' => 'Försvarskommando',
        'subject' => 'Missilangrepp på :planet_coords',
        'body' => 'Din planet :planet_name på :planet_coords (ID: :planet_id) har attackerats av interplanetära missiler från :attacker_name! 

Inkommande missiler: :missiles_incoming 
Missiler avlyssnade: :missiles_intercepted 
Missiles hit: :missiles_hit 

Försvar förstört: :defenses_destroyed',
        'your_planet' => 'Your planet ',
        'attacked_by_prefix' => ' has been attacked by interplanetary missiles from ',
        'incoming_label' => 'Incoming Missiles:',
        'intercepted_label' => 'Missiles Intercepted:',
        'defenses_hit_label' => 'Defenses Hit',
        'none' => 'None',
    ],
    'alliance_broadcast' => [
        'from' => ':avsändarens namn',
        'subject' => '[:alliance_tag] Allianssändning från :sender_name',
        'body' => ':meddelande',
    ],
    'alliance_application_received' => [
        'from' => 'Alliansledning',
        'subject' => 'Ny alliansansökan',
        'body' => 'Spelare :applicant_name har ansökt om att få gå med i din allians. 

Ansökan meddelande: 
:applikationsmeddelande',
    ],
    'planet_relocation_success' => [
        'from' => 'Hantera kolonier',
        'subject' => ':planet_names flytt har lyckats',
        'body' => 'Planeten :planet_name har framgångsrikt flyttats från koordinaterna [koordinater]:gamla_koordinater[/koordinater] till [koordinater]:nya_koordinater[/koordinater].',
    ],
    'fleet_union_invite' => [
        'from' => 'Flottans kommando',
        'subject' => 'Inbjudan till alliansstrid',
        'body' => ':sender_name bjöd in dig till uppdrag :union_name mot :target_player på [:target_coords], flottan har tagits tid till :arrival_time. 

FÖRSIKTIGHET: Ankomsttiden kan ändras på grund av att flottan ansluts. Varje ny flotta kan utöka denna tid med maximalt 30 %, annars kommer den inte att tillåtas att gå med. 

OBS: Den totala styrkan för alla deltagare jämfört med försvararnas totala styrka avgör om det blir en hedervärd kamp eller inte.',
    ],
    'Shipyard is being upgraded.' => 'Varvet håller på att uppgraderas.',
    'Nanite Factory is being upgraded.' => 'Nanite Factory håller på att uppgraderas.',
    'moon_destruction_success' => [
        'from' => 'Flottans kommando',
        'subject' => 'Moon :moon_name [:moon_coords] har förstörts!',
        'body' => 'Med en förstörelsesannolikhet på :destruction_chance och en Deathstar-förlustsannolikhet på :loss_chance, har din flotta framgångsrikt förstört månen :moon_name vid :moon_coords.',
    ],
    'moon_destruction_failure' => [
        'from' => 'Flottans kommando',
        'subject' => 'Månförstörelse vid :moon_coords misslyckades',
        'body' => 'Med en förstörelsesannolikhet på :destruction_chance och en Deathstar-förlustsannolikhet på :loss_chance, misslyckades din flotta med att förstöra månen :moon_name vid :moon_coords. Flottan är på väg tillbaka.',
    ],
    'moon_destruction_catastrophic' => [
        'from' => 'Flottans kommando',
        'subject' => 'Katastrofal förlust under månförstörelse vid :moon_coords',
        'body' => 'Med en förstörelsesannolikhet på :destruction_chance och en Deathstar-förlustsannolikhet på :loss_chance, misslyckades din flotta med att förstöra månen :moon_name vid :moon_coords. Dessutom gick alla Deathstars förlorade i försöket. Det finns inga vrakdelar.',
    ],
    'moon_destruction_mission_failed' => [
        'from' => 'Flottans kommando',
        'subject' => 'Uppdraget att förstöra månen misslyckades vid :koordinater',
        'body' => 'Din flotta anlände till :koordinater men ingen måne hittades på målplatsen. Flottan är på väg tillbaka.',
    ],
    'moon_destruction_repelled' => [
        'from' => 'Rymdövervakning',
        'subject' => 'Destruktionsförsök på månen :moon_name [:moon_coords] avvisades',
        'body' => ':attacker_name attackerade din måne :moon_name vid :moon_coords med en destruktionssannolikhet på :destruction_chance och en Deathstar-förlustsannolikhet på :loss_chance. Din måne har överlevt attacken!',
    ],
    'moon_destroyed' => [
        'from' => 'Rymdövervakning',
        'subject' => 'Moon :moon_name [:moon_coords] har förstörts!',
        'body' => 'Din måne :moon_name på :moon_coords har förstörts av en Deathstar-flotta som tillhör :attacker_name!',
    ],
    'wreck_field_repair_completed' => [
        'from' => 'Systemmeddelande',
        'subject' => 'Reparation slutförd',
        'body' => 'Din reparationsförfrågan på planet :planet har slutförts. 
:ship_count-fartyg har tagits i bruk igen.',
    ],
];
