<?php

/**
 * AUTO-GENERATED by generate_locales.php. DO NOT EDIT BY HAND.
 *
 * Language : sv (OGame: se)
 * Source   : resources/lang/en/t_resources.php
 * Built    : 2026-04-12T16:28:31+00:00
 */

return [
    'metal_mine' => [
        'title' => 'Metallgruva',
        'description' => 'På alla planeter, såväl nya som gamla, krävs metallgruvor för att kunna bryta metallmalm.',
        'description_long' => 'På alla planeter, såväl nya som gamla, krävs metallgruvor för att kunna bryta metallmalm.',
    ],
    'crystal_mine' => [
        'title' => 'Kristallgruva',
        'description' => 'Kristall är den huvudsakliga resursen för att kunna tillverka 
elektroniska kretskort och skapa speciella legeringar.',
        'description_long' => 'Kristall är den huvudsakliga resursen för att kunna tillverka 
elektroniska kretskort och skapa speciella legeringar.',
    ],
    'deuterium_synthesizer' => [
        'title' => 'Deuteriumplattform',
        'description' => 'Deuterium används som bränsle för rymdskeppen och skördas 
djupt nere i vattnet. Deuterium är en sällsynt substans och är mycket dyr.',
        'description_long' => 'Deuterium används som bränsle för rymdskeppen och skördas 
djupt nere i vattnet. Deuterium är en sällsynt substans och är mycket dyr.',
    ],
    'solar_plant' => [
        'title' => 'Solkraftverk',
        'description' => 'Solkraftverken absorberar solenergi. Alla gruvor behöver energi för att fungera.',
        'description_long' => 'Solkraftverken absorberar solenergi. Alla gruvor behöver energi för att fungera.',
    ],
    'fusion_plant' => [
        'title' => 'Fusionskraftverk',
        'description' => 'Fusionkraftverket använder deuterium för att producera 
energi.',
        'description_long' => 'Fusionkraftverket använder deuterium för att producera 
energi.',
    ],
    'metal_store' => [
        'title' => 'Metallager',
        'description' => 'Ger lagringsutrymme för överskottsmetall.',
        'description_long' => 'Ger lagringsutrymme för överskottsmetall.',
    ],
    'crystal_store' => [
        'title' => 'Kristallager',
        'description' => 'Ger lagringsutrymme för överskottskristall.',
        'description_long' => 'Ger lagringsutrymme för överskottskristall.',
    ],
    'deuterium_store' => [
        'title' => 'Deuteriumtank',
        'description' => 'Stora tankar för lagring av nyligen extraherad deuterium.',
        'description_long' => 'Stora tankar för lagring av nyligen extraherad deuterium.',
    ],
    'robot_factory' => [
        'title' => 'Robotfabrik',
        'description' => 'Robotfabriken tillverkar konstruktionsrobotar som assisterar 
i byggandet. Varje nivå ökar hastigheten för att bygga.',
        'description_long' => 'Robotfabriken tillverkar konstruktionsrobotar som assisterar 
i byggandet. Varje nivå ökar hastigheten för att bygga.',
    ],
    'shipyard' => [
        'title' => 'Skeppsvarv',
        'description' => 'Alla typer av skepp och försvarsbyggnader kan byggas i det planetära skeppsvarvet.',
        'description_long' => 'Alla typer av skepp och försvarsbyggnader kan byggas i det planetära skeppsvarvet.',
    ],
    'research_lab' => [
        'title' => 'Forskningslabb',
        'description' => 'Forskningslabbet är nödvändigt för att kunna forska fram nya 
teknologier.',
        'description_long' => 'Forskningslabbet är nödvändigt för att kunna forska fram nya 
teknologier.',
    ],
    'alliance_depot' => [
        'title' => 'Alliansdepå',
        'description' => 'Alliansdepån levererar bränsle till vänligt sinnade flottor som är 
i omloppsbana och hjälper till med försvaret.',
        'description_long' => 'Alliansdepån levererar bränsle till vänligt sinnade flottor som är 
i omloppsbana och hjälper till med försvaret.',
    ],
    'missile_silo' => [
        'title' => 'Missilsilo',
        'description' => 'Missilsilon används till att lagra och avfyra missiler.',
        'description_long' => 'Missilsilon används till att lagra och avfyra missiler.',
    ],
    'nano_factory' => [
        'title' => 'Nanofabrik',
        'description' => 'Detta är den ultimata robotteknologin. Varje nivå halverar konstruktionstiden för byggnader, skepp och försvar.',
        'description_long' => 'Detta är den ultimata robotteknologin. Varje nivå halverar konstruktionstiden för byggnader, skepp och försvar.',
    ],
    'terraformer' => [
        'title' => 'Terraformare',
        'description' => 'Terraformaren ökar den brukbara ytan på planeten.',
        'description_long' => 'Terraformaren ökar den brukbara ytan på planeten.',
    ],
    'space_dock' => [
        'title' => 'Rymddocka',
        'description' => 'Vrak kan lagas i rymddockan.',
        'description_long' => 'Vrak kan lagas i rymddockan.',
    ],
    'lunar_base' => [
        'title' => 'Månbas',
        'description' => 'Eftersom månen inte har någon atmosfär krävs en månbas för att generera beboeligt utrymme.',
        'description_long' => 'Då månen inte har någon atmosfär, är månbasen nödvändig för 
att skapa boendeyta.',
    ],
    'sensor_phalanx' => [
        'title' => 'Radarstation',
        'description' => 'Med hjälp av sensorfalangen kan flottor av andra imperier upptäckas och observeras. Ju större sensorfalangarrayen är, desto större räckvidd kan den skanna.',
        'description_long' => 'När man använder radarstationen, kan flottor från andras imperium bli upptäckta och observerade. Ju större radarstation man har desto längre kan man scanna.',
    ],
    'jump_gate' => [
        'title' => 'Månportal',
        'description' => 'Hoppportar är enorma sändtagare som kan skicka även den största flottan på nolltid till en avlägsen hoppgrind.',
        'description_long' => 'Månportalen är som stora sändare och mottagare, kapabla att 
skicka och ta emot t.o.m. de största flottorna helt utan tidsförluster.',
    ],
    'energy_technology' => [
        'title' => 'Energiteknologi',
        'description' => 'Att kunna kontrollera olika energier är nödvändigt för att 
kunna utveckla nya teknologier.',
        'description_long' => 'Att kunna kontrollera olika energier är nödvändigt för att 
kunna utveckla nya teknologier.',
    ],
    'laser_technology' => [
        'title' => 'Laserteknologi',
        'description' => 'Ljus som fokuseras till att träffa en liten punkt kan därigenom skada mål som träffas.',
        'description_long' => 'Ljus som fokuseras till att träffa en liten punkt kan därigenom skada mål som träffas.',
    ],
    'ion_technology' => [
        'title' => 'Jonteknologi',
        'description' => 'Koncentrationer av joner tillåter tillverkningen av kanoner, vilka orsakar enorm skada och reducerar dekonstruktionskostnaden per nivå med 4%.',
        'description_long' => 'Koncentrationer av joner tillåter tillverkningen av kanoner, vilka orsakar enorm skada och reducerar dekonstruktionskostnaden per nivå med 4%.',
    ],
    'hyperspace_technology' => [
        'title' => 'Hyperrymd Teknologi',
        'description' => 'Genom att integrera den 4:e och 5:e dimensionen är det nu möjligt att utforska en ny typ av drivning som är mer ekonomisk och effektiv.',
        'description_long' => 'Genom att introducera fjärde och femte dimensionen är det 
nu möjligt att forska fram en ny motor som är mer ekonomisk och mer 
effektiv än tidigare. Genom att använda fjärde och femte dimensionen är det nu möjligt att krympa lastkajerna på dina skepp för att spara plats.',
    ],
    'plasma_technology' => [
        'title' => 'Plasmateknologi',
        'description' => 'Ytterligare en utveckling av jonteknologin vilken accelererar hög-energi plasma, som  i sin tur orsakar förödande skada och ytterligare optimerar produktionen av metall och kristall (1%/0,66%/0,33% per nivå).',
        'description_long' => 'Ytterligare en utveckling av jonteknologin vilken accelererar hög-energi plasma, som  i sin tur orsakar förödande skada och ytterligare optimerar produktionen av metall och kristall (1%/0,66%/0,33% per nivå).',
    ],
    'combustion_drive' => [
        'title' => 'Raketmotor',
        'description' => 'Utvecklingen av denna motor gör att skeppen med raketmotor 
får högre hastighet. Varje nivå ökar hastigheten med 10 % av basvärdet.',
        'description_long' => 'Utvecklingen av denna motor gör att skeppen med raketmotor 
får högre hastighet. Varje nivå ökar hastigheten med 10 % av basvärdet.',
    ],
    'impulse_drive' => [
        'title' => 'Impulsmotor',
        'description' => 'Impulsmotorn är baserad på reaktionsprincipen. 
Vidareutveckling av denna motor gör så att vissa skepp får högre hastighet. 
Varje nivå ökar hastigheten med 20 % av basvärdet.',
        'description_long' => 'Impulsmotorn är baserad på reaktionsprincipen. 
Vidareutveckling av denna motor gör så att vissa skepp får högre hastighet. 
Varje nivå ökar hastigheten med 20 % av basvärdet.',
    ],
    'hyperspace_drive' => [
        'title' => 'Hyperrymdmotor',
        'description' => 'Hyperrymdmotor vrider rymden runt skeppet. Utvecklingen 
av denna teknologi gör att vissa skepp blir snabbare. Varje nivå ökar 
hastigheten med 30 % av basvärdet.',
        'description_long' => 'Hyperrymdmotor vrider rymden runt skeppet. Utvecklingen 
av denna teknologi gör att vissa skepp blir snabbare. Varje nivå ökar 
hastigheten med 30 % av basvärdet.',
    ],
    'espionage_technology' => [
        'title' => 'Spionageteknologi',
        'description' => 'Ger information om andra planeter och månar när man forskar 
fram denna teknologi.',
        'description_long' => 'Ger information om andra planeter och månar när man forskar 
fram denna teknologi.',
    ],
    'computer_technology' => [
        'title' => 'Datorteknologi',
        'description' => 'Fler flottor kan skickas iväg på uppdrag om 
datorteknologin uppgraderas. Varje nivå av datorteknologin ökar det 
maximala antalet flottor som man kan ha ute samtidigt med 1.',
        'description_long' => 'Fler flottor kan skickas iväg på uppdrag om 
datorteknologin uppgraderas. Varje nivå av datorteknologin ökar det 
maximala antalet flottor som man kan ha ute samtidigt med 1.',
    ],
    'astrophysics' => [
        'title' => 'Astrofysik',
        'description' => 'Med en astrofysisk forskningsmodul så kan skepp åka ut på långa expeditioner. Varannan nivå av den här teknologin låter dig kolonisera en extra planet.',
        'description_long' => 'Med en astrofysisk forskningsmodul så kan skepp åka ut på långa expeditioner. Varannan nivå av den här teknologin låter dig kolonisera en extra planet.',
    ],
    'intergalactic_research_network' => [
        'title' => 'Intergalaktiskt forskningsnätverk',
        'description' => 'Forskningen sker på flera planeter istället för på bara en. Planeterna kommunicerar via detta nätverk.',
        'description_long' => 'Forskningen sker på flera planeter istället för på bara en. Planeterna kommunicerar via detta nätverk.',
    ],
    'graviton_technology' => [
        'title' => 'Gravitonteknologi',
        'description' => 'Avfyrar en koncentrerad laddning av gravitonpartiklar som 
genererar ett tillfälligt kraftfält. Det kan förstöra skepp och även hela 
månar.',
        'description_long' => 'Avfyrar en koncentrerad laddning av gravitonpartiklar som 
genererar ett tillfälligt kraftfält. Det kan förstöra skepp och även hela 
månar.',
    ],
    'weapon_technology' => [
        'title' => 'Vapenteknologi',
        'description' => 'Vapenteknologin gör att vapensystemen blir mer effektiva. 
Varje nivå av vapenteknologin som man forskar ökar vapenstyrkan med 10 % av basvärdet.',
        'description_long' => 'Vapenteknologin gör att vapensystemen blir mer effektiva. 
Varje nivå av vapenteknologin som man forskar ökar vapenstyrkan med 10 % av basvärdet.',
    ],
    'shielding_technology' => [
        'title' => 'Sköldteknologi',
        'description' => 'Shield-teknik gör sköldarna på fartyg och defensiva anläggningar mer effektiva. Varje nivå av sköldteknologi ökar sköldarnas styrka med 10 % av basvärdet.',
        'description_long' => 'Sköldteknologin gör så att skeppens och försvarsbyggnadernas sköldar blir mer effektiva. Varje nivå av Sköldteknologin ökar styrkan med 10 % av basvärdet.',
    ],
    'armor_technology' => [
        'title' => 'Pansarteknologi',
        'description' => 'Speciella legeringar gör att pansaret blir starkare på skepp och försvarsbyggnader. Pansaret blir 10% starkare per nivå.',
        'description_long' => 'Speciella legeringar gör att pansaret blir starkare på skepp och försvarsbyggnader. Pansaret blir 10% starkare per nivå.',
    ],
    'small_cargo' => [
        'title' => 'Litet transportskepp',
        'description' => 'Det lilla transportskeppet är ett lättmanövrerat skepp som snabbt kan transportera resurser till andra planeter.',
        'description_long' => 'Det lilla transportskeppet är ett lättmanövrerat skepp som snabbt kan transportera resurser till andra planeter.',
    ],
    'large_cargo' => [
        'title' => 'Stort transportskepp',
        'description' => 'Det stora transportskeppet har en mycket större lastkapacitet än det lilla transportskeppet, och är generellt snabbare tack vare en förbättrad motor.',
        'description_long' => 'Det stora transportskeppet har en mycket större lastkapacitet än det lilla transportskeppet, och är generellt snabbare tack vare en förbättrad motor.',
    ],
    'colony_ship' => [
        'title' => 'Koloniskepp',
        'description' => 'Obebodda planeter kan bli koloniserade med detta skepp.',
        'description_long' => 'Obebodda planeter kan bli koloniserade med detta skepp.',
    ],
    'recycler' => [
        'title' => 'Återvinnare',
        'description' => 'Återvinningsföretag är de enda fartyg som kan skörda skräpfält som flyter i en planets omloppsbana efter strid.',
        'description_long' => 'Återvinnaren är det enda skepp som kan skörda vrakfält. 
Vrakfälten flyter runt i omloppsbana runt en planet efter en strid.',
    ],
    'espionage_probe' => [
        'title' => 'Spionsond',
        'description' => 'Spionsonder är små, snabba sonder som samlar information från andra planeter genom att spionera.',
        'description_long' => 'Spionsonder är små, snabba sonder som samlar information från andra planeter genom att spionera.',
    ],
    'solar_satellite' => [
        'title' => 'Solsatellit',
        'description' => 'Solsatelliter är enkla plattformar av solceller, belägna i en hög, stationär bana. De samlar in solljus och överför det till markstationen via laser.',
        'description_long' => 'Solsatelliter är enkla plattformar med solceller. De är 
stationerade högt upp i en omloppsbana runt planeten. De absorberar solljus 
och skickar det sedan vidare till planeten via laser. En sol satellit producerar 35 energi på denna planeten.',
    ],
    'crawler' => [
        'title' => 'Krypare',
        'description' => 'Krypare ökar produktionen av metall, kristall och deuterium på deras uppdragsplanet med respektive 0,02%, 0,02% och 0,02%. Som en samlare ökar också produktionen. Den maximala totala bonusen beror på den totala nivån för dina gruvor.',
        'description_long' => 'Krypare ökar produktionen av metall, kristall och deuterium på deras uppdragsplanet med respektive 0,02%, 0,02% och 0,02%. Som en samlare ökar också produktionen. Den maximala totala bonusen beror på den totala nivån för dina gruvor.',
    ],
    'pathfinder' => [
        'title' => 'Stigfinnare',
        'description' => 'Pathfinder är ett snabbt och smidigt fartyg, specialbyggt för expeditioner till okända rymdsektorer.',
        'description_long' => 'Stigfinnare är snabba, rymliga och kan bryta vrakfält under expeditioner. Totalavkastningen ökar också.',
    ],
    'light_fighter' => [
        'title' => 'Litet jaktskepp',
        'description' => 'Det här är det första jaktskeppet alla kejsare kommer bygga. Det lilla jaktskeppet är lättmanövrerat, men ett lätt byte om det är ensamt. I stort antal kan dom hota vilket imperium som helst. Dom är först och främst till för att följa små och stora fraktskepp till fientliga planeter med litet motstånd.',
        'description_long' => 'Det här är det första jaktskeppet alla kejsare kommer bygga. Det lilla jaktskeppet är lättmanövrerat, men ett lätt byte om det är ensamt. I stort antal kan dom hota vilket imperium som helst. Dom är först och främst till för att följa små och stora fraktskepp till fientliga planeter med litet motstånd.',
    ],
    'heavy_fighter' => [
        'title' => 'Stort jaktskepp',
        'description' => 'Det stora jaktskeppet är bättre bepansrat och har en högre 
attackstyrka än de små jaktskeppen.',
        'description_long' => 'Det stora jaktskeppet är bättre bepansrat och har en högre 
attackstyrka än de små jaktskeppen.',
    ],
    'cruiser' => [
        'title' => 'Kryssare',
        'description' => 'Kryssaren är nästan tre gånger mer bepansrad än det stora 
jaktskeppet och har nästan två gånger mer i attackstyrka. Den är även väldigt 
snabb.',
        'description_long' => 'Kryssaren är nästan tre gånger mer bepansrad än det stora 
jaktskeppet och har nästan två gånger mer i attackstyrka. Den är även väldigt 
snabb.',
    ],
    'battle_ship' => [
        'title' => 'Slagskepp',
        'description' => 'Slagskeppen utgör ryggraden i varje flotta. Deras kraftiga kanoner, höga hastighet och stora lastkapacitet ger fienden rysningar.',
        'description_long' => 'Slagskeppen utgör ryggraden i varje flotta. Deras kraftiga kanoner, höga hastighet och stora lastkapacitet ger fienden rysningar.',
    ],
    'battlecruiser' => [
        'title' => 'Jagare',
        'description' => 'Jagaren är specialiserad på att hindra fientliga flottor att ta sig fram.',
        'description_long' => 'Jagaren är specialiserad på att hindra fientliga flottor att ta sig fram.',
    ],
    'bomber' => [
        'title' => 'Bombare',
        'description' => 'Bombaren är speciellt utvecklad för att förstöra en planets försvar.',
        'description_long' => 'Bombaren är speciellt utvecklad för att förstöra en planets försvar.',
    ],
    'destroyer' => [
        'title' => 'Flaggskepp',
        'description' => 'Flaggskeppet är krigsskeppens konung.',
        'description_long' => 'Flaggskeppet är krigsskeppens konung.',
    ],
    'deathstar' => [
        'title' => 'Dödsstjärna',
        'description' => 'Den enorma styrkan i en dödsstjärna är oöverträffad.',
        'description_long' => 'Den enorma styrkan i en dödsstjärna är oöverträffad.',
    ],
    'reaper' => [
        'title' => 'Dödsängel',
        'description' => 'The Reaper är ett kraftfullt stridsfartyg som är specialiserat för aggressiv raid och skörd av skräpfält.',
        'description_long' => 'Ett skepp i Dödsängel-klassen är ett mäktigt destruktivt instrument som kan plundra vrakfälten omedelbart efter striden.',
    ],
    'rocket_launcher' => [
        'title' => 'Raketramp',
        'description' => 'Raketrampen är ett enkelt och kostnadseffektivt försvarsval.',
        'description_long' => 'Raketrampen är ett enkelt och kostnadseffektivt försvarsval.',
    ],
    'light_laser' => [
        'title' => 'Litet lasertorn',
        'description' => 'Koncentrerad avfyrning mot målen med protoner kan förorsaka större skada än vanliga ballistiska skjutvapen.',
        'description_long' => 'Koncentrerad avfyrning mot målen med protoner kan förorsaka större skada än vanliga ballistiska skjutvapen.',
    ],
    'heavy_laser' => [
        'title' => 'Stort lasertorn',
        'description' => 'Det stora lasertornet är en vidareutveckling av det lilla lasertornet.',
        'description_long' => 'Det stora lasertornet är en vidareutveckling av det lilla lasertornet.',
    ],
    'gauss_cannon' => [
        'title' => 'Gausskanon',
        'description' => 'Gausskanonen avfyrar höghastighetsprojektiler som väger hundratals ton.',
        'description_long' => 'Gausskanonen avfyrar höghastighetsprojektiler som väger hundratals ton.',
    ],
    'ion_cannon' => [
        'title' => 'Jonkanon',
        'description' => 'Jonkanonen avfyrar en kontinuerlig stråle av accelererande joner, vilket orsakar stora skador på föremål som den träffar.',
        'description_long' => 'Jonkanonen avfyrar en kontinuerlig stråle av accelererande joner, vilket orsakar stora skador på föremål som den träffar.',
    ],
    'plasma_turret' => [
        'title' => 'Plasmakanon',
        'description' => 'Plasmakanonen frigör sin energi likt en solstråle och överträffar till och med Flaggskeppet med sin attackstyrka.',
        'description_long' => 'Plasmakanonen frigör sin energi likt en solstråle och överträffar till och med Flaggskeppet med sin attackstyrka.',
    ],
    'small_shield_dome' => [
        'title' => 'Liten Sköldkupol',
        'description' => 'Den Lilla sköld kupolen täcker hela planeten med ett fält 
som kan absorbera enorma mängder energi från attackerande fiender.',
        'description_long' => 'Den Lilla sköld kupolen täcker hela planeten med ett fält 
som kan absorbera enorma mängder energi från attackerande fiender.',
    ],
    'large_shield_dome' => [
        'title' => 'Stor sköldkupol',
        'description' => 'Utvecklingen av den lilla sköld kupolen kan använda betydligt mer energi för att stå emot angrepp.',
        'description_long' => 'Utvecklingen av den lilla sköld kupolen kan använda betydligt mer energi för att stå emot angrepp.',
    ],
    'anti_ballistic_missile' => [
        'title' => 'Antiballistiska missiler',
        'description' => 'Antiballistiska missiler förstör inkommande Interplanetära 
missiler.',
        'description_long' => 'Antiballistiska missiler förstör inkommande Interplanetära 
missiler.',
    ],
    'interplanetary_missile' => [
        'title' => 'Interplanetära missiler',
        'description' => 'Interplanetära missiler förstör fiendens försvar.',
        'description_long' => 'Interplanetära missiler förstör fiendens 
försvarsbyggnader. Dina interplanetära missiler täcker 0 system.',
    ],
    'kraken' => [
        'title' => 'KRAKEN',
        'description' => 'Minskar byggtiden för byggnader som för närvarande är under uppförande med <b>:duration</b>.',
    ],
    'detroid' => [
        'title' => 'DETROID',
        'description' => 'Minskar byggtiden för nuvarande varvskontrakt med <b>:duration</b>.',
    ],
    'newtron' => [
        'title' => 'NEWTRON',
        'description' => 'Minskar forskningstiden för all forskning som för närvarande pågår med <b>:duration</b>.',
    ],
];
