name: Docker Compose Unit Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'resources/css/**'
      - 'resources/js/**'
      - 'public/css/**'
      - 'public/js/**'
      - 'public/build/**'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.js'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'resources/css/**'
      - 'resources/js/**'
      - 'public/css/**'
      - 'public/js/**'
      - 'public/build/**'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.js'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-docker:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:26.0.0
        options: --privileged
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]
    name: Tests (shard ${{ matrix.shard }}/3)
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check for no external remote sources
        uses: ./.github/actions/check-remote-sources

      - name: Setup Docker Compose
        uses: ./.github/actions/docker-compose-setup

      - name: Run Tests (shard ${{ matrix.shard }}/3)
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: docker compose exec -T ogamex-app ./vendor/bin/pest --shard=${{ matrix.shard }}/3 --parallel

  race-condition:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:26.0.0
        options: --privileged
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check for no external remote sources
        uses: ./.github/actions/check-remote-sources

      - name: Setup Docker Compose
        uses: ./.github/actions/docker-compose-setup

      - name: Run custom Race Condition Tests
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            docker compose exec -T ogamex-app php artisan ogamex:test:race-condition-unitqueue
            docker compose exec -T ogamex-app php artisan ogamex:test:race-condition-game-mission
            docker compose exec -T ogamex-app php artisan ogamex:test:race-condition-fleet-dispatch
            docker compose exec -T ogamex-app php artisan ogamex:test:race-condition-unitqueue-creation
