name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Viene eseguito ogni giorno a mezzanotte
  workflow_dispatch: # Ti permette di lanciarlo anche a mano dai tasti di GitHub

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          ref: main # O il nome del tuo branch principale (es. master)

      - name: Sync upstream changes
        id: sync
        uses: a2vu/sync-upstream-repo@v1.1.0
        with:
          upstream_repo: https://github.com/lanedirt/OGameX.git
          upstream_branch: main
          target_branch: main # Il tuo branch
          force: false # Metti true solo se vuoi sovrascrivere tutto (rischioso!)